src/objects/Access_Set__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant_Access_By__c</fullName>
        <label>Grant Access By</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Pardot_Region</valueSetName>
        </valueSet>
    </fields>
    <label>Access Set</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Access Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Access_Set_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set__c</fullName>
        <label>Access Set</label>
        <referenceTo>Access_Set__c</referenceTo>
        <relationshipLabel>Access Set Assignments</relationshipLabel>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Access Set Assignment</label>
    <nameField>
        <displayFormat>ASM-{0000000000}</displayFormat>
        <label>Access Set Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Set Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Others ( e-commerce, etc.)</fullName>
    </customValue>
    <customValue>
        <fullName>Private Label / Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Product Group or Brand Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Trade House</fullName>
    </customValue>
    <customValue>
        <fullName>B2B Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Food Service / Quick Service Restaurants</fullName>
    </customValue>
    <customValue>
        <fullName>Importer / Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Channel TWO</fullName>
        <isActive>false</isActive>
        <label>Channel TWO</label>
    </customValue>
    <customValue>
        <fullName>Channel ONE</fullName>
        <isActive>false</isActive>
        <label>Channel ONE</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

src/globalValueSets/Pardot_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>EMENA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and North Africa</fullName>
        <isActive>false</isActive>
        <label>Middle East and North Africa</label>
    </customValue>
    <customValue>
        <fullName>West Europe</fullName>
        <isActive>false</isActive>
        <label>West Europe</label>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
        <isActive>false</isActive>
        <label>South America</label>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
        <isActive>false</isActive>
        <label>North America</label>
    </customValue>
    <customValue>
        <fullName>Central America</fullName>
        <isActive>false</isActive>
        <label>Central America</label>
    </customValue>
    <customValue>
        <fullName>East Asia</fullName>
        <isActive>false</isActive>
        <label>East Asia</label>
    </customValue>
    <customValue>
        <fullName>Central Asia</fullName>
        <isActive>false</isActive>
        <label>Central Asia</label>
    </customValue>
    <customValue>
        <fullName>Southern Asia</fullName>
        <isActive>false</isActive>
        <label>Southern Asia</label>
    </customValue>
    <customValue>
        <fullName>Sub Sahara Africa</fullName>
        <isActive>false</isActive>
        <label>Sub Sahara Africa</label>
    </customValue>
    <customValue>
        <fullName>East Europe and Russia</fullName>
        <isActive>false</isActive>
        <label>East Europe and Russia</label>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
        <isActive>false</isActive>
        <label>Middle East</label>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
        <isActive>false</isActive>
        <label>South East Asia</label>
    </customValue>
    <customValue>
        <fullName>Australia and New Zealand</fullName>
        <isActive>false</isActive>
        <label>Australia and New Zealand</label>
    </customValue>
    <masterLabel>Pardot Region</masterLabel>
</GlobalValueSet>

src/classes/AccessSetAssignmentTrigger_Test.cls
@isTest
public class AccessSetAssignmentTrigger_Test {
@testSetup
    public static void createData()
{
    Access_Set__c access1 = new Access_Set__c(Grant_Access_By__c = 'Region',BU__c = 'All' , Region__c = 'APAC' , Customer_Group__c = 'TH' , Channel__c = 'Trade House');
        insert access1;
    Access_Set_Assignment__c assign = OFI_TestDataFactory.createAccessSetAssignment(access1.Id, UserInfo.getUserId(),//'Sales',
                                                                                    true);
}
public static testmethod void data()
{
    Access_Set_Assignment__c assign = [Select Id, Name, User__c, Access_Set__c From Access_Set_Assignment__c];
    try{
        delete assign;
    }Catch(Exception e){}
}
}