src/objects/Access_Set__c.object
<CustomObject>
    <label>Access Set</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Access Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Access_Set_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set__c</fullName>
        <label>Access Set</label>
        <referenceTo>Access_Set__c</referenceTo>
        <relationshipLabel>Access Set Assignments</relationshipLabel>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Access Set Assignment</label>
    <nameField>
        <displayFormat>ASM-{0000000000}</displayFormat>
        <label>Access Set Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Set Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <label>Inco Terms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CFR</fullName>
                    <label>CFR - Costs and freight</label>
                </value>
                <value>
                    <fullName>CIF</fullName>
                    <label>CIF - Costs, insurance &amp; freight</label>
                </value>
                <value>
                    <fullName>CIP</fullName>
                    <label>CIP - Carriage and insurance paid</label>
                </value>
                <value>
                    <fullName>CPT</fullName>
                    <label>CPT - Carriage paid to</label>
                </value>
                <value>
                    <fullName>DAP</fullName>
                    <label>DAP - Delivered At Place</label>
                </value>
                <value>
                    <fullName>DDP</fullName>
                    <label>DDP - Delivered Duty Paid</label>
                </value>
                <value>
                    <fullName>DPU</fullName>
                    <label>DPU - Delivered At Place Unloaded</label>
                </value>
                <value>
                    <fullName>EXW</fullName>
                    <label>EXW - Ex Works</label>
                </value>
                <value>
                    <fullName>FAS</fullName>
                    <label>FAS - Free Along Sideship</label>
                </value>
                <value>
                    <fullName>FCA</fullName>
                    <label>FCA - Free Carrier</label>
                </value>
                <value>
                    <fullName>FOB</fullName>
                    <label>FOB - Free On Board</label>
                </value>
                <value>
                    <fullName>Instore</fullName>
                </value>
                <value>
                    <fullName>CNF</fullName>
                    <isActive>false</isActive>
                    <label>CNF</label>
                </value>
                <value>
                    <fullName>DAT</fullName>
                    <isActive>false</isActive>
                    <label>DAT</label>
                </value>
                <value>
                    <fullName>DDU</fullName>
                    <isActive>false</isActive>
                    <label>DDU</label>
                </value>
                <value>
                    <fullName>DES</fullName>
                    <isActive>false</isActive>
                    <label>DES</label>
                </value>
                <value>
                    <fullName>FOR</fullName>
                    <isActive>false</isActive>
                    <label>FOR</label>
                </value>
                <value>
                    <fullName>FOT</fullName>
                    <isActive>false</isActive>
                    <label>FOT</label>
                </value>
                <value>
                    <fullName>UN</fullName>
                    <isActive>false</isActive>
                    <label>UN</label>
                </value>
                <value>
                    <fullName>Z05</fullName>
                    <isActive>false</isActive>
                    <label>Z05</label>
                </value>
                <value>
                    <fullName>Z06</fullName>
                    <isActive>false</isActive>
                    <label>Z06</label>
                </value>
                <value>
                    <fullName>Z09</fullName>
                    <isActive>false</isActive>
                    <label>Z09</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ZU13 - Net 60 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>Z070 - 2% 15 days, 60 days net</fullName>
                </value>
                <value>
                    <fullName>ZU10 - Net 30 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>ZU14 - Net 90 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>ZU17 - Payment in Advance,Prepayment</fullName>
                </value>
                <value>
                    <fullName>ZU07 - Net 15 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>ZS87 - CAD at Sight In Trust@120 day-98%-2% Pay on req</fullName>
                </value>
                <value>
                    <fullName>ZU12 - Net 45 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>USBM - 2% 10 NET 45</fullName>
                </value>
                <value>
                    <fullName>US0D - 1% 10 NET 60</fullName>
                </value>
                <value>
                    <fullName>ZU04 - Net 7 days - Date of Invoice</fullName>
                    <default>true</default>
                    <label>ZU04 - Net 7 days - Date of Invoice</label>
                </value>
                <value>
                    <fullName>ZS96 - CAD at Sight In Trust @ 75 day - 100%</fullName>
                </value>
                <value>
                    <fullName>USAE - Net due in 65 days</fullName>
                </value>
                <value>
                    <fullName>ZU11 - Net 40 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>SG06 - Letter of credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>KG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Bussiness_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                    <label>Spices</label>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <description>Text Box Field Inco Terms</description>
        <inlineHelpText>Enter Inco Terms</inlineHelpText>
        <label>Inco Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFR - Costs and freight</fullName>
                </value>
                <value>
                    <fullName>CIF - Costs, insurance &amp; freight</fullName>
                </value>
                <value>
                    <fullName>CIP - Carriage and insurance paid</fullName>
                </value>
                <value>
                    <fullName>CPT - Carriage paid to</fullName>
                </value>
                <value>
                    <fullName>DAP - Delivered At Place</fullName>
                </value>
                <value>
                    <fullName>DDP - Delivered Duty Paid</fullName>
                </value>
                <value>
                    <fullName>EXW - Ex Works</fullName>
                </value>
                <value>
                    <fullName>FAS - Free Along Sideship</fullName>
                </value>
                <value>
                    <fullName>FCA - Free Carrier</fullName>
                </value>
                <value>
                    <fullName>FOB - Free On Board</fullName>
                </value>
                <value>
                    <fullName>DPU - Delivered At Place Unloaded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <formula>TEXT( Opportunity.Account.Payment_Terms__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Terms</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Unit_Of_Measure__c</fullName>
        <label>Unit Of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Unit_of_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MT</fullName>
        <default>true</default>
        <label>MT</label>
    </customValue>
    <customValue>
        <fullName>LB</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>QE</fullName>
        <isActive>false</isActive>
        <label>QE</label>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
        <isActive>false</isActive>
        <label>Carton</label>
    </customValue>
    <masterLabel>Unit of Measure</masterLabel>
</GlobalValueSet>

src/classes/QuoteTrigger_Test.cls
//Created by Ashwini Godase 12/1/22
@isTest
public class QuoteTrigger_Test {
    @testSetUp
    static void createData () {
        
        Profile profOfi = [select id from profile where name='OFI'];
        
        
        User ofiuser = new User(alias = 'jack qu', email='jackqu@noemail.com',
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US',
                                localesidkey='en_US', profileid = profOfi.Id,
                                timezonesidkey='America/Los_Angeles',
                                //Access_Set_Role__c='PDI',  
                                username='jackqu@noemail.com');
        insert ofiuser;  
        
        User ofiuser1 = new User(alias = 'jack8', email='jackqu@noemail.com',
                                 emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US',
                                 localesidkey='en_US', profileid = profOfi.Id,
                                 timezonesidkey='America/Los_Angeles',
                                 //Access_Set_Role__c='Sales',  
                                 username='jack8@noemail.com');
        insert ofiuser1;
        
        List<user> currentuser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Account acc= OFI_TestDataFactory.createMultipleAccount('Test for Quote', 'India','In', null, null, null, true);
        Account acc1= OFI_TestDataFactory.createMultipleAccount('TestQuote1', 'India','In', null, null, null, true);
        Account acc2= OFI_TestDataFactory.createMultipleAccount('TestQuoteFailure', 'India','In', null, null, null, true);
        
        
        //  Access_Set__c accset= OFI_TestDataFactory.createAccessSet('country', null, 'In','Spice', null, null, null, true); 
        //  Access_Set_Assignment__c accsetass=OFI_TestDataFactory.createAccessSetAssignment(accset.Id, ofiuser.id,'PDI', true);
        
        Access_Set__c accset1= OFI_TestDataFactory.createAccessSet('country', null, 'In','Cocoa', null, null, null, true); 
        Access_Set_Assignment__c accsetass1=OFI_TestDataFactory.createAccessSetAssignment(accset1.Id, ofiuser.id,
                                                                                          //'PDI', 
                                                                                          true);
        
        
        Access_Set__c accsetall= OFI_TestDataFactory.createAccessSet('country', null, 'In','All', null, null, null, true); 
        Access_Set_Assignment__c accsetassall=OFI_TestDataFactory.createAccessSetAssignment(accsetall.Id, ofiuser1.id,
                                                                                            //'Sales', 
                                                                                            true);
        Teams__C teamall=OFI_TestDataFactory.createAccountTeam(acc1.id,  ofiuser1.id, 'All', 'Edit Access',
                                                               //'Sales', 
                                                               True, True);        
        //  Teams__C team1=OFI_TestDataFactory.createAccountTeam(acc.id,  ofiuser.id, 'Spice', 'Edit Access','PDI', false, True);
        //  Teams__C team=OFI_TestDataFactory.createAccountTeam(acc1.id,  ofiuser.id, 'Cocoa', 'Edit Access','PDI', false, True);
        
        
        Id priceBookID = Test.getStandardPricebookId();
        
        Product2 p_test = new Product2(IsActive=true,Name='test Product',Description='Description for test Product');
        insert p_test;
        
        PricebookEntry pbe = new PricebookEntry(IsActive=true,Pricebook2Id=priceBookID,Product2Id=p_test.Id,UnitPrice=10.00);  
        insert pbe;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId =acc1.id;
        opp.CloseDate =system.today()+30;
        opp.StageName= 'Offering';
        opp.Business_Unit__c='All';   
        opp.Pricebook2Id=pricebookId;
        opp.RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId();
        insert opp; 
        Quote qu= new Quote(OpportunityId=opp.Id,Name='testqAdmin',pricebook2Id =pricebookId,ExpirationDate=system.today()+30,Inco_Terms__c='DAP',Ship_To_Party__c=acc.id);
        insert qu;
        opp.SyncedQuoteId=qu.id;
        update opp;
        QuoteLineItem qiItem = new  QuoteLineItem(QuoteId = qu.Id ,Product2Id=p_test.Id  ,PricebookEntryId=pbe.Id,Volume__c=1, Quantity =1 , UnitPrice=123,Unit_Of_Measure__c='KG' );
        insert  qiItem;
        Contact c= new Contact(AccountId=acc.id,Lastname='jack1',Email='jakk@gmail.com');   
        insert c;
        Contact c2= new Contact(AccountId=acc1.id,Lastname='jack12',Email='jakk1@gmail.com');   
        insert c2;
        OpportunityTeamMember oppt=new OpportunityTeamMember(OpportunityId=opp.id,TeamMemberRole='PD&I Member',UserId=userinfo.getuserId());
        insert oppt;
        
        /*  Opportunity opp3 = new Opportunity();
opp3.Name = 'Test Opp3';
opp3.AccountId =acc.id;
opp3.CloseDate =system.today()+30;
opp3.StageName= 'Offering';
opp3.Business_Unit__c='Cocoa';     
opp3.RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId();
insert opp3; 
Quote qun= new Quote(OpportunityId=opp3.Id,Name='testq',pricebook2Id =pricebookId,ExpirationDate=system.today()+30,Inco_Terms__c='DAP',Ship_To_Party__c=acc.id,Payment_Terms__c='Net 30');
insert qun;
opp3.SyncedQuoteId=qun.id;
update opp3;
QuoteLineItem qiIte21 = new  QuoteLineItem(QuoteId = qun.Id ,Product2Id=p_test.Id  ,PricebookEntryId=pbe.Id,Volume__c=1, Quantity =1 , UnitPrice=123,Unit_Of_Measure__c='KG' );
insert  qiIte21;*/
        
        
        System.runAs(ofiuser1){
            test.startTest();
            
            Opportunity opp3 = new Opportunity();
            opp3.Name = 'Test Opp3';
            opp3.AccountId =acc1.id;
            opp3.CloseDate =system.today()+30;
            opp3.StageName= 'Offering';
            opp3.Business_Unit__c='Cocoa'; 
            opp3.Pricebook2Id=pricebookId;
            opp3.RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId();
            insert opp3; 
            
            Quote qun= new Quote(OpportunityId=opp3.Id,Name='testq',pricebook2Id =pricebookId,ExpirationDate=system.today()+30,Inco_Terms__c='DAP',Ship_To_Party__c=acc.id);
            insert qun;
            opp3.SyncedQuoteId=qun.id;
            update opp3;
            QuoteLineItem qiIte21 = new  QuoteLineItem(QuoteId = qun.Id ,Product2Id=p_test.Id  ,PricebookEntryId=pbe.Id,Volume__c=1, Quantity =1 , UnitPrice=123,Unit_Of_Measure__c='KG' );
            try{ insert  qiIte21;
               }   Catch(DMLException e){}
            Teams__C teamnew=OFI_TestDataFactory.createAccountTeam(acc1.id,  ofiuser.id, 
                                                                   'Cocoa', 
                                                                   'Edit Access',
                                                                   //'PDI', 
                                                                   false, True);
            
            Quote qu1= new Quote(OpportunityId=opp.Id,Name='testq',Bussiness_Unit__c='Cocoa',ExpirationDate=system.today()+30,Inco_Terms__c='DAP',Ship_To_Party__c=acc.id);
            
            try{
                insert qu1;
            }  
            Catch(DMLException e){}
            
            Quote qu13= new Quote(OpportunityId=opp.Id,Name='testq',ExpirationDate=system.today()+30,Inco_Terms__c='DAP',Ship_To_Party__c=acc.id);
            
            try{
                insert qu13;
            }  
            Catch(DMLException e){}
            
            
            try{
                
                QuoteLineItem qiItem1 = new  QuoteLineItem(QuoteId = qu.Id ,Product2Id=p_test.Id  ,PricebookEntryId=pbe.Id,Volume__c=1, Quantity =1 , UnitPrice=123,Unit_Of_Measure__c='KG' );
                insert  qiItem1; //line failed
                qiItem1.UnitPrice=99;
                update qiItem1; 
            }  
            Catch(DMLException e){}
            
            try{
                
                QuoteLineItem qiItem2 = new  QuoteLineItem(QuoteId = qu.Id ,Product2Id=p_test.Id  ,PricebookEntryId=pbe.Id,Volume__c=1, Quantity =1 , UnitPrice=123,Unit_Of_Measure__c='KG' );
                insert  qiItem2; //line failed
                qiItem2.UnitPrice=99;
                update qiItem2; 
            }  
            Catch(DMLException e){}
            
            try{
                // qiIte21.Volume__c=2;
                //  update qiIte21;
                
            }  
            Catch(DMLException e){}
            try{
                qiItem.UnitPrice=200;
                update qiItem;
            }  
            Catch(DMLException e){}
        }
        test.stopTest();
    }
    
    @isTest 
    static void testGetDetails () {
        test.startTest();
        List<user> user=[select id from user ];
        List<Account> acc=[select id from account];
        List<Opportunity> opp=[select id from opportunity];
        List<Access_Set__c> accset=[select id from Access_Set__c];
        List<Quote> quote=[select id from Quote];
        
        List<Product2> pr1=[select id from Product2];
        List<PricebookEntry> pre=[select id from PricebookEntry];
        List<QuoteLineItem> quline=[select id,UnitPrice from QuoteLineItem];
        System.runAs(user[1]){
            
            //  Access_Set_Assignment__c accsetass1=OFI_TestDataFactory.createAccessSetAssignmentRole(accset[0].Id,user[1].id ,'PDI', true);
            //  Access_Set_Assignment__c accsetass2=OFI_TestDataFactory.createAccessSetAssignmentRole(accset[1].Id,user[1].id ,'PDI', true);
            
            // Teams__C team1=OFI_TestDataFactory.createAccountTeamPrimary(acc[0].id,user[1].id, 'Spice', 'Edit Access', True, True);
            // Teams__C team2=OFI_TestDataFactory.createAccountTeamPrimary(acc[1].id,user[1].id, 'Cocoa', 'Edit Access', False, True);
            
            try{
                quline[0].Volume__c=2;
                update quline[0];
                
            }  
            Catch(DMLException e){}
            Quote qu= new Quote(OpportunityId=opp[0].Id,Name='testq',ExpirationDate=system.today()+30,Inco_Terms__c='DAP',Ship_To_Party__c=acc[0].id);
            
            try{
                insert qu;
            }  
            Catch(DMLException e){}
            try{
                quote[0].Bussiness_Unit__c='Cocoa';
                update quote[0];
            }  
            Catch(DMLException e){}
            
            try{
                
                QuoteLineItem qiItem = new  QuoteLineItem(QuoteId = quote[0].Id ,Product2Id=pr1[0].Id  ,PricebookEntryId=pre[0].Id,Volume__c=1, Quantity =1 , UnitPrice=123,Unit_Of_Measure__c='KG' );
                insert  qiItem; //line failed
                qiItem.UnitPrice=99;
                update qiItem; 
            }  
            Catch(DMLException e){}
            
            try{
                quline[0].UnitPrice=200;
                update quline[0];
            }  
            Catch(DMLException e){}
            
            
            
            Quote que= new Quote(OpportunityId=opp[0].Id,Name='testq',ExpirationDate=system.today()+30,Inco_Terms__c='DAP',Ship_To_Party__c=acc[0].id);
            
            try{
                insert que;
            }  
            Catch(DMLException e){}
            try{
                quote[0].Bussiness_Unit__c='All';
                update quote[0];
            }  
            Catch(DMLException e){}
            
            try{
                
                QuoteLineItem qiItem3 = new  QuoteLineItem(QuoteId = quote[0].Id ,Product2Id=pr1[0].Id  ,PricebookEntryId=pre[0].Id,Volume__c=1, Quantity =1 , UnitPrice=123,Unit_Of_Measure__c='KG' );
                insert  qiItem3; //line failed
                
            }  
            Catch(DMLException e){}
            
            
            test.stopTest();
        }
    }  
}