src/objects/Access_Set__c.object
<CustomObject>
    <label>Access Set</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Access Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Access_Set_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set__c</fullName>
        <label>Access Set</label>
        <referenceTo>Access_Set__c</referenceTo>
        <relationshipLabel>Access Set Assignments</relationshipLabel>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Teams_Creation_Status__c</fullName>
        <defaultValue>&quot;Initiated&quot;</defaultValue>
        <label>Account Teams Creation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Access Set Assignment</label>
    <nameField>
        <displayFormat>ASM-{0000000000}</displayFormat>
        <label>Access Set Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Set Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Create_Account_Team__e.object
<CustomObject>
    <label>Create Account Team</label>
    <pluralLabel>Create Account Teams</pluralLabel>
</CustomObject>

src/objects/Retry_Log__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Access Set Assignment</label>
        <referenceTo>Access_Set_Assignment__c</referenceTo>
        <relationshipLabel>Retry Logs</relationshipLabel>
        <relationshipName>Retry_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retry_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Retry Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Team Creation</fullName>
                </value>
                <value>
                    <fullName>Account Team Grant Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retry Log</label>
    <nameField>
        <displayFormat>RL-{0000000000}</displayFormat>
        <label>Retry Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retry Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateAccountTeamsPEventScheduler.cls
global class CreateAccountTeamsPEventScheduler implements schedulable{
    
    global void execute(SchedulableContext SC) {
        //Check Access_Set_Assignment__c records if the account teams has to be created for any record
        List<Access_Set_Assignment__c> listOfAccessSetAssgnmntToProcess = new List<Access_Set_Assignment__c>();
        System.debug('listOfAccessSetAssgnmntToProcess: ');
        listOfAccessSetAssgnmntToProcess = [Select Id,Name,Access_Set__c,User__c,Account_Teams_Creation_Status__c 
                                            from Access_Set_Assignment__c 
                                            where Account_Teams_Creation_Status__c =: SharingUtility.ACCOUNT_TEAM_CREATION_STATUS_INITIATED and //"Failed" STATUS SHOULD BE HANDLED ON BASIS OF RETRY MECHANISM
                                            Id NOT IN (
                                                Select Access_Set_Assignment__c 
                                                from Retry_Log__c 
                                                where Type__c =: SharingUtility.RETRYLOGTYPE_ACCOUNT_TEAM_CREATION 
                                                and Retry_Count__c >: SharingUtility.ACCOUNTTEAMCREATE_RETRY_COUNT_LIMIT
                                            )
                                            limit 1];
        System.debug('listOfAccessSetAssgnmntToProcess: '+listOfAccessSetAssgnmntToProcess);
        if(!listOfAccessSetAssgnmntToProcess.isEmpty()){
            //Fire the grant access platform event
            Create_Account_Team__e createAccountTeamsPEvent = new Create_Account_Team__e ();
            Database.SaveResult result = Eventbus.publish(createAccountTeamsPEvent);
            //abort the current Job (it will be rescheduled in the platform event only if there is no record left to be processed )
            System.abortJob(SC.getTriggerId());
        }
        else{
            //abort the current Job (it will be rescheduled in the platform event only if there is no record left to be processed )
            System.abortJob(SC.getTriggerId());
            //Schedule a Job to run after 10 mins from now
            /*String hour = String.valueOf(Datetime.now().hour());
            String min = String.valueOf(Datetime.now().minute() + 10); 
            String seconds = String.valueOf(Datetime.now().second());
            
            String nextJobScheduleTime = seconds + ' ' + min + ' ' + hour + ' * * ?';*/
            Datetime workTime = System.now().addMinutes(10);
            String nextJobScheduleTime = '' + workTime.second() + ' ' + workTime.minute() + ' ' + workTime.hour()+ ' ' + workTime.day() + ' ' + workTime.month() + ' ? ' + workTime.year();

            String jobId = System.schedule('Create Team Job- ' + String.valueOf(Datetime.now()), nextJobScheduleTime, new CreateAccountTeamsPEventScheduler());
            System.debug('jobId: '+jobId);
        }
    }
}