src/objects/Access_Set__c.object
<CustomObject>
    <label>Access Set</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Access Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Access_Set_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set__c</fullName>
        <label>Access Set</label>
        <referenceTo>Access_Set__c</referenceTo>
        <relationshipLabel>Access Set Assignments</relationshipLabel>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Teams_Creation_Status__c</fullName>
        <defaultValue>&quot;Initiated&quot;</defaultValue>
        <label>Account Teams Creation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Access Set Assignment</label>
    <nameField>
        <displayFormat>ASM-{0000000000}</displayFormat>
        <label>Access Set Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Set Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Create_Account_Team__e.object
<CustomObject>
    <label>Create Account Team</label>
    <pluralLabel>Create Account Teams</pluralLabel>
</CustomObject>

src/objects/Retry_Log__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Access Set Assignment</label>
        <referenceTo>Access_Set_Assignment__c</referenceTo>
        <relationshipLabel>Retry Logs</relationshipLabel>
        <relationshipName>Retry_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Retry_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Retry Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Team Creation</fullName>
                </value>
                <value>
                    <fullName>Account Team Grant Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retry Log</label>
    <nameField>
        <displayFormat>RL-{0000000000}</displayFormat>
        <label>Retry Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retry Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <defaultValue>&quot;Read Access&quot;</defaultValue>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read Access</fullName>
                </value>
                <value>
                    <fullName>Edit Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Access_Set_Ids__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Access Set Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/CreateAccountTeamsPEventTrigger_Test.cls
@isTest
public class CreateAccountTeamsPEventTrigger_Test {
    @testSetup
    public static void createData()
    {
        User user = new User(ProfileId = [SELECT Id FROM Profile WHERE Name = 'Dairy Sales'].Id, LastName = 'UnitTestUser1', Email = 'unittestuser000@unittestuser.com',
                             Username = 'unittestuser000@unittestuser.com' + System.currentTimeMillis(), CompanyName = 'TEST', Title = 'title',
                             Alias = 'alias', TimeZoneSidKey = 'America/Los_Angeles', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US',
                             LocaleSidKey = 'en_US'
                             //,Access_Set_Role__c = 'Sales'
                             );    
        insert user;
        User user2 = new User(ProfileId = [SELECT Id FROM Profile WHERE Name = 'Cocoa Sales'].Id, LastName = 'UnitTestUser2', Email = 'unittestuser000@unittestuser.com2',
                             Username = 'unittestuser000@unittestuser.com2' + System.currentTimeMillis(), CompanyName = 'TEST', Title = 'title',
                             Alias = 'alias', TimeZoneSidKey = 'America/Los_Angeles', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US',
                             LocaleSidKey = 'en_US'
                             //,Access_Set_Role__c = 'Sales'
                             );    
        insert user2;
        
        Account acc = OFI_TestDataFactory.createAccount(true);
        Id pricebookId = Test.getStandardPricebookId();
        Access_Set__c access = OFI_TestDataFactory.createAccessSet('Country', null, 'IN', 'Cocoa', null, 'Nestle', null, true);
        Access_Set_Assignment__c assign = OFI_TestDataFactory.createAccessSetAssignment(access.Id, user.Id, //'Sales',
          																				true);
        /*Account acc2 = OFI_TestDataFactory.createMultipleAccount('demo acc', 'Singapore', 'SG', 'APAC', null, null, true);                                                                                
                     Access_Set__c    access2 = OFI_TestDataFactory.createAccessSet('Region', 'APAC', null, 'All', null, null, null, true);                                                               
        Access_Set_Assignment__c assign2 = OFI_TestDataFactory.createAccessSetAssignment(access2.Id, user2.Id, //'Sales',
                                                                                         true);*/
      Teams__c team = new Teams__c(Account__c = acc.Id, User__c = user2.Id, Is_Primary__c = false, Business_Unit__c = 'All', 
                                     Access_Level__c = 'Read Access', //Access_Set_Role__c = 'Sales', 
                                     Access_Set_Ids__c = access.Id);
        insert team;
    }
    
    public static testMethod void testschedule() {
        Test.StartTest();
        CreateAccountTeamsPEventScheduler testsche = new CreateAccountTeamsPEventScheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, testsche );
        Test.stopTest();
    }
    public static testMethod void testschedule2() {
        List <Access_Set_Assignment__c> assignList = [Select Id,Account_Teams_Creation_Status__c from Access_Set_Assignment__c limit 1];
        Create_Account_Team__e createAccountTeamsPEvent = new Create_Account_Team__e ();
        Test.StartTest();
        if(!assignList.isEmpty()){
            assignList[0].Account_Teams_Creation_Status__c = SharingUtility.ACCOUNT_TEAM_CREATION_STATUS_PROCESSED;
            update assignList[0];
        }
        
        Database.SaveResult result = Eventbus.publish(createAccountTeamsPEvent);
        Test.stopTest();
    }
    //method to cover if retry log count less than 3
     @isTest
    static void testValidScenario3() {
        List<Access_Set_Assignment__c> assign = [Select Id, user__c, Access_set__c, Account_Teams_Creation_Status__c From Access_Set_Assignment__c];
        Create_Account_Team__e createAccountTeamsPEvent = new Create_Account_Team__e ();
        Test.startTest();
        if(!assign.isEmpty())
        {
        Retry_Log__c retry1 = new Retry_Log__c(Type__c = SharingUtility.RETRYLOGTYPE_ACCOUNT_TEAM_CREATION, Access_Set_Assignment__c = assign[0].Id, Error_Message__c = 'Error Message1');
        insert retry1;
        }
        Database.SaveResult result = Eventbus.publish(createAccountTeamsPEvent);
        Test.stopTest();
    }
    //method to cover if retry log count more than 3
     @isTest
    static void testValidScenario4() {
        List<Access_Set_Assignment__c> assign = [Select Id, user__c, Access_set__c, Account_Teams_Creation_Status__c From Access_Set_Assignment__c];
        Create_Account_Team__e createAccountTeamsPEvent = new Create_Account_Team__e ();
        Test.startTest();
        if(!assign.isEmpty())
        {
        Retry_Log__c retry1 = new Retry_Log__c(Retry_Count__c = 3, Type__c = SharingUtility.RETRYLOGTYPE_ACCOUNT_TEAM_CREATION, Access_Set_Assignment__c = assign[0].Id, Error_Message__c = 'Error Message1');
        insert retry1;
        }
        Database.SaveResult result = Eventbus.publish(createAccountTeamsPEvent);
        Test.stopTest();
    }
	 public static testMethod void testscheduleCatch() {
        Test.StartTest();
         //User user = [Select Id, Name From User where Email =: ]
        // Access_Set__c access = OFI_TestDataFactory.createAccessSet('Country', null, 'IN', 'Cocoa', null, 'Nestle', null, true);
        //Access_Set_Assignment__c assign = OFI_TestDataFactory.createAccessSetAssignment(access.Id, user.Id, //'Sales',
         // 																				true);
         
        /*List<Access_Set_Assignment__c> assign = [Select Id,Name,Account_Teams_Creation_Status__c From Access_Set_Assignment__c];
        assign[0].Account_Teams_Creation_Status__c = SharingUtility.ACCOUNT_TEAM_CREATION_STATUS_FAILED ;
         update assign;*/
         Test.stopTest();
    }
    
}