src/objects/Access_Set__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Pardot_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Regions</valueSetName>
        </valueSet>
    </fields>
    <label>Access Set</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Access Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Access_Set_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set__c</fullName>
        <label>Access Set</label>
        <referenceTo>Access_Set__c</referenceTo>
        <relationshipLabel>Access Set Assignments</relationshipLabel>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Teams_Creation_Status__c</fullName>
        <defaultValue>&quot;Initiated&quot;</defaultValue>
        <label>Account Teams Creation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Access Set Assignment</label>
    <nameField>
        <displayFormat>ASM-{0000000000}</displayFormat>
        <label>Access Set Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Set Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <description>To Identify the account region</description>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                    <isActive>false</isActive>
                    <label>Africa</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                    <isActive>false</isActive>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>Europe</fullName>
                    <isActive>false</isActive>
                    <label>Europe</label>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                    <isActive>false</isActive>
                    <label>Latin America</label>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                    <isActive>false</isActive>
                    <label>Middle East</label>
                </value>
                <value>
                    <fullName>North America</fullName>
                    <isActive>false</isActive>
                    <label>North America</label>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                    <isActive>false</isActive>
                    <label>Oceania</label>
                </value>
                <value>
                    <fullName>South America</fullName>
                    <isActive>false</isActive>
                    <label>South America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Team_Member_Role__mdt.object
<CustomObject>
    <description>Opportunity team member roles</description>
    <label>Opportunity Team Member Role</label>
    <pluralLabel>Opportunity Team Member Roles</pluralLabel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Regions</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <defaultValue>&quot;Read Access&quot;</defaultValue>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read Access</fullName>
                </value>
                <value>
                    <fullName>Edit Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Others ( e-commerce, etc.)</fullName>
    </customValue>
    <customValue>
        <fullName>Private Label / Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Product Group or Brand Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Trade House</fullName>
    </customValue>
    <customValue>
        <fullName>B2B Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Food Service / Quick Service Restaurants</fullName>
    </customValue>
    <customValue>
        <fullName>Importer / Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Channel TWO</fullName>
        <isActive>false</isActive>
        <label>Channel TWO</label>
    </customValue>
    <customValue>
        <fullName>Channel ONE</fullName>
        <isActive>false</isActive>
        <label>Channel ONE</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

src/globalValueSets/Pardot_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>EMENA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and North Africa</fullName>
        <isActive>false</isActive>
        <label>Middle East and North Africa</label>
    </customValue>
    <customValue>
        <fullName>West Europe</fullName>
        <isActive>false</isActive>
        <label>West Europe</label>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
        <isActive>false</isActive>
        <label>South America</label>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
        <isActive>false</isActive>
        <label>North America</label>
    </customValue>
    <customValue>
        <fullName>Central America</fullName>
        <isActive>false</isActive>
        <label>Central America</label>
    </customValue>
    <customValue>
        <fullName>East Asia</fullName>
        <isActive>false</isActive>
        <label>East Asia</label>
    </customValue>
    <customValue>
        <fullName>Central Asia</fullName>
        <isActive>false</isActive>
        <label>Central Asia</label>
    </customValue>
    <customValue>
        <fullName>Southern Asia</fullName>
        <isActive>false</isActive>
        <label>Southern Asia</label>
    </customValue>
    <customValue>
        <fullName>Sub Sahara Africa</fullName>
        <isActive>false</isActive>
        <label>Sub Sahara Africa</label>
    </customValue>
    <customValue>
        <fullName>East Europe and Russia</fullName>
        <isActive>false</isActive>
        <label>East Europe and Russia</label>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
        <isActive>false</isActive>
        <label>Middle East</label>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
        <isActive>false</isActive>
        <label>South East Asia</label>
    </customValue>
    <customValue>
        <fullName>Australia and New Zealand</fullName>
        <isActive>false</isActive>
        <label>Australia and New Zealand</label>
    </customValue>
    <masterLabel>Pardot Region</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>West Europe</fullName>
    </customValue>
    <customValue>
        <fullName>East Europe and Russia</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Central America</fullName>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and North Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Sub Sahara Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Central Asia</fullName>
    </customValue>
    <customValue>
        <fullName>East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia and New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>North East</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>West Coast</fullName>
    </customValue>
    <customValue>
        <fullName>South West</fullName>
    </customValue>
    <customValue>
        <fullName>South East</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
        <isActive>false</isActive>
        <label>APAC</label>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

src/globalValueSets/Regions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>EMENA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

src/classes/OFI_QuoteLinteItemHandler.cls
// 
// Class created by Ashwini
// Last modified by Joel Tom on 01/02/2022
// 

public class OFI_QuoteLinteItemHandler {
    
    public static void checkUserAccessForInsert(list<QuoteLineItem> newQuLineItemList){
        
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Access_Set_Admins');
        if(!hasCustomPermission){ 
            Map<string,Teams__c> mapOfUserIdToTeams =new Map<string,Teams__c>();
            Map<string,Access_Set__c> mapOfproductCatToAcessset=new Map<string,Access_Set__c>();
            Map<id,QuoteLineItem> newMapOfIdtoQuLine = new Map<id,QuoteLineItem>();
            Map<id,Quote> mapOfIdtoQu=new Map<id,Quote>();
            Map<Id,PricebookEntry> mapOfIdtoPriceBookEntry=new Map<Id,PricebookEntry>();
            set<id> QuId=new set<Id>();
            set<id> AccountID=new set<Id>();
            set<id> idForPriceBookEntry=new set<Id>();
            Map<String,Opportunity_Team_Member_Role__mdt> mapofLabeltoOppTeamMemberRoleMDT=new Map<String,Opportunity_Team_Member_Role__mdt>();

            
            map<id,id> OppIdQuoteId=new map<Id,id>();
            set<id> OpportunityId = new set<id>();
            for(QuoteLineItem quLineItem:newQuLineItemList){
                QuId.add(quLineItem.QuoteId);
                idForPriceBookEntry.add(quLineItem.PriceBookEntryID);
            }
                        
            List<Quote> oli = new List<Quote>([SELECT AccountId,OpportunityId FROM Quote WHERE Id IN: quId]);    
            for(Quote o : oli){
                AccountID.add(o.AccountId);
               	OppIdQuoteId.put(o.Id,o.OpportunityId);   
                OpportunityId.add(o.OpportunityId);
            }
            
            mapOfIdtoQu=getAccIdFromQuId(QuId);
            mapOfUserIdToTeams=getAccountTeams(AccountID);
            mapOfIdtoPriceBookEntry=getProductDetailsFromPricebokentryId(idForPriceBookEntry);

            //
            //Commented by JOEL
            //Skipping the product category validation for existing Sprint 1 code in UAT
            //
            //mapOfproductCatToAcessset=getMapOfUserAccessSet(userinfo.getuserId());
            
            //Code Added by Joel Tom to validate Opp team members
            Map<Id,Map<Id,String>> oppUserRoleMap = opportunityTriggerOfiUser.fetchOppTeamMemberAndRole(OpportunityId);
            mapofLabeltoOppTeamMemberRoleMDT = opportunityTriggerOfiUser.getOppTeamMemberRoleMDT('OpportunityLineItem');
            
            for(QuoteLineItem quLineItem:newQuLineItemList){
                if(!oppUserRoleMap.isEmpty()){
                    Id quoteId =  quLineItem.QuoteId;
                    Id oppid = OppIdQuoteId.get(quoteId);
                    if(oppUserRoleMap.containskey(oppid))
                    {
                        if(!(mapofLabeltoOppTeamMemberRoleMDT.containsKey(oppUserRoleMap.get(oppid).get(userinfo.getuserId())))){
                            lineItemValidationInsert(quLineItem,mapOfUserIdToTeams,mapOfIdtoQu,mapOfproductCatToAcessset,mapOfIdtoPriceBookEntry);}       
                    }
                    else{lineItemValidationInsert(quLineItem,mapOfUserIdToTeams,mapOfIdtoQu,mapOfproductCatToAcessset,mapOfIdtoPriceBookEntry);}  
                }
                else{lineItemValidationInsert(quLineItem,mapOfUserIdToTeams,mapOfIdtoQu,mapOfproductCatToAcessset,mapOfIdtoPriceBookEntry);}            
            }
        }
    }
            
    public static void checkUserAccessForUpdate(list<QuoteLineItem> newQuLineItemList,Map<Id,QuoteLineItem> newMapOFQupLineItem,Map<Id,QuoteLineItem> oldMapOfQuLineItem){
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Access_Set_Admins');
        if(!hasCustomPermission){      
            Map<id,Quote> mapOfIdtoQu=new Map<id,Quote>();
            Map<string,Teams__c> mapOfUserIdToTeams =new Map<string,Teams__c>();
            Map<string,Access_Set__c> mapOfproductCatToAcessset=new Map<string,Access_Set__c>();
            Map<id,QuoteLineItem> oldMapOfIdtoQuLine = new Map<id,QuoteLineItem>();
            Map<id,QuoteLineItem> newMapOfIdtoQuLine = new Map<id,QuoteLineItem>();
            set<id> QuId=new set<Id>();
            set<id> AccountID=new set<Id>();
        	Map<String,Opportunity_Team_Member_Role__mdt> mapofLabeltoOppTeamMemberRoleMDT=new Map<String,Opportunity_Team_Member_Role__mdt>();
            map<id,id> OppIdQuoteId=new map<Id,id>();
            set<id> OpportunityId = new set<id>();
            
            for(QuoteLineItem quLineItem:newQuLineItemList){
                QuId.add(quLineItem.QuoteId);                
            }
            
            List<Quote> oli = new List<Quote>([SELECT AccountId,OpportunityId FROM Quote WHERE Id IN: QuId]);
            for(Quote o : oli){
                AccountID.add(o.AccountId);
                OppIdQuoteId.put(o.Id,o.OpportunityId);   
                OpportunityId.add(o.OpportunityId);
            }
            
            //Code Added by Joel Tom to validate Opp team members
            Map<Id,Map<Id,String>> oppUserRoleMap = opportunityTriggerOfiUser.fetchOppTeamMemberAndRole(OpportunityId);
            mapofLabeltoOppTeamMemberRoleMDT = opportunityTriggerOfiUser.getOppTeamMemberRoleMDT('OpportunityLineItem');  
            mapOfIdtoQu=getAccIdFromQuId(quId);
            oldMapOfIdtoQuLine=getQuAndProductFromoppLine(oldMapOfQuLineItem);
            newMapOfIdtoQuLine=getQuAndProductFromoppLine(newMapOFQupLineItem);
            mapOfUserIdToTeams=getAccountTeams(AccountID);
            
            //
            //Commented by JOEL
            //Skipping the product category validation for existing Sprint 1 code in UAT
            //
            //mapOfproductCatToAcessset=getMapOfUserAccessSet(userinfo.getuserId());           
            for(QuoteLineItem quLineItem:newQuLineItemList){       
                if(!oppUserRoleMap.isEmpty()){
                    Id quoteId =  quLineItem.QuoteId;
                    Id oppid = OppIdQuoteId.get(quoteId);
                    if(oppUserRoleMap.containskey(oppid))
                    {
                        if(!(mapofLabeltoOppTeamMemberRoleMDT.containsKey(oppUserRoleMap.get(oppid).get(userinfo.getuserId())))){
                            lineItemValidationUpdate(quLineItem,mapOfUserIdToTeams,newMapOfIdtoQuLine,oldMapOfIdtoQuLine,mapOfproductCatToAcessset,mapOfIdtoQu);}        
                    }
                    else{
                        lineItemValidationUpdate(quLineItem,mapOfUserIdToTeams,newMapOfIdtoQuLine,oldMapOfIdtoQuLine,mapOfproductCatToAcessset,mapOfIdtoQu);}
                }
                else{
                    lineItemValidationUpdate(quLineItem,mapOfUserIdToTeams,newMapOfIdtoQuLine,oldMapOfIdtoQuLine,mapOfproductCatToAcessset,mapOfIdtoQu);}   
            }
        }     
    }
    
    public static void lineItemValidationInsert(QuoteLineItem quLineItem, Map<string,Teams__c> mapOfUserIdToTeams,Map<id,Quote> mapOfIdtoQu,Map<string,Access_Set__c> mapOfproductCatToAcessset, Map<Id,PricebookEntry> mapOfIdtoPriceBookEntry)
    {
        if((!mapOfUserIdToTeams.isEmpty())&& (!mapOfIdtoQu.isEmpty()) && (!mapOfIdtoPriceBookEntry.isEmpty()) /*&&(!mapOfproductCatToAcessset.isEmpty())*/){
            if((mapOfUserIdToTeams.containskey(String.ValueOF(mapOfIdtoQu.get(quLineItem.QuoteId).AccountId)+String.valueOf(userinfo.getuserId())))){
                if(mapOfUserIdToTeams.get(String.ValueOF(mapOfIdtoQu.get(quLineItem.QuoteId).AccountId)+String.valueOf(userinfo.getuserId())).Business_Unit__c==mapOfIdtoPriceBookEntry.get(quLineItem.PriceBookEntryID).Product2.Business_Unit__c ||mapOfUserIdToTeams.get(String.ValueOF(mapOfIdtoQu.get(quLineItem.QuoteId).AccountId)+String.valueOf(userinfo.getuserId())).Business_Unit__c==OpportunityConstants.OFI_BU_ALL){  
                    //
                    //Commented by JOEL
                    //Skipping the product category validation for existing Sprint 1 code in UAT
                    //
                    /*if(!mapOfproductCatToAcessset.isEmpty()){
                        if((mapOfproductCatToAcessset.containskey(String.valueOf(mapOfIdtoPriceBookEntry.get(quLineItem.PriceBookEntryID).Product2.Product_Category__c)+(String.valueOf(mapOfIdtoQu.get(quLineItem.QuoteId).Account.regions__c))))
                        ||((mapOfproductCatToAcessset.containskey(String.valueOf(mapOfIdtoPriceBookEntry.get(quLineItem.PriceBookEntryID).Product2.Product_Category__c)+(String.valueOf(mapOfIdtoQu.get(quLineItem.QuoteId).Account.billingcountrycode)))))
                        ||mapOfproductCatToAcessset.containskey('null'+(String.valueOf(mapOfIdtoQu.get(quLineItem.QuoteId).Account.billingcountrycode)))
                        ||mapOfproductCatToAcessset.containskey('null'+(String.valueOf(mapOfIdtoQu.get(quLineItem.QuoteId).Account.regions__c)))) 
                        {
                        }
                        else{quLineItem.addError('You have no access to this product category, region or the selected country. Please contact the administrator');}   
                        } */                                                                                                                                                                                                                                                                                                                                                                                }
                else{quLineItem.addError('You are not a part of the same business unit. Please contact the administrator');}   
            }else{quLineItem.addError('You have no permission to do this action. Please contact the administrator');}
        }else{quLineItem.addError('You are not part of this account. Please contact the administrator');} 
        
    }

    public static void lineItemValidationUpdate(QuoteLineItem quLineItem, Map<string,Teams__c> mapOfUserIdToTeams, Map<id,QuoteLineItem> newMapOfIdtoQuLine, Map<id,QuoteLineItem> oldMapOfIdtoQuLine,Map<string,Access_Set__c> mapOfproductCatToAcessset,Map<id,Quote> mapOfIdtoQu){
        
        if(!mapOfUserIdToTeams.isempty() && !newMapOfIdtoQuLine.isEmpty() && !oldMapOfIdtoQuLine.isEmpty() /* &&(!mapOfproductCatToAcessset.isEmpty()) */){
            if((mapOfUserIdToTeams.containskey(String.ValueOF(newMapOfIdtoQuLine.get(quLineItem.Id).Quote.AccountId)+String.valueOf(userinfo.getuserId())))){
                if((mapOfUserIdToTeams.get(String.ValueOF(newMapOfIdtoQuLine.get(quLineItem.Id).Quote.AccountId)+String.valueOf(userinfo.getuserId())).Business_Unit__c==(oldMapOfIdtoQuLine.get(quLineItem.Id).Product2.Business_Unit__c))&&((oldMapOfIdtoQuLine.get(quLineItem.Id).Product2.Family)==(newMapOfIdtoQuLine.get(quLineItem.Id).Product2.Family)) ||mapOfUserIdToTeams.get(String.ValueOF(newMapOfIdtoQuLine.get(quLineItem.Id).Quote.AccountId)+String.valueOf(userinfo.getuserId())).Business_Unit__c==OpportunityConstants.OFI_BU_ALL){
                    //
                    //Commented by JOEL
                    //Skipping the product category validation for existing Sprint 1 code in UAT
                    //
                    /*if(!mapOfproductCatToAcessset.isempty()){
                    if((mapOfproductCatToAcessset.containskey(String.valueOf(oldMapOfIdtoQuLine.get(quLineItem.Id).Product2.Product_Category__c)+(String.valueOf(mapOfIdtoQu.get(quLineItem.QuoteId).Account.regions__c))))
                    ||((mapOfproductCatToAcessset.containskey(String.valueOf(oldMapOfIdtoQuLine.get(quLineItem.Id).Product2.Product_Category__c)+(String.valueOf(mapOfIdtoQu.get(quLineItem.QuoteId).Account.billingcountrycode)))))
                    ||mapOfproductCatToAcessset.containskey('null'+(String.valueOf(mapOfIdtoQu.get(quLineItem.QuoteId).Account.billingcountrycode)))
                    ||mapOfproductCatToAcessset.containskey('null'+(String.valueOf(mapOfIdtoQu.get(quLineItem.QuoteId).Account.regions__c))))
                    {
                    }
                    else{quLineItem.addError('You have no access to this product category, region or the selected country. Please contact the administrator');}   
                    }*/
                }else{quLineItem.addError('You are not a part of the same business unit. Please contact the administrator');}   
            }else{quLineItem.addError('You have no permission to do this action. Please contact the administrator');}
        }else{quLineItem.addError('You are not part of this account. Please contact the administrator');} 
    }
    
   /* public static  Map<string,Access_Set__c> getMapOfUserAccessSet(id userId){
        List<Access_Set_Assignment__c> listOfAccessSetAssgnmnt= new List<Access_Set_Assignment__c>();
        set<id> idOfUserAcessSet=new set<id>();
        Map<string,Access_Set__c> mapOfproductCatToAcessset=new Map<string,Access_Set__c>();
        
        listOfAccessSetAssgnmnt=[Select Id,Access_Set__c,User__c,Account_Teams_Creation_Status__c 
                                 from Access_Set_Assignment__c 
                                 where User__c =:userId];
        for(Access_Set_Assignment__c accessSetAssgnments:listOfAccessSetAssgnmnt)
        {
            idOfUserAcessSet.add(accessSetAssgnments.Access_Set__c);
        }
        
        List<Access_Set__c> listOfUserAccessSet = [Select Id,Name,Region__c,Country__c,Customer_Group__c,Channel__c,Product_Category__c from Access_Set__c where Id IN: idOfUserAcessSet];
        
        for(Access_Set__c UserAccessSet:listOfUserAccessSet)
        {
            if(UserAccessSet.Country__c!=null){ 
                mapOfproductCatToAcessset.put(String.valueof(UserAccessSet.Product_Category__c)+String.valueOf(UserAccessSet.Country__c),UserAccessSet);
            }else{
                mapOfproductCatToAcessset.put(String.valueof(UserAccessSet.Product_Category__c)+String.valueOf(UserAccessSet.Region__c),UserAccessSet);        
            } 
        }
        return mapOfproductCatToAcessset; 
    }*/
    
    public static Map<id,QuoteLineItem> getQuAndProductFromoppLine(Map<id,QuoteLineItem> mapOfQuLine){
        Map<id,QuoteLineItem> mapOfIdtoOppLine = new Map<id,QuoteLineItem>([SELECT Quote.AccountId,Product2.Product_Category__c, Product2.Family, Product2.Business_Unit__c FROM QuoteLineItem WHERE Id IN: mapOfQuLine.keySet()]); 
        return mapOfIdtoOppLine;
    }
    
    public static Map<id,Quote> getAccIdFromQuId(set<id> QuId){
        Map<id,Quote> mapOfIdtoOpp=new Map<id,Quote>([SELECT Id, Name, AccountId,Account.billingcountrycode,Account.regions__c FROM Quote WHERE Id IN:QuId]);
        return mapOfIdtoOpp;
    }
    
    public static Map<id,PricebookEntry> getProductDetailsFromPricebokentryId(set<id> idForPriceBookEntry){
        Map<id,PricebookEntry> mapOfIdtoPriceBookEntry=new Map<id,PricebookEntry>([SELECT Id, Name,Product2.Product_Category__c, Product2.Family, Product2.Business_Unit__c  FROM PricebookEntry WHERE Id IN:idForPriceBookEntry]);
        return mapOfIdtoPriceBookEntry;
    }
    public static Map<string,Teams__c> getAccountTeams(Set<id> accntId)
    {
        list<Teams__c> listOfTeams=[Select id,Name,Business_Unit__c,Account__c,Is_Primary__c,User__c,Access_Level__c from Teams__c where Access_Level__c=:OpportunityConstants.EDIT_ACCESS AND Account__c IN:accntId];
        Map<string,Teams__c> mapOfUserIdToTeams =new Map<string,Teams__c>();
        For(Teams__c tempTeam: listOfTeams){
            mapOfUserIdToTeams.put(String.valueOf(tempTeam.Account__c) + String.valueOF(tempTeam.User__c),tempTeam);
        }
        return mapOfUserIdToTeams;
    }
    
}