src/objects/Access_Set__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Regions</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Access Set</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Access Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Others ( e-commerce, etc.)</fullName>
    </customValue>
    <customValue>
        <fullName>Private Label / Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Product Group or Brand Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Trade House</fullName>
    </customValue>
    <customValue>
        <fullName>B2B Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Food Service / Quick Service Restaurants</fullName>
    </customValue>
    <customValue>
        <fullName>Importer / Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Channel TWO</fullName>
        <isActive>false</isActive>
        <label>Channel TWO</label>
    </customValue>
    <customValue>
        <fullName>Channel ONE</fullName>
        <isActive>false</isActive>
        <label>Channel ONE</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Regions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>EMENA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

src/classes/AccessSetTriggerHelper.cls
public class AccessSetTriggerHelper {
    public static void populateUniqueId(List<Access_Set__c> listOfAccessSet){
        for(Access_Set__c accessSet : listOfAccessSet){
            String uniqueId = '';
            uniqueId = String.isNotBlank(accessSet.Regions__c) ? uniqueId+accessSet.Regions__c: uniqueId;
            uniqueId = String.isNotBlank(accessSet.Country__c) ? uniqueId+accessSet.Country__c: uniqueId;
            uniqueId = String.isNotBlank(accessSet.Customer_Group__c) ? uniqueId+accessSet.Customer_Group__c: uniqueId;
            uniqueId = String.isNotBlank(accessSet.Channel__c) ? uniqueId+accessSet.Channel__c: uniqueId;
            uniqueId = String.isNotBlank(accessSet.BU__c) ? uniqueId+accessSet.BU__c: uniqueId;
            uniqueId = String.isNotBlank(accessSet.Product_Category__c) ? uniqueId+accessSet.Product_Category__c: uniqueId;
            //+String.isNotBlank(accessSet.Country__c)+String.isNotBlank(accessSet.Customer_Group__c)+String.isNotBlank(accessSet.Channel__c)+String.isNotBlank(accessSet.BU__c)+String.isNotBlank(accessSet.Product_Category__c);
            accessSet.Unique_Key__c = uniqueId;
        }
    }
    
}