src/objects/Access_Set_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set__c</fullName>
        <label>Access Set</label>
        <referenceTo>Access_Set__c</referenceTo>
        <relationshipLabel>Access Set Assignments</relationshipLabel>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Access Set Assignment</label>
    <nameField>
        <displayFormat>ASM-{0000000000}</displayFormat>
        <label>Access Set Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Set Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WET</fullName>
                </value>
                <value>
                    <fullName>FAT</fullName>
                </value>
                <value>
                    <fullName>DRY</fullName>
                </value>
                <value>
                    <fullName>MISCELLANEOUS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Volume_MT__c</fullName>
        <inlineHelpText>Possible / Potential Volume Olam (MT) expects to get</inlineHelpText>
        <label>Estimated Volume</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Sample_Due_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Sample Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key_Driver_to_Win_Project__c</fullName>
        <label>Key Driver to Win Project</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cost</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Time to Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sample</fullName>
                </value>
                <value>
                    <fullName>Match</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Application Development</fullName>
                    <isActive>false</isActive>
                    <label>Application Development</label>
                </value>
                <value>
                    <fullName>Co-development</fullName>
                    <isActive>false</isActive>
                    <label>Co-development</label>
                </value>
                <value>
                    <fullName>Ingredient Development</fullName>
                    <isActive>false</isActive>
                    <label>Ingredient Development</label>
                </value>
                <value>
                    <fullName>New Development</fullName>
                    <isActive>false</isActive>
                    <label>New Development</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>DAIRY</fullName>
                </value>
                <value>
                    <fullName>DAIRY ALTERNATIVES</fullName>
                </value>
                <value>
                    <fullName>FROZEN DAIRY</fullName>
                </value>
                <value>
                    <fullName>FILLINGS (WB)</fullName>
                </value>
                <value>
                    <fullName>SYRUPS (WB)</fullName>
                </value>
                <value>
                    <fullName>BEVERAGES</fullName>
                </value>
                <value>
                    <fullName>CHOCOLATE (LIKE)</fullName>
                </value>
                <value>
                    <fullName>CONFECTIONERY MIXES</fullName>
                </value>
                <value>
                    <fullName>FILLINGS (FB)</fullName>
                </value>
                <value>
                    <fullName>SPREADS (FB)</fullName>
                </value>
                <value>
                    <fullName>SYRUPS (FB)</fullName>
                </value>
                <value>
                    <fullName>DECORATION</fullName>
                </value>
                <value>
                    <fullName>DAIRY MIXES</fullName>
                </value>
                <value>
                    <fullName>INSTANT MIXES</fullName>
                </value>
                <value>
                    <fullName>BAKERY MIXES</fullName>
                </value>
                <value>
                    <fullName>REPACKING</fullName>
                </value>
                <value>
                    <fullName>BAKERY</fullName>
                </value>
                <value>
                    <fullName>CEREALS</fullName>
                </value>
                <value>
                    <fullName>OTHER APPLICATIONS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Segment__c</fullName>
        <label>Sub Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Segment__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chocolate milk</fullName>
                </value>
                <value>
                    <fullName>Milk shake</fullName>
                </value>
                <value>
                    <fullName>Pudding</fullName>
                </value>
                <value>
                    <fullName>Custard</fullName>
                </value>
                <value>
                    <fullName>Mousse</fullName>
                </value>
                <value>
                    <fullName>Yoghurt</fullName>
                </value>
                <value>
                    <fullName>Chocolate cream</fullName>
                </value>
                <value>
                    <fullName>Cream Cheese</fullName>
                </value>
                <value>
                    <fullName>Remaining wet dairy products</fullName>
                </value>
                <value>
                    <fullName>Beverages</fullName>
                </value>
                <value>
                    <fullName>Desserts</fullName>
                </value>
                <value>
                    <fullName>Ice Cream</fullName>
                </value>
                <value>
                    <fullName>Yogurts</fullName>
                </value>
                <value>
                    <fullName>Other dairy alternatives</fullName>
                </value>
                <value>
                    <fullName>Ice (Cream)</fullName>
                </value>
                <value>
                    <fullName>Frozen yoghurt</fullName>
                </value>
                <value>
                    <fullName>Other frozen dairy products</fullName>
                </value>
                <value>
                    <fullName>Marshmallow</fullName>
                </value>
                <value>
                    <fullName>Cream fillings (WB)</fullName>
                </value>
                <value>
                    <fullName>Hard candy fillings (WB)</fullName>
                </value>
                <value>
                    <fullName>Foam fillings</fullName>
                </value>
                <value>
                    <fullName>Fondant Fillings</fullName>
                </value>
                <value>
                    <fullName>Other WB fillings</fullName>
                </value>
                <value>
                    <fullName>Modifier for chocolate drinks (WB)</fullName>
                </value>
                <value>
                    <fullName>Toppings (WB)</fullName>
                </value>
                <value>
                    <fullName>Bread spreads (WB)</fullName>
                </value>
                <value>
                    <fullName>Frostings / Fudges (WB)</fullName>
                </value>
                <value>
                    <fullName>Cereal Coatings (WB)</fullName>
                </value>
                <value>
                    <fullName>Other WB syrups</fullName>
                </value>
                <value>
                    <fullName>Hot Coffee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Margin__c</fullName>
        <label>Target Margin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Selling_Price__c</fullName>
        <label>Target Selling Price (Per Unit)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM(Sample)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KG</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>MT</fullName>
                    <label>Metric Ton</label>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>LB</fullName>
                    <label>US pound</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <defaultValue>&quot;Read Access&quot;</defaultValue>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read Access</fullName>
                </value>
                <value>
                    <fullName>Edit Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/classes/OFI_OpportunityTriggerTest.cls
@isTest
public class OFI_OpportunityTriggerTest {
    

    @isTest 
    static void testGetDetails () {
        
        
        Access_Set__c accset = OFI_TestDataFactory.createAccessSet('country', null, 'In', 'All', null, null, null, true);
        
        
        Profile p = [select id from profile where name='OFI'];
        
        User u = new User(alias = 'test123', email='test123@noemail.com',
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                          localesidkey='en_US', profileid = p.Id,
                          timezonesidkey='America/Los_Angeles', username='test123@noemail.com'/*, Access_Set_Role__c = 'PDI'*/ );
        insert u; 
        User u2 = new User(alias = 'test1234', email='test123@noemail.com2',
                          emailencodingkey='UTF-8', lastname='Testing2', languagelocalekey='en_US',
                          localesidkey='en_US', profileid = p.Id,
                          timezonesidkey='America/Los_Angeles', username='test123@noemail.com2'/*, Access_Set_Role__c = 'PDI'*/ );
        insert u2; 
        User u3 = new User(alias = 't13234', email='test1fa23@nafoemail.com2',
                          emailencodingkey='UTF-8', lastname='Tessfting2', languagelocalekey='en_US',
                          localesidkey='en_US', profileid = p.Id,
                          timezonesidkey='America/Los_Angeles', username='test123@noemasfsil.csom2'/*, Access_Set_Role__c = 'PDI'*/ );
        insert u3; 
        
        Access_Set_Assignment__c accsetass1=OFI_TestDataFactory.createAccessSetAssignment(accset.Id, u.id, /*, 'PDI'*/ true);
        Access_Set_Assignment__c accsetass2=OFI_TestDataFactory.createAccessSetAssignment(accset.Id, u2.id, /*, 'PDI'*/ true);

        
        Account acc= OFI_TestDataFactory.createMultipleAccount('Test', 'India','In', null, null, null, true);
        Account acc1= OFI_TestDataFactory.createMultipleAccount('Test1', 'India','In', null, null, null, true);

        Set<id> userIds = new Set<id>();
        userIds.add(u.Id);
        userIds.add(u2.Id);
        
        Teams__c teamSpice = new Teams__c(Account__c =acc.id,Access_Level__c= 'Edit Access',Business_Unit__c ='Spice',User__c=u3.id);   
        insert teamSpice;
        
        List<Teams__c> TeamUpdate = [Select Id,Access_Level__c,User__c from Teams__c where User__c IN : userIds];
        for(Teams__c obj : TeamUpdate){
            obj.Access_Level__c = 'Edit Access';
        }
        update TeamUpdate;
        
        Product2 prod = new Product2(Name = 'Laptop X200', Family = 'Hardware');
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod.Id, UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry(Pricebook2Id = customPB.Id, Product2Id = prod.Id, UnitPrice = 12000, IsActive = true);
        insert customPrice;
        
        Contact c= new Contact(AccountId=acc.id,Lastname='jack',Email='jakck@gmail.com');   
        insert c;
        Contact c2= new Contact(AccountId=acc1.id,Lastname='jack3',Email='jakck3@gmai3l.com');   
        insert c2;
        
        Opportunity opp1 = new Opportunity(Name='TestOpportunity', 
                                           AccountId=acc.Id, CloseDate=Date.Today(), StageName='Suspect',
                                           Business_unit__c ='Cocoa',
                                          RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId());
        insert opp1;
        OpportunityTeamMember oppt=new OpportunityTeamMember(OpportunityId=opp1.id,TeamMemberRole='PD&I Member',UserId=u2.Id);
        insert oppt;
        OpportunityContactRole ocr =new OpportunityContactRole(OpportunityId=opp1.Id,ContactId=c2.id);
        insert ocr;
        
       
        OpportunityLineItem oli1 = new OpportunityLineItem(OpportunityId = opp1.Id, Quantity = 5, PricebookEntryId = customPrice.Id, TotalPrice = 500);
        insert oli1;
        oli1.Quantity=6;
        update oli1;
        System.runAs(u){
            oli1.Quantity=12;
            try{
                update oli1; }catch(DMLException ex){}
            
            Opportunity oppTest = [Select Id, Name from Opportunity where id =: opp1.Id];
            System.debug('***oppTest '+oppTest);
             OpportunityLineItem oliTest = new OpportunityLineItem(OpportunityId = oppTest.Id, Quantity = 5, PricebookEntryId = customPrice.Id, TotalPrice = 500);
            try{
            insert oliTest;
            update oliTest;
            }catch(Exception e){}

            test.startTest();

            Contact c1= new Contact(AccountId=acc.id,Lastname='jack1',Email='jakk@gmail.com');   
            insert c1;
            
            Opportunity opp1new = new Opportunity(Name='TestOpportunityforuser', 
                                                  AccountId=acc1.Id, CloseDate=Date.Today(), StageName='Suspect',Business_unit__c = 'Cocoa', 
                                                  Pricebook2Id=customPB.Id);
            
            try{
                insert opp1new;
            }Catch(Exception e){}
            
            OpportunityContactRole ocr2 =new OpportunityContactRole(OpportunityId=opp1new.Id,ContactId=c2.id);
        	insert ocr2;
            
            Opportunity opdef = new Opportunity(Name = 'Test Opp2',AccountId =acc.id,CloseDate=system.today()+30,Description='test',Estimated_Volume_MT__c =3,Target_Selling_Price__c=2,
                                                Target_Margin__c='Low',Key_Driver_to_Win_Project__c ='Cost',First_Sample_Due_Date__c=system.today()+10,	CurrencyIsoCode ='USD',
                                                Category__c='WET',Segment__c ='DAIRY',Sub_Segment__c ='Chocolate milk',
                                                StageName= 'Briefing',Pricebook2Id=customPB.id, Business_unit__c = 'Cocoa'
                                                ,RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Defend Opportunity').getRecordTypeId());
            
            try{
                insert opdef;
            }Catch(Exception e){}
            OpportunityContactRole ocr3 =new OpportunityContactRole(OpportunityId=opdef.Id,ContactId=c.id);
        	insert ocr3;
            
            Opportunity opdev = new Opportunity(Name = 'Test Opp develop',AccountId =acc.id,CloseDate=system.today()+30,Description='test',Estimated_Volume_MT__c =22,Target_Selling_Price__c=3,
                                                Target_Margin__c='Low',Key_Driver_to_Win_Project__c ='Cost',First_Sample_Due_Date__c=system.today()+10,CurrencyIsoCode ='USD',
                                                Category__c='WET',Segment__c ='DAIRY',Sub_Segment__c ='Chocolate milk',
                                                StageName= 'Briefing',Pricebook2Id=customPB.id, Business_unit__c = 'Dairy'
                                                ,RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Develop Opportunity').getRecordTypeId());
            
            try{
                insert opdev;
            }Catch(Exception e){}
            OpportunityContactRole ocr4 =new OpportunityContactRole(OpportunityId=opdev.Id,ContactId=c.id);
        	insert ocr4;
            
            Opportunity opp = new Opportunity(Name='TestOpportunity',Business_Unit__c='Dairy', AccountId=acc.Id, CloseDate=Date.Today(), StageName='Suspect', Pricebook2Id=customPB.Id,RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Develop Opportunity').getRecordTypeId());
            opp.Project_Type__c = 'Sample';
            try{
                insert opp;}catch(Exception e){}
            OpportunityContactRole ocr5 =new OpportunityContactRole(OpportunityId=opp.Id,ContactId=c.id);
        	insert ocr5;
            
            Opportunity oppNull = new Opportunity(Name='TestOpportunityBUnull', Business_unit__c ='', AccountId=acc.Id, CloseDate=Date.Today(), StageName='Suspect', Pricebook2Id=customPB.Id);
            try{
                insert oppNull;
            }catch(Exception e){}               
            try{
            
            OpportunityContactRole ocr1 =new OpportunityContactRole(OpportunityId=opp.Id,ContactId=c1.id);
            insert ocr1;
            opp.Amount=12;
            
            update opp;
            
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id, Quantity = 5, PricebookEntryId = customPrice.Id, TotalPrice = 500, UoM__c='KG', Sampling_Status__c='1', Quantity_of_Sample_Grams__c=2);
            
                insert oli;
            }catch(DMLException ex){}
            
            oli1.Quantity=12;
            try{
                update oli1; }catch(DMLException ex){}
            
            test.stopTest();
           
        }
        System.runAs(u3){
            Opportunity opp13 = new Opportunity(Name='TestOpportunityGain1', 
                                           AccountId=acc.Id, CloseDate=Date.Today(), StageName='Suspect',
                                          RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId());
        insert opp13;

        OpportunityContactRole ocr76 =new OpportunityContactRole(OpportunityId=opp13.Id,ContactId=c2.id);
        insert ocr76;
        }
    }
    /*
    @isTest
    static void test_getMapOfUserAccessSet()
    {
        List<User> user = [Select Id, Name From User where email='test123@noemail.com'];
        OFI_OpportunityLineItemHandler.getMapOfUserAccessSet(user[0].Id);
    }*/
    
}