src/objects/Access_Set__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant_Access_By__c</fullName>
        <label>Grant Access By</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Pardot_Region</valueSetName>
        </valueSet>
    </fields>
    <label>Access Set</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Access Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Access_Set_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set__c</fullName>
        <label>Access Set</label>
        <referenceTo>Access_Set__c</referenceTo>
        <relationshipLabel>Access Set Assignments</relationshipLabel>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Access Set Assignment</label>
    <nameField>
        <displayFormat>ASM-{0000000000}</displayFormat>
        <label>Access Set Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Set Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Engagement_Plan__c.object
<CustomObject>
    <label>Engagement Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Engagement Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Pardot_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>EMENA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and North Africa</fullName>
        <isActive>false</isActive>
        <label>Middle East and North Africa</label>
    </customValue>
    <customValue>
        <fullName>West Europe</fullName>
        <isActive>false</isActive>
        <label>West Europe</label>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
        <isActive>false</isActive>
        <label>South America</label>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
        <isActive>false</isActive>
        <label>North America</label>
    </customValue>
    <customValue>
        <fullName>Central America</fullName>
        <isActive>false</isActive>
        <label>Central America</label>
    </customValue>
    <customValue>
        <fullName>East Asia</fullName>
        <isActive>false</isActive>
        <label>East Asia</label>
    </customValue>
    <customValue>
        <fullName>Central Asia</fullName>
        <isActive>false</isActive>
        <label>Central Asia</label>
    </customValue>
    <customValue>
        <fullName>Southern Asia</fullName>
        <isActive>false</isActive>
        <label>Southern Asia</label>
    </customValue>
    <customValue>
        <fullName>Sub Sahara Africa</fullName>
        <isActive>false</isActive>
        <label>Sub Sahara Africa</label>
    </customValue>
    <customValue>
        <fullName>East Europe and Russia</fullName>
        <isActive>false</isActive>
        <label>East Europe and Russia</label>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
        <isActive>false</isActive>
        <label>Middle East</label>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
        <isActive>false</isActive>
        <label>South East Asia</label>
    </customValue>
    <customValue>
        <fullName>Australia and New Zealand</fullName>
        <isActive>false</isActive>
        <label>Australia and New Zealand</label>
    </customValue>
    <masterLabel>Pardot Region</masterLabel>
</GlobalValueSet>

src/classes/EngagementPlansTrigger_Test.cls
@isTest
public class EngagementPlansTrigger_Test {

    @testSetup
    public static void createData()
{
    UserRole r = [select id,name from UserRole where name LIKE '%Cocoa%' limit 1];
        Profile prof = [select id,name from profile where name LIKE '%Cocoa%' limit 1]; 
    User usr1 = new User(ProfileId = prof.Id, LastName = 'OLTest01', Email = 'olam.test@test.olam.com1',
                             Username = 'olam.test@test.olam.com1' + System.currentTimeMillis(), CompanyName = 'TEST', Title = 'title',
                             Alias = 'OLTest02', TimeZoneSidKey = 'America/Los_Angeles', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US',
                             LocaleSidKey = 'en_US');    
        insert usr1;
    Access_Set__c access1 = new Access_Set__c(Grant_Access_By__c = 'Country',BU__c = 'All' , Region__c = null , Country__c = 'IN');
        insert access1; 
    Access_Set_Assignment__c assign = OFI_TestDataFactory.createAccessSetAssignment(access1.Id, usr1.Id,//'Sales',
                                                                                    true);
    System.runAs(usr1){
    Account acc = new Account();
            acc.name='Test01';
            acc.BillingCountry = 'India';
            acc.BillingStreet ='Test';
            insert acc;
    Engagement_Plan__c ep = OFI_TestDataFactory.createEngagementPlan(acc.Id, 'Dairy', true);
        
    }
}
    @isTest
    public static void testData()
{
    User u = [Select Id, Name From User where Email =: 'olam.test@test.olam.com1'];
    System.runAs(u){
   List<Engagement_Plan__c> ep = [Select Id,Name From Engagement_Plan__c];
   ep[0].Name = 'Demo Plan 2';
        update ep;
    }
}
}