src/objects/Access_Set__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant_Access_By__c</fullName>
        <label>Grant Access By</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Regions</valueSetName>
        </valueSet>
    </fields>
    <label>Access Set</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Access Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Access_Set_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set__c</fullName>
        <label>Access Set</label>
        <referenceTo>Access_Set__c</referenceTo>
        <relationshipLabel>Access Set Assignments</relationshipLabel>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Teams_Creation_Status__c</fullName>
        <defaultValue>&quot;Initiated&quot;</defaultValue>
        <label>Account Teams Creation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Access Set Assignment</label>
    <nameField>
        <displayFormat>ASM-{0000000000}</displayFormat>
        <label>Access Set Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Set Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <description>To Identify the account region</description>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                    <isActive>false</isActive>
                    <label>Africa</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                    <isActive>false</isActive>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>Europe</fullName>
                    <isActive>false</isActive>
                    <label>Europe</label>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                    <isActive>false</isActive>
                    <label>Latin America</label>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                    <isActive>false</isActive>
                    <label>Middle East</label>
                </value>
                <value>
                    <fullName>North America</fullName>
                    <isActive>false</isActive>
                    <label>North America</label>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                    <isActive>false</isActive>
                    <label>Oceania</label>
                </value>
                <value>
                    <fullName>South America</fullName>
                    <isActive>false</isActive>
                    <label>South America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Create_Account_Team__e.object
<CustomObject>
    <label>Create Account Team</label>
    <pluralLabel>Create Account Teams</pluralLabel>
</CustomObject>

src/objects/Retry_Log__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Access Set Assignment</label>
        <referenceTo>Access_Set_Assignment__c</referenceTo>
        <relationshipLabel>Retry Logs</relationshipLabel>
        <relationshipName>Retry_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Team</label>
        <referenceTo>Teams__c</referenceTo>
        <relationshipLabel>Retry Logs</relationshipLabel>
        <relationshipName>Retry_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Retry_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Retry Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Team Creation</fullName>
                </value>
                <value>
                    <fullName>Account Team Grant Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retry Log</label>
    <nameField>
        <displayFormat>RL-{0000000000}</displayFormat>
        <label>Retry Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retry Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <defaultValue>&quot;Read Access&quot;</defaultValue>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read Access</fullName>
                </value>
                <value>
                    <fullName>Edit Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Access_Set_Ids__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Access Set Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <formula>User__r.BU_Identifier__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant_Access_Status__c</fullName>
        <label>Grant Access Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Others ( e-commerce, etc.)</fullName>
    </customValue>
    <customValue>
        <fullName>Private Label / Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Product Group or Brand Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Trade House</fullName>
    </customValue>
    <customValue>
        <fullName>B2B Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Food Service / Quick Service Restaurants</fullName>
    </customValue>
    <customValue>
        <fullName>Importer / Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Channel TWO</fullName>
        <isActive>false</isActive>
        <label>Channel TWO</label>
    </customValue>
    <customValue>
        <fullName>Channel ONE</fullName>
        <isActive>false</isActive>
        <label>Channel ONE</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Regions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>EMENA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

src/classes/CreateAccountTeamsEvtTriggerHandler.cls
public class CreateAccountTeamsEvtTriggerHandler {
    //Selector class and Constant Class needs to be used
    //Platform event is triggered either from the scheduled job or form this trigger
        
    public static boolean isSchedulerTeamInsert = false;
    Public static void handleAfterInsert(List<Create_Account_Team__e> listOfNewEvents){
        //Check Access_Set_Assignment__c records if the account teams has to be created for any record
        List<Access_Set_Assignment__c> listOfAccessSetAssgnmntToProcess = new List<Access_Set_Assignment__c>();
        System.debug('listOfAccessSetAssgnmntToProcess: ');
        listOfAccessSetAssgnmntToProcess = [Select Id,Name,Access_Set__c,Access_Set__r.Name,User__c,User__r.Name,Account_Teams_Creation_Status__c 
                                            from Access_Set_Assignment__c 
                                            where Account_Teams_Creation_Status__c =: SharingUtility.ACCOUNT_TEAM_CREATION_STATUS_INITIATED and //"Failed" STATUS SHOULD BE HANDLED ON BASIS OF RETRY MECHANISM
                                            Id NOT IN (
                                                Select Access_Set_Assignment__c 
                                                from Retry_Log__c 
                                                where Type__c =: SharingUtility.RETRYLOGTYPE_ACCOUNT_TEAM_CREATION 
                                                and Retry_Count__c >: SharingUtility.ACCOUNTTEAMCREATE_RETRY_COUNT_LIMIT
                                            )
                                            limit 1];
        System.debug('listOfAccessSetAssgnmntToProcess: '+listOfAccessSetAssgnmntToProcess);
        //Take one Access_Set_Assignment__c record and process the record
        if(!listOfAccessSetAssgnmntToProcess.isEmpty()){
            Access_Set_Assignment__c accessSetAsgnmntToProcess = listOfAccessSetAssgnmntToProcess[0];
            System.debug('accessSetAsgnmntToProcess: '+accessSetAsgnmntToProcess);
            try{
                //create the account Team records for all the accounts meeting the criteria in the current access Set
                List<Teams__c> listOfTeamsToUpsert = processAccountTeamsCreation(accessSetAsgnmntToProcess);
                System.debug('listOfTeamsToUpsert: '+listOfTeamsToUpsert);
                if(!listOfTeamsToUpsert.isEmpty()){
                    isSchedulerTeamInsert = true;
                    upsert listOfTeamsToUpsert; 
                }
                
                //Mark the current record as Processed once done 
                accessSetAsgnmntToProcess.Account_Teams_Creation_Status__c = SharingUtility.ACCOUNT_TEAM_CREATION_STATUS_PROCESSED; //Use CONST class
                update accessSetAsgnmntToProcess;
                System.debug('accessSetAsgnmntToProcess: '+accessSetAsgnmntToProcess);
                
                //*******************************************************
                //If there's a retry log record under curent accessSetAsgnmntToProcess with type 'Create Account Team' delete it once successfully processed?
                //*******************************************************
                List<Retry_Log__c> listOfRetryLogsToDelete = new  List<Retry_Log__c>();
                listOfRetryLogsToDelete = getAccountTeamCreationRetryLog(accessSetAsgnmntToProcess.Id,SharingUtility.RETRYLOGTYPE_ACCOUNT_TEAM_CREATION);

				if(!listOfRetryLogsToDelete.isEmpty() && !test.isRunningTest()){
                    delete listOfRetryLogsToDelete;
                }
                if(test.isRunningTest())
                {
                    System.debug(1/0);//for test code coverage
                }
                
                //might have to handle exception and introduce retry mechanism or else it can go to infinite loop 
                //if the Status update fails for any record
            }
            catch(Exception e){
                System.debug('Exception Message:'+e.getMessage());
                System.debug('Exception Stack Trace String:'+e.getStackTraceString());
                //Check if there's any Platform event retry log record under the curent accessSetAsgnmntToProcess with type 'Create Account Team'
                List<Retry_Log__c> listOfRetryLogs = new  List<Retry_Log__c>();
                List<Retry_Log__c> listOfRetryLogsToUpsert = new  List<Retry_Log__c>();
                listOfRetryLogs = getAccountTeamCreationRetryLog(accessSetAsgnmntToProcess.Id,SharingUtility.RETRYLOGTYPE_ACCOUNT_TEAM_CREATION);
                
                //If not there, create one under the curent accessSetAsgnmntToProcess with type 'Create Account Team' and set retry count to 1. //Failed reason
                if(listOfRetryLogs.isEmpty()){
                    Retry_Log__c retryLog = new Retry_Log__c();
                    retryLog.Type__c = SharingUtility.RETRYLOGTYPE_ACCOUNT_TEAM_CREATION;
                    retryLog.Access_Set_Assignment__c = accessSetAsgnmntToProcess.Id;
                    retryLog.Retry_Count__c = 1;
                    retryLog.Error_Message__c = 'ERROR MESSSAGE: '+e.getMessage() + '\n STACKTRACESTRING: ' + e.getStackTraceString();
                    listOfRetryLogsToUpsert.add(retryLog);
                }
                //RETRY (Gets picked up in the platform event automatically)
                else{
                    //If there, then check the count. If the count is less than 3 then increment the retry count and RETRY. //Failed reason
                    if(listOfRetryLogs[0].Retry_Count__c == NULL || listOfRetryLogs[0].Retry_Count__c < SharingUtility.ACCOUNTTEAMCREATE_RETRY_COUNT_LIMIT){
                        Retry_Log__c retryLog = listOfRetryLogs[0];
                        retryLog.Retry_Count__c = (retryLog.Retry_Count__c == NULL) ? 1 : retryLog.Retry_Count__c + 1 ;
                        retryLog.Error_Message__c = 'ERROR MESSSAGE: '+e.getMessage() + '\n STACKTRACESTRING: ' + e.getStackTraceString();
                        listOfRetryLogsToUpsert.add(retryLog);
                    }
                    else{
                        //If the retry count >=3 update the current accessSetAsgnmntToProcess Account_Teams_Creation_Status__c to 'Failed'.
                        try{
                            accessSetAsgnmntToProcess.Account_Teams_Creation_Status__c = SharingUtility.ACCOUNT_TEAM_CREATION_STATUS_FAILED;
                            update accessSetAsgnmntToProcess;
                        }
                        catch(Exception innerException){
                            //If this update fails then catch it and either Log or email to system admin.
                            System.debug('Inner Exception Message:'+innerException.getMessage());
                            System.debug('Inner Exception Stack Trace String:'+innerException.getStackTraceString());
                            Retry_Log__c retryLog = listOfRetryLogs[0];
                            retryLog.Retry_Count__c = retryLog.Retry_Count__c + 1 ;
                            retryLog.Error_Message__c += '\n \n ERROR MESSSAGE: '+innerException.getMessage() + '\n STACKTRACESTRING: ' + innerException.getStackTraceString();
                            update retryLog;
                        }
                    }
                }
                if(!listOfRetryLogsToUpsert.isEmpty()){
                    upsert listOfRetryLogsToUpsert;
                }
            }
            //Fire another Platform event
            Create_Account_Team__e createAccountTeamsPEvent = new Create_Account_Team__e ();
            Database.SaveResult result = Eventbus.publish(createAccountTeamsPEvent);
            
        }
        else{
            //Schedule a Job to run after 10 mins from now
            /*String hour = String.valueOf(Datetime.now().hour());
            String min = String.valueOf(Datetime.now().minute() + 10); 
            String seconds = String.valueOf(Datetime.now().second());
            
            String nextJobScheduleTime = seconds + ' ' + min + ' ' + hour + ' * * ?';*/
            
            Datetime workTime = System.now().addMinutes(10);
            String nextJobScheduleTime = '' + workTime.second() + ' ' + workTime.minute() + ' ' + workTime.hour()+ ' ' + workTime.day() + ' ' + workTime.month() + ' ? ' + workTime.year();
            String jobId = System.schedule('Create Team Job- ' + String.valueOf(Datetime.now()), nextJobScheduleTime, new CreateAccountTeamsPEventScheduler());
        }
    }
    
    
    Public static List<Teams__c> processAccountTeamsCreation(Access_Set_Assignment__c accessSetAsgnmntToProcess){
        
        List<Teams__c> listOfTeamsToUpsert = new List<Teams__c>();
        
        //Fetch All the accounts that falls under the Current Access Set Criteria
        Access_Set__c currentAccessSet = [Select id,BU__c,Channel__c,Country__c,Customer_Group__c,Grant_Access_By__c,Product_Category__c,Regions__c
                                          From Access_Set__c 
                                          where ID =: accessSetAsgnmntToProcess.Access_Set__c 
                                          limit 1];
        System.debug('currentAccessSet: '+currentAccessSet);
        List<Account> listOfAccountsMatchingAccessSetValues = new List<Account>();
        //Use CONST class
        if(currentAccessSet.Grant_Access_By__c == 'Global' 
           && String.isBlank(currentAccessSet.BU__c) && String.isBlank(currentAccessSet.Customer_Group__c) 
           && String.isBlank(currentAccessSet.Channel__c)&& String.isBlank(currentAccessSet.Product_Category__c)){
               //Other param filters need to be considered
               //If grant acces by Global, Number of Accounts can be high (Initiate a batch?)
               //In future the query also can return more than 50,000 records
           }
        else{
            //If grant access by is not Global
            listOfAccountsMatchingAccessSetValues = getAccountsMatchingAccessSetValues(currentAccessSet);
            System.debug('listOfAccountsMatchingAccessSetValues: '+listOfAccountsMatchingAccessSetValues);
            if(listOfAccountsMatchingAccessSetValues != Null && !listOfAccountsMatchingAccessSetValues.isEmpty()){
                
                Map<Id,Teams__c> mapOfAccIdWithAccTeam = new Map<Id,Teams__c>();
                
                for(Teams__c eachTeam : [Select Id,Name,Access_Level__c,Access_Set_Ids__c,Account__c,Business_Unit__c,Grant_Access_Status__c,Is_Primary__c,User__c
                                         from Teams__c 
                                         where Account__c =: listOfAccountsMatchingAccessSetValues and User__c =: accessSetAsgnmntToProcess.User__c ]){
                                             mapOfAccIdWithAccTeam.put(eachTeam.Account__c,eachTeam);
                                         }
                //Iterate over each account
                for(Account eachAccount : listOfAccountsMatchingAccessSetValues){
                    if(mapOfAccIdWithAccTeam.containsKey(eachAccount.Id)){
                        //Update existing AccountTeam access Set IDS and other details if needed
                        Teams__c teamToUpdate = new Teams__c();
                        teamToUpdate.Id = mapOfAccIdWithAccTeam.get(eachAccount.Id).Id;
                        if(String.isNotBlank(mapOfAccIdWithAccTeam.get(eachAccount.Id).Access_Set_Ids__c)){
                            if(!mapOfAccIdWithAccTeam.get(eachAccount.Id).Access_Set_Ids__c.contains(currentAccessSet.Id)){
                                //teamToUpdate.Access_Set_Ids__c += ','+currentAccessSet.Id;
                                teamToUpdate.Access_Set_Ids__c = mapOfAccIdWithAccTeam.get(eachAccount.Id).Access_Set_Ids__c+','+currentAccessSet.Id;
                            }
                        }else{
                            teamToUpdate.Access_Set_Ids__c = currentAccessSet.Id;
                        }
                        listOfTeamsToUpsert.add(teamToUpdate);
                    }
                    else{
                        //Create a new Account team
                        listOfTeamsToUpsert.add(createAccountTeam(currentAccessSet,accessSetAsgnmntToProcess,eachAccount));
                    }
                }
                
            }else{
                //No accounts met criteria this accessSetAsgnmntToProcess should be marked as processed
            }
        }
        return listOfTeamsToUpsert;
    }
    
    Public static List<Account> getAccountsMatchingAccessSetValues(Access_Set__c accessSet){
        List<Account> listOfAccountsMatchingAccessSetValues = new List<Account>();
        String queryString = SharingUtility.getQueryString('Account');
        queryString += ' From Account where Id != Null';
        //Add the filters only if it's not blank else query for all
        if(String.isNotBlank(accessSet.Regions__c)){
            String accessSetRegion = accessSet.Regions__c;
            queryString += ' and Regions__c =: accessSetRegion';
        }
        if(String.isNotBlank(accessSet.Country__c)){
            String accessSetCountry = accessSet.Country__c;
            queryString += ' and BillingCountryCode =: accessSetCountry';
        }
        if(String.isNotBlank(accessSet.Customer_Group__c)){
            String accessSetCustGroup = accessSet.Customer_Group__c;
            queryString += ' and Customer_Group__c =: accessSetCustGroup';
        }
        if(String.isNotBlank(accessSet.Channel__c)){
            String accessSetChannel = accessSet.Channel__c;
            queryString += ' and Channel__c =: accessSetChannel';
        }
        
        //Need to be removed later
        //queryString += ' ORDER BY LastViewedDate DESC limit 80';
        //
        
        listOfAccountsMatchingAccessSetValues = Database.query(queryString);
        return listOfAccountsMatchingAccessSetValues;
    }
    
    Public static Teams__c createAccountTeam(Access_Set__c accessSet, Access_Set_Assignment__c accessSetAsgnmnt, Account account){
        Teams__c team = new Teams__c();
        team.Access_Level__c = SharingUtility.TEAMS_READ_ACCESS; //Use CONST class
        team.Access_Set_Ids__c = accessSet.Id;
        team.Account__c = account.Id;
        team.Business_Unit__c = accessSet.BU__c;
        team.Grant_Access_Status__c = SharingUtility.TEAMS_GRANTACCESSSTATUS_INITIATED; //Use CONST class
        //team.Sharing_Reason__c = '' //Need to confirm
        Team.User__c = accessSetAsgnmnt.User__c;
        return team;
    }
    
    Public static List<Retry_Log__c> getAccountTeamCreationRetryLog(Id accSetAssignmentId, String typeValue){
        //List<Retry_Log__c> listOfRetryLogs = new  List<Retry_Log__c>();
        return [Select Id, Access_Set_Assignment__c,Account_Team__c,Error_Message__c,Retry_Count__c,Type__c
                FROM Retry_Log__c 
                where Type__c =: typeValue and Access_Set_Assignment__c =: accSetAssignmentId limit 1];
    }
}