src/objects/Access_Set__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Pardot_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Grant_Access_By__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Regions</valueSetName>
        </valueSet>
    </fields>
    <label>Access Set</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Access Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Access_Set_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set__c</fullName>
        <label>Access Set</label>
        <referenceTo>Access_Set__c</referenceTo>
        <relationshipLabel>Access Set Assignments</relationshipLabel>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Teams_Creation_Status__c</fullName>
        <defaultValue>&quot;Initiated&quot;</defaultValue>
        <label>Account Teams Creation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Access Set Assignment</label>
    <nameField>
        <displayFormat>ASM-{0000000000}</displayFormat>
        <label>Access Set Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Set Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(Owner.UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;, 
IF( CONTAINS(Owner.UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;, &apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <description>To Identify the account region</description>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                    <isActive>false</isActive>
                    <label>Africa</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                    <isActive>false</isActive>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>Europe</fullName>
                    <isActive>false</isActive>
                    <label>Europe</label>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                    <isActive>false</isActive>
                    <label>Latin America</label>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                    <isActive>false</isActive>
                    <label>Middle East</label>
                </value>
                <value>
                    <fullName>North America</fullName>
                    <isActive>false</isActive>
                    <label>North America</label>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                    <isActive>false</isActive>
                    <label>Oceania</label>
                </value>
                <value>
                    <fullName>South America</fullName>
                    <isActive>false</isActive>
                    <label>South America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Text (Account.Regions__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_Team_Member_Role__mdt.object
<CustomObject>
    <description>Opportunity team member roles</description>
    <label>Opportunity Team Member Role</label>
    <pluralLabel>Opportunity Team Member Roles</pluralLabel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Regions</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;,
IF( CONTAINS(UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;,
IF( CONTAINS(UserRole.Name, &apos;Spice&apos;) , &apos;Spice&apos;,
IF( CONTAINS(UserRole.Name, &apos;Edible_Nuts&apos;) , &apos;Edible_Nuts&apos;, &apos;&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Others ( e-commerce, etc.)</fullName>
    </customValue>
    <customValue>
        <fullName>Private Label / Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Product Group or Brand Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Trade House</fullName>
    </customValue>
    <customValue>
        <fullName>B2B Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Food Service / Quick Service Restaurants</fullName>
    </customValue>
    <customValue>
        <fullName>Importer / Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Channel TWO</fullName>
        <isActive>false</isActive>
        <label>Channel TWO</label>
    </customValue>
    <customValue>
        <fullName>Channel ONE</fullName>
        <isActive>false</isActive>
        <label>Channel ONE</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

src/globalValueSets/Pardot_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>EMENA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and North Africa</fullName>
        <isActive>false</isActive>
        <label>Middle East and North Africa</label>
    </customValue>
    <customValue>
        <fullName>West Europe</fullName>
        <isActive>false</isActive>
        <label>West Europe</label>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
        <isActive>false</isActive>
        <label>South America</label>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
        <isActive>false</isActive>
        <label>North America</label>
    </customValue>
    <customValue>
        <fullName>Central America</fullName>
        <isActive>false</isActive>
        <label>Central America</label>
    </customValue>
    <customValue>
        <fullName>East Asia</fullName>
        <isActive>false</isActive>
        <label>East Asia</label>
    </customValue>
    <customValue>
        <fullName>Central Asia</fullName>
        <isActive>false</isActive>
        <label>Central Asia</label>
    </customValue>
    <customValue>
        <fullName>Southern Asia</fullName>
        <isActive>false</isActive>
        <label>Southern Asia</label>
    </customValue>
    <customValue>
        <fullName>Sub Sahara Africa</fullName>
        <isActive>false</isActive>
        <label>Sub Sahara Africa</label>
    </customValue>
    <customValue>
        <fullName>East Europe and Russia</fullName>
        <isActive>false</isActive>
        <label>East Europe and Russia</label>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
        <isActive>false</isActive>
        <label>Middle East</label>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
        <isActive>false</isActive>
        <label>South East Asia</label>
    </customValue>
    <customValue>
        <fullName>Australia and New Zealand</fullName>
        <isActive>false</isActive>
        <label>Australia and New Zealand</label>
    </customValue>
    <masterLabel>Pardot Region</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>West Europe</fullName>
    </customValue>
    <customValue>
        <fullName>East Europe and Russia</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Central America</fullName>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and North Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Sub Sahara Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Central Asia</fullName>
    </customValue>
    <customValue>
        <fullName>East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia and New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>North East</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>West Coast</fullName>
    </customValue>
    <customValue>
        <fullName>South West</fullName>
    </customValue>
    <customValue>
        <fullName>South East</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
        <isActive>false</isActive>
        <label>APAC</label>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

src/globalValueSets/Regions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>EMENA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

src/classes/OFI_OpportunityLineItemHandler.cls
// 
// Class created by Punam
// Last modified by Joel Tom on 01/02/2022
// 

public class OFI_OpportunityLineItemHandler {
    
    public static void checkUserAccessForInsert(list<OpportunityLineItem> newOppLineItemList){
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Access_Set_Admins');
        if(!hasCustomPermission  && userInfo.getName() != System.Label.Automated_Process){
            User u=[Select Id,Name,Email,BU_Identifier__c,UserRole.Name from User where Id=:userinfo.getuserId()];
            Map<string,Teams__c> mapOfUserIdToTeams =new Map<string,Teams__c>();
            Map<string,Access_Set__c> mapOfproductCatToAcessset=new Map<string,Access_Set__c>();
            Map<id,OpportunityLineItem> newMapOfIdtoOppLine = new Map<id,OpportunityLineItem>();
            Map<id,Opportunity> mapOfIdtoOpp=new Map<id,Opportunity>();
            Map<Id,PricebookEntry> mapOfIdtoPriceBookEntry=new Map<Id,PricebookEntry>();
            Map<String,Opportunity_Team_Member_Role__mdt> mapofLabeltoOppTeamMemberRoleMDT=new Map<String,Opportunity_Team_Member_Role__mdt>();
            set<id> OppId=new set<Id>();
            set<id> AccountID=new set<Id>();
            set<id> idForPriceBookEntry=new set<Id>();
            
            for(OpportunityLineItem oppLineItem:newOppLineItemList){
                OppId.add(oppLineItem.OpportunityId);
                idForPriceBookEntry.add(oppLineItem.PriceBookEntryID);
            }
            
            //Code Added by Joel Tom to validate Opp team members
            Map<Id,Map<Id,String>> oppUserRoleMap = opportunityTriggerOfiUser.fetchOppTeamMemberAndRole(OppId);
            
            List<Opportunity> oli = new List<Opportunity>([SELECT AccountId FROM Opportunity WHERE Id IN: OppId]);
            for(Opportunity o : oli){
                AccountID.add(o.AccountId);
            }
            
            //
            //Commented by JOEL
            //Skipping the product category validation for existing Sprint 1 code in UAT
            //
            //mapOfproductCatToAcessset=getMapOfUserAccessSet(u.Id);
            mapOfIdtoPriceBookEntry=getProductDetailsFromPricebokentryId(idForPriceBookEntry);
            mapOfUserIdToTeams=opportunityTriggerOfiUser.getAccountTeams(AccountID);    
            mapOfIdtoOpp=getAccIdFromOppId(OppId);
            mapofLabeltoOppTeamMemberRoleMDT = opportunityTriggerOfiUser.getOppTeamMemberRoleMDT('OpportunityLineItem');
            
            for(OpportunityLineItem oppLineItem:newOppLineItemList){
                if(!oppUserRoleMap.isEmpty()){
                    if(oppUserRoleMap.containskey(oppLineItem.OpportunityId)){
                        if(!(mapofLabeltoOppTeamMemberRoleMDT.containsKey(oppUserRoleMap.get(oppLineItem.OpportunityId).get(u.Id)))){
                            lineItemValidationInsert(oppLineItem,mapOfUserIdToTeams,mapOfIdtoOpp,mapOfproductCatToAcessset,mapOfIdtoPriceBookEntry);
                        }
                    }  
                    else{
                        lineItemValidationInsert(oppLineItem,mapOfUserIdToTeams,mapOfIdtoOpp,mapOfproductCatToAcessset,mapOfIdtoPriceBookEntry);
                    }
                }
                else{
                    lineItemValidationInsert(oppLineItem,mapOfUserIdToTeams,mapOfIdtoOpp,mapOfproductCatToAcessset,mapOfIdtoPriceBookEntry);
                }                       
            }
        } 
    }
    
    public static void checkUserAccessForUpdate(list<OpportunityLineItem> newOppLineItemList,Map<Id,OpportunityLineItem> newMapOFOppLineItem,Map<Id,OpportunityLineItem> oldMapOfOppLineItem){
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Access_Set_Admins');
        if(!hasCustomPermission && userInfo.getName() != System.Label.Automated_Process){   
            User u=[Select Id,Name,Email,BU_Identifier__c,UserRole.Name from User where Id=:userinfo.getuserId()];
            Map<id,Opportunity> mapOfIdtoOpp=new Map<id,Opportunity>();
            Map<string,Teams__c> mapOfUserIdToTeams =new Map<string,Teams__c>();
            Map<string,Access_Set__c> mapOfproductCatToAcessset=new Map<string,Access_Set__c>();
            Map<id,OpportunityLineItem> oldMapOfIdtoOppLine = new Map<id,OpportunityLineItem>();
            Map<id,OpportunityLineItem> newMapOfIdtoOppLine = new Map<id,OpportunityLineItem>();
            Map<String,Opportunity_Team_Member_Role__mdt> mapofLabeltoOppTeamMemberRoleMDT=new Map<String,Opportunity_Team_Member_Role__mdt>();

            set<id> OppId=new set<Id>();
            set<id> AccountID=new set<Id>();
            for(OpportunityLineItem oppLineItem:newOppLineItemList){
                OppId.add(oppLineItem.OpportunityId);          
            }
            
            //Code Added by Joel Tom to validate Opp team members
            Map<Id,Map<Id,String>> oppUserRoleMap = opportunityTriggerOfiUser.fetchOppTeamMemberAndRole(OppId);
            
            List<Opportunity> oli = new List<Opportunity>([SELECT AccountId FROM Opportunity WHERE Id IN: OppId]);
            for(Opportunity o : oli){
                AccountID.add(o.AccountId);
            }
            
            //
            //Commented by JOEL
            //Skipping the product category validation for existing Sprint 1 code in UAT
            //
            //mapOfproductCatToAcessset=getMapOfUserAccessSet(u.Id);
            mapOfIdtoOpp=OFI_OpportunityLineItemHandler.getAccIdFromOppId(OppId);
            oldMapOfIdtoOppLine=getOppAndProductFromoppLine(oldMapOfOppLineItem);
            newMapOfIdtoOppLine=getOppAndProductFromoppLine(newMapOFOppLineItem);
            mapOfUserIdToTeams=opportunityTriggerOfiUser.getAccountTeams(AccountID);
            mapofLabeltoOppTeamMemberRoleMDT = opportunityTriggerOfiUser.getOppTeamMemberRoleMDT('OpportunityLineItem');
            
            for(OpportunityLineItem oppLineItem:newOppLineItemList){
                if(!oppUserRoleMap.isEmpty()){
                    if(oppUserRoleMap.containskey(oppLineItem.OpportunityId)){
                        if(!(mapofLabeltoOppTeamMemberRoleMDT.containsKey(oppUserRoleMap.get(oppLineItem.OpportunityId).get(u.Id)))){
                            lineItemValidationUpdate(oppLineItem,mapOfUserIdToTeams,newMapOfIdtoOppLine,oldMapOfIdtoOppLine,mapOfproductCatToAcessset,mapOfIdtoOpp);
                        }     
                    }  
                    else{
                        lineItemValidationUpdate(oppLineItem,mapOfUserIdToTeams,newMapOfIdtoOppLine,oldMapOfIdtoOppLine,mapOfproductCatToAcessset,mapOfIdtoOpp);}
                }
                else{
                    lineItemValidationUpdate(oppLineItem,mapOfUserIdToTeams,newMapOfIdtoOppLine,oldMapOfIdtoOppLine,mapOfproductCatToAcessset,mapOfIdtoOpp);}
            }
        }
    }
    
    //
    //
    //TO BE CONFIRMED - COMMENT THESE BELOW 2 METHODS FOR SKIPPING THE LINEITEM VALIDATION
    //
    //
    public static void lineItemValidationInsert(OpportunityLineItem oppLineItem, Map<string,Teams__c> mapOfUserIdToTeams,Map<id,Opportunity> mapOfIdtoOpp,Map<string,Access_Set__c> mapOfproductCatToAcessset, Map<Id,PricebookEntry> mapOfIdtoPriceBookEntry){
        if((!mapOfUserIdToTeams.isEmpty())&& (!mapOfIdtoOpp.isEmpty()) && (!mapOfIdtoPriceBookEntry.isEmpty())/* &&(!mapOfproductCatToAcessset.isEmpty())*/){
            if((mapOfUserIdToTeams.containskey(String.ValueOF(mapOfIdtoOpp.get(oppLineItem.OpportunityId).AccountId)+String.valueOf(userinfo.getuserId())))){
                if(mapOfUserIdToTeams.get(String.ValueOF(mapOfIdtoOpp.get(oppLineItem.OpportunityId).AccountId)+String.valueOf(userinfo.getuserId())).Business_Unit__c==mapOfIdtoPriceBookEntry.get(oppLineItem.PriceBookEntryID).Product2.Business_Unit__c || mapOfUserIdToTeams.get(String.ValueOF(mapOfIdtoOpp.get(oppLineItem.OpportunityId).AccountId)+String.valueOf(userinfo.getuserId())).Business_Unit__c==OpportunityConstants.OFI_BU_ALL){
                   	//
                   	//Commented by JOEL
                   	//Skipping the product category validation for existing Sprint 1 code in UAT
                   	// 
                    /* if(!mapOfproductCatToAcessset.isEmpty()){
                        if(!(mapOfUserIdToTeams.get(String.ValueOF(mapOfIdtoOpp.get(oppLineItem.OpportunityId).AccountId)+String.valueOf(userinfo.getuserId())).Access_Set_Role__c=='Sales')){  
                            if((mapOfproductCatToAcessset.containskey(String.valueOf(mapOfIdtoPriceBookEntry.get(oppLineItem.PriceBookEntryID).Product2.Product_Category__c)+(String.valueOf(mapOfIdtoOpp.get(oppLineItem.OpportunityId).Account.regions__c))))
                               ||((mapOfproductCatToAcessset.containskey(String.valueOf(mapOfIdtoPriceBookEntry.get(oppLineItem.PriceBookEntryID).Product2.Product_Category__c)+(String.valueOf(mapOfIdtoOpp.get(oppLineItem.OpportunityId).Account.billingcountrycode)))))
                               ||mapOfproductCatToAcessset.containskey('null'+(String.valueOf(mapOfIdtoOpp.get(oppLineItem.OpportunityId).Account.billingcountrycode)))
                               ||mapOfproductCatToAcessset.containskey('null'+(String.valueOf(mapOfIdtoOpp.get(oppLineItem.OpportunityId).Account.regions__c))))    
                            {
                            }
                            else{oppLineItem.addError('You have no access to this product category, region or the selected country. Please contact the administrator');}   
                        }
                    }*/
                }
                else{oppLineItem.addError('You are not a part of the same business unit. Please contact the administrator');}       
            }
            else{oppLineItem.addError('You have no permission to do this action. Please contact the administrator');} 
        }
        else{oppLineItem.addError('You are not part of this account. Please contact the administrator');}
    }
    
    public static void lineItemValidationUpdate(OpportunityLineItem oppLineItem, Map<string,Teams__c> mapOfUserIdToTeams, Map<id,OpportunityLineItem> newMapOfIdtoOppLine, Map<id,OpportunityLineItem> oldMapOfIdtoOppLine,Map<string,Access_Set__c> mapOfproductCatToAcessset,Map<id,Opportunity> mapOfIdtoOpp){
        if(!mapOfUserIdToTeams.isempty() && !newMapOfIdtoOppLine.isEmpty() && !oldMapOfIdtoOppLine.isEmpty()/*&&(!mapOfproductCatToAcessset.isEmpty())*/){
            if((mapOfUserIdToTeams.containskey(String.ValueOF(newMapOfIdtoOppLine.get(oppLineItem.Id).Opportunity.AccountId)+String.valueOf(userinfo.getuserId())))){
                if((mapOfUserIdToTeams.get(String.ValueOF(newMapOfIdtoOppLine.get(oppLineItem.Id).Opportunity.AccountId)+String.valueOf(userinfo.getuserId())).Business_Unit__c==(oldMapOfIdtoOppLine.get(oppLineItem.Id).Product2.Business_Unit__c))&&((oldMapOfIdtoOppLine.get(oppLineItem.Id).Product2.Family)==(newMapOfIdtoOppLine.get(oppLineItem.Id).Product2.Family)) ||mapOfUserIdToTeams.get(String.ValueOF(newMapOfIdtoOppLine.get(oppLineItem.Id).Opportunity.AccountId)+String.valueOf(userinfo.getuserId())).Business_Unit__c==OpportunityConstants.OFI_BU_ALL){
                  	//
                   	//Commented by JOEL
                   	//Skipping the product category validation for existing Sprint 1 code in UAT
                   	//
                    /* if(!mapOfproductCatToAcessset.isempty()){
                        if(!(mapOfUserIdToTeams.get(String.ValueOF(mapOfIdtoOpp.get(oppLineItem.OpportunityId).AccountId)+String.valueOf(userinfo.getuserId())).Access_Set_Role__c=='Sales')){      
                            if((mapOfproductCatToAcessset.containskey(String.valueOf(oldMapOfIdtoOppLine.get(oppLineItem.Id).Product2.Product_Category__c)+(String.valueOf(mapOfIdtoOpp.get(oppLineItem.OpportunityId).Account.regions__c))))
                               ||((mapOfproductCatToAcessset.containskey(String.valueOf(oldMapOfIdtoOppLine.get(oppLineItem.Id).Product2.Product_Category__c)+(String.valueOf(mapOfIdtoOpp.get(oppLineItem.OpportunityId).Account.billingcountrycode)))))
                               ||mapOfproductCatToAcessset.containskey('null'+(String.valueOf(mapOfIdtoOpp.get(oppLineItem.OpportunityId).Account.billingcountrycode)))
                               ||mapOfproductCatToAcessset.containskey('null'+(String.valueOf(mapOfIdtoOpp.get(oppLineItem.OpportunityId).Account.regions__c))))   
                            {
                            }
                            else{oppLineItem.addError('You have no access to this product category, region or the selected country. Please contact the administrator');}   
                        }
                    }*/
                }
                else{oppLineItem.addError('You are not a part of the same business unit. Please contact the administrator');}    
            }
            else{oppLineItem.addError('You have no permission to do this action. Please contact the administrator');} 
        }
        else{oppLineItem.addError('You are not part of this account. Please contact the administrator');} 
    }
    
    /*
    public static  Map<string,Access_Set__c> getMapOfUserAccessSet(id userId){
        List<Access_Set_Assignment__c> listOfAccessSetAssgnmnt= new List<Access_Set_Assignment__c>();
        set<id> idOfUserAcessSet=new set<id>();
        Map<string,Access_Set__c> mapOfproductCatToAcessset=new Map<string,Access_Set__c>();
        listOfAccessSetAssgnmnt=[Select Id,Access_Set__c,User__c,Account_Teams_Creation_Status__c 
                                 from Access_Set_Assignment__c 
                                 where User__c =:userId];
        
        for(Access_Set_Assignment__c accessSetAssgnments:listOfAccessSetAssgnmnt)
        {
            idOfUserAcessSet.add(accessSetAssgnments.Access_Set__c);
        }
        List<Access_Set__c> listOfUserAccessSet = [Select Id,Name,Region__c,Country__c,Customer_Group__c,Channel__c,Product_Category__c from Access_Set__c where Id IN: idOfUserAcessSet];
        
        for(Access_Set__c UserAccessSet:listOfUserAccessSet)
        {
            if(UserAccessSet.Country__c!=null){ 
                mapOfproductCatToAcessset.put(String.valueof(UserAccessSet.Product_Category__c)+String.valueOf(UserAccessSet.Country__c),UserAccessSet);
            }else{
                mapOfproductCatToAcessset.put(String.valueof(UserAccessSet.Product_Category__c)+String.valueOf(UserAccessSet.Region__c),UserAccessSet);  
            }
        }
        return mapOfproductCatToAcessset; 
    }
    */
        
    public static Map<id,OpportunityLineItem> getOppAndProductFromoppLine(Map<id,OpportunityLineItem> mapOfOppLine){
        Map<id,OpportunityLineItem> mapOfIdtoOppLine = new Map<id,OpportunityLineItem>([SELECT Opportunity.AccountId,Product2.Product_Category__c, Product2.Family, Product2.Business_Unit__c FROM OpportunityLineItem WHERE Id IN: mapOfOppLine.keySet()]); 
        return mapOfIdtoOppLine;
    }
    
    public static Map<id,Opportunity> getAccIdFromOppId(set<id> OppId){
        Map<id,opportunity> mapOfIdtoOpp=new Map<id,opportunity>([SELECT Id, Name, AccountId,Account.billingcountrycode,Account.regions__c FROM Opportunity WHERE Id IN:OppId]);
        return mapOfIdtoOpp;
    }
    
    public static Map<id,PricebookEntry> getProductDetailsFromPricebokentryId(set<id> idForPriceBookEntry){
        Map<id,PricebookEntry> mapOfIdtoPriceBookEntry=new Map<id,PricebookEntry>([SELECT Id, Name,Product2.Product_Category__c, Product2.Family, Product2.Business_Unit__c FROM PricebookEntry WHERE Id IN:idForPriceBookEntry]);
        return mapOfIdtoPriceBookEntry;  
    }
    
}