src/objects/Access_Set__c.object
<CustomObject>
    <label>Access Set</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Access Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Access_Set_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Set__c</fullName>
        <label>Access Set</label>
        <referenceTo>Access_Set__c</referenceTo>
        <relationshipLabel>Access Set Assignments</relationshipLabel>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Access_Set_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Access Set Assignment</label>
    <nameField>
        <displayFormat>ASM-{0000000000}</displayFormat>
        <label>Access Set Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Set Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Key Account</fullName>
                </value>
                <value>
                    <fullName>Global Account</fullName>
                </value>
                <value>
                    <fullName>Regional Key Account</fullName>
                </value>
                <value>
                    <fullName>Regional Account</fullName>
                </value>
                <value>
                    <fullName>Local Key Account</fullName>
                </value>
                <value>
                    <fullName>Local Account</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(Owner.UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;, 
IF( CONTAINS(Owner.UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;, &apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Plans__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <label>BU Identifier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plans Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Budget_vs_Actual_Line__c.object
<CustomObject>
    <fields>
        <fullName>Budget_vs_Actuals__c</fullName>
        <label>Budget vs Actuals</label>
        <referenceTo>Budget_vs_Actuals__c</referenceTo>
        <relationshipLabel>Budget vs Actual Lines</relationshipLabel>
        <relationshipName>Budget_vs_Actual_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Annual Budget Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Budget vs Actual Line</label>
    <nameField>
        <displayFormat>BVSAL-{0000000}</displayFormat>
        <label>Budget vs Actual Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget vs Actual Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget_vs_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budget vs Actuals</relationshipLabel>
        <relationshipName>Budget_vs_Actuals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Budget_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Budget Locked ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Budget vs Actuals</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Budget vs Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget vs Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;,
IF( CONTAINS(UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;,
IF( CONTAINS(UserRole.Name, &apos;Spice&apos;) , &apos;Spice&apos;,
IF( CONTAINS(UserRole.Name, &apos;Edible_Nuts&apos;) , &apos;Edible_Nuts&apos;, &apos;&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Approval_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Request for edit</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

src/classes/KAM_BudgetActualsCntlTest.cls
@isTest
public class KAM_BudgetActualsCntlTest {

    @testSetup
    public static void createData()
    {
        Account acc=new Account();
        acc.Name='Test';
        acc.Account_Type__c='Distributor';
        acc.BillingCountry='India';
        acc.BillingStreet='Pune-Mumbai road';
        insert acc;
        
        Account_Plans__c app = new Account_Plans__c();
        app.Name = 'accountPlan';
        app.Account__c = acc.id;
        app.BU_Identifier__c='Dairy';
        app.StartDate__c=system.today();
        app.EndDate__c=system.today().addDays(365);
        insert app;
        
       Budget_vs_Actuals__c budget=new Budget_vs_Actuals__c();
        budget.Account__c=acc.Id;
        budget.Business_Unit__c='Dairy';
        budget.Start_date__c=system.today();
        budget.End_Date__c=system.today().addDays(365);
        budget.Is_Budget_Locked__c=false;
        budget.Year__c='2021';
        budget.Approval_Status__c='';
        insert budget;
        
        Budget_vs_Actual_Line__c budgetLine=new Budget_vs_Actual_Line__c();
        budgetLine.Budget_vs_Actuals__c=budget.id;
        budgetLine.Business_Unit__c = 'Dairy';
        budgetLine.Category__c='BLEND';
        budgetLine.Volume__c=10;
        insert budgetLine;
        
         //Added by Sameer
        Access_Set__c access = OFI_TestDataFactory.createAccessSet('Country', null, 'IN', 'All', null, null, null, true);
        Access_Set_Assignment__c assign = OFI_TestDataFactory.createAccessSetAssignment(access.ID, userinfo.getUserId(), //'Sales', 
                                                                                        true);
		Teams__c team = OFI_TestDataFactory.createAccountTeam(acc.Id, UserInfo.getUserId(), 'All', 'Edit Access', //'Sales',
                                                              true, true);
    }
    
    public static testmethod void getDetailsTest()
    {
        Account acc=[select id from account];
       Account_Plans__c app=[select Name,Account__c,BU_Identifier__c,StartDate__c,EndDate__c from Account_Plans__c limit 1 ];
      //  String data='{"accountPlan":[{"Name":"Test","Account__c":"a0e1s000001pogbAAA","BU_Identifier__c":"Cocoa","StartDate__c":"2021-08-12","EndDate__c":"2021-08-31"}]}';
        KAM_BudgetActualsCntl BudgetCntl=new KAM_BudgetActualsCntl();
       String res= BudgetCntl.getDetails(JSON.serialize(new Map<String, Object> {'accountPlan' => app}));
         String res1= BudgetCntl.getDetails(JSON.serialize(app));
        system.assert(res!=null, 'Account Plans Details not found');
              
    }
    public static testmethod void refreshBudgetPlanTest(){
               Account_Plans__c app=[select Name,Account__c,BU_Identifier__c,StartDate__c,EndDate__c from Account_Plans__c limit 1 ];
                 system.assert(app!=null, 'Account Plans Details not found');
                 String res= KAM_BudgetActualsCntl.refreshBudgetPlan(JSON.serialize(app));
        try{
                String res1= KAM_BudgetActualsCntl.refreshBudgetPlan(JSON.serialize(null));
        }catch(exception e)
        {
            system.debug(e);
        }
            system.assert(res!=null, 'Budget Plan not Refresh');

        
    }
    public static testmethod void refreshOverAllBudget(){
        
             Account_Plans__c app=[select Name,Account__c,BU_Identifier__c,StartDate__c,EndDate__c from Account_Plans__c limit 1 ];
             system.assert(app!=null, 'Account Plans Details not found');
             list<integer> years=new list<integer>();
            years.add(2020);
            years.add(2021);
            years.add(2019);
            years.add(2018);
            List<Budget_vs_Actuals__c> res=KAM_BudgetActualsCntl.refreshOverAllBudget(JSON.serialize(app),JSON.serialize(years));
        try{
            List<Budget_vs_Actuals__c> res1=KAM_BudgetActualsCntl.refreshOverAllBudget(JSON.serialize(app),JSON.serialize(app));
        }catch(exception e)
        {
            system.debug(e);
        }
            system.assert(res!=null, 'not refresh budget');
        
    }
   public static testmethod void getOverAllBudgetsTest(){
            
   
             Account_Plans__c app=[select Name,Account__c,BU_Identifier__c,StartDate__c,EndDate__c from Account_Plans__c limit 1 ];
             system.assert(app!=null, 'Account Plans Details not found');  
            Account acc=[select id from account];
             list<integer> years=new list<integer>();
            years.add(2020);
            years.add(2021);
            years.add(2019);
            years.add(2018);
            List<Budget_vs_Actuals__c> res=KAM_BudgetActualsCntl.getOverAllBudgets(JSON.serialize(app),JSON.serialize(years));    
            system.assert(res!=null, 'Not Found Overall Budget'); 
       try{ 
       
          List<Budget_vs_Actuals__c> res1=KAM_BudgetActualsCntl.getOverAllBudgets(JSON.serialize(acc),JSON.serialize(acc));
       }catch(exception e)
       {
           system.debug(e);
       }
   }
       
       
      public static testmethod void riseRequestForBudgetEditTest(){
       Account acc=[select id from account];
       Budget_vs_Actuals__c budget1=new Budget_vs_Actuals__c();
        budget1.Account__c=acc.Id;
        budget1.Business_Unit__c='Cocoa';
        budget1.Start_date__c=system.today();
        budget1.End_Date__c=system.today().addDays(365);
        budget1.Is_Budget_Locked__c=true;
        budget1.Year__c='2022';
        budget1.Approval_Status__c='pending';
          insert budget1;
        Budget_vs_Actuals__c budget=[select Id,Account__c,Business_Unit__c,Start_date__c,End_Date__c,Is_Budget_Locked__c from Budget_vs_Actuals__c where Year__c='2022'];
        String res=KAM_BudgetActualsCntl.riseRequestForBudgetEdit(JSON.serialize(budget));
        
         Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(res);
        
        System.assert(resultMap.containsKey ('success'), 'Invalid response');
        //System.assert((Boolean)resultMap.get ('success'), 'Exception thrown while processing record');
        String res1=KAM_BudgetActualsCntl.riseRequestForBudgetEdit(JSON.serialize(acc));
          
      } 
    public static testmethod void createBudgetTest(){
         Account acc=[select id from account];
       Budget_vs_Actuals__c budget1=new Budget_vs_Actuals__c();
        budget1.Account__c=acc.Id;
        budget1.Business_Unit__c='Cocoa';
        budget1.Start_date__c=system.today();
        budget1.End_Date__c=system.today().addDays(365);
        budget1.Is_Budget_Locked__c=true;
        budget1.Year__c='2022';
        budget1.Approval_Status__c='pending';
        
      Budget_vs_Actuals__c budget=[select Id,Account__c,Business_Unit__c,Start_date__c,End_Date__c,Is_Budget_Locked__c from Budget_vs_Actuals__c limit 1];
      list<Budget_vs_Actual_Line__c> budget_Line =[select Id,Budget_vs_Actuals__c,Category__c from Budget_vs_Actual_Line__c ];
      String res=KAM_BudgetActualsCntl.createBudget(JSON.serialize(budget),JSON.serialize(budget_Line)); 
      String res1=KAM_BudgetActualsCntl.createBudget(JSON.serialize(budget1),JSON.serialize(null));
      system.assert(res!=null, ' Budget Not create'); 
        
    }
    public static testmethod void getBudgetvsActualsTest(){
        
        Account acc=[select id from account];
         List<Budget_vs_Actuals__c> res=KAM_BudgetActualsCntl.getBudgetvsActuals(acc.Id);
        //commented by sameer
        //system.assert(res!=null, 'not found budgetvsActuals');
        
        //System.assertEquals(acc.id, res[0].Account__c , ' not matches actual and expected value');
        
    }
    
   public static testmethod void getBudgetActualsByIdTest()
   {
       Budget_vs_Actuals__c budget=[select Id from Budget_vs_Actuals__c limit 1];
       system.assert(budget!=null, 'not found budgetvsActuals');
       String res=KAM_BudgetActualsCntl.getBudgetActualsById(budget.Id);
       system.assert(res!=null, 'not found budgetvsActuals');

       
   }
    public static testmethod void getBudgetPickListValuesByFieldTest()
    {
      List<KAM_Util.PicklistEntry> result=KAM_BudgetActualsCntl.getBudgetPickListValuesByField('Budget_vs_Actuals__c','Year__c',false,false); 
       system.assert(result!=null,'No year');
        try{
            List<KAM_Util.PicklistEntry> result1=KAM_BudgetActualsCntl.getBudgetPickListValuesByField('Account','Start_date__c',false,false);
        }
        catch(exception e)
        {
            system.debug(e);
        }    
        
    }
    public static testmethod void createBudgetvsActualsTest(){
         Account acc=[select id from account];
        //Added by sameer
        Id currentUserId = UserInfo.getUserId();
        List<Teams__c> team = [Select Id,Name,Business_Unit__c From Teams__c where User__c =:currentUserId  and Account__c =: acc.Id];
       System.debug('Error acc======>'+acc);
        System.debug('Error team======>'+team);
        //added bu by sameer
       Budget_vs_Actuals__c budget = KAM_BudgetActualsCntl.createBudgetvsActuals('2020',acc.Id,team[0].Business_Unit__c);
         System.debug('budet=======sam>'+budget);
        system.assert(budget!=null,'No year');
         system.assertEquals(budget.Year__c, '2020');
        
    }
     //added by sameer
    @isTest
    public static void test_getUserBU(){
        User u = KAM_BudgetActualsCntl.getUserBU();
        System.assert(u!=null, 'No user found');
    }
    //added by sameer
    @isTest
    public static void test_getAccountTeams(){
        Account acc = [Select Id, Name From Account];
        List<Teams__c> team = KAM_BudgetActualsCntl.getAccountTeams(acc.Id);
        System.debug('teamlist======>'+team);
        System.assert(!team.isEmpty(), 'No team member found');
    }
    //added by sameer
    @isTest
    public static void test_getcurrentUserAccountTeam(){
	Account acc = [Select Id, Name From Account];
        Teams__c team = KAM_BudgetActualsCntl.getcurrentUserAccountTeam(acc.Id);
        System.assert(team!=null, 'No team member found');        
    }
}