src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Pardot</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Developing_Hours__c</fullName>
        <label>Actual Developing Hours</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Account Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>DAIRY</fullName>
                </value>
                <value>
                    <fullName>DAIRY ALTERNATIVES</fullName>
                </value>
                <value>
                    <fullName>FROZEN DAIRY</fullName>
                </value>
                <value>
                    <fullName>FILLINGS (WB)</fullName>
                </value>
                <value>
                    <fullName>SYRUPS (WB)</fullName>
                </value>
                <value>
                    <fullName>BEVERAGES</fullName>
                </value>
                <value>
                    <fullName>CHOCOLATE (LIKE)</fullName>
                </value>
                <value>
                    <fullName>CONFECTIONERY MIXES</fullName>
                </value>
                <value>
                    <fullName>FILLINGS (FB)</fullName>
                </value>
                <value>
                    <fullName>SPREADS (FB)</fullName>
                </value>
                <value>
                    <fullName>SYRUPS (FB)</fullName>
                </value>
                <value>
                    <fullName>DECORATION</fullName>
                </value>
                <value>
                    <fullName>DAIRY MIXES</fullName>
                </value>
                <value>
                    <fullName>INSTANT MIXES</fullName>
                </value>
                <value>
                    <fullName>BAKERY MIXES</fullName>
                </value>
                <value>
                    <fullName>REPACKING</fullName>
                </value>
                <value>
                    <fullName>BAKERY</fullName>
                </value>
                <value>
                    <fullName>CEREALS</fullName>
                </value>
                <value>
                    <fullName>OTHER APPLICATIONS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Configuration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Bussiness_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                    <label>Spices</label>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approver_Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Approver Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Configuration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Role_Name__c</fullName>
        <label>User Role Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Cocoa PDI Manager</fullName>
                </value>
                <value>
                    <fullName>Dairy Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Dairy PDI Manager</fullName>
                </value>
                <value>
                    <fullName>Spice Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Spice PDI Manager</fullName>
                </value>
                <value>
                    <fullName>Edible Nuts Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Edible Nuts PDI Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Application_Pardot.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Confectionery</fullName>
    </customValue>
    <customValue>
        <fullName>Drinks</fullName>
    </customValue>
    <customValue>
        <fullName>Ice Creams</fullName>
    </customValue>
    <customValue>
        <fullName>Desserts</fullName>
    </customValue>
    <customValue>
        <fullName>Savoury</fullName>
    </customValue>
    <customValue>
        <fullName>Bevarage</fullName>
    </customValue>
    <customValue>
        <fullName>Frozen Desserts</fullName>
    </customValue>
    <masterLabel>application</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/OpportunityTriggerTest.cls
@isTest
public class OpportunityTriggerTest {
    
    @testSetup
    public static void setupData()
    {
        //Create an Account
        //Account acc = TestData_Factory.createAccount(true);
        //Spices PDI
        /*Profile p = [select id from profile where name='Spices PDI'];
      
        User user1 = new User(alias = 'aksh', email='aksh@noemail.com',
                              emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US',
                              localesidkey='en_US', profileid = p.Id,UserRoleId ='00E2v000001LFNtEAO',
                              timezonesidkey='America/Los_Angeles', username='aksh@noemail.com');
        insert user1;*/
         Account acc = new Account();
        acc.name='TestForOpportunity';
        acc.BillingCountry = 'USA';
        acc.BillingStreet ='Test';
        //acc.Segment__c = 'Agent/ Distributor';
        insert acc;
       // Teams__C team=new Teams__c(Account__c=acc.id,User__c=user1.id,User_Role_Name__c='Spice Sales Manager');
        //insert team;
        //Get the pricebookId
        Id pricebookId = Test.getStandardPricebookId();
        
        //Create an Opportunity
       // Opportunity opp = TestData_Factory.createOpportunity(acc, pricebookId, true);
       // System.runAs(user1){
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Name = 'Test Opp for gain opp';
        opp.StageName = 'Briefing';
        opp.RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId();
        opp.CloseDate = System.today();
        opp.Actual_Developing_Hours__c=2;
        opp.Business_Unit__c = 'Spice';
        
        //opp.Application__c = 'Agent/ Distributor';
        opp.Pricebook2Id = pricebookId;
        opp.CurrencyIsoCode = 'USD';
        insert opp;
        //Create a Quote
       // Quote quote = TestData_Factory.createQuote(acc, opp, true);
        Quote quote=new Quote();
        quote.OpportunityId=opp.Id;
        quote.Name='quote testing1';
        quote.Bussiness_Unit__c=opp.Business_Unit__c;
        quote.ExpirationDate=opp.CloseDate;
        quote.Status='Draft';
        insert quote;
         opp.SyncedQuoteId=quote.id;
         update opp;
        //Create a Product
        
        Product2 prod = TestData_Factory.createProduct('12-Spices', 'Tropical', 'Pepper', 'Black Pepper', true);
        
        //Create a PricebookEntry
        //PricebookEntry pbe = TestData_Factory.createPricebookEntry(pricebookId, prod, true);
        
        PricebookEntry pbe = [Select Id from PricebookEntry where Product2Id =: prod.Id and CurrencyIsoCode =: opp.CurrencyIsoCode limit 1];
       // }
        //Create a QuoteLineItem
        //QuoteLineItem qLI = TestData_Factory.createQuoteLineItemNew(pbe, prod, quote, 'Rejected',true);
        QuoteLineItem qli=new QuoteLineItem();
        qli.QuoteId=quote.Id;
        //qli.Product2Id=p.Id;
        qli.PricebookEntryId=pbe.Id;
        qli.UnitPrice = 0;
        qli.Volume__c=3;
        qli.Quantity=5;
        qli.Approver_Comment__c = 'Test';
        qli.Product_Configuration__c='[{"varient_character_mapping":"ZVAR_MULTI_THRU","uom":"%","quantitative":"Yes","qualitative":"","olam_range":"0,000 - 50,000","mic":"-U100","description":"% THRU US #100","customer_range":"0,000 - 50,000"},{"varient_character_mapping":"ZVAR2_MULTI_THRU","uom":"%","quantitative":"No","qualitative":"","olam_range":"0,000 - 80,000","mic":"-U200","description":"% THRU UK #200","customer_range":"0,000 - 80,000"}]';
        insert qli;
        //System.debug('qLI: '+qLI);
    }
    
    @isTest
    public static void checkOpportunityStatusWithLatestQuoteStatusTest()
    {
         Test.startTest();
        Map<Id,Opportunity> mapOpp = new Map<Id,Opportunity>();
       
        Opportunity opp1 = [SELECT Id,stageName FROM Opportunity LIMIT 1];
        Opportunity opp2 = [SELECT Id,stageName FROM Opportunity LIMIT 1];
        Quote qu1 = [SELECT Id,Status,OpportunityId FROM Quote where OpportunityId= :opp1.Id LIMIT 1];
        qu1.Status='Customer Accepted';
        update qu1;
        opp1.stageName = 'Closing Won';
        update opp1;
        update opp2;
        mapOpp.put(opp2.id,opp2);
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(opp1);
       
		//OpportunityTriggerHelper.checkOpportunityStatusWithLatestQuoteStatus(oppList,mapOpp);        
        test.stopTest();
    }
      @isTest static void testOne() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        
        Test.startTest();
        Opportunity opp = new Opportunity(
            Name = 'Test1',
            AccountId = acc.Id,
            CloseDate = System.Today(),
            CurrencyIsoCode = 'USD',
            //Application__c = 'Agent/ Distributor',
            StageName = 'Briefing',
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId(),
            Business_Unit__c = 'Cocoa',
            Pricebook2Id = Test.getStandardPricebookId()
        );
        insert opp;
        
        OpportunityLineItem oppli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            PricebookEntryId = [SELECT Id FROM PricebookEntry][0].Id
        );
        insert oppli;
        Test.stopTest();
    }

}