src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cocoa_Owner__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cocoa Owner</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dairy_Owner_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Dairy Owner Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Edible_Nuts_Owner_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Edible Nuts Owner Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spice_Owner_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Spices Owner Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consumption</relationshipLabel>
        <relationshipName>Consumption</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>Coffee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Consumption</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>RecordId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumption</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Interactions__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <defaultValue>IF(CONTAINS($UserRole.Name, &apos;Cocoa&apos;), &apos;Cocoa Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Dairy&apos;), &apos;Dairy Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Spice&apos;), &apos;Spice Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Edible_Nuts&apos;), &apos;Edible_Nuts Sales Manager&apos;, &apos; &apos;)))))))</defaultValue>
        <label>Role Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Dairy Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Spice Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts Sales Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/OlamTeamSharing.cls
public class OlamTeamSharing {
    
    private Set<Id> accountList;
    private Map<Id, List<Teams__c>> accountTeamsMap;
    
    public OlamTeamSharing(List<Teams__c> inputs) {
        accountList = new Set<Id>();
        accountTeamsMap = new Map<Id, List<Teams__c>>();
        for(Teams__c team : inputs) {
            accountList.Add(team.Account__c);
            if(!accountTeamsMap.containsKey(team.Account__c)) {
                accountTeamsMap.put(team.Account__c, new List<Teams__c>());
            }
            accountTeamsMap.get(team.Account__c).add(team);
        }
        // OlamLogger.log('OlamTeamSharing - accountTeamsMap =' + JSON.serializePretty(accountTeamsMap));
    }
    
    private List<SObject> queryObject(String objName, String accountFieldName) {
        String query = 'SELECT Id, Business_Unit__c, ' + accountFieldName;
        query += ' FROM ' + objName;
		query += ' WHERE ' + accountFieldName + ' in :accountList';
        //OlamLogger.log('OlamTeamSharing - queryObject string = '  + query);
        List<SObject> ret = Database.query(query);
        //OlamLogger.logPretty('OlamTeamSharing - queryObject result', ret);
		return ret;
    }

    private List<SObject> getObjectShareList(String objName) {
        ObjectSharingFieldMap fieldMap = new ObjectSharingFieldMap(objName);
        String accountFieldName = fieldMap.objectAccountId;
        String businessUnitFieldName = fieldMap.objectBU;
        
        List<SObject> objShareList = new List<SObject>();
        for(SObject obj: queryObject(objName, accountFieldName)) {               
            for(Teams__c team: accountTeamsMap.get((Id)obj.get(accountFieldName))) {
                if(OlamSharingHelper.isTeamMatchWithBU(team.Role_Name__c, (String)obj.get(businessUnitFieldName))) {
                    SObject objShare = OlamSharingHelper.createObjectShare(objName, (Id)obj.get('Id'), team.User__c);
                    if(objShare != null)
                    	objShareList.add(objShare);
                }
            }
        }
        //OlamLogger.logPretty('OlamTeamSharing - getObjectShareList return', objShareList);
        return objShareList;
    }
    
    public void addSharing() {
        List<OpportunityShare> oppShareList = getObjectShareList('opportunity');
        oppShareList = OlamSharingHelper.filterDuplicateObjectShare('opportunity', oppShareList);
        insert oppShareList;
        
        List<Interactions__Share> interactionShareList = getObjectShareList('Interactions__c');
        interactionShareList = OlamSharingHelper.filterDuplicateObjectShare('Interactions__c', interactionShareList);
        insert interactionShareList;
        
        List<Consumption__Share> consumptionShareList = getObjectShareList('Consumption__c');
        consumptionShareList = OlamSharingHelper.filterDuplicateObjectShare('Consumption__c', consumptionShareList);
        insert consumptionShareList;
    }
    
    public void removeSharing() {
        List<OpportunityShare> oppShareExpectToDeleteList = getObjectShareList('opportunity');
        oppShareExpectToDeleteList = OlamSharingHelper.getObjectShareToDeleteList('opportunity', oppShareExpectToDeleteList);
        delete oppShareExpectToDeleteList;

        List<OpportunityShare> interactionShareExpectToDeleteList = getObjectShareList('Interactions__c');
        interactionShareExpectToDeleteList = OlamSharingHelper.getObjectShareToDeleteList('Interactions__c', interactionShareExpectToDeleteList);
        delete interactionShareExpectToDeleteList;
        
        List<OpportunityShare> consumptionShareExpectToDeleteList = getObjectShareList('Consumption__c');
        consumptionShareExpectToDeleteList = OlamSharingHelper.getObjectShareToDeleteList('Consumption__c', consumptionShareExpectToDeleteList);
        delete consumptionShareExpectToDeleteList;
    }
    
    public void clearAccountBUOwner() {
        List<Account> accToUpdate = new List<Account>();
        for(Account acc: [Select Id, Cocoa_Owner__c , Dairy_Owner_Id__c , Spice_Owner_Id__c, Edible_Nuts_Owner_Id__c
                                            from Account 
                                            where Id in :accountList]) {                                               
            for(Teams__c team: accountTeamsMap.get(acc.Id)) {  
                if(OlamSharingHelper.isCocoaPrimary(team.Is_Primary__c, team.Role_Name__c)) {
                    acc.Cocoa_Owner__c = null;
                    accToUpdate.add(acc);
                } 
                else if(OlamSharingHelper.isDairyPrimary(team.Is_Primary__c, team.Role_Name__c)) {
                    acc.Dairy_Owner_Id__c = null;
                    accToUpdate.add(acc);
                }
              	else if(OlamSharingHelper.isSpicePrimary(team.Is_Primary__c, team.Role_Name__c)) {
                    acc.Spice_Owner_Id__c = null;
                    accToUpdate.add(acc);
                }
                else if(OlamSharingHelper.isEdibleNutsPrimary(team.Is_Primary__c, team.Role_Name__c)) {
                    acc.Edible_Nuts_Owner_Id__c = null;
                    accToUpdate.add(acc);
                }
            }
		}
        if(!accToUpdate.isEmpty())
        	update accToUpdate;
    }
}