src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(Owner.UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;, 
IF( CONTAINS(Owner.UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;, &apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Plans__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <label>BU Identifier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <formula>Account__r.Customer_Group__c</formula>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plans Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Role_Name__c</fullName>
        <label>User Role Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Cocoa PDI Manager</fullName>
                </value>
                <value>
                    <fullName>Dairy Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Dairy PDI Manager</fullName>
                </value>
                <value>
                    <fullName>Spice Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Spice PDI Manager</fullName>
                </value>
                <value>
                    <fullName>Edible Nuts Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Edible Nuts PDI Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;,
IF( CONTAINS(UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;,
IF( CONTAINS(UserRole.Name, &apos;Spice&apos;) , &apos;Spice&apos;,
IF( CONTAINS(UserRole.Name, &apos;Edible_Nuts&apos;) , &apos;Edible_Nuts&apos;, &apos;&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/KAM_AccountTeamsCntl.cls
public class KAM_AccountTeamsCntl implements KAM_AccountPlan{
    public static String getDetails (String data) {
        Map<String, Object> requestMap = (Map<String, Object>) JSON.deserializeUntyped(data);
        if (requestMap.containsKey ('accountId')) {
            return JSON.serialize(getAccountTeams (String.valueOf(requestMap.get('accountId'))));
        }
        return null;
    }
    @AuraEnabled
    public static String getGroupDetails (String data) {
        Map<String, Object> requestMap = (Map<String, Object>) JSON.deserializeUntyped(data);
        if (requestMap.containsKey ('accountPlan')) {
            return JSON.serialize(getAccounts ((Account_Plans__c) JSON.deserialize(JSON.serialize(requestMap.get ('accountPlan')), Account_Plans__c.class)));
        }
        return null;
    }
    @AuraEnabled
    public static List<AccountTeamsWrapper> getAccountTeams(Id accountId){
        try {
            if (String.isBlank(accountId)) {
                return null;
            }
            List<AccountTeamsWrapper>listOfAccountTeams = new List<AccountTeamsWrapper>();
            for(Teams__c ts: [Select id,Name,Account__c, Account__r.Name, Is_Primary__c,User__c,User__r.BU_Identifier__c,User__r.Name,User_Role_Name__c from Teams__c where Account__c=:accountId ]){
                AccountTeamsWrapper atw = new AccountTeamsWrapper();
                atw.UserName = ts.User__r.Name;
                atw.Role = ts.User_Role_Name__c;
                atw.Primary = ts.Is_Primary__c;
                atw.BusinessUnit = ts.User__r.BU_Identifier__c;
                atw.Id = ts.Id;
                atw.accountId = ts.Account__c;
                atw.accountName = ts.Account__r.Name;

                listOfAccountTeams.add(atw);
            }
            return listOfAccountTeams;
        }catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }  
    }
    @AuraEnabled
    public static List<AccountTeamsWrapper> getAccountTeamsForGroup(Id accountId){
        try {
            if (String.isBlank(accountId)) {
                return null;
            }
            List<AccountTeamsWrapper>listOfAccountTeams = new List<AccountTeamsWrapper>();
            for(Teams__c ts: [Select id,Name,Account__c, Account__r.Name, Is_Primary__c,User__c,User__r.BU_Identifier__c,User__r.Name,User_Role_Name__c from Teams__c where Account__c=:accountId AND Is_Primary__c=true]){
                AccountTeamsWrapper atw = new AccountTeamsWrapper();
                atw.UserName = ts.User__r.Name;
                atw.Role = ts.User_Role_Name__c;
                atw.Primary = ts.Is_Primary__c;
                atw.BusinessUnit = ts.User__r.BU_Identifier__c;
                atw.Id = ts.Id;
                atw.accountId = ts.Account__c;
                atw.accountName = ts.Account__r.Name;

                listOfAccountTeams.add(atw);
            }
            return listOfAccountTeams;
        }catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }  
    }
    public static List<Account> getAccounts(Account_Plans__c accountPlan){
        if (accountPlan == null || String.isBlank(accountPlan.Customer_Group__c)) {
            NullPointerException e = new NullPointerException ();
            e.setMessage(Label.KAM_Invalid_Account_Plan_Detail_Error_Message);
            throw e;
        }
        return AccountSelector.getAccountsByCustomerGroupforoverview(accountPlan.Customer_Group__c,accountPlan.BU_Identifier__c);
    }
    
    
    public class AccountTeamsWrapper{
        @AuraEnabled
        public String Id;
        @AuraEnabled
        public String UserName;
        @AuraEnabled
        public String Role;
        @AuraEnabled
        public Boolean Primary;
        @AuraEnabled
        public String BusinessUnit;
        @AuraEnabled
        public String accountId;
        @AuraEnabled
        public String accountName;
    }
}