src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Key Account</fullName>
                </value>
                <value>
                    <fullName>Global Account</fullName>
                </value>
                <value>
                    <fullName>Regional Key Account</fullName>
                </value>
                <value>
                    <fullName>Regional Account</fullName>
                </value>
                <value>
                    <fullName>Local Key Account</fullName>
                </value>
                <value>
                    <fullName>Local Account</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Engagement_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Engagement Plans</relationshipLabel>
        <relationshipName>Engagement_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Engagement_Plan_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Engagement Plan Locked?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <label>Engagement Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Engagement Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Engagement_Plan_Line__c.object
<CustomObject>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actuals (Number)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Attendee__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Attendee</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Engagement_Plan__c</fullName>
        <label>Engagement Plan</label>
        <referenceTo>Engagement_Plan__c</referenceTo>
        <relationshipLabel>Engagement Plan Lines</relationshipLabel>
        <relationshipName>Engagement_Plan_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Frequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Engagement_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Engagement (Date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned__c</fullName>
        <label>Planned (Number)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Engagement__c</fullName>
        <label>Type of Engagement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_Engagement</valueSetName>
        </valueSet>
    </fields>
    <label>Engagement Plan Line</label>
    <nameField>
        <displayFormat>EPN-{0000000}</displayFormat>
        <label>Engagement Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Plan Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Interactions__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Approval_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Request for edit</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Frequency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bi Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Half Yearly</fullName>
    </customValue>
    <customValue>
        <fullName>Need Based</fullName>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

src/globalValueSets/Type_of_Engagement.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>C Level Engagement</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial (Sales &amp; Pricing)</fullName>
    </customValue>
    <customValue>
        <fullName>Finance (Structures &amp; Payments)</fullName>
    </customValue>
    <customValue>
        <fullName>Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>Risk (Solutions)</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;D (Market View Exchange)</fullName>
    </customValue>
    <customValue>
        <fullName>Sales &amp; Ops Planning/Review</fullName>
    </customValue>
    <customValue>
        <fullName>Sustainability</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Type of Engagement</masterLabel>
</GlobalValueSet>

src/classes/KAM_EngagementPlanSelectorTest.cls
@isTest
public class KAM_EngagementPlanSelectorTest {
    
    @testSetUp
    static void createData (){
        
         Account acc=new Account();
        acc.Name='DemoAccount';
        acc.Account_Type__c='Distributor';
        acc.BillingCountry='India';
        acc.BillingStreet='Pune-Mumbai road';
        insert acc;
        
        Engagement_Plan__c engPlan=new Engagement_Plan__c();
        engPlan.Account__c=acc.Id;
        engPlan.Is_Engagement_Plan_Locked__c=true;
        engPlan.End_Date__c=system.today().addDays (365);
        engPlan.Start_date__c=system.today();
        engPlan.Approval_Status__c='Pending';
        engPlan.Business_Unit__c='Cocoa';
        insert engPlan;
        
        Engagement_Plan_Line__c engPlanLine= new Engagement_Plan_Line__c();
        engPlanLine.Engagement_Plan__c=engPlan.Id;
        engPlanLine.Actuals__c=10;
            engPlanLine.Attendee__c='Test';
            engPlanLine.Description__c='its test data'; 
            engPlanLine.Frequency__c='Monthly';
            engPlanLine.Last_Engagement_Date__c=system.today();
            engPlanLine.Planned__c=20; 
            engPlanLine.Type_of_Engagement__c='C Level Engagement'; 
        	insert engPlanLine;
        
        Interactions__c inter=new Interactions__c();
        inter.Account__c=acc.Id;
        inter.Business_Unit__c='Cocoa';
        inter.Name='Test Interaction';
        insert inter;
        
    }
    
    public static testmethod void getEngangementPlansByAccountIdTest(){
      list<Account> acc=[select Id from Account where Name = 'DemoAccount'];
       String accId= acc[0].Id;
       String buIdentifier='Cocoa';
       Date startDate=system.Today();
        Date endDate=system.today().addDays (365);
       List<Engagement_Plan__c> EngPlan=EngagementPlanSelector.getEngangementPlansByAccountId(accId,buIdentifier,startDate,endDate);
        
       system.assert(EngPlan!=null, 'No active mapping for given type / occured an internal error');
       System.assert(!EngPlan.isEmpty (), 'Values not found for the given EngPlan'); 
        
       system.assertEquals(engPlan[0].Account__c, acc[0].id, 'Not matches Actual value and Expected Value');
    }
    public static testmethod void getEngagementPlanByInteractionDetailTest(){
        
        Interactions__c inter=[select Id,Account__c,Business_Unit__c,Name from Interactions__c where Name = 'Test Interaction'];
        Set<String> interType=new set<string>{'C Level Engagement','Commercial (Sales & Pricing)','Finance (Structures & Payments)','Innovation','Risk (Solutions)','S&D (Market View Exchange)'};
        List<Engagement_Plan__c> EngPlan= EngagementPlanSelector.getEngagementPlanByInteractionDetail(inter, interType);
        
        system.assert(EngPlan!=null, 'No active mapping for given type / occured an internal error');
        System.assert(!EngPlan.isEmpty (), 'Values not found for the given EngPlan');
        
       List<Engagement_Plan__c> engplanTest=[SELECT Id, Account__c, Business_Unit__c, End_Date__c, Start_date__c from Engagement_Plan__c where Business_Unit__c =: inter.Business_Unit__c ];
         system.assertEquals(engPlan[0].Start_date__c, engplanTest[0].Start_date__c, 'Not matches Actual value and Expected Value');
       }
    
    public static testmethod void getEngangementPlansByIdTest()
    {
          List<Engagement_Plan__c> engPlan =[SELECT Id, Account__c, Business_Unit__c, End_Date__c, Start_date__c from Engagement_Plan__c where Business_Unit__c = 'Cocoa' limit 1];
        String EngagementPlanId=engPlan[0].Id;
        List<Engagement_Plan__c> EngPlanTest= EngagementPlanSelector.getEngangementPlansBytId(EngagementPlanId);
        
        system.assert(EngPlanTest!=null, 'No active mapping for given type / occured an internal error');
        System.assert(!EngPlanTest.isEmpty (), 'Values not found for the given EngPlan');
      
       system.assertEquals(engPlan[0].Id, EngPlanTest[0].Id, 'Not matches Actual value and Expected Value');


    }

}