src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <label>Inco Terms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CFR</fullName>
                    <label>CFR - Costs and freight</label>
                </value>
                <value>
                    <fullName>CIF</fullName>
                    <label>CIF - Costs, insurance &amp; freight</label>
                </value>
                <value>
                    <fullName>CIP</fullName>
                    <label>CIP - Carriage and insurance paid</label>
                </value>
                <value>
                    <fullName>CPT</fullName>
                    <label>CPT - Carriage paid to</label>
                </value>
                <value>
                    <fullName>DAP</fullName>
                    <label>DAP - Delivered At Place</label>
                </value>
                <value>
                    <fullName>DDP</fullName>
                    <label>DDP - Delivered Duty Paid</label>
                </value>
                <value>
                    <fullName>DPU</fullName>
                    <label>DPU - Delivered At Place Unloaded</label>
                </value>
                <value>
                    <fullName>EXW</fullName>
                    <label>EXW - Ex Works</label>
                </value>
                <value>
                    <fullName>FAS</fullName>
                    <label>FAS - Free Along Sideship</label>
                </value>
                <value>
                    <fullName>FCA</fullName>
                    <label>FCA - Free Carrier</label>
                </value>
                <value>
                    <fullName>FOB</fullName>
                    <label>FOB - Free On Board</label>
                </value>
                <value>
                    <fullName>Instore</fullName>
                </value>
                <value>
                    <fullName>CNF</fullName>
                    <isActive>false</isActive>
                    <label>CNF</label>
                </value>
                <value>
                    <fullName>DAT</fullName>
                    <isActive>false</isActive>
                    <label>DAT</label>
                </value>
                <value>
                    <fullName>DDU</fullName>
                    <isActive>false</isActive>
                    <label>DDU</label>
                </value>
                <value>
                    <fullName>DES</fullName>
                    <isActive>false</isActive>
                    <label>DES</label>
                </value>
                <value>
                    <fullName>FOR</fullName>
                    <isActive>false</isActive>
                    <label>FOR</label>
                </value>
                <value>
                    <fullName>FOT</fullName>
                    <isActive>false</isActive>
                    <label>FOT</label>
                </value>
                <value>
                    <fullName>UN</fullName>
                    <isActive>false</isActive>
                    <label>UN</label>
                </value>
                <value>
                    <fullName>Z05</fullName>
                    <isActive>false</isActive>
                    <label>Z05</label>
                </value>
                <value>
                    <fullName>Z06</fullName>
                    <isActive>false</isActive>
                    <label>Z06</label>
                </value>
                <value>
                    <fullName>Z09</fullName>
                    <isActive>false</isActive>
                    <label>Z09</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <label>Sales Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SG41 - 01 - 03</fullName>
                </value>
                <value>
                    <fullName>SG41 - 02 - 03</fullName>
                </value>
                <value>
                    <fullName>SG41 - 07 - 03</fullName>
                </value>
                <value>
                    <fullName>SG42 - 01 - 03</fullName>
                </value>
                <value>
                    <fullName>SG42 - 02 - 03</fullName>
                </value>
                <value>
                    <fullName>SG42 - 07 - 03</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Sales_Area__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Credit Limit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Distribution Channel</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Division</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Inco Terms</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Org</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Conditions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipping Conditions</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Terms of Payment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To Delete</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Area</label>
    <nameField>
        <displayFormat>SalesArea--{00000}</displayFormat>
        <label>Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SalesAreaTriggerHandler_Test.cls
@isTest
public class SalesAreaTriggerHandler_Test {
    
    public static void createTestUser() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
            UserRole cocoaRole = new UserRole(DeveloperName = 'Cocoa_Something_Role', Name = 'Cocoa Something');
            insert cocoaRole;
            
            Id cocoaProfileId = [SELECT Id FROM Profile WHERE Name = 'Cocoa Sales'].Id;
            User user = new User(
                ProfileId = cocoaProfileId,
                LastName = 'UnitTestCocoaUser1',
                Email = 'UnitTestCocoaUser1' + '@unittestuser.com',
                Username = 'UnitTestCocoaUser1' + '@unittestuser.com' + System.currentTimeMillis(),
                CompanyName = 'TEST',
                Title = 'title',
                Alias = 'alias',
                TimeZoneSidKey = 'America/Los_Angeles',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                UserRoleId = cocoaRole.Id
            );    
            insert user;
        }
    }
    
    @testSetup
    public static void prepare() {
        createTestUser();
        
        User user1 = [SELECT Id FROM User WHERE LastName = 'UnitTestCocoaUser1'];
        System.runAs (user1) {
            Account acc = new Account(Name = 'UNIT TEST account',
                                          BillingStreet = 'Test 1 street',
                                          BillingCountry = 'Singapore');
            insert acc;
       }
    }
    
    // Existing: 
    // New:      1
    // Expected result: Add 1
    @isTest
    public static void addNew() {
        Test.startTest();
        // Arrange
        Account acc = [SELECT Id FROM Account WHERE Name = 'UNIT TEST account'];
        
        // Action
        Sales_Area__c salesArea1 = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG41-OIL Processing-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality',
                                                    Credit_Limit__c = 'CreditLimitCocoa',
                                                    Inco_Terms__c = 'IncoTermsCocoa',
                                                    Shipping_Conditions__c = 'ShippingConditionCocoa', 
                                                    Terms_of_Payment__c= 'TermsOfPaymentCocoa');
        insert salesArea1;
        
        // Assert
        List<Sales_Area__c> currentSalesAreas = [Select Id from Sales_Area__c where Account_Name__c = :acc.Id];
        Test.stopTest();
        
        System.assertEquals(1, currentSalesAreas.size(), 'Number of the current sales areas are wrong');
        System.assertEquals(salesArea1.Id, currentSalesAreas[0].Id, 'salesArea1 is changed');
    }
    
    // Existing: 1 2
    // New:      1 2
    // Expected result: remains existing 1 2
    @isTest
    public static void sameThenDoNothing() {
        Test.startTest();
        // Arrange
        Account acc = [SELECT Id FROM Account WHERE Name = 'UNIT TEST account'];        
        Sales_Area__c salesArea1 = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG41-OIL Processing-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality',
                                                    Credit_Limit__c = 'CreditLimitCocoa',
                                                    Inco_Terms__c = 'IncoTermsCocoa',
                                                    Shipping_Conditions__c = 'ShippingConditionCocoa', 
                                                    Terms_of_Payment__c= 'TermsOfPaymentCocoa');
        Sales_Area__c salesArea2 = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG42-OIL Beans-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality',
                                                    Credit_Limit__c = 'CreditLimitCocoa',
                                                    Inco_Terms__c = 'IncoTermsCocoa',
                                                    Shipping_Conditions__c = 'ShippingConditionCocoa', 
                                                    Terms_of_Payment__c= 'TermsOfPaymentCocoa');
        List<Sales_Area__c> existingSalesAreas = new List<Sales_Area__c>{salesArea1, salesArea2};
        insert existingSalesAreas;
        // Action
        Sales_Area__c salesArea1New = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG41-OIL Processing-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality',
                                                    Credit_Limit__c = 'CreditLimitCocoa',
                                                    Inco_Terms__c = 'IncoTermsCocoa',
                                                    Shipping_Conditions__c = 'ShippingConditionCocoa', 
                                                    Terms_of_Payment__c= 'TermsOfPaymentCocoa');
        Sales_Area__c salesArea2New = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG42-OIL Beans-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality',
                                                    Credit_Limit__c = 'CreditLimitCocoa',
                                                    Inco_Terms__c = 'IncoTermsCocoa',
                                                    Shipping_Conditions__c = 'ShippingConditionCocoa', 
                                                    Terms_of_Payment__c= 'TermsOfPaymentCocoa');
        List<Sales_Area__c> newSalesAreas = new List<Sales_Area__c>{salesArea1New, salesArea2New};
        insert newSalesAreas;
        
        // Assert
        List<Sales_Area__c> currentSalesAreas = [Select Id from Sales_Area__c where Account_Name__c = :acc.Id];
        Test.stopTest();
        
        System.assertEquals(2, currentSalesAreas.size(), 'Number of the current sales areas are wrong');
        System.assertEquals(salesArea1.Id, currentSalesAreas[0].Id, 'salesArea1 is changed');
        System.assertEquals(salesArea2.Id, currentSalesAreas[1].Id, 'salesArea2 is changed');
    }
    
    // Existing: 1 2
    // New:      1 2(changed)
    // Expected result: keep   existing 1 and new 2
    //                  delete new 1 and existing 2
    @isTest
    public static void ifChangedThenUseNewOne() {
        Test.startTest();
        // Arrange
        Account acc = [SELECT Id FROM Account WHERE Name = 'UNIT TEST account'];
        
        Sales_Area__c salesArea1 = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG41-OIL Processing-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality',
                                                    Credit_Limit__c = 'CreditLimitCocoa',
                                                    Inco_Terms__c = 'IncoTermsCocoa',
                                                    Shipping_Conditions__c = 'ShippingConditionCocoa', 
                                                    Terms_of_Payment__c= 'TermsOfPaymentCocoa');
        Sales_Area__c salesArea2 = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG42-OIL Beans-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality',
                                                    Credit_Limit__c = 'CreditLimitCocoa',
                                                    Inco_Terms__c = 'IncoTermsCocoa',
                                                    Shipping_Conditions__c = 'ShippingConditionCocoa', 
                                                    Terms_of_Payment__c= 'TermsOfPaymentCocoa');
        List<Sales_Area__c> existingSalesAreas = new List<Sales_Area__c>{salesArea1, salesArea2};
        insert existingSalesAreas;
        // Action
        Sales_Area__c salesArea1New = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG41-OIL Processing-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality',
                                                    Credit_Limit__c = 'CreditLimitCocoa',
                                                    Inco_Terms__c = 'IncoTermsCocoa',
                                                    Shipping_Conditions__c = 'ShippingConditionCocoa', 
                                                    Terms_of_Payment__c= 'TermsOfPaymentCocoa');
        Sales_Area__c salesArea2New = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG42-OIL Beans-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality',
                                                    Credit_Limit__c = 'CreditLimitCocoa2',
                                                    Inco_Terms__c = 'IncoTermsCocoa2',
                                                    Shipping_Conditions__c = 'ShippingConditionCocoa2', 
                                                    Terms_of_Payment__c= 'TermsOfPaymentCocoa2');
        List<Sales_Area__c> newSalesAreas = new List<Sales_Area__c>{salesArea1New, salesArea2New};
        insert newSalesAreas;
        
        // Assert
        List<Sales_Area__c> currentSalesAreas = [Select Id from Sales_Area__c where Account_Name__c = :acc.Id];
        Test.stopTest();
        
        System.assertEquals(2, currentSalesAreas.size(), 'Number of the current sales areas are wrong');
        System.assertEquals(salesArea1.Id, currentSalesAreas[0].Id, 'salesArea1 is changed');
        System.assertEquals(salesArea2New.Id, currentSalesAreas[1].Id, 'salesArea2 is not deleted');
    }
    
    @isTest
    public static void removeExisting() {
        Test.startTest();
        // Arrange
        Account acc = [SELECT Id FROM Account WHERE Name = 'UNIT TEST account'];
        Sales_Area__c salesArea1 = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG41-OIL Processing-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality',
                                                    Credit_Limit__c = 'CreditLimitCocoa',
                                                    Inco_Terms__c = 'IncoTermsCocoa',
                                                    Shipping_Conditions__c = 'ShippingConditionCocoa', 
                                                    Terms_of_Payment__c= 'TermsOfPaymentCocoa');
        insert salesArea1;
        
        // Action
        Sales_Area__c salesArea2 = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG41-OIL Processing-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality',
                                                    Credit_Limit__c = 'CreditLimitCocoa',
                                                    Inco_Terms__c = 'IncoTermsCocoa',
                                                    Shipping_Conditions__c = 'ShippingConditionCocoa', 
                                                    Terms_of_Payment__c= 'TermsOfPaymentCocoa',
                                                    To_Delete__c = true);
        insert salesArea2;
        
        // Assert
        List<Sales_Area__c> currentSalesAreas = [Select Id from Sales_Area__c where Account_Name__c = :acc.Id];
        Test.stopTest();
        
        System.assertEquals(0, currentSalesAreas.size(), 'sales areas is not removed');
    }
    
    // Existing: 1 2 3
    // New:      2 3 4
    // Expected result: Remove 1 and Add 4
    /*@isTest
    public static void addNewAndDeleteUnmatch() {
        Test.startTest();
        // Arrange
        Account acc = new Account(Name = 'UNIT TEST account',
                                      BillingStreet = 'Test 1 street',
                                      BillingCountry = 'Singapore');
        insert acc;
        Sales_Area__c salesArea1 = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG41-OIL Processing-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality');
        Sales_Area__c salesArea2 = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG42-OIL Beans-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality');
        Sales_Area__c salesArea3 = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG43-OIL Products-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality');
        List<Sales_Area__c> existingSalesAreas = new List<Sales_Area__c>{salesArea1, salesArea2, salesArea3};
        insert existingSalesAreas;
        
        // Action
        Sales_Area__c salesArea2New = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG42-OIL Beans-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality');
        Sales_Area__c salesArea3New = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG43-OIL Products-Cocoa',
                                                    Distribution_Channel__c = '01-Export',
                                                    Division__c = '03-Cocoa and Speciality');
        Sales_Area__c salesArea4 = new Sales_Area__c(Account_Name__c = acc.Id, 
                                                    Sales_Org__c = 'SG41-OIL Processing-Cocoa',
                                                    Distribution_Channel__c = '02-Wholesale',
                                                    Division__c = '03-Cocoa and Speciality');
        List<Sales_Area__c> newSalesAreas = new List<Sales_Area__c>{salesArea2New, salesArea3New, salesArea4};
        insert newSalesAreas;
        
        // Assert
        List<Sales_Area__c> currentSalesAreas = [Select Id from Sales_Area__c where Account_Name__c = :acc.Id];
        Test.stopTest();
        
        System.assertEquals(3, currentSalesAreas.size(), 'Number of the current sales areas are wrong');
        System.assertEquals(salesArea2.Id, currentSalesAreas[0].Id, 'salesArea2 is changed');
        System.assertEquals(salesArea3.Id, currentSalesAreas[1].Id, 'salesArea3 is changed');
        System.assertEquals(salesArea4.Id, currentSalesAreas[2].Id, 'salesArea4 is changed');
    }*/
}