src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Interest__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Kit__c</fullName>
        <label>Price Kit</label>
        <referenceTo>Price_Kit__c</referenceTo>
        <relationshipLabel>Interest</relationshipLabel>
        <relationshipName>Interest</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Interest %</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Interest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PLBS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>PLBS_Product__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>TEXT(PLBS_Product__r.Product_Family__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Packing_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Packing_Cost_lbs__c</fullName>
        <label>Packing Cost ($/lbs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Kit__c</fullName>
        <label>Price Kit</label>
        <referenceTo>Price_Kit__c</referenceTo>
        <relationshipLabel>Packing Cost</relationshipLabel>
        <relationshipName>Packing_Cost</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Packing Cost</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Packing Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Cost</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pallet__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Kit__c</fullName>
        <label>Price Kit</label>
        <referenceTo>Price_Kit__c</referenceTo>
        <relationshipLabel>Pallet</relationshipLabel>
        <relationshipName>Pallet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pallet</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Pallet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pallet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PLBS_Product__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Family__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>PLBS_Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Family</valueSetName>
        </valueSet>
    </fields>
    <label>Private Label Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Private Label Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Price_Kit__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Price Kit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Price Kit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Kits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Price_Kit__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Kit__c</fullName>
        <label>Price Kit</label>
        <referenceTo>Price_Kit__c</referenceTo>
        <relationshipLabel>Product Price Kit</relationshipLabel>
        <relationshipName>Product_Price_Kit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Processing_cost_USD_lb__c</fullName>
        <label>Processing cost (USD/lb)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Processing_loss__c</fullName>
        <label>Processing loss %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PLBS_Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Family</valueSetName>
        </valueSet>
    </fields>
    <label>Product Price Kit</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product Price Kit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Price Kit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quotations_as_per__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fobbing_container__c</fullName>
        <label>Fobbing/container</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>20FT Container</fullName>
                </value>
                <value>
                    <fullName>40FT Container</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Kit__c</fullName>
        <label>Price Kit</label>
        <referenceTo>Price_Kit__c</referenceTo>
        <relationshipLabel>Quotations as per</relationshipLabel>
        <relationshipName>Quotations_as_per</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>USD__c</fullName>
        <label>USD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Quotations as per</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Quotations as per Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations as per</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Fobbing_Container__c</fullName>
        <label>Fobbing/ Container</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Packing_Cost_lbs__c</fullName>
        <label>Packing Cost ($/lbs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TCB__c.object
<CustomObject>
    <fields>
        <fullName>Fobbing_Container__c</fullName>
        <label>Fobbing / Container</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>TCB</label>
    <nameField>
        <displayFormat>TCB - {00000}</displayFormat>
        <label>TCB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/X1st_PM__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loss__c</fullName>
        <label>Loss %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Price_Kit__c</fullName>
        <label>Price Kit</label>
        <referenceTo>Price_Kit__c</referenceTo>
        <relationshipLabel>1st PM</relationshipLabel>
        <relationshipName>X1st_PM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X1st_PM_Type__c</fullName>
        <label>1st PM Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DOY</fullName>
                </value>
                <value>
                    <fullName>PILLOW</fullName>
                </value>
                <value>
                    <fullName>FOUR SIDE SEAL</fullName>
                </value>
                <value>
                    <fullName>DOY FLAT BOTTOM</fullName>
                </value>
                <value>
                    <fullName>PILLOW BLOCK BOTTOM</fullName>
                </value>
                <value>
                    <fullName>VACUUM</fullName>
                </value>
                <value>
                    <fullName>PET JAR</fullName>
                </value>
                <value>
                    <fullName>GLASS JAR</fullName>
                </value>
                <value>
                    <fullName>PET CYLINDER JAR</fullName>
                </value>
                <value>
                    <fullName>METAL CANISTER</fullName>
                </value>
                <value>
                    <fullName>COMPOSITE CANISTER</fullName>
                </value>
                <value>
                    <fullName>PET CANISTER</fullName>
                </value>
                <value>
                    <fullName>PAPER MILK BOTTLE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>1st PM</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>1st PM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1st PM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/X2nd_PM__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loss__c</fullName>
        <label>Loss %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Price_Kit__c</fullName>
        <label>Price Kit</label>
        <referenceTo>Price_Kit__c</referenceTo>
        <relationshipLabel>2nd PM</relationshipLabel>
        <relationshipName>X2nd_PM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X2nd_PM_Type__c</fullName>
        <label>2nd PM Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RSC</fullName>
                </value>
                <value>
                    <fullName>TRAY &amp; LID</fullName>
                </value>
                <value>
                    <fullName>TRAY ONLY</fullName>
                </value>
                <value>
                    <fullName>PRE CUT RSC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>2nd PM</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>2nd PM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>2nd PM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/PLBS_Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Nut mixes</fullName>
    </customValue>
    <customValue>
        <fullName>Pasteurized nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Dry roasted nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Oil roasted nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Salts nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Seasoned nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Trail mixes</fullName>
    </customValue>
    <customValue>
        <fullName>Natural nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Blanched nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Diced nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Slivered nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Sliced nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Nut meal</fullName>
    </customValue>
    <customValue>
        <fullName>Natural paste</fullName>
    </customValue>
    <customValue>
        <fullName>Blanched paste</fullName>
    </customValue>
    <customValue>
        <fullName>Roasted paste</fullName>
    </customValue>
    <customValue>
        <fullName>Pure paste</fullName>
    </customValue>
    <customValue>
        <fullName>Flavored paste</fullName>
    </customValue>
    <customValue>
        <fullName>Granola</fullName>
    </customValue>
    <customValue>
        <fullName>Protein</fullName>
    </customValue>
    <customValue>
        <fullName>Coated bars</fullName>
    </customValue>
    <customValue>
        <fullName>Nut-based cookies</fullName>
    </customValue>
    <customValue>
        <fullName>Natural oil</fullName>
    </customValue>
    <customValue>
        <fullName>Infused oil</fullName>
    </customValue>
    <customValue>
        <fullName>Natural milk</fullName>
    </customValue>
    <customValue>
        <fullName>Flavored milk</fullName>
    </customValue>
    <customValue>
        <fullName>Single Nuts/Fruits</fullName>
        <isActive>false</isActive>
        <label>Single Nuts/Fruits</label>
    </customValue>
    <customValue>
        <fullName>Mixed Nuts</fullName>
        <isActive>false</isActive>
        <label>Mixed Nuts</label>
    </customValue>
    <customValue>
        <fullName>Nut Meal/Flour</fullName>
        <isActive>false</isActive>
        <label>Nut Meal/Flour</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Family.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Snacks</fullName>
    </customValue>
    <customValue>
        <fullName>Ingredients</fullName>
    </customValue>
    <customValue>
        <fullName>Paste</fullName>
    </customValue>
    <customValue>
        <fullName>Bars &amp; Cookies</fullName>
    </customValue>
    <customValue>
        <fullName>Nut &amp; Seed Oils</fullName>
    </customValue>
    <customValue>
        <fullName>Milk</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

src/classes/OpportunityTriggerHelperVietnamTest.cls
@isTest
public class OpportunityTriggerHelperVietnamTest {
    
     @testSetup 
    static void testRecords(){
        
        Profile proId =[select Id from Profile where Name='Vietnam PLBS'];
         User us = createTestUser('Tester',ProId.id,null);
        PermissionSet ps = new PermissionSet(Label = 'mockPs', Name = 'mockPs');
        insert ps;
        CustomPermission ps1 = [SELECT Id FROM CustomPermission WHERE DeveloperName = 'Olam_Validation_Exception' limit 1];
        SetupEntityAccess sea = new SetupEntityAccess(
            ParentId = ps.Id,
            SetupEntityId = ps1.Id
        );
        insert sea;
        insert new PermissionSetAssignment(AssigneeId = us.id, PermissionSetId = ps.Id);  
        
        system.runAs(us){
        Account acc = new Account(Name = 'UNIT TEST account1', BillingCity='TestIndia', BillingStreet = 'Test 1 street', BillingCountry = 'India', BillingCountryCode ='IN', BillingPostalCode = '123456' , ShippingStreet = 'Test 2 street', ShippingCountry = 'India', ShippingCountryCode ='IN', ShippingPostalCode = '123456');        
        insert acc;
        Product2 product1 = new Product2(Name = 'UNIT TEST Product 1');
        insert product1;
        Pricebook2 standardPricebook = new Pricebook2(Id = Test.getStandardPricebookId(),IsActive = true);     
        Update standardPricebook;
        PricebookEntry pbEntry1 = new PricebookEntry(Pricebook2Id = standardPricebook.Id, Product2Id = product1.Id, UnitPrice = 100, IsActive = true);
        insert pbEntry1;
        
        PLBS_Product__c plbsPro=new PLBS_Product__c(Name='TestingPro',Product_Family__c='Snacks',Product_Category__c='Nut mixes');
        insert plbsPro;
        
        Price_Kit__c pk=new Price_Kit__c(Active__c=true,Name='2021',Start_Date__c=system.today());
        insert pk;
        Product_Price_Kit__c ppk = new Product_Price_Kit__c(Price_Kit__c=pk.Id,Product_Family__c='Snacks',Product_Category__c='Nut mixes',Processing_loss__c=20,Processing_cost_USD_lb__c=10,Active__c=true);
        insert ppk;
        X1st_PM__c pm1st = new X1st_PM__c(Price_Kit__c=pk.Id,X1st_PM_Type__c='DOY',Loss__c=0.2,Active__c=true);
        insert pm1st;
        X2nd_PM__c pm2st = new X2nd_PM__c(Price_Kit__c=pk.Id,X2nd_PM_Type__c='RSC',Loss__c=0.2,Active__c=true);
        insert pm2st;
        Quotations_as_per__c Qap= new Quotations_as_per__c(Price_Kit__c=pk.Id, USD__c=200,Fobbing_container__c='40FT Container',Active__c=true);
        insert qap;
        Packing_Cost__c pc = new Packing_Cost__c(Price_Kit__c=pk.Id,Active__c=true,To__c=101,From__c=10,Packing_Cost_lbs__c=10);     
        insert pc;   
        Pallet__c pt = new Pallet__c(Price_Kit__c=pk.Id,Active__c=true,Pallet_Type__c='Disposal - 0.8x1.2m',USD_each__c=10);
        insert pt;
        Interest__c ints = new Interest__c(Price_Kit__c=pk.Id,Active__c=true,Interest__c=5);
        insert ints;
            
        Id ParentRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Opportunity').getRecordTypeId();
        Id TCBRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Product').getRecordTypeId();
        Opportunity opp = new Opportunity(AccountId = acc.Id, 
                                          Name = 'unittest - opp',
                                          StageName = 'Briefing',
                                          CloseDate = date.newInstance(2050, 11, 21),
                                          Business_Unit__c = 'Dairy',
                                          RecordTypeId = ParentRecordTypeId,
                                          Local_Currency__c='USD',
                                          Pricebook2Id = standardPricebook.Id,
                                          Project_Type__c = 'Sample');
        insert opp;
        Opportunity opp1 = new Opportunity(AccountId = acc.Id, 
                                           Name = 'unittest - opp1',
                                           parent_Opportunity__c=Opp.Id,
                                           StageName = 'Briefing',
                                           PLBS_Product__c = plbsPro.Id,
                                           Plbs_Weight_G__c=100,
                                           CloseDate = date.newInstance(2050, 11, 21),
                                           Business_Unit__c = 'Dairy',
                                           RecordTypeId = TCBRecordTypeId,
                                           Pricebook2Id = standardPricebook.Id,
                                           Plbs_Annual_Unit__c =1,
                                           Plbs_Est_Award__c=1000,
                                           Project_Type__c = 'Sample');
        insert opp1;
        
        tcb__c tcb=new TCb__c(Opportunity__c=Opp1.Id,PM_Type_1st__c='DOY',PM_Type_2nd__c='RSC',Fobbing_Container__c=20,CTN_40FT_HC__c =20,Unit_CTN__c=10,
                              Pallet_Type__c='Disposal - 0.8x1.2m',Quotations_Given_as_Per__c='40FT Container');
        tcb.Opportunity_Processing__c=10;
        tcb.Interest__c=10;
        //tcb.Initial_Design_TCB__c=10;
        tcb.Loss_Product__c=10;
        tcb.Initial_Design__c=1;
        insert tcb;
        
            
        Quote qun= new Quote(OpportunityId=opp1.Id,Name='testq',pricebook2Id =standardPricebook.Id,ExpirationDate=system.today()+30,Inco_Terms__c='DAP',Ship_To_Party__c=acc.id);
            insert qun;
        
        
    }

    }
    
    @istest static void testMethod1(){
        
    }
    
 public static User createTestUser(string lastName, Id profileId, Id roleId) {
        User user = new User(
            ProfileId = profileId,
            LastName = lastName,
            Email = lastName + '@unittestuser.com',
            Username = lastName + '@unittestuser.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            UserRoleId = roleId
        );    
        insert user;
        return user;
    }
    
    

}