src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <description>To Identify the account region</description>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                    <isActive>false</isActive>
                    <label>Africa</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                    <isActive>false</isActive>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>Europe</fullName>
                    <isActive>false</isActive>
                    <label>Europe</label>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                    <isActive>false</isActive>
                    <label>Latin America</label>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                    <isActive>false</isActive>
                    <label>Middle East</label>
                </value>
                <value>
                    <fullName>North America</fullName>
                    <isActive>false</isActive>
                    <label>North America</label>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                    <isActive>false</isActive>
                    <label>Oceania</label>
                </value>
                <value>
                    <fullName>South America</fullName>
                    <isActive>false</isActive>
                    <label>South America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Others ( e-commerce, etc.)</fullName>
    </customValue>
    <customValue>
        <fullName>Private Label / Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Product Group or Brand Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Trade House</fullName>
    </customValue>
    <customValue>
        <fullName>B2B Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Food Service / Quick Service Restaurants</fullName>
    </customValue>
    <customValue>
        <fullName>Importer / Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Channel TWO</fullName>
        <isActive>false</isActive>
        <label>Channel TWO</label>
    </customValue>
    <customValue>
        <fullName>Channel ONE</fullName>
        <isActive>false</isActive>
        <label>Channel ONE</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

src/classes/SharingUtilityTest.cls
@isTest
public class SharingUtilityTest {
 @testSetup
    public static void createData()
    {
        Id currentUserId = UserInfo.getUserId();
        User user = new User(ProfileId = [SELECT Id FROM Profile WHERE Name = 'Dairy Sales'].Id, LastName = 'UnitTestUser1', Email = 'unittestuser000@unittestuser.com',
                             Username = 'unittestuser000@unittestuser.com' + System.currentTimeMillis(), CompanyName = 'TEST', Title = 'title',
                             Alias = 'alias', TimeZoneSidKey = 'America/Los_Angeles', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US',
                             LocaleSidKey = 'en_US'//, Access_Set_Role__c = 'Sales'
                            );    
        insert user;
        Account acc1 = OFI_TestDataFactory.createAccount(true);
        Account acc2 = new Account(Name='Test02', BillingCountry = 'China', BillingStreet ='Test',//Segment__c = 'Agent/ Distributor',
                                   Regions__c ='APAC',Customer_Group__c = 'Cadboury');
        insert acc2;
        Teams__c team = OFI_TestDataFactory.createAccountTeam(acc1.Id, user.Id, 'All', 'Edit Access',//'Sales',
                                                              true, true);
        Teams__c team2 = OFI_TestDataFactory.createAccountTeam(acc2.Id, currentUserId, 'Cocoa', 'Read Access',//'PDI',
                                                               false, true);
        
    }
    public static testmethod void data()
    {
        List<Account> account = [Select Id, Name, BillingCountryCode, Regions__c, Customer_Group__c, Channel__c From Account];
        Set<Id> setOfNewAccountIds = new Set<Id>();
        if(!account.isEmpty()){
        for(Account acc : account)
        {
            setOfNewAccountIds.add(acc.Id);
        }
            System.debug('acc====>'+account);
            System.debug('setofAccIds====>'+setOfNewAccountIds);
        SharingUtility.getAccountTeamsUserBUs(setOfNewAccountIds);
        }
    }
}