src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <label>Inco Terms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CFR</fullName>
                    <label>CFR - Costs and freight</label>
                </value>
                <value>
                    <fullName>CIF</fullName>
                    <label>CIF - Costs, insurance &amp; freight</label>
                </value>
                <value>
                    <fullName>CIP</fullName>
                    <label>CIP - Carriage and insurance paid</label>
                </value>
                <value>
                    <fullName>CPT</fullName>
                    <label>CPT - Carriage paid to</label>
                </value>
                <value>
                    <fullName>DAP</fullName>
                    <label>DAP - Delivered At Place</label>
                </value>
                <value>
                    <fullName>DDP</fullName>
                    <label>DDP - Delivered Duty Paid</label>
                </value>
                <value>
                    <fullName>DPU</fullName>
                    <label>DPU - Delivered At Place Unloaded</label>
                </value>
                <value>
                    <fullName>EXW</fullName>
                    <label>EXW - Ex Works</label>
                </value>
                <value>
                    <fullName>FAS</fullName>
                    <label>FAS - Free Along Sideship</label>
                </value>
                <value>
                    <fullName>FCA</fullName>
                    <label>FCA - Free Carrier</label>
                </value>
                <value>
                    <fullName>FOB</fullName>
                    <label>FOB - Free On Board</label>
                </value>
                <value>
                    <fullName>Instore</fullName>
                </value>
                <value>
                    <fullName>CNF</fullName>
                    <isActive>false</isActive>
                    <label>CNF</label>
                </value>
                <value>
                    <fullName>DAT</fullName>
                    <isActive>false</isActive>
                    <label>DAT</label>
                </value>
                <value>
                    <fullName>DDU</fullName>
                    <isActive>false</isActive>
                    <label>DDU</label>
                </value>
                <value>
                    <fullName>DES</fullName>
                    <isActive>false</isActive>
                    <label>DES</label>
                </value>
                <value>
                    <fullName>FOR</fullName>
                    <isActive>false</isActive>
                    <label>FOR</label>
                </value>
                <value>
                    <fullName>FOT</fullName>
                    <isActive>false</isActive>
                    <label>FOT</label>
                </value>
                <value>
                    <fullName>UN</fullName>
                    <isActive>false</isActive>
                    <label>UN</label>
                </value>
                <value>
                    <fullName>Z05</fullName>
                    <isActive>false</isActive>
                    <label>Z05</label>
                </value>
                <value>
                    <fullName>Z06</fullName>
                    <isActive>false</isActive>
                    <label>Z06</label>
                </value>
                <value>
                    <fullName>Z09</fullName>
                    <isActive>false</isActive>
                    <label>Z09</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ZU13 - Net 60 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>Z070 - 2% 15 days, 60 days net</fullName>
                </value>
                <value>
                    <fullName>ZU10 - Net 30 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>ZU14 - Net 90 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>ZU17 - Payment in Advance,Prepayment</fullName>
                </value>
                <value>
                    <fullName>ZU07 - Net 15 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>ZS87 - CAD at Sight In Trust@120 day-98%-2% Pay on req</fullName>
                </value>
                <value>
                    <fullName>ZU12 - Net 45 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>USBM - 2% 10 NET 45</fullName>
                </value>
                <value>
                    <fullName>US0D - 1% 10 NET 60</fullName>
                </value>
                <value>
                    <fullName>ZU04 - Net 7 days - Date of Invoice</fullName>
                    <default>true</default>
                    <label>ZU04 - Net 7 days - Date of Invoice</label>
                </value>
                <value>
                    <fullName>ZS96 - CAD at Sight In Trust @ 75 day - 100%</fullName>
                </value>
                <value>
                    <fullName>USAE - Net due in 65 days</fullName>
                </value>
                <value>
                    <fullName>ZU11 - Net 40 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>SG06 - Letter of credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>KG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Contract_end_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract end date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_start_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ratio__c</fullName>
        <label>Ratio</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_of_measure__c</fullName>
        <label>Unit of measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <description>Text Box Field Inco Terms</description>
        <inlineHelpText>Enter Inco Terms</inlineHelpText>
        <label>Inco Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFR - Costs and freight</fullName>
                </value>
                <value>
                    <fullName>CIF - Costs, insurance &amp; freight</fullName>
                </value>
                <value>
                    <fullName>CIP - Carriage and insurance paid</fullName>
                </value>
                <value>
                    <fullName>CPT - Carriage paid to</fullName>
                </value>
                <value>
                    <fullName>DAP - Delivered At Place</fullName>
                </value>
                <value>
                    <fullName>DDP - Delivered Duty Paid</fullName>
                </value>
                <value>
                    <fullName>EXW - Ex Works</fullName>
                </value>
                <value>
                    <fullName>FAS - Free Along Sideship</fullName>
                </value>
                <value>
                    <fullName>FCA - Free Carrier</fullName>
                </value>
                <value>
                    <fullName>FOB - Free On Board</fullName>
                </value>
                <value>
                    <fullName>DPU - Delivered At Place Unloaded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MOQ_Packaging_1st__c</fullName>
        <label>MOQ Packaging (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Olam_Quote_Number__c</fullName>
        <formula>Opportunity.OlamQuoteNumber__c &amp;&apos;_&apos;&amp; TEXT(Version__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Olam Quote Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PM_Type_1st__c</fullName>
        <label>PM Type (1st)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1st_PM_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <formula>TEXT( Opportunity.Account.Payment_Terms__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Terms</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Terms_Conditions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Terms &amp; Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ratio__c</fullName>
        <label>Ratio</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measure__c</fullName>
        <label>Unit Of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Unit_of_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MT</fullName>
        <default>true</default>
        <label>MT</label>
    </customValue>
    <customValue>
        <fullName>LB</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>QE</fullName>
        <isActive>false</isActive>
        <label>QE</label>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
        <isActive>false</isActive>
        <label>Carton</label>
    </customValue>
    <masterLabel>Unit of Measure</masterLabel>
</GlobalValueSet>

src/globalValueSets/X1st_PM_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DOY</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW</fullName>
    </customValue>
    <customValue>
        <fullName>FOUR SIDE SEAL</fullName>
    </customValue>
    <customValue>
        <fullName>DOY FLAT BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW BLOCK BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>VACUUM</fullName>
    </customValue>
    <customValue>
        <fullName>PET JAR</fullName>
    </customValue>
    <customValue>
        <fullName>GLASS JAR</fullName>
    </customValue>
    <customValue>
        <fullName>PET CYLINDER JAR</fullName>
    </customValue>
    <customValue>
        <fullName>METAL CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>COMPOSITE CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PET CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PAPER MILK BOTTLE</fullName>
    </customValue>
    <masterLabel>1st PM Type</masterLabel>
</GlobalValueSet>

src/classes/PLBSQuotePDFCustomCntl_Test.cls
@isTest
public class PLBSQuotePDFCustomCntl_Test {
@testSetup
    public static void createData()
{
     Profile profOfi = [select id from profile where name='OFI'];
        
        
        User ofiuser = new User(alias = 'jack qu', email='jackqu@noemail.com',
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US',
                                localesidkey='en_US', profileid = profOfi.Id,
                                timezonesidkey='America/Los_Angeles',  username='jackqu@noemail.com');
        insert ofiuser;  
        
        User ofiuser1 = new User(alias = 'jack8', email='jackqu@noemail.com',
                                 emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US',
                                 localesidkey='en_US', profileid = profOfi.Id,
                                 timezonesidkey='America/Los_Angeles',  username='jack8@noemail.com');
        insert ofiuser1;
        
        List<user> currentuser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Account acc= OFI_TestDataFactory.createMultipleAccount('Test for Quote', 'India','In', null, null, null, true);
        Account acc1= OFI_TestDataFactory.createMultipleAccount('TestQuote1', 'India','In', null, null, null, true);
        Account acc2= OFI_TestDataFactory.createMultipleAccount('TestQuoteFailure', 'India','In', null, null, null, true);
        
		Contact con = new Contact(AccountId = acc.Id, LastName = 'ABC');
    	insert con;
      Id priceBookID = Test.getStandardPricebookId();
        
        Product2 p_test = new Product2(IsActive=true,Name='test Product',Description='Description for test Product');
        insert p_test;
        
        PricebookEntry pbe = new PricebookEntry(IsActive=true,Pricebook2Id=priceBookID,Product2Id=p_test.Id,UnitPrice=10.00);  
        insert pbe;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId =acc1.id;
        opp.CloseDate =system.today()+30;
        opp.StageName= 'Offering';
        opp.Business_Unit__c='All';   
        opp.Pricebook2Id=pricebookId;
        opp.RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId();
        insert opp; 
     OpportunityLineItem oppLineItem1 = new OpportunityLineItem(OpportunityId = opp.Id, 
                                                                   Product2Id = p_test.Id, 
                                                                   PricebookEntryId = pbe.Id,Ratio__c=100,
                                                                   Sampling_Status__c = '7');
        insert oppLineItem1;
        Quote qu= new Quote(OpportunityId=opp.Id,Name='testqAdmin',pricebook2Id =pricebookId,ExpirationDate=system.today()+30,Inco_Terms__c='DAP',Ship_To_Party__c=acc.id,Terms_Conditions__c='abc',PM_Type_1st__c = 'DOY',MOQ_Packaging_1st__c = 34);  
    insert qu;
    opp.SyncedQuoteId = qu.Id;
    update opp;
    QuoteLineItem qiItem = new  QuoteLineItem(QuoteId = qu.Id ,Product2Id=p_test.Id  ,PricebookEntryId=pbe.Id,Volume__c=1, Quantity =1 , UnitPrice=123,Unit_Of_Measure__c='KG' );
        insert  qiItem;
}
    @isTest
    public static void testQuotePDFCustomCntl()
    {
        Quote q = [SELECT Id, Name,Inco_Terms__c,ExpirationDate,Payment_Terms__c,Contract_Start_Date__c,Contract_End_Date__c,Olam_Quote_Number__c, Account.Name,Opportunity.RecordType.Name,(SELECT Id, Product2.Name,Approval_Status__c, UnitPrice, Volume__c FROM QuoteLineItems) FROM Quote ]; 
        system.assert(q!=null, 'Null values found');
        PageReference testPage = Page.PLBSQuotePDFCustom; 
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', String.valueOf(q.Id));
        ApexPages.StandardController sc=new ApexPages.StandardController(q);
        PLBSQuotePDFCustomCntl qcc= new PLBSQuotePDFCustomCntl(sc);
    }
}