src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Regions__c</fullName>
        <description>To Identify the account region</description>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                    <isActive>false</isActive>
                    <label>Africa</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                    <isActive>false</isActive>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>Europe</fullName>
                    <isActive>false</isActive>
                    <label>Europe</label>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                    <isActive>false</isActive>
                    <label>Latin America</label>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                    <isActive>false</isActive>
                    <label>Middle East</label>
                </value>
                <value>
                    <fullName>North America</fullName>
                    <isActive>false</isActive>
                    <label>North America</label>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                    <isActive>false</isActive>
                    <label>Oceania</label>
                </value>
                <value>
                    <fullName>South America</fullName>
                    <isActive>false</isActive>
                    <label>South America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa Powder</fullName>
                </value>
                <value>
                    <fullName>Cocoa Butter</fullName>
                </value>
                <value>
                    <fullName>Cocoa Mass</fullName>
                </value>
                <value>
                    <fullName>Cocoa Nibs</fullName>
                </value>
                <value>
                    <fullName>Cocoa Beans</fullName>
                </value>
                <value>
                    <fullName>Cocoa Liquor</fullName>
                </value>
                <value>
                    <fullName>Chocolate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>First_Sample_Due_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Sample Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PDI_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PDI Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PDNI_Approval_Status__c</fullName>
        <label>PDI Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PLM_Approval_Status__c</fullName>
        <label>PLM Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Total Products</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Text (Account.Regions__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>KG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PD_I_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PD&amp;I User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Product1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Regions</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_of_measure__c</fullName>
        <label>Unit of measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Sample_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sample Requests</relationshipLabel>
        <relationshipName>Sample_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sample Requests</relationshipLabel>
        <relationshipName>Sample_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PD_I__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PD&amp;I</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sample_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sample_Due_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sample Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sample_Requested_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sample Requested Date</label>
        <type>Date</type>
    </fields>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sample_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Product</label>
        <referenceTo>OpportunityLineItem</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sample_Due_Date__c</fullName>
        <formula>Sample_Request__r.Sample_Due_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sample Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sample_Request__c</fullName>
        <label>Sample Request</label>
        <referenceTo>Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_of_measure__c</fullName>
        <label>Unit of measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                    <label>Metric Ton</label>
                </value>
                <value>
                    <fullName>LB</fullName>
                    <label>US pound</label>
                </value>
                <value>
                    <fullName>KG</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Gram</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sample Request Line Item</label>
    <nameField>
        <displayFormat>SRLI-{00000}</displayFormat>
        <label>Sample Request Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>West Europe</fullName>
    </customValue>
    <customValue>
        <fullName>East Europe and Russia</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Central America</fullName>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and North Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Sub Sahara Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Central Asia</fullName>
    </customValue>
    <customValue>
        <fullName>East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia and New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>North East</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>West Coast</fullName>
    </customValue>
    <customValue>
        <fullName>South West</fullName>
    </customValue>
    <customValue>
        <fullName>South East</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
        <isActive>false</isActive>
        <label>APAC</label>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

src/globalValueSets/Regions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>EMENA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Unit_of_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MT</fullName>
        <default>true</default>
        <label>MT</label>
    </customValue>
    <customValue>
        <fullName>LB</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>QE</fullName>
        <isActive>false</isActive>
        <label>QE</label>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
        <isActive>false</isActive>
        <label>Carton</label>
    </customValue>
    <masterLabel>Unit of Measure</masterLabel>
</GlobalValueSet>

src/classes/SamplingRequestToOSSMController.cls
public class SamplingRequestToOSSMController {
    @AuraEnabled
    public static String createSampleRequest(String opportunityId){
        String message = 'SUCCESS';
        Boolean hasError = false;
        Boolean reprocessFailedRequest = false;
        
        Opportunity opp = new Opportunity();
        opp = getOpportunity(opportunityId);
        
        if(opp.OpportunityLineItems == null || opp.OpportunityLineItems.size() == 0){
            message = 'Please add a product for sampling!';
            hasError = true;
        }
        
        /*if(opp.OpportunityLineItems != null && opp.OpportunityLineItems.size() > 1){
            message = 'Please make sure only one product is added to the opportuntiy!';
            hasError = true;
        }*/
        
        if(opp.PDI_Member__c == null){
            message = 'Please make sure PDI Member is added!';
            hasError = true;
        }
        
        if(opp.PLM_Approval_Status__c != 'Approved' || opp.PDNI_Approval_Status__c != 'Approved'){
            message = 'Opportunity needs to be approved by both PLM and PDI Lead before submitting to OSSM!';
            hasError = true;
        }        
        
        List<Sample_Request__c> sampleRequestList = new List<Sample_Request__c>();
        sampleRequestList = getSampleRequests(opportunityId);
        
        if(sampleRequestList.size() > 0){
            if(sampleRequestList[0].Integration_Status__c == 'failed'){
                Sample_Request__c sampleRequestToUpdate = new Sample_Request__c(
                    Id = sampleRequestList[0].Id,
                    PD_I__c = opp.PDI_Member__c
                );
                update sampleRequestToUpdate;
                
                List<OpportunityLineItem> oppLineListToUpdate = new List<OpportunityLineItem>();
                for(OpportunityLineItem oppLine :opp.OpportunityLineItems){
                    oppLine.Opportunity_Owner__c = opp.OwnerId;
                    oppLine.PD_I_User__c = opp.PDI_Member__c;
                    oppLineListToUpdate.add(oppLine);
                }
                update oppLineListToUpdate;
                
                DELETE [SELECT Id FROM Sample_Request_Line_Item__c WHERE Sample_Request__c = :sampleRequestList[0].Id];
                
                List<Sample_Request_Line_Item__c> sampleLineListToInsert = new List<Sample_Request_Line_Item__c>();
                for(OpportunityLineItem oppLine :opp.OpportunityLineItems){
                    sampleLineListToInsert.add(createSampleRequestLine(sampleRequestList[0], oppLine));
                }
                insert sampleLineListToInsert;
                
                //publishPlatformEvent(sampleRequestList[0].Id);
                reprocessFailedRequest = true;
            }
            else{
                message = 'This opportunity has already been submitted for sampling!';
                hasError = true;
            }
        }
        
        if(hasError == false && reprocessFailedRequest == false){
            Sample_Request__c sampleRequest = createSampleRequest(opp);
            insert sampleRequest;
            
            List<OpportunityLineItem> oppLineListToUpdate = new List<OpportunityLineItem>();
            for(OpportunityLineItem oppLine :opp.OpportunityLineItems){
                oppLine.Opportunity_Owner__c = opp.OwnerId;
                oppLine.PD_I_User__c = opp.PDI_Member__c;
                oppLineListToUpdate.add(oppLine);
            }
            update oppLineListToUpdate;
            
            List<Sample_Request_Line_Item__c> sampleLineListToInsert = new List<Sample_Request_Line_Item__c>();
            for(OpportunityLineItem oppLine :opp.OpportunityLineItems){
                sampleLineListToInsert.add(createSampleRequestLine(sampleRequest, oppLine));
            }
            insert sampleLineListToInsert;
        }
        
        return message;
    }
    
    
    public static Sample_Request__c createSampleRequest(Opportunity opp){
        return new Sample_Request__c(
            Account__c = opp.AccountId,
            Opportunity__c = opp.Id,
            Sample_Due_Date__c = opp.First_Sample_Due_Date__c,
            Region__c = opp.Account.Regions__c,
            Country__c = opp.Account.BillingCountryCode,
            Sample_Requested_Date__c = Date.valueOf(opp.CreatedDate),
            PD_I__c = opp.PDI_Member__c
        );   
    }
    
    
    public static Sample_Request_Line_Item__c createSampleRequestLine(Sample_Request__c sampleRequest, OpportunityLineItem oppLine){
        return new Sample_Request_Line_Item__c(
                Sample_Request__c = sampleRequest.Id,
                Product__c = oppLine.Product2Id,
                Opportunity_Product__c = oppLine.Id,
                Sampling_Status__c = oppLine.Sampling_Status__c,
                Unit_of_measure__c = oppLine.UoM__c,
                Integration_Status__c = 'create',
                Tracking_Number__c = oppLine.Tracking_Number__c,
                Sample_with_Billing__c = oppLine.Sample_with_Billing__c,
                Sample_Feedback__c = oppLine.Sample_Feedback__c,
                Quantity__c = oppLine.Quantity_of_Sample_Grams__c,
                Development_Code__c = oppLine.Product2.Development_Code__c
            );
    }
    
    
    public static Opportunity getOpportunity(String opportunityId){
        return [SELECT Id, Name, AccountId, First_Sample_Due_Date__c, Account.Regions__c, Account.BillingCountryCode,
                CreatedDate, OwnerId,PLM_Approval_Status__c, PDNI_Approval_Status__c, PDI_Lead__c, PDI_Member__c,
               (
                   SELECT Id, Product2Id, Sampling_Status__c, UoM__c, Tracking_Number__c, Sample_with_Billing__c, 
                   Sample_Feedback__c, Quantity_of_Sample_Grams__c, Product2.Development_Code__c 
                   FROM OpportunityLineItems
               )
               FROM Opportunity
               WHERE Id = :opportunityId];
    }
    
    
    public static List<Sample_Request__c> getSampleRequests(String opportunityId){
        return [SELECT Id, Opportunity__c, Integration_Status__c,
                (SELECT Id FROM Sample_Request_Line_Items__r)
                FROM Sample_Request__c WHERE Opportunity__c = :opportunityId];
    }
    
    
    public static void publishPlatformEvent(String sampleRequestId){
        SampleRequest__e srEvent = new SampleRequest__e(SampleRequestId__c = sampleRequestId);
        
        Database.SaveResult result = EventBus.publish(srEvent);
        if (result.isSuccess()) {
            System.debug('Successfully published event.');
        } else {
            for(Database.Error err : result.getErrors()) {
                System.debug('Error returned: ' +
                             err.getStatusCode() +
                             ' - ' +
                             err.getMessage());
            }
        }       
    }
}