src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Key Account</fullName>
                </value>
                <value>
                    <fullName>Global Account</fullName>
                </value>
                <value>
                    <fullName>Regional Key Account</fullName>
                </value>
                <value>
                    <fullName>Regional Account</fullName>
                </value>
                <value>
                    <fullName>Local Key Account</fullName>
                </value>
                <value>
                    <fullName>Local Account</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <formula>User__r.BU_Identifier__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountSelector.cls
public inherited sharing class AccountSelector {
    
    public static List<Account> getAccountsByCustomerGroup (String customerGroup) {
       
        return [SELECT  Id, Name, Description, Customer_Group__c, Account_Type__c 
                                        FROM Account  
                                        WHERE Customer_Group__c LIKE :customerGroup
                                        LIMIT :(Limits.getLimitQueryRows() - Limits.getQueryRows()) ];
    } 
   
public static List<Account> getAccountsByCustomerGroupforoverview (String customerGroup,String BuisnessUnit) {
    List<Account> acc=new list<Account>();
    acc= [SELECT  Id, Name, Description, Customer_Group__c, Account_Type__c 
     FROM Account where id IN(select Account__c from Teams__c where Is_Primary__c=true AND  BU__c=:BuisnessUnit And Account__r.Customer_Group__c LIKE :customerGroup   ) LIMIT :(Limits.getLimitQueryRows() - Limits.getQueryRows())];
    return acc;

}
}