src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Pardot</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Matrix1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                    <label>Spices</label>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sub Category 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Approval Matrix</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Approval Matrix Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Account Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>DAIRY</fullName>
                </value>
                <value>
                    <fullName>DAIRY ALTERNATIVES</fullName>
                </value>
                <value>
                    <fullName>FROZEN DAIRY</fullName>
                </value>
                <value>
                    <fullName>FILLINGS (WB)</fullName>
                </value>
                <value>
                    <fullName>SYRUPS (WB)</fullName>
                </value>
                <value>
                    <fullName>BEVERAGES</fullName>
                </value>
                <value>
                    <fullName>CHOCOLATE (LIKE)</fullName>
                </value>
                <value>
                    <fullName>CONFECTIONERY MIXES</fullName>
                </value>
                <value>
                    <fullName>FILLINGS (FB)</fullName>
                </value>
                <value>
                    <fullName>SPREADS (FB)</fullName>
                </value>
                <value>
                    <fullName>SYRUPS (FB)</fullName>
                </value>
                <value>
                    <fullName>DECORATION</fullName>
                </value>
                <value>
                    <fullName>DAIRY MIXES</fullName>
                </value>
                <value>
                    <fullName>INSTANT MIXES</fullName>
                </value>
                <value>
                    <fullName>BAKERY MIXES</fullName>
                </value>
                <value>
                    <fullName>REPACKING</fullName>
                </value>
                <value>
                    <fullName>BAKERY</fullName>
                </value>
                <value>
                    <fullName>CEREALS</fullName>
                </value>
                <value>
                    <fullName>OTHER APPLICATIONS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Sub_Category_2__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Sub Category 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Sub_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Sub Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Bussiness_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                    <label>Spices</label>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Line_Approval__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quote_Line_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quote_Line_Approvals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sub Category 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Quote Line Approvals</relationshipLabel>
        <relationshipName>Quote_Line_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <formula>Quote_Line_Item__r.Volume__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Line Approval</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Approval Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <label>Approval Required ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <isActive>false</isActive>
                    <label>N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Application_Pardot.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Confectionery</fullName>
    </customValue>
    <customValue>
        <fullName>Drinks</fullName>
    </customValue>
    <customValue>
        <fullName>Ice Creams</fullName>
    </customValue>
    <customValue>
        <fullName>Desserts</fullName>
    </customValue>
    <customValue>
        <fullName>Savoury</fullName>
    </customValue>
    <customValue>
        <fullName>Bevarage</fullName>
    </customValue>
    <customValue>
        <fullName>Frozen Desserts</fullName>
    </customValue>
    <masterLabel>application</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <customValue>
        <fullName>Tropical</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acid</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI HH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI LH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI MH</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Blanched</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Oil Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Reject</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth Organic</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN STYLE CH</fullName>
    </customValue>
    <customValue>
        <fullName>AMF</fullName>
    </customValue>
    <customValue>
        <fullName>Analogue</fullName>
    </customValue>
    <customValue>
        <fullName>Black Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Bleached</fullName>
    </customValue>
    <customValue>
        <fullName>Blends</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Ingredient</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTERMLKCONCENTRATE</fullName>
    </customValue>
    <customValue>
        <fullName>Butter Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Cagliata</fullName>
    </customValue>
    <customValue>
        <fullName>Calcium Caseinate</fullName>
    </customValue>
    <customValue>
        <fullName>Pepper</fullName>
    </customValue>
    <masterLabel>Product Sub Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>#640 Colored</fullName>
    </customValue>
    <customValue>
        <fullName>#640 Whites</fullName>
    </customValue>
    <customValue>
        <fullName>100#</fullName>
    </customValue>
    <customValue>
        <fullName>200#</fullName>
    </customValue>
    <customValue>
        <fullName>40#</fullName>
    </customValue>
    <customValue>
        <fullName>40# Block</fullName>
    </customValue>
    <customValue>
        <fullName>40#Colby Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# colored</fullName>
    </customValue>
    <customValue>
        <fullName>40#Monterey Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# Pepper Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# White</fullName>
    </customValue>
    <customValue>
        <fullName>500# Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>500# White</fullName>
    </customValue>
    <customValue>
        <fullName>60-80#</fullName>
    </customValue>
    <customValue>
        <fullName>70%</fullName>
    </customValue>
    <customValue>
        <fullName>72.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>80%</fullName>
    </customValue>
    <customValue>
        <fullName>80% salted</fullName>
    </customValue>
    <customValue>
        <fullName>80% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>AA InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Extra No. 1</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Pieces</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Select Sheller Run</fullName>
    </customValue>
    <customValue>
        <fullName>Black Pepper</fullName>
    </customValue>
    <masterLabel>Product Sub Category 2</masterLabel>
</GlobalValueSet>

src/classes/QuoteLineApprovalTriggerTest.cls
@isTest
public class QuoteLineApprovalTriggerTest {
	
    @testSetup
    public static void setupData()
    {
       /* Account acc = new Account();
        acc.name='Test01';
        acc.BillingCountry = 'India';
        acc.BillingStreet ='Test';
        acc.Segment__c = 'Agent/ Distributor';
        insert acc;
        
        Product2 prod = [Select Name,Product_Category__c,Product_Sub_Category__c,Product_Sub_Category_2__c from Product2 
                         Where Product_Category__c = 'Tropical' and Product_Sub_Category__c = 'Pepper' Limit 1];
        
          // Product2 prod = new Product2();
          // prod.Name = 'Cocoa Beans';
          // prod.IsActive = true;
          // prod.Product_Category__c = 'Tropical';
           //prod.Product_Category__c = 'Pepper';
          // prod.Product_Category__c = 'Black Pepper';
            
        //insert prod;
        
        Product2 prod2 = new Product2(
            Name = 'Cocoa Butter',
            IsActive = true
        );
        insert prod2;
        
        Id pricebookId = Test.getStandardPricebookId();
        System.debug('PBI '+pricebookId);
        
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            CurrencyIsoCode = 'USD',
            UnitPrice = 0,
            IsActive = true
        );
        insert pbe;
        
        PricebookEntry pbe2 = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod2.Id,
            CurrencyIsoCode = 'USD',
            UnitPrice = 0,
            IsActive = true
        );
        insert pbe2;
        
        Opportunity opp = new Opportunity(
            AccountId = acc.Id,
            Name = 'Test Opp',
            StageName = 'Briefing',
            RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId(),
            CloseDate = System.today(),
            Business_Unit__c = 'Cocoa',
            Application__c = 'Agent/ Distributor',
            Pricebook2Id = pricebookId,
            CurrencyIsoCode = 'USD'
        );
        insert opp;
        
        Quote q=new Quote();
        q.OpportunityId=opp.Id;
        //q.AccountId=acc.Id;
        q.Name=opp.Name;
        q.Bussiness_Unit__c=opp.Business_Unit__c;
        q.ExpirationDate=opp.CloseDate;
        //q.Ship_To_Party__c=acc.Id;
        q.Status='Draft';
        insert q;
        
        QuoteLineItem qLI = new QuoteLineItem();
        qLI.Approval_Required__c = 'Yes';
        qLI.Approval_Status__c = 'Not Started';
        qLI.PricebookEntryId = pbe.Id;
        qLI.Product2Id = prod.Id;
        
        Product2 p = [Select Product_Category__c,Product_Sub_Category__c,Product_Sub_Category_2__c from product2 where Name = 'prod' and Id =: qLI.Product2Id];
        Quote_Line_Approval__c quoteLineApproval = new Quote_Line_Approval__c();
        quoteLineApproval.Quote_Line_Item__c = qLI.Id;
        quoteLineApproval.Approval_Status__c = qLI.Approval_Status__c;
        quoteLineApproval.Product_Category__c = p.Product_Category__c;
        quoteLineApproval.Product_Sub_Category__c = p.Product_Sub_Category__c;
        quoteLineApproval.Product_Sub_Category_2__c = p.Product_Sub_Category_2__c;
        insert quoteLineApproval;
        
        User u1 = new User();
        u1.FirstName = 'Test';
        u1.Email = 'abc@gamil.com';
        u1.IsActive = true;
        
        User u2 = new User();
        u2.FirstName = 'Test1';
        u2.Email = 'xyz@gmail.com';
        u2.IsActive = true;
        
        Approval_Matrix__C appMat = new Approval_Matrix__C();
        appMat.Approver_1__c = u1.Id;
        appMat.Approver_2__c = u2.Id;
        appMat.Product_Category__c = 'Tropical';
        appMat.Product_Category__c = 'Pepper';
        appMat.Product_Sub_Category_2__c = 'Black Pepper';
        */
            
        Account acc=new Account();
        acc.Name='Spices';
        acc.BillingCountry='India';
        acc.BillingStreet='xyz area';
        insert acc;
        Contact con =new Contact();
        con.AccountId=acc.Id;
        con.LastName='Ben';
        con.Email='abc@gmail.com';
        insert con;
         /*Product2 p=new Product2();
        p.Name='BP-14';
        p.IsActive=true;
		insert p;
        Pricebook2 pb2 = [SELECT Id FROM Pricebook2 WHERE IsStandard = true];
		 PricebookEntry pbe=new PricebookEntry();
        pbe.Product2Id=p.Id;
        pbe.Pricebook2Id=pb2.Id;
        pbe.UnitPrice=54;
        insert pbe;*/
        Product2 prod = new Product2(
            Name = 'Cocoa Beans',
            IsActive = true
        );
        insert prod;
        /*Product2 prod2 = new Product2(
            Name = 'Cocoa Butter',
            IsActive = true
        );
        insert prod2;*/
        Id pricebookId = Test.getStandardPricebookId();
        System.debug('PBI '+pricebookId);
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            CurrencyIsoCode = 'USD',
            UnitPrice = 0,
            IsActive = true
        );
        insert pbe;
        /*PricebookEntry pbe2 = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod2.Id,
            CurrencyIsoCode = 'USD',
            UnitPrice = 0,
            IsActive = true
        );
        insert pbe2;*/
        Opportunity opp = new Opportunity();
        opp.AccountId=acc.Id;
        opp.Name='Gain';
        //opp.ContactId=con.Id;
        opp.StageName='Offering';
        opp.CloseDate=System.today()+1;
        opp.Type='New Business';
        opp.Business_Unit__c='Spice';
        opp.Pricebook2Id=pricebookId;
        //opp.CurrencyIsoCode='USD - U.S. Dollar';
        insert opp;
        OpportunityLineItem oli=new OpportunityLineItem();
        oli.OpportunityId=opp.Id;
        oli.UnitPrice=44;
        oli.PricebookEntryId=pbe.Id;
        insert oli;
        Quote q=new Quote();
        q.OpportunityId=opp.Id;
        //q.ContactId=con.Id;
        //q.AccountId=acc.Id;
        q.Name=opp.Name;
        q.Bussiness_Unit__c=opp.Business_Unit__c;
        q.ExpirationDate=opp.CloseDate;
        //q.Ship_To_Party__c=acc.Id;
        q.Status='Draft';
        insert q;
        QuoteLineItem qli=new QuoteLineItem();
        qli.QuoteId=q.Id;
        //qli.Product2Id=p.Id;
        qli.PricebookEntryId=pbe.Id;
        qli.UnitPrice = 0;
        qli.Volume__c=3;
        qli.Quantity=5;
        qli.Approver_Comment__c = 'Test';
        qli.Product_Configuration__c='[{"varient_character_mapping":"ZVAR_MULTI_THRU","uom":"%","quantitative":"Yes","qualitative":"","olam_range":"0,000 - 50,000","mic":"-U100","description":"% THRU US #100","customer_range":"0,000 - 50,000"},{"varient_character_mapping":"ZVAR2_MULTI_THRU","uom":"%","quantitative":"No","qualitative":"","olam_range":"0,000 - 80,000","mic":"-U200","description":"% THRU UK #200","customer_range":"0,000 - 80,000"}]';
        insert qli;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        
        Quote_Line_Approval__c qla=new Quote_Line_Approval__c();
        qla.Account__c=acc.Id;
        qla.Quote_Line_Item__c=qli.Id;
        qla.Quote__c=q.Id;
        qla.Approval_Status__c = 'In Progress';
        qla.Approver_1__c=u.id;
        qla.Approver_2__c=u.id;
        qla.Approver_3__c=u.id;
        insert qla;
        qla.Approval_Status__c = 'Rejected';
        update qla;
    }
    
    @isTest
    public static void addApprover()
    {
        
        
        List<Quote_Line_Approval__c> quoteLineApproval = [Select Id,Quote_Line_Item__c,Product_Category__c,	Product_Sub_Category__c,Product_Sub_Category_2__c,
                                                         Approver_1__c,Approver_2__c,Approver_3__c,Quote_Line_Item__r.Approver_Comment__c from Quote_Line_Approval__c Limit 1];
        System.assert(quoteLineApproval!=null,'Null values');
        
        QuoteLineApprovalTriggerHandler.onAfterInsert(quoteLineApproval);
        
       /* Map<Id,Quote_Line_Approval__c> map1 = new Map<Id,Quote_Line_Approval__c>();
        map1.put(quoteLineApproval[0].Id,quoteLineApproval[0]);
       	QuoteLineApprovalTriggerHandler.onAfterUpdate(quoteLineApproval,map1); */
    }
    
   
}