src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Key Account</fullName>
                </value>
                <value>
                    <fullName>Global Account</fullName>
                </value>
                <value>
                    <fullName>Regional Key Account</fullName>
                </value>
                <value>
                    <fullName>Regional Account</fullName>
                </value>
                <value>
                    <fullName>Local Key Account</fullName>
                </value>
                <value>
                    <fullName>Local Account</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(Owner.UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;, 
IF( CONTAINS(Owner.UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;, &apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Plans__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <label>BU Identifier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <formula>Account__r.Customer_Group__c</formula>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plans Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Volume_MT__c</fullName>
        <inlineHelpText>Possible / Potential Volume Olam (MT) expects to get</inlineHelpText>
        <label>Estimated Volume</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Defend_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Defend</businessProcess>
        <description>Defend existing Olam business that may be at threat due to quality, product functionality, or price. Involves upgrading our product offering by Sampling a different SKU, Matching competitor offers, Developing new SKU</description>
        <label>Defend Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Develop_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Develop</businessProcess>
        <description>To Develop new business with the customer. This may involve either Sampling an existing Portfolio SKU, Matching an existing grade used by the customer, Developing a new product for the customer or Partnering with the customer to develop a new Product</description>
        <label>Develop Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Present</fullName>
        <active>true</active>
        <businessProcess>Service%2FPresent</businessProcess>
        <description>Opportunity to present new concepts or solutions to the customer that may lead to new business</description>
        <label>Presentation Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <businessProcess>Service%2FPresent</businessProcess>
        <description>Request from customer for documents, logistics issues, other ad hoc requests. Does not have any commercial impact</description>
        <label>Service</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Sub_Category_2__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Sub Category 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Sub_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Sub Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_of_Sample_Grams__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity of Sample</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sample_Sent_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sample Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM(Sample)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KG</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>MT</fullName>
                    <label>Metric Ton</label>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>LB</fullName>
                    <label>US pound</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acid</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI HH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI LH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI MH</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Blanched</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Oil Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Reject</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth Organic</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN STYLE CH</fullName>
    </customValue>
    <customValue>
        <fullName>AMF</fullName>
    </customValue>
    <customValue>
        <fullName>Analogue</fullName>
    </customValue>
    <customValue>
        <fullName>Black Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Bleached</fullName>
    </customValue>
    <customValue>
        <fullName>Blends</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Ingredient</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTERMLKCONCENTRATE</fullName>
    </customValue>
    <customValue>
        <fullName>Butter Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Cagliata</fullName>
    </customValue>
    <customValue>
        <fullName>Calcium Caseinate</fullName>
    </customValue>
    <masterLabel>Product Sub Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>#640 Colored</fullName>
    </customValue>
    <customValue>
        <fullName>#640 Whites</fullName>
    </customValue>
    <customValue>
        <fullName>100#</fullName>
    </customValue>
    <customValue>
        <fullName>200#</fullName>
    </customValue>
    <customValue>
        <fullName>40#</fullName>
    </customValue>
    <customValue>
        <fullName>40# Block</fullName>
    </customValue>
    <customValue>
        <fullName>40#Colby Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# colored</fullName>
    </customValue>
    <customValue>
        <fullName>40#Monterey Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# Pepper Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# White</fullName>
    </customValue>
    <customValue>
        <fullName>500# Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>500# White</fullName>
    </customValue>
    <customValue>
        <fullName>60-80#</fullName>
    </customValue>
    <customValue>
        <fullName>70%</fullName>
    </customValue>
    <customValue>
        <fullName>72.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>80%</fullName>
    </customValue>
    <customValue>
        <fullName>80% salted</fullName>
    </customValue>
    <customValue>
        <fullName>80% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>AA InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Extra No. 1</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Pieces</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Select Sheller Run</fullName>
    </customValue>
    <masterLabel>Product Sub Category 2</masterLabel>
</GlobalValueSet>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/classes/KAM_ActionPlanCntlTest.cls
@isTest
public class KAM_ActionPlanCntlTest {

    @testSetup
    public static void createData()
    {
        List<Account> accList = new List<Account>();
        Account acc=new Account();
        acc.Name='DemoAccount';
        acc.Account_Type__c='Distributor';
        acc.BillingCountry='India';
        acc.BillingStreet='Pune-Mumbai road';
        accList.add(acc);
        
        Account acc1 = new Account();
        acc1.Name = 'Test1';
        acc1.BillingCity = 'Testcity';
        acc1.BillingCountry = 'india';
        acc1.Customer_Group__c='Test Group';
        accList.add(acc1);
        
        insert accList;
        
         Account_Plans__c app1 = new Account_Plans__c();
        app1.Name = 'test1';
        app1.Account__c = acc1.id;
         app1.Type__c='group';
        app1.BU_Identifier__c='Cocoa';
        app1.StartDate__c=system.today();
        app1.EndDate__c=system.today().addDays(365);
        insert app1;
        
         Id RecordTypeIdDefendOpportunity4 = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Service').getRecordTypeId();
        
        
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity Opp3=new Opportunity();
        Opp3.AccountId=acc1.Id;
        Opp3.Name='NewOpportunityService';
        Opp3.CloseDate=system.today();
        Opp3.Business_Unit__c='Cocoa';
        Opp3.StageName='Closing Won';
        Opp3.RecordTypeId=RecordTypeIdDefendOpportunity4;
        Opp3.Estimated_Volume_MT__c=200;
        oppList.add(Opp3);
        
         Id RecordTypeIdDefendOpportunity5 = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Present').getRecordTypeId();
        Opportunity Opp4=new Opportunity();
        Opp4.AccountId=acc1.Id;
        Opp4.Name='NewOpportunityPresent';
        Opp4.CloseDate=system.today();
        Opp4.Business_Unit__c='Cocoa';
        Opp4.StageName=' Offering';
        Opp4.RecordTypeId=RecordTypeIdDefendOpportunity5;
        Opp4.Estimated_Volume_MT__c=200;
        oppList.add(Opp4);
        
        Id RecordTypeIdDefendOpportunity6 = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Defend_Opportunity').getRecordTypeId();
        Opportunity Opp5=new Opportunity();
        Opp5.AccountId=acc1.Id;
        Opp5.Name='NewOpportunityDefend';
        Opp5.CloseDate=system.today();
        Opp5.Business_Unit__c='Cocoa';
        Opp5.StageName=' Offering';
        Opp5.RecordTypeId=RecordTypeIdDefendOpportunity6;
        Opp5.Estimated_Volume_MT__c=200;
        oppList.add(Opp5);
        
        Id RecordTypeIdDefendOpportunity7 =Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Develop_Opportunity').getRecordTypeId();
        Opportunity Opp6=new Opportunity();
        Opp6.AccountId=acc1.Id;
        Opp6.Name='NewOpportunityDefend';
        Opp6.CloseDate=system.today();
        Opp6.Business_Unit__c='Cocoa';
        Opp6.StageName=' Offering';
        Opp6.RecordTypeId=RecordTypeIdDefendOpportunity7;
        Opp6.Estimated_Volume_MT__c=200;
        oppList.add(Opp6);
        
        insert oppList;
        
         Account_Plans__c ap = new Account_Plans__c();
        ap.Name = 'test';
        ap.Account__c = acc.id;
         ap.BU_Identifier__c='Cocoa';
        ap.StartDate__c=system.today();
        ap.EndDate__c=system.today().addDays(20);
        insert ap;
        
        List<Opportunity> oppList2 = new List<Opportunity>();
        
        Id RecordTypeIdDefendOpportunity = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Service').getRecordTypeId();
        Opportunity Opp=new Opportunity();
        Opp.AccountId=acc.Id;
        Opp.Name='NewOpportunityService';
        Opp.CloseDate=system.today();
        Opp.Business_Unit__c='Cocoa';
        Opp.StageName='Closing Won';
        Opp.RecordTypeId=RecordTypeIdDefendOpportunity;
        opp.Estimated_Volume_MT__c=200;
        oppList2.add(Opp);
        
        Id RecordTypeIdDefendOpportunity1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Defend_Opportunity').getRecordTypeId();
        Opportunity Opp1=new Opportunity();
        Opp1.AccountId=acc.Id;
        Opp1.Name='NewOpportunityDefend';
        Opp1.CloseDate=system.today();
        Opp1.Business_Unit__c='Cocoa';
        Opp1.StageName=' Offering';
        Opp1.RecordTypeId=RecordTypeIdDefendOpportunity1;
        opp1.Estimated_Volume_MT__c=200;
        oppList2.add(Opp1);
        
        Id RecordTypeIdDefendOpportunity2 = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Present').getRecordTypeId();
        Opportunity Opp2=new Opportunity();
        Opp2.AccountId=acc.Id;
        Opp2.Name='NewOpportunityPresent';
        Opp2.CloseDate=system.today();
        Opp2.Business_Unit__c='Cocoa';
        Opp2.StageName=' Offering';
        Opp2.RecordTypeId=RecordTypeIdDefendOpportunity2;
        Opp2.Estimated_Volume_MT__c=200;
        oppList2.add(Opp2);
        
        insert oppList2;
        
         Product2 p_test= new Product2(Name='Product1');
        /*p_test.Name='TEST_PRODUCT';
        p_test.Product_Sub_Category__c='';
        p_test.Product_Category__c=' Cocoa Cake';
        p_test.Product_Sub_Category_2__c='';*/
        insert p_test;
        Id pricebookId = Test.getStandardPricebookId();
        System.debug('PBI '+pricebookId);
        
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = p_test.Id,
            CurrencyIsoCode = 'USD',
            UnitPrice = 0,
            IsActive = true
        );
        insert pbe;
        
        List<OpportunityLineItem> oppLineList = new List<OpportunityLineItem>();
        
        OpportunityLineItem oppLine=new OpportunityLineItem();
        oppLine.Product2Id=p_test.Id;
        oppLine.OpportunityId=opp.Id;
        oppLine.Sample_Sent_Date__c=System.today();
        oppLine.Sampling_Status__c='7';
        oppLine.UoM__c ='G';
        oppLine.Quantity_of_Sample_Grams__c = 100;
        oppLine.PricebookEntryId=pbe.id;
        oppLineList.add(oppLine);
        
        
        OpportunityLineItem oppLine1=new OpportunityLineItem();
        oppLine1.Product2Id=p_test.Id;
        oppLine1.OpportunityId=opp1.Id;
        oppLine1.Sample_Sent_Date__c=System.today();
        oppLine1.Sampling_Status__c='7';
        oppLine1.UoM__c ='G';
        oppLine1.Quantity_of_Sample_Grams__c = 100;
        oppLine1.PricebookEntryId=pbe.id;
        oppLineList.add(oppLine1);
        
         OpportunityLineItem oppLine2=new OpportunityLineItem();
        oppLine2.Product2Id=p_test.Id;
        oppLine2.OpportunityId=opp2.Id;
        oppLine2.Sample_Sent_Date__c=System.today();
        oppLine2.Sampling_Status__c='7';
        oppLine2.UoM__c ='G';
        oppLine2.Quantity_of_Sample_Grams__c = 100;
        oppLine2.PricebookEntryId=pbe.id;
        oppLineList.add(oppLine2);
        
        insert oppLineList;
        
        ContentDocument cd=new ContentDocument();
        
        
            
  }
    
     public static testmethod void test_getDetails()
    {
        Test.startTest();
        Account_Plans__c ap=[Select id,name,Account__c,BU_Identifier__c from Account_Plans__c where BU_Identifier__c='cocoa' Limit 1];
        System.assert(ap!=null, 'Its having null values');
        KAM_ActionPlanCntl apc=new KAM_ActionPlanCntl();
       String res= apc.getDetails(JSON.serialize(new Map<String, Object> {'accountPlan'=> ap}));
        system.assert(res!=null, 'not found response');
       String res1= apc.getDetails(JSON.serialize(ap));
        
        Test.stopTest();
        
    }
   
     public static testmethod void test_getClosedServiceAndPresentationOpportunities()
    {
        Test.startTest();
        Account_Plans__c ap=[Select id,name,StartDate__c,EndDate__c,BU_Identifier__c,Account__c from Account_Plans__c  where name='test'];
        System.assert(ap!=null, 'Its having null values');
       system.debug(ap);
       List<Opportunity> res= KAM_ActionPlanCntl.getPresentationOpportunities(ap);
        system.assert(res!=null && !res.isEmpty(), 'Opportunity not found');
        
        
         List<Opportunity> res1= KAM_ActionPlanCntl.getServiceOpportunities(ap);
        system.assert(res1!=null && !res1.isEmpty(), 'Opportunity not found');
        
        Account_Plans__c ap1=[Select id,name,StartDate__c,EndDate__c,BU_Identifier__c,Account__c from Account_Plans__c  where name='test1'];
        res = KAM_ActionPlanCntl.getGroupServiceOpportunities (ap1, JSON.serialize(new Set<Id> {ap1.Account__c}));
        res1 = KAM_ActionPlanCntl.getGroupPresentationOpportunities (ap1, JSON.serialize(new Set<Id> {ap1.Account__c}));
        try{
              Account_Plans__c ap2=[Select id,StartDate__c,EndDate__c,BU_Identifier__c from Account_Plans__c  Limit 1];
      
             KAM_ActionPlanCntl.getServiceOpportunities(ap2);
             KAM_ActionPlanCntl.getPresentationOpportunities(ap2);
            
        }catch(exception e)
        {
            system.debug(e);
        }
        Test.stopTest();
        
    }
    public static testmethod void test_getOpenDefendDevelopOpportunities()
    {
        Test.startTest();
        Account_Plans__c ap=[Select id,StartDate__c,EndDate__c,BU_Identifier__c,Account__c from Account_Plans__c where name='test'  Limit 1];
        System.assert(ap!=null, 'Its having null values');
        List<opportunity> res=KAM_ActionPlanCntl.getOpenDefendDevelopOpportunities(ap);
        system.assert(res!=null && !res.isEmpty(), 'Opportunity not found');
         try{
              Account_Plans__c ap1=[Select id,StartDate__c,EndDate__c,BU_Identifier__c from Account_Plans__c  Limit 1];
      
             List<Opportunity> res1= KAM_ActionPlanCntl.getOpenDefendDevelopOpportunities(ap1);
        }catch(exception e)
        {
            system.debug(e);
        }
        Test.stopTest();
       
    }
      public static testmethod void getDefendDevelopGainOpportunitiesTest()
    {
        Test.startTest();
        Account_Plans__c ap=[Select id,StartDate__c,EndDate__c,BU_Identifier__c,Account__c from Account_Plans__c where name='test1' Limit 1];
        System.assert(ap!=null, 'Its having null values');
        
        List<opportunity> res=KAM_ActionPlanCntl.getDefendDevelopGainOpportunities(ap);
        
        res=KAM_ActionPlanCntl.getGroupOpenDefendDevelopOpportunities(ap, JSON.serialize(new Set<Id> {ap.Account__c}));
        system.assert(res!=null && !res.isEmpty(), 'Opportunity not found');
        
         try{
              Account_Plans__c ap1=[Select id,StartDate__c,EndDate__c,BU_Identifier__c from Account_Plans__c  Limit 1];
      
             List<Opportunity> res1= KAM_ActionPlanCntl.getDefendDevelopGainOpportunities(ap1);
        }catch(exception e)
        {
            system.debug(e);
        }
        
       Test.stopTest();
    }
    public static testmethod void getCommentsTest()
    {
        Test.startTest();
        Account_Plans__c ap=[Select id,StartDate__c,EndDate__c,BU_Identifier__c,Account__c from Account_Plans__c  Limit 1];
        System.assert(ap!=null, 'Its having null values');
        String res=KAM_ActionPlanCntl.getComments(ap);
        Test.stopTest();
        
    }
    
   
   
     public static testmethod void test_saveComments()
    {
        Test.startTest();
        Account_Plans__c ap=[Select id,StartDate__c,EndDate__c,BU_Identifier__c,Account__c from Account_Plans__c  Limit 1];
        System.assert(ap!=null, 'Its having null values');
        String Result=KAM_ActionPlanCntl.saveComments(ap, null, 'Testing Purpose');
         System.assert(Result!=null, 'no result found');
         Map<String,object > Result1 = (Map<String,object >) JSON.deserializeUntyped(Result);
        String Result2=KAM_ActionPlanCntl.saveComments(ap, String.ValueOf(Result1.get('contentDocumentId')),'Testing1');
        
        Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(Result2);
        System.assert(!resultMap.isEmpty (), 'unable to save comments');
        
        String res=KAM_ActionPlanCntl.getComments(ap); 
         Map<String, Object> resultMap1 = (Map<String, Object>) JSON.deserializeUntyped(res);
        System.assert(!resultMap1.isEmpty (), 'unable to save comments');
        
         try{
         Account_Plans__c ap1=[Select StartDate__c,EndDate__c,BU_Identifier__c from Account_Plans__c  Limit 1];
         KAM_ActionPlanCntl.saveComments(ap1, null, 'Testing Purpose');
        }catch(exception e)
        {
            system.debug(e);
        }
        Test.stopTest();
    }
}