src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Key Account</fullName>
                </value>
                <value>
                    <fullName>Global Account</fullName>
                </value>
                <value>
                    <fullName>Regional Key Account</fullName>
                </value>
                <value>
                    <fullName>Regional Account</fullName>
                </value>
                <value>
                    <fullName>Local Key Account</fullName>
                </value>
                <value>
                    <fullName>Local Account</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Plan_Overview_Component__mdt.object
<CustomObject>
    <fields>
        <fullName>ApexClass__c</fullName>
        <label>ApexClass</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Name__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                    <label>Individual</label>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Plan Overview Component</label>
    <pluralLabel>Account Plan Overview Components</pluralLabel>
</CustomObject>

src/classes/KAM_CustomerOverViewCntlTest.cls
@isTest
public class KAM_CustomerOverViewCntlTest {
    
    @testSetup
    static void createMetaData () {
        Account acc=new Account();
        acc.Name='DemoAccount';
        acc.Account_Type__c='Distributor';
        acc.BillingCountry='India';
        acc.BillingStreet='Pune-Mumbai road';
        insert acc;
    }
    
    @isTest 
    static void getDetails () {
        List<Account_Plan_Overview_Component__mdt> accountPlanMetaData 
            = (List<Account_Plan_Overview_Component__mdt>) KAM_CustomMetaDataDAO.getCustomMetadataRecords (
                'SELECT Id, DeveloperName, Title__c, Order__c, ApexClass__c, Component_Name__c, Is_Active__c, Type__c FROM Account_Plan_Overview_Component__mdt WHERE DeveloperName = \'CustomerOverview\'');
        System.assert(accountPlanMetaData.size () > 0, 'Unable to find CustomerOverview component details ' );
        String res = KAM_AccountPlanOverviewCntl.getDetails(JSON.serialize(accountPlanMetaData[0]), null);
        
        Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(res);
        System.assert(resultMap.containsKey ('fields'), 'Unable to find field set wrapper');
        
        List<FieldWrapper> fieldWrapper = (List<FieldWrapper>)JSON.deserialize(JSON.serialize(resultMap.get ('fields')), List<FieldWrapper>.class );
        System.assert(!fieldWrapper.isEmpty (), 'Field api names list is empty');
    }
    @isTest 
    static void getDetailsException () {
        List<Account_Plan_Overview_Component__mdt> accountPlanMetaData 
            = (List<Account_Plan_Overview_Component__mdt>) KAM_CustomMetaDataDAO.getCustomMetadataRecords (
                'SELECT Id, DeveloperName, Title__c, Order__c, ApexClass__c, Component_Name__c, Is_Active__c, Type__c FROM Account_Plan_Overview_Component__mdt WHERE DeveloperName = \'CustomerOverview\'');
        System.assert(accountPlanMetaData.size () > 0, 'Unable to find CustomerOverview component details ' );
        accountPlanMetaData[0].ApexClass__c = null;
        Boolean exceptionThrown = false;
        try {
         	String res = KAM_AccountPlanOverviewCntl.getDetails(JSON.serialize(accountPlanMetaData[0]), null);   
        } catch (Exception e) {
            exceptionThrown =  true;
        } finally {
         	System.assert(exceptionThrown, 'Expected an exception to be thrown, but there was no exception ');
        }
    }
}