src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Pardot</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(Owner.UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;, 
IF( CONTAINS(Owner.UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;, &apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Plans__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <label>BU Identifier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <formula>Account__r.Customer_Group__c</formula>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plans Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consumption</relationshipLabel>
        <relationshipName>Consumption</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <label>Brands</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Brand</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>Coffee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>DATE(VALUE(TEXT(Year__c)) ,12,31)</formula>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Share__c</fullName>
        <label>Share</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <formula>DATE(VALUE(TEXT(Year__c)) ,1,1)</formula>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Strength__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Strength</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume_MT__c</fullName>
        <label>Annual Consumption Volume</label>
        <precision>11</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Consumption</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>RecordId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumption</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Application_Pardot.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Confectionery</fullName>
    </customValue>
    <customValue>
        <fullName>Drinks</fullName>
    </customValue>
    <customValue>
        <fullName>Ice Creams</fullName>
    </customValue>
    <customValue>
        <fullName>Desserts</fullName>
    </customValue>
    <customValue>
        <fullName>Savoury</fullName>
    </customValue>
    <customValue>
        <fullName>Bevarage</fullName>
    </customValue>
    <customValue>
        <fullName>Frozen Desserts</fullName>
    </customValue>
    <masterLabel>application</masterLabel>
</GlobalValueSet>

src/globalValueSets/Brand.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>5 STAR</fullName>
    </customValue>
    <customValue>
        <fullName>ADECOAGRO</fullName>
    </customValue>
    <customValue>
        <fullName>AGRI-MARK</fullName>
    </customValue>
    <customValue>
        <fullName>AGROPUR</fullName>
    </customValue>
    <customValue>
        <fullName>ALBAN</fullName>
    </customValue>
    <customValue>
        <fullName>ALIMA</fullName>
    </customValue>
    <customValue>
        <fullName>ALIMENTA</fullName>
    </customValue>
    <customValue>
        <fullName>ALISA</fullName>
    </customValue>
    <customValue>
        <fullName>Ammerland</fullName>
    </customValue>
    <customValue>
        <fullName>AMUL</fullName>
    </customValue>
    <customValue>
        <fullName>ANDRUSHOVCA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENLAC</fullName>
    </customValue>
    <customValue>
        <fullName>ARLA</fullName>
    </customValue>
    <customValue>
        <fullName>ARLA DANO</fullName>
    </customValue>
    <customValue>
        <fullName>ARRABAWN</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATED MILK PRODUCERS</fullName>
    </customValue>
    <customValue>
        <fullName>AURIVO</fullName>
    </customValue>
    <customValue>
        <fullName>BABUSHKINA KRINKA</fullName>
    </customValue>
    <customValue>
        <fullName>BALCHEM</fullName>
    </customValue>
    <customValue>
        <fullName>Barry Callebaut</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIOIOSO</fullName>
    </customValue>
    <customValue>
        <fullName>BELGOMILK</fullName>
    </customValue>
    <customValue>
        <fullName>BELLADEL</fullName>
    </customValue>
    <customValue>
        <fullName>BELLAKT</fullName>
    </customValue>
    <customValue>
        <fullName>BIERUN</fullName>
    </customValue>
    <customValue>
        <fullName>BIERY</fullName>
    </customValue>
    <customValue>
        <fullName>BILOSERKIVKA</fullName>
    </customValue>
    <customValue>
        <fullName>BINCO</fullName>
    </customValue>
    <customValue>
        <fullName>BLOMMER</fullName>
    </customValue>
    <customValue>
        <fullName>BMI</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acid</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI HH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI LH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI MH</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Blanched</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Oil Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Reject</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth Organic</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN STYLE CH</fullName>
    </customValue>
    <customValue>
        <fullName>AMF</fullName>
    </customValue>
    <customValue>
        <fullName>Analogue</fullName>
    </customValue>
    <customValue>
        <fullName>Black Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Bleached</fullName>
    </customValue>
    <customValue>
        <fullName>Blends</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Ingredient</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTERMLKCONCENTRATE</fullName>
    </customValue>
    <customValue>
        <fullName>Butter Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Cagliata</fullName>
    </customValue>
    <customValue>
        <fullName>Calcium Caseinate</fullName>
    </customValue>
    <masterLabel>Product Sub Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>#640 Colored</fullName>
    </customValue>
    <customValue>
        <fullName>#640 Whites</fullName>
    </customValue>
    <customValue>
        <fullName>100#</fullName>
    </customValue>
    <customValue>
        <fullName>200#</fullName>
    </customValue>
    <customValue>
        <fullName>40#</fullName>
    </customValue>
    <customValue>
        <fullName>40# Block</fullName>
    </customValue>
    <customValue>
        <fullName>40#Colby Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# colored</fullName>
    </customValue>
    <customValue>
        <fullName>40#Monterey Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# Pepper Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# White</fullName>
    </customValue>
    <customValue>
        <fullName>500# Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>500# White</fullName>
    </customValue>
    <customValue>
        <fullName>60-80#</fullName>
    </customValue>
    <customValue>
        <fullName>70%</fullName>
    </customValue>
    <customValue>
        <fullName>72.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>80%</fullName>
    </customValue>
    <customValue>
        <fullName>80% salted</fullName>
    </customValue>
    <customValue>
        <fullName>80% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>AA InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Extra No. 1</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Pieces</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Select Sheller Run</fullName>
    </customValue>
    <masterLabel>Product Sub Category 2</masterLabel>
</GlobalValueSet>

src/classes/KAM_ConsumptionCntl.cls
public with sharing class KAM_ConsumptionCntl implements KAM_AccountPlan{
    public static String getDetails (String data) {
        Map<String, Object> requestMap = (Map<String, Object>) JSON.deserializeUntyped(data);
        if (requestMap.containsKey ('accountId')&&requestMap.containsKey ('accountPlan')) {
            return JSON.serialize(getConsumptions (String.valueOf(requestMap.get('accountId')),(Account_Plans__c) JSON.deserialize(JSON.serialize(requestMap.get ('accountPlan')), Account_Plans__c.class)));
        } 
        return null;
    }
    @AuraEnabled
     public static String getGroupDetails (String data) {
        Map<String, Object> requestMap = (Map<String, Object>) JSON.deserializeUntyped(data);
        if (requestMap.containsKey ('accountPlan')) {
           return JSON.serialize(getGroupConsumptions ((Account_Plans__c) JSON.deserialize(JSON.serialize(requestMap.get ('accountPlan')), Account_Plans__c.class)));
        }
        return null;
    }
    @AuraEnabled
    public static List<Consumption__c> getConsumptions(String accountId,Account_Plans__c accountPlan){
       
		try {        
        List<Consumption__c>listOfConsumption = [Select  Category__c, Sub_Category_2__c, Sub_Category__c,Application__c, Brands__c, Business_Unit__c,
                                                 Volume_MT__c, Share__c, Strength__c 
                                                 From Consumption__c 
                                                 where Account__c=:accountId 
                                                 AND Business_Unit__c=:accountPlan.BU_Identifier__c 
                                                 AND Start_Date__c =: accountPlan.StartDate__c 
                                                 AND End_Date__c =: accountPlan.EndDate__c];
        
        System.debug(listOfConsumption);
        return listOfConsumption;
        }catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static List<Consumption__c> getGroupConsumptions(Account_Plans__c accountPlan){
        try {
            if (accountPlan == null || String.isBlank(accountPlan.Customer_Group__c)) {
                NullPointerException e = new NullPointerException ();
                e.setMessage(Label.KAM_Invalid_Account_Plan_Detail_Error_Message);
                throw e;
            }
            List<Consumption__c>listOfConsumption = [Select  Category__c, Sub_Category_2__c, Sub_Category__c,Application__c, Brands__c, Business_Unit__c,
                                                    Volume_MT__c, Share__c, Strength__c,Account__r.Name,Account__c
                                                    From Consumption__c 
                                                    where  Account__r.Customer_Group__c=:accountPlan.Customer_Group__c AND Business_Unit__c=:accountPlan.BU_Identifier__c AND Start_Date__c>=:accountPlan.StartDate__c AND End_Date__c>=:accountPlan.EndDate__c];
            return listOfConsumption;
        }catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        } 
    }
}