src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Regions__c</fullName>
        <description>To Identify the account region</description>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                    <isActive>false</isActive>
                    <label>Africa</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                    <isActive>false</isActive>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>Europe</fullName>
                    <isActive>false</isActive>
                    <label>Europe</label>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                    <isActive>false</isActive>
                    <label>Latin America</label>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                    <isActive>false</isActive>
                    <label>Middle East</label>
                </value>
                <value>
                    <fullName>North America</fullName>
                    <isActive>false</isActive>
                    <label>North America</label>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                    <isActive>false</isActive>
                    <label>Oceania</label>
                </value>
                <value>
                    <fullName>South America</fullName>
                    <isActive>false</isActive>
                    <label>South America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ofi_Sub_Region_2__c</fullName>
        <label>ofi Sub Region 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia and New Zealand</fullName>
                </value>
                <value>
                    <fullName>Caribbean</fullName>
                </value>
                <value>
                    <fullName>Central America</fullName>
                </value>
                <value>
                    <fullName>Central Asia</fullName>
                </value>
                <value>
                    <fullName>Channel Islands</fullName>
                </value>
                <value>
                    <fullName>East Africa</fullName>
                </value>
                <value>
                    <fullName>East Asia</fullName>
                </value>
                <value>
                    <fullName>East Europe</fullName>
                </value>
                <value>
                    <fullName>Melanesia</fullName>
                </value>
                <value>
                    <fullName>Micronesia</fullName>
                </value>
                <value>
                    <fullName>Middle Africa</fullName>
                </value>
                <value>
                    <fullName>North Africa</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>North Europe</fullName>
                </value>
                <value>
                    <fullName>Polynesia</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                </value>
                <value>
                    <fullName>South America</fullName>
                </value>
                <value>
                    <fullName>South Asia</fullName>
                </value>
                <value>
                    <fullName>South-East Asia</fullName>
                </value>
                <value>
                    <fullName>South Europe</fullName>
                </value>
                <value>
                    <fullName>West Africa</fullName>
                </value>
                <value>
                    <fullName>West Asia</fullName>
                </value>
                <value>
                    <fullName>West Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ofi_Sub_Region__c</fullName>
        <label>ofi Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Asia</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AccountRegionUpdate_test.cls
@isTest
public class AccountRegionUpdate_test {

    
    public static void createTestUser() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
            UserRole cocoaRole = new UserRole(DeveloperName = 'Cocoa_Something_Role', Name = 'Cocoa Something');
            insert cocoaRole;
            
            Id cocoaProfileId = [SELECT Id FROM Profile WHERE Name = 'Cocoa Sales'].Id;
            User user = new User(
                ProfileId = cocoaProfileId,
                LastName = 'UnitTestCocoaUser1',
                Email = 'UnitTestCocoaUser1' + '@unittestuser.com',
                Username = 'UnitTestCocoaUser1' + '@unittestuser.com' + System.currentTimeMillis(),
                CompanyName = 'TEST',
                Title = 'title',
                Alias = 'alias',
                TimeZoneSidKey = 'America/Los_Angeles',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                UserRoleId = cocoaRole.Id
            );    
            insert user;
        }
    }
    
    @isTest
    public static void testRegionUpdate() {
        Test.startTest();
        
        createTestUser();
        Account acc1, acc2, acc3;
        User user1 = [SELECT Id FROM User WHERE LastName = 'UnitTestCocoaUser1'];
        //System.runAs (user1) {
            acc1 = new Account(Name = 'UNIT TEST account1', BillingStreet = 'Test 1 street', BillingCountry = 'Australia',BillingCountryCode = 'AU');
            acc2 = new Account(Name = 'UNIT TEST account2', BillingStreet = 'Test 1 street', BillingCountry = 'Singapore',BillingCountryCode = 'SG');
            acc3 = new Account(Name = 'UNIT TEST account5', BillingStreet = 'Test 1 street', BillingCountry = 'India',BillingCountryCode = 'IN');
            List<Account> accounts = new List<Account>{acc1, acc2, acc3};
            insert accounts;
        //}
        Map<id,account> actualResults= new map<id,account> ([select regions__c,ofi_sub_region__c,ofi_sub_region_2__c from account]);
        Test.stopTest();
        System.assertEquals('APAC', actualResults.get(acc1.Id).regions__c, 'Expecpted OFI Region');        
        System.assertEquals('Asia', actualResults.get(acc2.Id).ofi_sub_region__c, 'Expecpted OFI Sub Region');

    }
}