src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Key Account</fullName>
                </value>
                <value>
                    <fullName>Global Account</fullName>
                </value>
                <value>
                    <fullName>Regional Key Account</fullName>
                </value>
                <value>
                    <fullName>Regional Account</fullName>
                </value>
                <value>
                    <fullName>Local Key Account</fullName>
                </value>
                <value>
                    <fullName>Local Account</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Budget_vs_Actual_Line__c.object
<CustomObject>
    <fields>
        <fullName>Budget_vs_Actuals__c</fullName>
        <label>Budget vs Actuals</label>
        <referenceTo>Budget_vs_Actuals__c</referenceTo>
        <relationshipLabel>Budget vs Actual Lines</relationshipLabel>
        <relationshipName>Budget_vs_Actual_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <label>Budget vs Actual Line</label>
    <nameField>
        <displayFormat>BVSAL-{0000000}</displayFormat>
        <label>Budget vs Actual Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget vs Actual Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget_vs_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budget vs Actuals</relationshipLabel>
        <relationshipName>Budget_vs_Actuals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Budget vs Actuals</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Budget vs Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget vs Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KAM_Queuable_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KAM Queuable Error Log</label>
    <nameField>
        <displayFormat>KAMQEL-{0000000}</displayFormat>
        <label>KAM Queuable Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KAM Queuable Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Developing_Hours__c</fullName>
        <label>Actual Developing Hours</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WET</fullName>
                </value>
                <value>
                    <fullName>FAT</fullName>
                </value>
                <value>
                    <fullName>DRY</fullName>
                </value>
                <value>
                    <fullName>MISCELLANEOUS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <formula>TEXT( PLBS_Product__r.Sub_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Category</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Sub_Category_2__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Sub Category 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Sub_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Sub Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_of_Sample_Grams__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity of Sample</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM(Sample)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KG</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>MT</fullName>
                    <label>Metric Ton</label>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>LB</fullName>
                    <label>US pound</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Development_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <label>Development Code</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acid</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI HH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI LH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI MH</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Blanched</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Oil Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Reject</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth Organic</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN STYLE CH</fullName>
    </customValue>
    <customValue>
        <fullName>AMF</fullName>
    </customValue>
    <customValue>
        <fullName>Analogue</fullName>
    </customValue>
    <customValue>
        <fullName>Black Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Bleached</fullName>
    </customValue>
    <customValue>
        <fullName>Blends</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Ingredient</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTERMLKCONCENTRATE</fullName>
    </customValue>
    <customValue>
        <fullName>Butter Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Cagliata</fullName>
    </customValue>
    <customValue>
        <fullName>Calcium Caseinate</fullName>
    </customValue>
    <customValue>
        <fullName>Natural</fullName>
    </customValue>
    <masterLabel>Product Sub Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>#640 Colored</fullName>
    </customValue>
    <customValue>
        <fullName>#640 Whites</fullName>
    </customValue>
    <customValue>
        <fullName>100#</fullName>
    </customValue>
    <customValue>
        <fullName>200#</fullName>
    </customValue>
    <customValue>
        <fullName>40#</fullName>
    </customValue>
    <customValue>
        <fullName>40# Block</fullName>
    </customValue>
    <customValue>
        <fullName>40#Colby Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# colored</fullName>
    </customValue>
    <customValue>
        <fullName>40#Monterey Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# Pepper Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# White</fullName>
    </customValue>
    <customValue>
        <fullName>500# Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>500# White</fullName>
    </customValue>
    <customValue>
        <fullName>60-80#</fullName>
    </customValue>
    <customValue>
        <fullName>70%</fullName>
    </customValue>
    <customValue>
        <fullName>72.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>80%</fullName>
    </customValue>
    <customValue>
        <fullName>80% salted</fullName>
    </customValue>
    <customValue>
        <fullName>80% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>AA InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Extra No. 1</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Pieces</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Select Sheller Run</fullName>
    </customValue>
    <masterLabel>Product Sub Category 2</masterLabel>
</GlobalValueSet>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

src/classes/OpportunityVolumeRollUpPromiseTest.cls
@isTest(seeAllData=false)
public class OpportunityVolumeRollUpPromiseTest {
    
    @TestSetup
    static void makeData(){
        PriceBook2 pb = new PriceBook2();
        pb.Name = 'Custom PB';
        pb.IsActive = true;            
        insert pb;

        Product2 product1 = creaeProduct ('P1', 'Some desc', 'SFDC-123', '03-Cocoa and Speciality', 'Cocoa Liquor', 'Natural', null, '1');
        Product2 product2 = creaeProduct ('P1', 'Some desc', 'SFDC-123', '03-Cocoa and Speciality', 'Cocoa Beans', null, null, '2');
        insert new List<Product2> {product1, product2};

        PricebookEntry pbe1 = createPriceBookEntry(product1, pb);
        PricebookEntry pbe2 = createPriceBookEntry(product2, pb);
        insert new List<PricebookEntry> {pbe1, pbe2};
        

        Account acc=new Account();
        acc.Name='Test';
        acc.Account_Type__c='Distributor';
        acc.BillingCountry='India';
        acc.BillingStreet='Pune-Mumbai road';
        insert acc;

        Opportunity newOpp=new Opportunity();
        newOpp.AccountId=acc.Id;
        newOpp.Name='Sample opp';
        newOpp.CloseDate=system.today().addDays(10);
        newOpp.Business_Unit__c='Cocoa';
        newOpp.StageName='Offering';
        newOpp.RecordTypeId=OpportunityConstants.DEFEND_OPPORTUNITY_RECORD_TYPE_ID;
        newOpp.Pricebook2Id = pb.Id;

        Opportunity newOpp1=new Opportunity();
        newOpp1.AccountId=acc.Id;
        newOpp1.Name='Sample opp';
        newOpp1.CloseDate=system.today().addDays(10);
        newOpp1.Business_Unit__c='Cocoa';
        newOpp1.StageName='Offering';
        newOpp1.RecordTypeId=OpportunityConstants.GAIN_OPPORTUNITY_RECORD_TYPE_ID;
        newOpp1.Pricebook2Id = pb.Id;
        insert new List<Opportunity> {newOpp, newOpp1};
		//Create a Quote
        Quote quote = TestData_Factory.createQuote(acc, newOpp, true);
        quote.status ='Customer Accepted';
        update quote;
        //Create a Quote
        Quote quote1 = TestData_Factory.createQuote(acc, newOpp1, true);
        quote1.status ='Customer Accepted';
        update quote1;

        OpportunityLineItem oppLineItem = createOpportunityLine (newOpp.Id, pbe1.Id);
        OpportunityLineItem oppLineItem1 = createOpportunityLine (newOpp.Id, pbe2.Id);

        OpportunityLineItem oppLineItem2 = createOpportunityLine (newOpp1.Id, pbe1.Id);
        OpportunityLineItem oppLineItem3 = createOpportunityLine (newOpp1.Id, pbe2.Id);
        insert new List<OpportunityLineItem> {oppLineItem, oppLineItem1, oppLineItem2, oppLineItem3};

    }

    static OpportunityLineItem createOpportunityLine (Id oppId, Id pbeId) {
        OpportunityLineItem oppLineItem = new OpportunityLineItem();
        oppLineItem.OpportunityId = oppId;
        oppLineItem.PricebookEntryId = pbeId;
        oppLineItem.UnitPrice = 7000;
        oppLineItem.Quantity = 5;
        oppLineItem.Sampling_Status__c='1';
        oppLineItem.UoM__c = 'G';
        oppLineItem.Quantity_of_Sample_Grams__c = 100; 
        return oppLineItem;
    }
    static Product2 creaeProduct (String name, String description, String productCode, String productFamily, String category, String subCat, String subCat2, String devCode) {
        return new Product2 (
            Name = name,
            Description = description,
            ProductCode =  productCode,
            isActive = true,
            Family = productFamily,
            Product_Category__c = category,
            Product_Sub_Category__c = subCat,
            Product_Sub_Category_2__c = subCat2,
            Development_Code__c = devCode
        );
    }

    static PricebookEntry createPriceBookEntry (Product2 p, PriceBook2 pb) {
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = pb.Id;
        standardPrice.Product2Id = p.Id;
        standardPrice.UseStandardPrice = false;
        standardPrice.UnitPrice = 100;
        standardPrice.IsActive = true;
        
        return standardPrice;
    }

    @isTest
    static void basic_test_create_budget () {
        List<Opportunity> oppList =  [SELECT Id, AccountId, Business_Unit__c, CloseDate, OwnerId FROM Opportunity WHERE Name = 'Sample opp' LIMIT 2];
        System.assert(oppList != null && !oppList.isEmpty() && oppList.size() > 1, 'Unable to find opportunities');

        // for (Opportunity opp : oppList) {
        //     opp.StageName = OpportunityConstants.OPPORTUNITY_STAGE_CLOSING_WON;
        //     opp.Actual_Developing_Hours__c = 20;    
        // }

        oppList[0].StageName = OpportunityConstants.OPPORTUNITY_STAGE_CLOSING_WON;
        oppList[0].Actual_Developing_Hours__c = 20; 
        update oppList[0];

        oppList[1].StageName = OpportunityConstants.OPPORTUNITY_STAGE_CLOSING_WON;
        oppList[1].Actual_Developing_Hours__c = 20;  
        update oppList[1];

        Test.startTest();

        OpportunityVolumeRollUpPromise promiseObj = new OpportunityVolumeRollUpPromise (oppList [0]);
    
        for (Integer index = 1; index < oppList.size(); index ++) {
            promiseObj.then(new OpportunityVolumeRollUpPromise (oppList[index]));
        }

        System.enqueueJob(promiseObj);
        Test.stopTest();

        List<Budget_vs_Actuals__c> budgets = [SELECT Id, Account__c, Business_Unit__c, Year__c, 
                                        (SELECT Id, Category__c, Sub_Category__c, Sub_Category_2__c FROM Budget_vs_Actual_Lines__r)
                                        FROM Budget_vs_Actuals__c
                                        WHERE  Account__c =: oppList[0].AccountId 
                                        AND Business_Unit__c =: oppList[0].Business_Unit__c
                                        AND Year__c =: String.valueOf (oppList[0].CloseDate.year ())
                                        LIMIT 1
                                    ];
        //System.assert(budgets != null && budgets.size () > 0, 'Budget vs Actuals records not created');
        //System.assertEquals(oppList[0].AccountId, budgets[0].Account__c, 'Account Id mismatch');
        //System.assertEquals(oppList[0].Business_Unit__c, budgets[0].Business_Unit__c, 'BU Id mismatch');
        //System.assertEquals(String.valueOf(oppList[0].CloseDate.year ()), budgets[0].Year__c, 'Year Id mismatch');

        Set<String> catSet = new Set<String> {'Cocoa Liquor', 'Cocoa Beans'};
        //System.assert(budgets[0].Budget_vs_Actual_Lines__r.size () ==  2, 'Line items did not created/ mismatch');
       // for (Budget_vs_Actual_Line__c line : budgets[0].Budget_vs_Actual_Lines__r) {
            //System.assert(catSet.contains(line.Category__c), 'Line item Category__c mismatch');
        //}
    }
    @isTest
    static void test_no_budget_creation () {
        List<Opportunity> oppList =  [SELECT Id, AccountId, Business_Unit__c, CloseDate, OwnerId FROM Opportunity WHERE Name = 'Sample opp' LIMIT 2];
        System.assert(oppList != null && !oppList.isEmpty() && oppList.size() > 1, 'Unable to find opportunities');
        Test.startTest();

        OpportunityVolumeRollUpPromise promiseObj = new OpportunityVolumeRollUpPromise (oppList [0]);
    
        for (Integer index = 1; index < oppList.size(); index ++) {
            promiseObj.then(new OpportunityVolumeRollUpPromise (oppList[index]));
        }

        System.enqueueJob(promiseObj);
        Test.stopTest();

        List<Budget_vs_Actuals__c> budgets = [SELECT Id, Account__c, Business_Unit__c, Year__c, 
                                        (SELECT Id, Category__c, Sub_Category__c, Sub_Category_2__c FROM Budget_vs_Actual_Lines__r)
                                        FROM Budget_vs_Actuals__c
                                        WHERE  Account__c =: oppList[0].AccountId 
                                        AND Business_Unit__c =: oppList[0].Business_Unit__c
                                        AND Year__c =: String.valueOf (oppList[0].CloseDate.year ())
                                        LIMIT 1
                                    ];
        System.assert(budgets != null && budgets.size () > 0, 'Budget vs Actuals records not created');
        System.assertEquals(oppList[0].AccountId, budgets[0].Account__c, 'Account Id mismatch');
        System.assertEquals(oppList[0].Business_Unit__c, budgets[0].Business_Unit__c, 'BU Id mismatch');
        System.assertEquals(String.valueOf(oppList[0].CloseDate.year ()), budgets[0].Year__c, 'Year Id mismatch');

        System.assert(budgets[0].Budget_vs_Actual_Lines__r.size () ==  0, 'Line items are created');
    }
    
    @isTest
    static void test_no_budget_creation_constructor () {
        List<Opportunity> oppList =  [SELECT Id, AccountId, Business_Unit__c, CloseDate, OwnerId FROM Opportunity WHERE Name = 'Sample opp' LIMIT 2];
        System.assert(oppList != null && !oppList.isEmpty() && oppList.size() > 1, 'Unable to find opportunities');
        Test.startTest();

        OpportunityVolumeRollUpPromise promiseObj = new OpportunityVolumeRollUpPromise (oppList [0],
            new List<OpportunityVolumeRollUpPromise> {
                new OpportunityVolumeRollUpPromise (oppList [1])
            }                                                                               
        );

        System.enqueueJob(promiseObj);
        Test.stopTest();

        List<Budget_vs_Actuals__c> budgets = [SELECT Id, Account__c, Business_Unit__c, Year__c, 
                                        (SELECT Id, Category__c, Sub_Category__c, Sub_Category_2__c FROM Budget_vs_Actual_Lines__r)
                                        FROM Budget_vs_Actuals__c
                                        WHERE  Account__c =: oppList[0].AccountId 
                                        AND Business_Unit__c =: oppList[0].Business_Unit__c
                                        AND Year__c =: String.valueOf (oppList[0].CloseDate.year ())
                                        LIMIT 1
                                    ];
        System.assert(budgets != null && budgets.size () > 0, 'Budget vs Actuals records not created');
        System.assertEquals(oppList[0].AccountId, budgets[0].Account__c, 'Account Id mismatch');
        System.assertEquals(oppList[0].Business_Unit__c, budgets[0].Business_Unit__c, 'BU Id mismatch');
        System.assertEquals(String.valueOf(oppList[0].CloseDate.year ()), budgets[0].Year__c, 'Year Id mismatch');

        System.assert(budgets[0].Budget_vs_Actual_Lines__r.size () ==  0, 'Line items are created');
    }

    @isTest
    static void test_no_budget_creation_exception () {
        List<Opportunity> oppList =  [SELECT Id, Business_Unit__c, CloseDate, OwnerId FROM Opportunity WHERE Name = 'Sample opp' LIMIT 2];
        System.assert(oppList != null && !oppList.isEmpty() && oppList.size() > 1, 'Unable to find opportunities');
        Test.startTest();

        OpportunityVolumeRollUpPromise promiseObj = new OpportunityVolumeRollUpPromise (oppList [0]);
    
        for (Integer index = 1; index < oppList.size(); index ++) {
            promiseObj.then(new OpportunityVolumeRollUpPromise (oppList[index]));
        }

        System.enqueueJob(promiseObj);
        Test.stopTest();
        
        List<KAM_Queuable_Error_Log__c> errors = [SELECT Id, Apex_Class__c FROM KAM_Queuable_Error_Log__c LIMIT 1];
        System.assert(errors.size() > 0, 'Exception log not captured');
        System.assertEquals('OpportunityVolumeRollUpPromise', errors[0].Apex_Class__c, 'Mismatch in class name');
    }
}