src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Pardot</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regions__c</fullName>
        <description>To Identify the account region</description>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                    <isActive>false</isActive>
                    <label>Africa</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                    <isActive>false</isActive>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>Europe</fullName>
                    <isActive>false</isActive>
                    <label>Europe</label>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                    <isActive>false</isActive>
                    <label>Latin America</label>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                    <isActive>false</isActive>
                    <label>Middle East</label>
                </value>
                <value>
                    <fullName>North America</fullName>
                    <isActive>false</isActive>
                    <label>North America</label>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                    <isActive>false</isActive>
                    <label>Oceania</label>
                </value>
                <value>
                    <fullName>South America</fullName>
                    <isActive>false</isActive>
                    <label>South America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SAP Account ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Customer_Material_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Material Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Configuration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Integration_Details__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Content_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Content Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Details</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Account Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Total Products</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>KG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Product_Config_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Product Config Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductConfigMaster__c.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product_Configuration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ProductConfigMaster</relationshipLabel>
        <relationshipName>ProductConfigMaster</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ProductConfigMaster</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ProductConfigMaster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductConfigMaster</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Bussiness_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                    <label>Spices</label>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approver_Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Approver Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Material_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Material Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Configuration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measure__c</fullName>
        <label>Unit Of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Application_Pardot.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Confectionery</fullName>
    </customValue>
    <customValue>
        <fullName>Drinks</fullName>
    </customValue>
    <customValue>
        <fullName>Ice Creams</fullName>
    </customValue>
    <customValue>
        <fullName>Desserts</fullName>
    </customValue>
    <customValue>
        <fullName>Savoury</fullName>
    </customValue>
    <customValue>
        <fullName>Bevarage</fullName>
    </customValue>
    <customValue>
        <fullName>Frozen Desserts</fullName>
    </customValue>
    <masterLabel>application</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <customValue>
        <fullName>Tropical</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acid</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI HH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI LH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI MH</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Blanched</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Oil Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Reject</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth Organic</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN STYLE CH</fullName>
    </customValue>
    <customValue>
        <fullName>AMF</fullName>
    </customValue>
    <customValue>
        <fullName>Analogue</fullName>
    </customValue>
    <customValue>
        <fullName>Black Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Bleached</fullName>
    </customValue>
    <customValue>
        <fullName>Blends</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Ingredient</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTERMLKCONCENTRATE</fullName>
    </customValue>
    <customValue>
        <fullName>Butter Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Cagliata</fullName>
    </customValue>
    <customValue>
        <fullName>Calcium Caseinate</fullName>
    </customValue>
    <customValue>
        <fullName>Pepper</fullName>
    </customValue>
    <masterLabel>Product Sub Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>#640 Colored</fullName>
    </customValue>
    <customValue>
        <fullName>#640 Whites</fullName>
    </customValue>
    <customValue>
        <fullName>100#</fullName>
    </customValue>
    <customValue>
        <fullName>200#</fullName>
    </customValue>
    <customValue>
        <fullName>40#</fullName>
    </customValue>
    <customValue>
        <fullName>40# Block</fullName>
    </customValue>
    <customValue>
        <fullName>40#Colby Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# colored</fullName>
    </customValue>
    <customValue>
        <fullName>40#Monterey Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# Pepper Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# White</fullName>
    </customValue>
    <customValue>
        <fullName>500# Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>500# White</fullName>
    </customValue>
    <customValue>
        <fullName>60-80#</fullName>
    </customValue>
    <customValue>
        <fullName>70%</fullName>
    </customValue>
    <customValue>
        <fullName>72.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>80%</fullName>
    </customValue>
    <customValue>
        <fullName>80% salted</fullName>
    </customValue>
    <customValue>
        <fullName>80% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>AA InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Extra No. 1</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Pieces</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Select Sheller Run</fullName>
    </customValue>
    <customValue>
        <fullName>Black Pepper</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <masterLabel>Product Sub Category 2</masterLabel>
</GlobalValueSet>

src/globalValueSets/Unit_of_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MT</fullName>
        <default>true</default>
        <label>MT</label>
    </customValue>
    <customValue>
        <fullName>LB</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>QE</fullName>
        <isActive>false</isActive>
        <label>QE</label>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
        <isActive>false</isActive>
        <label>Carton</label>
    </customValue>
    <masterLabel>Unit of Measure</masterLabel>
</GlobalValueSet>

src/classes/AddQuoteLineItemsController_Test.cls
@isTest
public class AddQuoteLineItemsController_Test {
    @testSetup
    public static void setupData()
    {
        //Create an Account
        //Account acc = TestData_Factory.createAccount(true);
        Account acc = new Account(Name = 'UNIT TEST', Regions__c='USA',SAP_Account_ID__c='123', BillingStreet = 'Test 1 street', BillingCountry = 'Usa');
        insert acc;
        //Get the pricebookId
        //Id pricebookId = Test.getStandardPricebookId();
        
        Integration_Details__c intergration= new  Integration_Details__c(Name='SAP Product Configuration',
                                                                         username__c='olam.pi@olamnet.com',password__c='OlamPI@123',content_Type__c='application/json',Method__c='POST',
                                                                         Endpoint__c='https://olamapi.prod.apimanagement.eu10.hana.ondemand.com:443/ProductConfig_QA',timeOut__c=12000);
        insert intergration;
        System.debug('intergration ((: '+intergration.Username__c);
        Pricebook2 pricebook = TestData_Factory.createPriceBook(true);
        Id pricebookId = pricebook.Id;
        
        //Create an Opportunity
        Opportunity opp = TestData_Factory.createOpportunity(acc, pricebookId, true);
        
        //Create a Quote
        
        Quote quote = TestData_Factory.createQuote(acc, opp, true);
        
        Opportunity opp1 = new Opportunity();
        opp1.AccountId = acc.Id;
        opp1.Name = 'TestOppnew';
        opp1.StageName = 'Briefing';
        opp1.RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId();
        opp1.CloseDate = System.today();
        opp1.Business_Unit__c = 'Cocoa';
        //opp1.Application__c = 'Bakery';
        opp1.CurrencyIsoCode = 'USD';
        insert opp1;
        Quote quote1=new Quote();
        quote1.OpportunityId=opp1.Id;
        //quote.AccountId = acc.Id;
        quote1.Name=opp1.Name;
        quote1.Bussiness_Unit__c=opp1.Business_Unit__c;
        quote1.ExpirationDate=opp1.CloseDate;
        quote1.Status='Draft';
        insert quote1;
        
        Opportunity oppDairy = new Opportunity(AccountId = acc.Id,Name = 'TestOppDairy',StageName = 'Briefing'
                                               ,RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId()
                                               ,CloseDate = System.today(),Business_Unit__c = 'Dairy',
                                               //Application__c = 'Bakery',
                                               CurrencyIsoCode = 'USD');
        
        insert oppDairy;
        Quote quoteDairy=new Quote(OpportunityId=oppDairy.Id,Name=oppDairy.Name,Bussiness_Unit__c=oppDairy.Business_Unit__c
                                   ,ExpirationDate=oppDairy.CloseDate,Status='Draft');
        insert quoteDairy;
        
        Opportunity oppEN = new Opportunity(AccountId = acc.Id,Name = 'TestOppEN',StageName = 'Briefing'
                                            ,RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId()
                                            ,CloseDate = System.today(),Business_Unit__c = 'Edible_Nuts',
                                            //Application__c = 'Bakery',
                                            CurrencyIsoCode = 'USD');
        
        insert oppEN;
        Quote quoteEN=new Quote(OpportunityId=oppEN.Id,Name=oppEN.Name,Bussiness_Unit__c=oppEN.Business_Unit__c
                                ,ExpirationDate=oppEN.CloseDate,Status='Draft');
        insert quoteEN;
        
        Opportunity oppBuNull = new Opportunity(AccountId = acc.Id,Name = 'TestOppBUNull',StageName = 'Briefing'
                                                ,RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId()
                                                ,CloseDate = System.today(),Business_Unit__c = '',
                                               //Application__c = 'Bakery',
                                                CurrencyIsoCode = 'USD');
        
        insert oppBuNull;
        Quote quoteNull=new Quote(OpportunityId=oppBuNull.Id,Name=oppBuNull.Name,Bussiness_Unit__c=oppBuNull.Business_Unit__c
                                  ,ExpirationDate=oppBuNull.CloseDate,Status='Draft');
        insert quoteNull;
        
        Opportunity oppSpice = new Opportunity(AccountId = acc.Id,Name = 'SpiceBUOpp',StageName = 'Briefing'
                                               ,RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId()
                                               ,CloseDate = System.today(),Business_Unit__c = 'Spice',
                                               //Application__c = 'Bakery',
                                               CurrencyIsoCode = 'USD');
        
        insert oppSpice;
        Quote quoteSpice=new Quote(OpportunityId=oppSpice.Id,Name=oppSpice.Name,Bussiness_Unit__c=oppSpice.Business_Unit__c
                                   ,ExpirationDate=oppSpice.CloseDate,Status='Draft');
        insert quoteSpice;
        //Create a Product
        Product2 prod = TestData_Factory.createProduct('12-Spices', 'Tropical', 'Pepper', 'Black Pepper', true);
        
        //Create a PricebookEntry
        PricebookEntry pbe = TestData_Factory.createPricebookEntry(pricebookId, prod, true);
        
        //PricebookEntry pbe = [Select Id from PricebookEntry where Product2Id =: prod.Id and CurrencyIsoCode =: opp.CurrencyIsoCode limit 1];
        
        //Create a QuoteLineItem
        //QuoteLineItem qLI = TestData_Factory.createQuoteLineItem(pbe, prod, quote, true);
        QuoteLineItem qli=new QuoteLineItem();
        qli.QuoteId=quote.Id;
        //qli.Product2Id=p.Id;
        qli.PricebookEntryId=pbe.Id;
        qli.UnitPrice = 11;
        qli.Volume__c=3;
        qli.Quantity=5;
        qli.Approver_Comment__c = 'Test';
        qli.Product_Configuration__c='[{ "customer_sap_id" : "1000018", "customer_material_code" : "321321355", "olam_material_code" : "100000000061"},{"customer_sap_id" : "1000018", "customer_material_code" : "33112244", "olam_material_code" : "100000000091"}]';
        insert qli;
        System.debug('qLI: '+qLI);
        
        
        //Create a Product Config Master
        // ProductConfigMaster__c prodConfigMaster = TestData_Factory.createProdConfigMaster(prod,true);
        ProductConfigMaster__c prodConfigMaster =  new ProductConfigMaster__c(
            Product_Category__c='BLEND',
            Product__c=prod.id,
            Name='Product',
            Product_Configuration__c='[{"olam_material_code":"100000039072","customer_sap_id":"1234","customer_material_code":"","configurations":[{"varient_character_mapping":"","uom":"%","quantitative":"Yes","qualitative":"","olam_range":"0,000 - 500,000","mic":"-U100","indicator":"Product","description":"MOLD COUNT PER GRAM","customer_range":"0,000 - 500,000"},{"varient_character_mapping":"MOIST","uom":"","quantitative":"Yes","qualitative":"","olam_range":"0,00 - 500,00","mic":"","indicator":"Product","description":"Moist 6","customer_range":"0,00 - 700,00"}]}]'
        );
        insert prodConfigMaster;
        
        prod.Is_Product_Config_Required__c = true;
        update prod;
        //Create an Approved SKU
        Asset approvedSKU = TestData_Factory.createApprovedSKU(acc,prod,true);
        
    }
    @isTest
    public static void getPriceBooksTest1()
    {
        Quote quote = [Select id from Quote limit 1];
        System.debug('quote: '+quote);
        Test.startTest();
        AddQuoteLineItemsController.getPriceBooks(quote.Id);
        
        // quote.Pricebook2Id = Null;
        // update quote;
        Quote quote1 = [Select id from Quote where name='TestOppnew' ];
        List<PriceBook2> r1=  AddQuoteLineItemsController.getPriceBooks(quote1.Id);
        System.assert(r1!=null, 'Result Is Null');
        Quote quoteDairy = [Select id from Quote where name='TestOppDairy' ];
        AddQuoteLineItemsController.getPriceBooks(quoteDairy.Id);
        Quote quoteEN = [Select id from Quote where name='TestOppEN' ];
        AddQuoteLineItemsController.getPriceBooks(quoteEN.Id);
        Quote quoteNull = [Select id from Quote where name='TestOppBUNull' ];
        AddQuoteLineItemsController.getPriceBooks(quoteNull.Id);
        List<Quote> quoteSpice = [Select id from Quote where name='SpiceBUOpp' ];
        AddQuoteLineItemsController.getPriceBooks(quoteSpice[0].Id);
        
        Test.stopTest();
    }
    @isTest
    public static void updateQuotePriceBookTest1()
    {
        Quote quote = [Select id,PriceBook2Id from Quote limit 1];
        System.debug('quote: '+quote);
        Id pricebookId = Test.getStandardPricebookId();
        Test.startTest();
        AddQuoteLineItemsController.updateQuotePriceBook(quote.Id,pricebookId);
        AddQuoteLineItemsController.updateQuotePriceBook(quote.Id,'pricebookId');
        AddQuoteLineItemsController.updateQuotePriceBook(quote.Id,quote.PriceBook2Id);
        Test.stopTest();
    }
    @isTest
    public static void getIsApprovalRequiredValuesTest1()
    {
        Quote quote = [Select id from Quote limit 1];
        System.debug('quote: '+quote);
        Id pricebookId = Test.getStandardPricebookId();
        Test.startTest();
        AddQuoteLineItemsController.getIsApprovalRequiredValues(quote.Id);
        Test.stopTest(); //Unit_Of_Measure__c
    }
    @isTest
    public static void getselectOptionsTest1()
    {
        QuoteLineItem qli = new QuoteLineItem();
        AddQuoteLineItemsController adQLI = new AddQuoteLineItemsController();
        Test.startTest();
        AddQuoteLineItemsController.getselectOptions(qli,'Unit_Of_Measure__c');
        AddQuoteLineItemsController.getQueryString('Quote');
        Test.stopTest(); 
    }
    @isTest
    public static void fetchLineItemWrapperTest1()
    {
        Quote quote = [Select id from Quote limit 1];
        Asset apSKU = [Select id,AccountId,Product2ID,Customer_Material_Code__c,Product_Configuration__c,Product2.Product_Category__c,Product2.Product_Sub_Category__c,Product2.Product_Sub_Category_2__c,Product2.Family,Product2.Brand__c,Product2.External_Product_Code__c from Asset];
        Test.startTest();
        List<AddQuoteLineItemsController.LineItemWrapper> lstLineItemWrapper = new List<AddQuoteLineItemsController.LineItemWrapper>();
        lstLineItemWrapper = AddQuoteLineItemsController.fetchLineItemWrapper(quote.Id,apSKU.Customer_Material_Code__c,apSKU.Product2.Product_Category__c,apSKU.Product2.Product_Sub_Category__c,apSKU.Product2.Product_Sub_Category_2__c,apSKU.Product2.Brand__c,apSKU.Product2.Family);
        System.debug('lstLineItemWrapper: '+lstLineItemWrapper);
        lstLineItemWrapper = AddQuoteLineItemsController.fetchLineItemWrapper(quote.Id,apSKU.Product2.External_Product_Code__c,apSKU.Product2.Product_Category__c,apSKU.Product2.Product_Sub_Category__c,apSKU.Product2.Product_Sub_Category_2__c,apSKU.Product2.Brand__c,apSKU.Product2.Family);
        System.debug('lstLineItemWrapper: '+lstLineItemWrapper);
        lstLineItemWrapper = AddQuoteLineItemsController.fetchLineItemWrapper(quote.Id,'','','','','','');
        System.debug('lstLineItemWrapper: '+lstLineItemWrapper);
        Test.stopTest(); 
    }
    @isTest
    public static void fetchProductConfigForSelectedProductsTest1()
    {
        Quote quote = [Select id from Quote limit 1];
        Asset apSKU = [Select id,AccountId,Product2ID,Customer_Material_Code__c,Product_Configuration__c,Product2.Product_Category__c,Product2.Product_Sub_Category__c,Product2.Product_Sub_Category_2__c,Product2.Family,Product2.Brand__c,Product2.External_Product_Code__c from Asset];
        Test.startTest();
        
        
        List<ProductConfigSAPWrapper> listOfProdConfigSAPWrapper = new List<ProductConfigSAPWrapper>();
        ProductConfigSAPWrapper sapWrapper = new ProductConfigSAPWrapper();
        sapWrapper.customer_sap_id ='1234';
        sapWrapper.customer_material_code ='';
        sapWrapper.olam_material_code ='100000039072'; //Product External_Product_Code;
        
        List<ProductConfigSAPWrapper.ProductConfigWrapper> listOfProdConfigWrap = new List<ProductConfigSAPWrapper.ProductConfigWrapper>();
        
        ProductConfigSAPWrapper.ProductConfigWrapper prodConfigWrap = new ProductConfigSAPWrapper.ProductConfigWrapper();
        prodConfigWrap.mic = '-U100';
        prodConfigWrap.varient_character_mapping = 'Test';
        prodConfigWrap.description = 'MOLD COUNT PER GRAM';
        prodConfigWrap.uom = '%';
        prodConfigWrap.quantitative = 'Yes';
        prodConfigWrap.qualitative = '';
        prodConfigWrap.olam_range = '0,00 - 500,00';
        prodConfigWrap.customer_range = '0,000 - 500,000';
        prodConfigWrap.indicator = 'Product';
        listOfProdConfigWrap.add(prodConfigWrap);
        sapWrapper.configurations = listOfProdConfigWrap;
        System.debug('listOfProdConfigWrap** '+listOfProdConfigWrap);
        listOfProdConfigSAPWrapper.add(sapWrapper);
        String prodConfig = Json.serialize(listOfProdConfigSAPWrapper);
        System.debug('prodConfig: '+prodConfig); 
        
        //--------------------------
        PricebookEntry pbe=[select id,Product2.External_Product_Code__c from PricebookEntry limit 1];
        AddQuoteLineItemsController.LineItemWrapper lineItemWrapper = new AddQuoteLineItemsController.LineItemWrapper();
        lineItemWrapper.isChecked=false;
        lineItemWrapper.customerMaterialCode='12345';
        lineItemWrapper.unitPrice=1;
        lineItemWrapper.volume=2;
        lineItemWrapper.unitOfMeasure='KG';
        lineItemWrapper.isPLMApprovalRequired='';
        lineItemWrapper.isProdConfigFetched=false;
        lineItemWrapper.isFileUploaded=false;
        lineItemWrapper.isProductConfigRequired=true;
        lineItemWrapper.customerMaterialCodeUserInput='34355';
        lineItemWrapper.prodConfigSource='abc';
        lineItemWrapper.accountSAPId='123';
        AddQuoteLineItemsController.ProductConfigWrapperFinal ProductConfigWrapperFinal=new AddQuoteLineItemsController.ProductConfigWrapperFinal();
        ProductConfigWrapperFinal.prodConfigFinal=prodConfigWrap;
        ProductConfigWrapperFinal.new_range='200';
        List<AddQuoteLineItemsController.ProductConfigWrapperFinal> ListOFProductConfigWrapperFinal=new List<AddQuoteLineItemsController.ProductConfigWrapperFinal>();
        ListOFProductConfigWrapperFinal.add(ProductConfigWrapperFinal);
        lineItemWrapper.objPBE=pbe;
        lineItemWrapper.listOfProductConfigWrapperFinal=ListOFProductConfigWrapperFinal;
        //lineItemWrapper.listOfContentDocIds=
        List<AddQuoteLineItemsController.LineItemWrapper> listoflineItemWrapper = new List<AddQuoteLineItemsController.LineItemWrapper>();
        listoflineItemWrapper.add(lineItemWrapper);
        AddQuoteLineItemsController.createQuoteLineItem(quote.Id, listoflineItemWrapper);
        //-----------------------
        
        
        
        
        List<AddQuoteLineItemsController.LineItemWrapper> lstLineItemWrapper = new List<AddQuoteLineItemsController.LineItemWrapper>();
        lstLineItemWrapper = AddQuoteLineItemsController.fetchLineItemWrapper(quote.Id,apSKU.Customer_Material_Code__c,apSKU.Product2.Product_Category__c,apSKU.Product2.Product_Sub_Category__c,apSKU.Product2.Product_Sub_Category_2__c,apSKU.Product2.Brand__c,apSKU.Product2.Family);
        
        System.debug('lstLineItemWrapper: '+lstLineItemWrapper);
        System.debug('quote id*******'+quote.Id);
        //  AddQuoteLineItemsController.createQuoteLineItem(quote.Id, lstLineItemWrapper);
        //AddQuoteLineItemsController.fetchProductConfigForSelectedProducts(quote.id, lstLineItemWrapper, true);
        delete apSKU;
        Test.setMock(HttpCalloutMock.class, new MockGenerator());  
        AddQuoteLineItemsController.fetchProductConfigForSelectedProducts(quote.id, lstLineItemWrapper, true);
        Test.stopTest(); 
    }   
    @isTest
    public static void testAPI()
    {
        Quote quote = [Select id from Quote limit 1];
        Asset apSKU = [Select id,AccountId,Product2ID,Customer_Material_Code__c,Product_Configuration__c,Product2.Product_Category__c,Product2.Product_Sub_Category__c,Product2.Product_Sub_Category_2__c,Product2.Family,Product2.Brand__c,Product2.External_Product_Code__c from Asset];
        List<AddQuoteLineItemsController.LineItemWrapper> lstLineItemWrapper = new List<AddQuoteLineItemsController.LineItemWrapper>();
        lstLineItemWrapper = AddQuoteLineItemsController.fetchLineItemWrapper(quote.Id,apSKU.Customer_Material_Code__c,apSKU.Product2.Product_Category__c,apSKU.Product2.Product_Sub_Category__c,apSKU.Product2.Product_Sub_Category_2__c,apSKU.Product2.Brand__c,apSKU.Product2.Family);
       
      
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockGenerator());  
        AddQuoteLineItemsController.fetchProductConfigForSelectedProducts(quote.id, lstLineItemWrapper, true);
        Test.stopTest(); 
        
        /*
        PricebookEntry pbe=[select id,Product2.External_Product_Code__c,Product2.Is_Product_Config_Required__c from PricebookEntry limit 1];
        AddQuoteLineItemsController.LineItemWrapper lineItemWrapper = new AddQuoteLineItemsController.LineItemWrapper();
        lineItemWrapper.isChecked=false;
        lineItemWrapper.customerMaterialCode='12345';
        lineItemWrapper.unitPrice=1;
        lineItemWrapper.volume=2;
        lineItemWrapper.unitOfMeasure='KG';
        lineItemWrapper.isPLMApprovalRequired='';
        lineItemWrapper.isProdConfigFetched=false;
        lineItemWrapper.isFileUploaded=false;
        lineItemWrapper.isProductConfigRequired=true;
        lineItemWrapper.customerMaterialCodeUserInput='34355';
        lineItemWrapper.prodConfigSource='abc';
        lineItemWrapper.accountSAPId='123';
        lineItemWrapper.objPBE=pbe;
         //lineItemWrapper.listOfContentDocIds=
            List<AddQuoteLineItemsController.LineItemWrapper> listoflineItemWrapper = new  List<AddQuoteLineItemsController.LineItemWrapper>();
        listoflineItemWrapper.add(lineItemWrapper);
        Test.setMock(HttpCalloutMock.class, new MockGenerator()); 
        AddQuoteLineItemsController.fetchProductConfigForSelectedProducts(quote.id, listoflineItemWrapper, true);
     */
    }
    
    
}