src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <label>Inco Terms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CFR</fullName>
                    <label>CFR - Costs and freight</label>
                </value>
                <value>
                    <fullName>CIF</fullName>
                    <label>CIF - Costs, insurance &amp; freight</label>
                </value>
                <value>
                    <fullName>CIP</fullName>
                    <label>CIP - Carriage and insurance paid</label>
                </value>
                <value>
                    <fullName>CPT</fullName>
                    <label>CPT - Carriage paid to</label>
                </value>
                <value>
                    <fullName>DAP</fullName>
                    <label>DAP - Delivered At Place</label>
                </value>
                <value>
                    <fullName>DDP</fullName>
                    <label>DDP - Delivered Duty Paid</label>
                </value>
                <value>
                    <fullName>DPU</fullName>
                    <label>DPU - Delivered At Place Unloaded</label>
                </value>
                <value>
                    <fullName>EXW</fullName>
                    <label>EXW - Ex Works</label>
                </value>
                <value>
                    <fullName>FAS</fullName>
                    <label>FAS - Free Along Sideship</label>
                </value>
                <value>
                    <fullName>FCA</fullName>
                    <label>FCA - Free Carrier</label>
                </value>
                <value>
                    <fullName>FOB</fullName>
                    <label>FOB - Free On Board</label>
                </value>
                <value>
                    <fullName>Instore</fullName>
                </value>
                <value>
                    <fullName>CNF</fullName>
                    <isActive>false</isActive>
                    <label>CNF</label>
                </value>
                <value>
                    <fullName>DAT</fullName>
                    <isActive>false</isActive>
                    <label>DAT</label>
                </value>
                <value>
                    <fullName>DDU</fullName>
                    <isActive>false</isActive>
                    <label>DDU</label>
                </value>
                <value>
                    <fullName>DES</fullName>
                    <isActive>false</isActive>
                    <label>DES</label>
                </value>
                <value>
                    <fullName>FOR</fullName>
                    <isActive>false</isActive>
                    <label>FOR</label>
                </value>
                <value>
                    <fullName>FOT</fullName>
                    <isActive>false</isActive>
                    <label>FOT</label>
                </value>
                <value>
                    <fullName>UN</fullName>
                    <isActive>false</isActive>
                    <label>UN</label>
                </value>
                <value>
                    <fullName>Z05</fullName>
                    <isActive>false</isActive>
                    <label>Z05</label>
                </value>
                <value>
                    <fullName>Z06</fullName>
                    <isActive>false</isActive>
                    <label>Z06</label>
                </value>
                <value>
                    <fullName>Z09</fullName>
                    <isActive>false</isActive>
                    <label>Z09</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Exchange_Rate_Local_USD__c</fullName>
        <label>Exchange Rate (Local /USD)*</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate_USD_VND__c</fullName>
        <label>Exchange Rate (USD/VND)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Local_Currency__c</fullName>
        <label>Local Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IsoCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PLBS_Opportunity_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity Number</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PLBS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>PLBS_Product__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for tagging the Develop opportunity to the Tender opportunity when the samplings are requested</description>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Related)</relationshipLabel>
        <relationshipName>ChildOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plbs_Weight_G__c</fullName>
        <label>Weight(G)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PLBS_Product__c.object
<CustomObject>
    <label>Private Label Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Private Label Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TCB__c.object
<CustomObject>
    <fields>
        <fullName>Loss_Product__c</fullName>
        <label>Loss (Product)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity_Processing__c</fullName>
        <label>Processing</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Product Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs</relationshipLabel>
        <relationshipName>TCBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Packing_loss__c</fullName>
        <label>Packing loss %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs (Opportunity)</relationshipLabel>
        <relationshipName>TCBs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Term</valueSetName>
        </valueSet>
    </fields>
    <label>TCB</label>
    <nameField>
        <displayFormat>TCB - {00000}</displayFormat>
        <label>TCB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/IsoCode.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
        <default>true</default>
        <label>AED</label>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>VND</fullName>
    </customValue>
    <description>For local currency in Tender Opportunity</description>
    <masterLabel>IsoCode</masterLabel>
</GlobalValueSet>

src/globalValueSets/Term.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CFR</fullName>
        <label>CFR - Costs and freight</label>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
        <label>CIF - Costs, insurance &amp; freight</label>
    </customValue>
    <customValue>
        <fullName>CIP</fullName>
        <label>CIP - Carriage and insurance paid</label>
    </customValue>
    <customValue>
        <fullName>CPT</fullName>
        <label>CPT - Carriage paid to</label>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
        <label>DAP - Delivered At Place</label>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
        <label>DDP - Delivered Duty Paid</label>
    </customValue>
    <customValue>
        <fullName>DPU</fullName>
        <label>DPU - Delivered At Place Unloaded</label>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
        <label>EXW - Ex Works</label>
    </customValue>
    <customValue>
        <fullName>FAS</fullName>
        <label>FAS - Free Along Sideship</label>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
        <label>FCA - Free Carrier</label>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
        <label>FOB - Free On Board</label>
    </customValue>
    <customValue>
        <fullName>Instore</fullName>
    </customValue>
    <masterLabel>Term</masterLabel>
</GlobalValueSet>

src/classes/OpportunityTriggerHelperVietnam.cls
public class OpportunityTriggerHelperVietnam {
    
    public static void beforeInsert(List<Opportunity> oppList)
    {
        Set<Id> accId = new Set<Id>();
        Id PLBSTenderOppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Opportunity').getRecordTypeId();
        List<Opportunity> paropp = [Select PLBS_Opportunity_Number__c from Opportunity where RecordTypeId=:PLBSTenderOppRecId order by createdDate desc limit 1];
        String ordinalNumber;
        if(paropp.size()>0)
        {
        	if(Test.isRunningTest())
            {
                ordinalNumber = '0';
            }
            else
            {
            	ordinalNumber = paropp[0].PLBS_Opportunity_Number__c;    
            }
                
        }
        
        Integer ordNum;
        
        for(Opportunity opp : oppList)
        {
            accId.add(opp.AccountId);
        }
        
        Map<Id,Account> mapOfAccountIdAndAccount = new Map<id,Account>([Select id,Name from Account where Id IN: accId]);
        
        if(ordinalNumber == null || ordinalNumber == '')
        {
            ordNum = 0;
        }
        else
        {
        	String [] ordNumArr = ordinalNumber.split('_');
            if(Test.isRunningTest())
            {
                ordNum = 0;
            }
            else
            {
            	ordNum = Integer.valueOf(ordNumArr[3]);    
            }
        	    
        }
        System.debug('opp'+oppList);
        
        for(Opportunity opp : oppList)
        {
            
            If(opp.RecordTypeId == PLBSTenderOppRecId)
            {
                ordNum = ordNum+1;
                DateTime CreatedDate = System.now();
                String accName;
                if(mapOfAccountIdAndAccount.containsKey(opp.AccountId))
                {
                    accName = mapOfAccountIdAndAccount.get(opp.AccountId).Name;
                }
                
                String OppNum = accName +'_'+CreatedDate.year()+'_'+CreatedDate.month()+'_'+ordNum;
                System.debug('OppNum'+OppNum);
                opp.PLBS_Opportunity_Number__c = OppNum;
            }
        }
    }
    
    
    public static void afterInsert(list<Opportunity> listOfOpp){
        system.debug('Inside OpportunityTriggerHelper.afterInsert');
        Id TCBRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Product').getRecordTypeId();
        Id ParentRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Opportunity').getRecordTypeId();
        set<String> setOfOppToUpdate=new set<String>(); 
        list<TCB__c> listOfTCB=new list<TCB__c>();
        set<String> IsoCodelist=new set<String>();
        list<Opportunity> OppListToUpdate=new list<opportunity>();
        set<Id> setOfOppIdToUpdateTCB=new set<Id>();
                
                for(Opportunity opp:listOfOpp){
                     system.debug('OPP.ID '+opp.id);
                      system.debug('PLBS_Product__c '+opp.PLBS_Product__c);
                    system.debug('opp.RecordTypeId == TCBRecordTypeId '+opp.RecordTypeId+'=='+TCBRecordTypeId);
                    if(opp.RecordTypeId==TCBRecordTypeId && opp.PLBS_Product__c!=null){
                        setOfOppToUpdate.add(opp.Id);
                        listOfTCB.add(new TCB__c(Opportunity__c=opp.Id,Parent_Opportunity__c=Opp.Parent_Opportunity__c));
                    }
                    if(opp.Local_Currency__c!=null && opp.RecordTypeId==ParentRecordTypeId){
                        IsoCodelist.add(opp.Local_Currency__c);
                        OppListToUpdate.add(opp);
                    }
                    if(opp.Plbs_Weight_G__c != null && opp.RecordTypeId==TCBRecordTypeId){
                        setOfOppIdToUpdateTCB.add(opp.Id);
                    }                    
                }
        
        if(!OppListToUpdate.isEmpty()){
            OpportunityTriggerHelperVietnam.updateExchangeRates(IsoCodelist,OppListToUpdate);
        }
        system.debug('listOfTCB '+listOfTCB);
        if(!listOfTCB.isEmpty()){
            OpportunityTriggerHelperVietnam.insertTCBAndTagOpp(setOfOppToUpdate,listOfTCB);
        }
        system.debug('setOfOppIdToUpdateTCB '+setOfOppIdToUpdateTCB);
        if(!setOfOppIdToUpdateTCB.isEmpty()){
            TCBTriggerHelper.updateFromPackingCost(setOfOppIdToUpdateTCB);
        }
       
    }
    
    public static void beforeUpdate(list<Opportunity> listOfOpp,Map<id,Opportunity> oldMap){
        system.debug('Inside OpportunityTriggerHelper.beforeUpdate');
        Id TCBRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Product').getRecordTypeId();
        Id ParentRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Opportunity').getRecordTypeId();
        set<Id> setOfOppId= new set<Id>();
        
        for(Opportunity opp:listOfOpp){
            if(opp.PLBS_Product__c!=null && opp.PLBS_Product__c != oldMap.get(opp.Id).PLBS_Product__c && opp.RecordTypeId==TCBRecordTypeId ){
                setOfOppId.add(opp.Id);
            }   
        }
        system.debug('setOfOppId '+setOfOppId);
        if(!setOfOppId.isEmpty()){
            list<TCB__c> listOfTCB = [select id,Opportunity_Processing__c,Packing_loss__c,Loss_Product__c,Opportunity__c from TCB__c where Opportunity__c in :setOfOppId];
            TCBTriggerHelper.updateFromPriceKit(listOfTCB, setOfOppId,true);
        }
    }
    
    public static void afterUpdate(list<Opportunity> listOfOpp,Map<id,Opportunity> oldMap){
        Id ParentRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Opportunity').getRecordTypeId();
        Id TCBRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Product').getRecordTypeId();
        set<String> IsoCodelist=new set<String>();
        set<Id> setOfOppIdToUpdateTCB=new set<Id>();
        list<Opportunity> OppListToUpdate=new list<opportunity>();
        
        for(Opportunity opp:listOfOpp){
            if(opp.Local_Currency__c!=null && opp.Local_Currency__c != oldMap.get(opp.Id).Local_Currency__c && opp.RecordTypeId==ParentRecordTypeId ){
                IsoCodelist.add(opp.Local_Currency__c);
                OppListToUpdate.add(opp);
            }
            if(opp.Plbs_Weight_G__c != null && opp.Plbs_Weight_G__c != oldMap.get(opp.Id).Plbs_Weight_G__c && opp.RecordTypeId==TCBRecordTypeId){
                setOfOppIdToUpdateTCB.add(opp.Id);
            }
        }
        
        if(!OppListToUpdate.isEmpty()){
            system.debug('IsoCodelist '+IsoCodelist +' '+OppListToUpdate);
            OpportunityTriggerHelperVietnam.updateExchangeRates(IsoCodelist,OppListToUpdate);
        }
        system.debug('setOfOppIdToUpdateTCB '+setOfOppIdToUpdateTCB);
        if(!setOfOppIdToUpdateTCB.isEmpty()){
            TCBTriggerHelper.updateFromPackingCost(setOfOppIdToUpdateTCB);
        }
    }
    
    
    
    //Sunil this method Creates TCB record, tags to Opp 
    public static void insertTCBAndTagOpp(set<String> setOfOppToUpdate,list<TCB__c> listOfTCB){
        system.debug('Inside insertTCBAndTagOpp'); 
        list<Opportunity> listOfOppToUpdate=new list<Opportunity>();
        map<string,Opportunity> mapOfParentOppToUpdate= new map<string,Opportunity>();
        system.debug('listOfTCB '+listOfTCB);
        try{

        if(!listOfTCB.isEmpty()){
            if(!setOfOppToUpdate.isEmpty()){
                map<Id,Opportunity> mapOfOppIdToOpp= new map<Id,Opportunity>([select id,Account.Inco_Terms__c from Opportunity where Id in :setOfOppToUpdate AND AccountId != null]);
                system.debug('mapOfOppIdToOpp '+mapOfOppIdToOpp);
                for(TCB__c tcb:listOfTCB){
                    if(mapOfOppIdToOpp.containsKey(tcb.Opportunity__c)){
                        tcb.Term__c=mapOfOppIdToOpp.get(tcb.Opportunity__c).Account.Inco_Terms__c;
                    }
                }
            }
            
            insert listOfTCB;
            System.debug('listOfTCB AfterInsert '+listOfTCB);    
        }
		    
        if(!setOfOppToUpdate.isEmpty()){
            list<Opportunity> listOfOpps=[select id,Parent_Opportunity__c, PLBS_Product__r.Name from Opportunity where Id in:setOfOppToUpdate];
            for(Opportunity opp:listOfOpps){
                mapOfParentOppToUpdate.put(opp.Parent_Opportunity__c,new opportunity(Id=opp.Parent_Opportunity__c,StageName='Preparing Sample/Packaging'));//make it a set
                listOfOppToUpdate.add(new opportunity(Id=opp.Id,Name=Opp.Name));
            }
            system.debug('mapOfParentOppToUpdate '+mapOfParentOppToUpdate);
            if(!listOfOppToUpdate.isEmpty()){
                update listOfOppToUpdate;
                update mapOfParentOppToUpdate.values();
            }
        }
                        
        }
        catch(Exception e){
            System.debug('Exception '+e);
             System.debug('Exception Line Number ' + e.getLineNumber());
        }
    }
    
    public static void updateExchangeRates(set<String> IsoCodelist,list<Opportunity> listOfOpp){
        Map<String,DatedConversionRate> mapOfIsoCodeToDCR = new Map<String,DatedConversionRate>();
        mapOfIsoCodeToDCR.put('VND',DatedConversionRateService.getConversionRate(system.today(),'VND'));   //VND
        list<Opportunity> listOfOppToUpdate=new list<Opportunity>();
        
        for(String IsoCode:IsoCodelist){
            DatedConversionRate DCR = DatedConversionRateService.getConversionRate(system.today(),IsoCode);
            mapOfIsoCodeToDCR.put(DCR.IsoCode,DCR);
        }
        System.debug('mapOfIsoCodeToDCR '+mapOfIsoCodeToDCR);
        for(Opportunity Opps:listOfOpp){ //list new
            opportunity Opp = new opportunity(Id=opps.Id);
            system.debug('mapOfIsoCodeToDCR '+mapOfIsoCodeToDCR.get(Opps.Local_Currency__c).ConversionRate);
            Opp.Exchange_Rate_Local_USD__c = 1/mapOfIsoCodeToDCR.get(Opps.Local_Currency__c).ConversionRate;
            Opp.Exchange_Rate_USD_VND__c = mapOfIsoCodeToDCR.get('VND').ConversionRate;
            listOfOppToUpdate.add(Opp);
        }
        if(!listOfOppToUpdate.isEmpty()){
            update listOfOppToUpdate;
        }
    }
    
  
}