src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Regions__c</fullName>
        <description>To Identify the account region</description>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                    <isActive>false</isActive>
                    <label>Africa</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                    <isActive>false</isActive>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>Europe</fullName>
                    <isActive>false</isActive>
                    <label>Europe</label>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                    <isActive>false</isActive>
                    <label>Latin America</label>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                    <isActive>false</isActive>
                    <label>Middle East</label>
                </value>
                <value>
                    <fullName>North America</fullName>
                    <isActive>false</isActive>
                    <label>North America</label>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                    <isActive>false</isActive>
                    <label>Oceania</label>
                </value>
                <value>
                    <fullName>South America</fullName>
                    <isActive>false</isActive>
                    <label>South America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ApprovalRequiredControl__mdt.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                    <default>true</default>
                    <label>Cocoa</label>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                    <default>true</default>
                    <label>APAC</label>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Required?</label>
        <type>Checkbox</type>
    </fields>
    <label>ApprovalRequiredControl</label>
    <pluralLabel>ApprovalRequiredControl</pluralLabel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Text (Account.Regions__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>KG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Bussiness_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                    <label>Spices</label>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <label>Approval Required ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <isActive>false</isActive>
                    <label>N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Material_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Material Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_File_Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is File Uploaded ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measure__c</fullName>
        <label>Unit Of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Unit_of_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MT</fullName>
        <default>true</default>
        <label>MT</label>
    </customValue>
    <customValue>
        <fullName>LB</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>QE</fullName>
        <isActive>false</isActive>
        <label>QE</label>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
        <isActive>false</isActive>
        <label>Carton</label>
    </customValue>
    <masterLabel>Unit of Measure</masterLabel>
</GlobalValueSet>

src/classes/EditQuoteLineItemsController.cls
public class EditQuoteLineItemsController {
    
    @AuraEnabled 
    public static List<LineItemWrapper> fetchLineItemWrapper(List<QuoteLineItem> QuoLIList,Id QuoteId){ 
        
        List<LineItemWrapper> lstLineItemWrapper = new List<LineItemWrapper>();
        System.debug('QuoLIList: '+QuoLIList);
        for(QuoteLineItem quoLI : QuoLIList)
        {
            lstLineItemWrapper.add(new LineItemWrapper(quoLI));
        }
        System.debug('lstLineItemWrapper: '+lstLineItemWrapper);
        return lstLineItemWrapper; 
    }
	
    public class LineItemWrapper {
        @AuraEnabled public QuoteLineItem objPBE{get;set;}
        @AuraEnabled public String customerMaterialCode{get;set;}
        @AuraEnabled public Double unitPrice{get;set;}
        @AuraEnabled public Double volume{get;set;}
        @AuraEnabled public String unitOfMeasure{get;set;}
        @AuraEnabled public String isPLMApprovalRequired{get;set;}
        @AuraEnabled public Boolean isFileUploaded{get;set;}
			
        public LineItemWrapper(QuoteLineItem objQLI){
            this.objPBE = objQLI;
            this.unitPrice = objQLI.UnitPrice;
            this.volume = objQLI.Volume__c;
            //this.isFileUploaded = false;
            this.isFileUploaded = objQLI.Is_File_Uploaded__c;
            this.isPLMApprovalRequired = objQLI.Approval_Required__c;
            this.customerMaterialCode = objQLI.Customer_Material_Code__c;
        }
        public LineItemWrapper(){
        }
    }
    
    @AuraEnabled
    public static List < String > getselectOptions(sObject objObject, string fld) {
        system.debug('objObject --->' + objObject);
        system.debug('fld --->' + fld);
        List < String > allOpts = new list < String > ();
        // Get the object type of the SObject.
        Schema.sObjectType objType = objObject.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();
        
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        }
        system.debug('allOpts ---->' + allOpts);
        allOpts.sort();
        return allOpts;
    }
    
    @AuraEnabled
    public static List<String> getIsApprovalRequiredValues(Id QuoteId)
    {
        //Boolean quoteAlreadyHasPricebook = False;
        List<String> returnList = new List<String>();
        List<Quote> listOfQuote = new List<Quote>();
        listOfQuote = [Select id,Bussiness_Unit__c,Opportunity.Account.Regions__c,OpportunityId from Quote where id=: QuoteId];
        if(!listOfQuote.isEmpty()){
            if(String.isNotBlank(listOfQuote[0].Bussiness_Unit__c) && String.isNotBlank(listOfQuote[0].Opportunity.Account.Regions__c)){
                List<ApprovalRequiredControl__mdt> listOfApprovalRequiredControlMtdt = new List<ApprovalRequiredControl__mdt>();
                listOfApprovalRequiredControlMtdt = [Select id,Business_Unit__c,Region__c,Required__c 
                                                     From ApprovalRequiredControl__mdt
                                                     Where Business_Unit__c =: listOfQuote[0].Bussiness_Unit__c and Region__c =: listOfQuote[0].Opportunity.Account.Regions__c and Required__c = True];
                if(listOfApprovalRequiredControlMtdt.isEmpty()){
                    System.debug('listOfApprovalRequiredControlMtdt: '+listOfApprovalRequiredControlMtdt);
                    returnList.add('Yes');
                    returnList.add('No');
                    //System.debug('returnList1: '+returnList);
                }
                else{
                    returnList.add('Yes');
                    //System.debug('returnList2: '+returnList);
                }
            }
            else{
                returnList.add('Yes');
                returnList.add('No');
                //System.debug('returnList3: '+returnList);
            }
        }
        System.debug('returnList4: '+returnList);
        return returnList;
    }
    
     @AuraEnabled
    public static String updateQuoteLineItem(Id QuoteId, List<LineItemWrapper> lstLineItemWrapper)
    {
        String returnResponse = 'OOOPS! Some error occurred. Please Contact System Admin.';
        Savepoint sp = Database.setSavepoint();
        try{
            if(!lstLineItemWrapper.isEmpty() && QuoteId != Null){
                List<QuoteLineItem> listOfQuoteLineItemToInsert = new List<QuoteLineItem>();
                for(LineItemWrapper wrapper: lstLineItemWrapper){
                    //For each selected line item create a quote line item record under the parent quote record
                    QuoteLineItem qtLineItem = new QuoteLineItem();
                    qtLineItem.Id = wrapper.objPBE.Id;
                    //qtLineItem.QuoteId = QuoteId;
                    qtLineItem.unitPrice = wrapper.unitPrice;
                    qtLineItem.Volume__c = wrapper.volume;
                    qtLineItem.Unit_Of_Measure__c = wrapper.unitOfMeasure;
                    qtLineItem.Approval_Required__c = wrapper.isPLMApprovalRequired;
                    qtLineItem.Is_File_Uploaded__c = wrapper.isFileUploaded;
                    
                    listOfQuoteLineItemToInsert.add(qtLineItem);
                }
                if(!listOfQuoteLineItemToInsert.isEmpty()){
                    System.debug('listOfQuoteLineItemToInsert: '+listOfQuoteLineItemToInsert);
                    update listOfQuoteLineItemToInsert;
                    returnResponse = 'SUCCESS';
                }
            }
        }
        catch(Exception e){
            System.debug('Exception Message: '+e.getMessage());
            System.debug('Exception StacktraceSTring: '+e.getStackTraceString());
            returnresponse = 'OOOPS! Some error occurred. Please Contact System Admin. SYSTEM ADMIN EMAIL' +e.getMessage();
            //returnresponse ='Divided by zero. Error';
            Database.rollback(sp);
        }
        System.debug('returnResponse: '+returnResponse);
        return returnResponse;
    }
}