src/objects/Account_Plan_Overview_Component__mdt.object
<CustomObject>
    <fields>
        <fullName>ApexClass__c</fullName>
        <label>ApexClass</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Name__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                    <label>Individual</label>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Plan Overview Component</label>
    <pluralLabel>Account Plan Overview Components</pluralLabel>
</CustomObject>

src/classes/KAM_AccountPlanOverviewCntl.cls
public with sharing class KAM_AccountPlanOverviewCntl {

    @AuraEnabled(cacheable=true)
    public static string getAccountPlanSections(String planType){
        try {
            return JSON.serialize([SELECT Id, DeveloperName, Title__c, Order__c, ApexClass__c, Component_Name__c, Is_Active__c, Type__c	 
            FROM Account_Plan_Overview_Component__mdt 
            WHERE Is_Active__c = true AND Type__c =: planType
            ORDER BY Order__c
            LIMIT :(Limits.getLimitQueryRows() - Limits.getQueryRows()) ]);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static string getDetails (String overViewMetadata, String data){
        try {
            Account_Plan_Overview_Component__mdt overViewMetaObj = (Account_Plan_Overview_Component__mdt) JSON.deserialize (overViewMetadata, Account_Plan_Overview_Component__mdt.class);
            Type handlerType = Type.forName(overViewMetaObj.ApexClass__c);
            KAM_AccountPlan accountPlanOverViewInstance = (KAM_AccountPlan) handlerType.newInstance();
            return accountPlanOverViewInstance.getDetails(data);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}