src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(Owner.UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;, 
IF( CONTAINS(Owner.UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;, &apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Plans__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <label>BU Identifier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plans Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Engagement_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Engagement Plans</relationshipLabel>
        <relationshipName>Engagement_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Engagement Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Engagement Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Engagement_Plan_Line__c.object
<CustomObject>
    <fields>
        <fullName>Engagement_Plan__c</fullName>
        <label>Engagement Plan</label>
        <referenceTo>Engagement_Plan__c</referenceTo>
        <relationshipLabel>Engagement Plan Lines</relationshipLabel>
        <relationshipName>Engagement_Plan_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type_of_Engagement__c</fullName>
        <label>Type of Engagement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_Engagement</valueSetName>
        </valueSet>
    </fields>
    <label>Engagement Plan Line</label>
    <nameField>
        <displayFormat>EPN-{0000000}</displayFormat>
        <label>Engagement Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Plan Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Frequency_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value_Type__c</fullName>
        <label>Value Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                    <default>true</default>
                    <label>Default</label>
                </value>
                <value>
                    <fullName>User Input</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Frequency Mapping</label>
    <pluralLabel>Frequency Mappings</pluralLabel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;,
IF( CONTAINS(UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;,
IF( CONTAINS(UserRole.Name, &apos;Spice&apos;) , &apos;Spice&apos;,
IF( CONTAINS(UserRole.Name, &apos;Edible_Nuts&apos;) , &apos;Edible_Nuts&apos;, &apos;&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Approval_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Request for edit</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Type_of_Engagement.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>C Level Engagement</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial (Sales &amp; Pricing)</fullName>
    </customValue>
    <customValue>
        <fullName>Finance (Structures &amp; Payments)</fullName>
    </customValue>
    <customValue>
        <fullName>Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>Risk (Solutions)</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;D (Market View Exchange)</fullName>
    </customValue>
    <customValue>
        <fullName>Sales &amp; Ops Planning/Review</fullName>
    </customValue>
    <customValue>
        <fullName>Sustainability</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Type of Engagement</masterLabel>
</GlobalValueSet>

src/globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

src/classes/KAM_EngagementPlanCntl.cls
public without sharing class KAM_EngagementPlanCntl implements KAM_AccountPlan{
    
    public String getDetails (String data) {
        Map<String, Object> requestMap = (Map<String, Object>) JSON.deserializeUntyped(data);
        if (requestMap.containsKey ('accountPlan')) {
            return JSON.serialize(getEngagementPlans ((Account_Plans__c) JSON.deserialize(JSON.serialize(requestMap.get ('accountPlan')), Account_Plans__c.class) ));
        }
        return null;
    }
    
    public static List<Engagement_Plan__c> getEngagementPlans (Account_Plans__c accountPlan) {
        return EngagementPlanSelector.getEngangementPlansByAccountId (
            accountPlan.Account__c, 
            accountPlan.BU_Identifier__c,
            accountPlan.StartDate__c,
            accountPlan.EndDate__c
        );
    }
    
    @AuraEnabled (cacheable=true)
    public static List<KAM_Util.PicklistEntry> getEngangementPickListValuesByField (String objectName, String fieldName, Boolean discardInactive, Boolean shouldIncludeNone){
        try {
            return KAM_Util.getPickListValues(objectName, fieldName, discardInactive, shouldIncludeNone);
            // return KAM_Util.getPickListValues('Engagement_Plan__c', 'Type_of_engagement__c', true, false);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled (cacheable=true)
    public static List<Frequency_Mapping__mdt> getActiveFrequencyMapping () {
        return [SELECT Id, DeveloperName, MasterLabel, Value__c, Value_Type__c 
                FROM Frequency_Mapping__mdt
                WHERE Is_Active__c = true
                LIMIT :(Limits.getLimitQueryRows() - Limits.getQueryRows()) ];
    }
    
    @AuraEnabled
    public static Boolean isLocked(String recordId){
        return Approval.isLocked(recordId);
    }
    
    @AuraEnabled
    public static string refreshEngagementPlan(Account_Plans__c accountPlan){
        try {
            return JSON.serialize(getEngagementPlans (accountPlan) );
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static String riseRequestForEngagementPlanEdit (String engagementPlanStr) {
        Savepoint sp = Database.setSavepoint ();
        Map<String, Object> resultMap = new Map<String, Object> ();
        try {
            Engagement_Plan__c engagementPlan = (Engagement_Plan__c) JSON.deserialize (engagementPlanStr, Engagement_Plan__c.class);
            
            if (isLocked (engagementPlan.Id)) {
                resultMap.put('success', false);
                resultMap.put('message', Label.KAM_Plan_Approval_Waiting_Message);
                
                return JSON.serialize(resultMap);
            }
            
            engagementPlan.Approval_Status__c = EngagementPlanConstants.APPROVAL_STATUS_REQUEST_FOR_EDIT;
            
            update engagementPlan;
            resultMap.put('engagementPlan', EngagementPlanSelector.getEngangementPlansBytId(engagementPlan.Id)[0]);
            
            resultMap.put('success', true);
        } catch (DmlException ex) {
            Database.rollback(sp);
            resultMap.put('success', false);
            resultMap.put('message', ex.getMessage());
            if (ex.getMessage().containsIgnoreCase('This approval request requires the next approver to be determined by the Manager field')) {
                resultMap.put('message', Label.KAM_Approval_Request_Manager_Unassigned_Error_Message);
            }
        }
        catch (Exception ex) {
            Database.rollback(sp);
            resultMap.put('success', false);
            resultMap.put('message', ex.getMessage());
        }
        return JSON.serialize(resultMap);
    }
    
    @AuraEnabled
    public static String createEngagementPlans (String engagementPlanLineStr, String engagementPlanStr)
    {
        List<Engagement_Plan_Line__c> engagementLines = (List<Engagement_Plan_Line__c>) JSON.deserialize (engagementPlanLineStr, List<Engagement_Plan_Line__c>.class);
        Engagement_Plan__c engagementPlan = (Engagement_Plan__c) JSON.deserialize (engagementPlanStr, Engagement_Plan__c.class);
        Map<String, Object> resultMap = new Map<String, Object> ();
        
        Savepoint sp = Database.setSavepoint ();
        try {
            if (engagementPlan.Id == null) {
                insert engagementPlan;
            } else {
                update engagementPlan;
            }
            
            for (Engagement_Plan_Line__c line : engagementLines) {
                if (String.isBlank(line.Engagement_Plan__c)) {
                    line.Engagement_Plan__c = engagementPlan.Id;
                }
            }
            
            upsert engagementLines;
            
            resultMap.put('engagementLines', engagementLines);
            resultMap.put('engagementPlan', engagementPlan);
            
            resultMap.put('success', true);
        } catch (Exception ex) {
            Database.rollback(sp);
            resultMap.put('success', false);
            resultMap.put('message', ex.getMessage());
        }
        return JSON.serialize(resultMap);
    }
    /**
* Reference : https://github.com/pozil/sfdc-ui-lookup-lwc/
*/
    @AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> getRecentlyViewed() {
        List<LookupSearchResult> results = new List<LookupSearchResult>();
        // Get recently viewed records of type Account or Opportunity
        List<RecentlyViewed> recentRecords = [
            SELECT Id, Name, Type
            FROM RecentlyViewed
            WHERE Type = 'User'
            ORDER BY LastViewedDate DESC
            LIMIT :Integer.valueOf (Label.KAM_Lookup_Min_Record_Limit)
        ];
        // Convert recent records into LookupSearchResult
        for (RecentlyViewed recentRecord : recentRecords) {
            if (recentRecord.Type == 'User') {
                results.add(
                    new LookupSearchResult(
                        recentRecord.Id,
                        'User',
                        'standard:user',
                        recentRecord.Name,
                        'User • ' + recentRecord.Name
                    )
                );
            }
        }
        return results;
    }
    
    /**
* Reference : https://github.com/pozil/sfdc-ui-lookup-lwc/
*/
    private final static Integer MAX_RESULTS = 5;
    
    @AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> search(String searchTerm, List<String> selectedIds) {
        // Prepare query paramters
        searchTerm += '*';
        
        // Execute search query
        List<List<SObject>> searchResults = [
            FIND :searchTerm
            IN ALL FIELDS
            RETURNING
            User(Id, Name, Email WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS
        ];
        
        // Prepare results
        List<LookupSearchResult> results = new List<LookupSearchResult>();
        
        // Extract users & convert them into LookupSearchResult
        String userIcon = 'standard:user';
        User[] users = (List<User>) searchResults[0];
        for (User eachUser : users) {
            String subtitle = eachUser.Email == null ? 'User' : 'User • ' + eachUser.Email;
            results.add(new LookupSearchResult(eachUser.Id, 'User', userIcon, eachUser.Name, subtitle));
        }
        
        // Optionnaly sort all results on title
        results.sort();
        
        return results;
    }
    
    
    @AuraEnabled
    public static List<Engagement_Plan__c> getEngagementPlansByAccountId(Id AccountId) {
        User u=[Select Id,Name,Email,BU_Identifier__c,UserRole.Name from User where Id=:userinfo.getuserId()];
        Teams__c currentUserTeam = KAM_EngagementPlanCntl.getcurrentUserAccountTeam(AccountId);
        //String BU=u.BU_Identifier__c;
        string BU = currentUserTeam.Business_Unit__c;
        if(BU==Null)
        {
            return NULL;
        } 
        else
        {   
        List<Engagement_Plan__c> engList=[Select Id,Name,Account__c,Business_Unit__c,
                                          Start_date__c,End_Date__c,Year__c	 From Engagement_Plan__c 
                                          where Account__c=:AccountId AND Business_Unit__c=:BU];
        
        return engList;
        
        }
    }
    @AuraEnabled
    public static String getEngagementPlansById(Id engagementId) {
        
        return json.serialize(EngagementPlanSelector.getEngangementPlansBytId(engagementId));       
        
    }
    
    @AuraEnabled
    public static Engagement_Plan__c createEngagementPlan(String selYear,String accountId,String businessUnit) {
        System.debug('year'+selYear);
        //User u=[Select Id,Name,Email,BU_Identifier__c,UserRole.Name from User where Id=:userinfo.getuserId()];
        Engagement_Plan__c engPlan = new Engagement_Plan__c();
        //engPlan.Name=u.BU_Identifier__c+'-'+selYear;
        engPlan.Name = businessUnit+'-'+selYear;
        engPlan.Account__c = accountId;
        //engPlan.Business_Unit__c = u.BU_Identifier__c;
        engPlan.Business_Unit__c = businessUnit;
        engPlan.Year__c=selYear;
        engPlan.Start_date__c = date.parse('01/01/'+selYear);
        engPlan.End_Date__c = date.parse('31/12/'+selYear);
        try{   
            System.debug('EngagementPlan'+engPlan);
            insert engPlan;
            return engPlan;
        }
        catch (DmlException e) {
            throw new AuraHandledException(e.getDmlMessage(0));
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        
    }
    @AuraEnabled
    public static User getUserBU(){
        User u=[Select Id,Name,Email,BU_Identifier__c,UserRole.Name from User where Id=:userinfo.getuserId()];
        return u;
    }
    @AuraEnabled
    public static List<Teams__c> getAccountTeams(Id accountId){
        try {
            if (String.isBlank(accountId)) {
                return null;
            }
            User u=[Select Id,Name,Email,BU_Identifier__c from User where Id=:userinfo.getuserId()];
            List<Teams__c> listOfTeams = new List<Teams__c>();
            for(Teams__c acctTeams:[Select id,Name,Account__c,Is_Primary__c,User__c from Teams__c where Account__c=:accountId AND Is_Primary__c=True]){
                if(acctTeams.User__c == u.Id){
                    listOfTeams.add(acctTeams);
                }
            }
            return listOfTeams;
        }catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static Teams__c getcurrentUserAccountTeam(Id accountId){
        Teams__c currentUserAccountTeam = new Teams__c();
        List<Teams__c> listOfTeams = new List<Teams__c>();
        listOfTeams = [select Id,Business_Unit__c,User__c,Account__c from Teams__c where User__c =: userinfo.getuserId() and Account__c =: accountId limit 1];
        if(!listOfTeams.isEmpty()){
            currentUserAccountTeam = listOfTeams[0];
        }
        return currentUserAccountTeam;
    }
}