src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Key Account</fullName>
                </value>
                <value>
                    <fullName>Global Account</fullName>
                </value>
                <value>
                    <fullName>Regional Key Account</fullName>
                </value>
                <value>
                    <fullName>Regional Account</fullName>
                </value>
                <value>
                    <fullName>Local Key Account</fullName>
                </value>
                <value>
                    <fullName>Local Account</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Interactions__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/InteractionSelectorTest.cls
@isTest
public class InteractionSelectorTest {
    
    @testSetup
    static void method()
    {
        Account acc=new Account();
        acc.Name='DemoAccount';
        acc.Account_Type__c='Distributor';
        acc.BillingCountry='India';
        acc.BillingStreet='Pune-Mumbai road';
        insert acc;
        
        Interactions__c i=new Interactions__c();
        i.Account__c=acc.Id;
        i.Business_Unit__c='Cocoa';
        insert i;
        
        
    }

	@isTest 
    static void test_getInteractionsByIds () {
        Interactions__c i=[Select Id,Business_Unit__c from Interactions__c where createdDate=Today Limit 1];
        List<Interactions__c> interactions = InteractionSelector.getInteractionsByIds (new set<Id> {null, i.Id});
        System.assert(interactions.size() > 0, 'No interactions found');
        System.assertEquals(i.Business_Unit__c, interactions[0].Business_Unit__c, 'Mismatch in BU');
    }    
    @isTest
    static void test_getInteractionsByAccountIds()
    {
        Account acc=[Select Id,Name from Account where createdDate=Today Limit 1];
        System.assert(acc!=null, 'Containing null values');
        Interactions__c i=[Select Id,Business_Unit__c from Interactions__c where createdDate=Today Limit 1];
        Set<Id> ids=new Set<Id>();	
        ids.add(acc.id);
        ids.add(null);
        Set<String> bu=new Set<String>();
        bu.add(i.Business_Unit__c);
        System.debug('ids==========>'+ids);
        System.debug('bu==========>'+bu);
        InteractionSelector.getInteractionsByAccountIds (ids,bu);
    }
    
}