src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Key Account</fullName>
                </value>
                <value>
                    <fullName>Global Account</fullName>
                </value>
                <value>
                    <fullName>Regional Key Account</fullName>
                </value>
                <value>
                    <fullName>Regional Account</fullName>
                </value>
                <value>
                    <fullName>Local Key Account</fullName>
                </value>
                <value>
                    <fullName>Local Account</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Engagement_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Engagement Plans</relationshipLabel>
        <relationshipName>Engagement_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Engagement_Plan_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Engagement Plan Locked?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <label>Engagement Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Engagement Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Approval_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Request for edit</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/LookupSearchResultTest.cls
@isTest
public class LookupSearchResultTest extends LookupSearchResult {
    
    @testSetUp
    static void createData (){
        
        Account acc=new Account();
        acc.Name='DemoAccount';
        acc.Account_Type__c='Distributor';
        acc.BillingCountry='India';
        acc.BillingStreet='Pune-Mumbai road';
        insert acc;
        
        Engagement_Plan__c engPlan=new Engagement_Plan__c();
        engPlan.Account__c=acc.Id;
        engPlan.Is_Engagement_Plan_Locked__c=true;
        engPlan.End_Date__c=system.today().addDays (365);
        engPlan.Start_date__c=system.today();
        engPlan.Approval_Status__c='Pending';
        engPlan.Business_Unit__c='Cocoa';
        insert engPlan;
        
    }
    
    @isTest
    static void testCompareToMethod () {
        LookupSearchResult r1 = getSearchResult(null);
        LookupSearchResult r2 = getSearchResult(null);
        Integer compareResult = r1.compareTo(r2);
        System.assertEquals(0, compareResult);
        
        r1 = getSearchResult(null);
        r2 = getSearchResult('a');
        compareResult = r1.compareTo(r2);
        System.assertEquals(1, compareResult);
        
        r1 = getSearchResult('a');
        r2 = getSearchResult(null);
        compareResult = r1.compareTo(r2);
        System.assertEquals(-1, compareResult);

        r1 = getSearchResult('a');
        r2 = getSearchResult('b');
        compareResult = r1.compareTo(r2);
        System.assertEquals(-1, compareResult); 
    }
    private static LookupSearchResult getSearchResult(String title) {
        return new LookupSearchResult(null, null, null, title, null);
    }
    
    @isTest
    static void lookupSearchResultTest()
    {
        Account acc=[select Id, Name, BillingCountry  from Account where Name = 'DemoAccount' LIMIT 1];
        System.assert(acc != null, 'Unable to find the account');
        Id acc_id=acc.Id;
        String sobjectType='Account';
        String icon='standard:account';
        String title=acc.Name;
        String subTitle=acc.BillingCountry;
        
        LookupSearchResult lookResult=new LookupSearchResult(acc_id,sobjectType,icon,title,subTitle);
        
        System.assertEquals(acc.Id, lookResult.getId());
        System.assertEquals(sobjectType, lookResult.getSObjectType());
        System.assertEquals(icon, lookResult.getIcon());
        System.assertEquals(acc.Name, lookResult.getTitle());
        System.assertEquals(acc.BillingCountry, lookResult.getSubtitle());
        
        lookResult = new LookupSearchResult (); 
        
    }
    
}