src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(Owner.UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;, 
IF( CONTAINS(Owner.UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;, &apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Plans__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <label>BU Identifier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <formula>Account__r.Customer_Group__c</formula>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plans Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/KAM_AccountTeamsCntlTest.cls
@isTest
public class KAM_AccountTeamsCntlTest {
 @testSetUp
    static void createData () {
         Account acc = new Account();
        acc.Name = 'Test';
        acc.BillingCity = 'Testcity';
        acc.BillingCountry = 'india';
        acc.Customer_Group__c='Test Group';
        insert acc;
        
         Account acc1 = new Account();
        acc1.Name = 'Test1';
        acc1.BillingCity = 'Testcity';
        acc1.BillingCountry = 'india';
        acc1.Customer_Group__c='Test Group';
        insert acc1;
         
         Account_Plans__c app = new Account_Plans__c();
        app.Name = 'test';
        app.Account__c = acc.id;
        insert app;
        
        Account_Plans__c app1 = new Account_Plans__c();
        app1.Name = 'test1';
        app1.Account__c = acc1.id;
         app1.Type__c='group';
        insert app1;
        
        Account_Plans__c app_group = new Account_Plans__c();
        app_group.Name = 'testGrp';
        app_group.Account__c = acc.id;
        app_group.Type__c='group';
        app_group.BU_Identifier__c='Cocoa';
        insert app_group; 
        
        Teams__c team=new Teams__c();
        team.Account__c= acc.id;
        team.Is_Primary__c=true;
        team.Business_Unit__c = 'All';
       insert team;
         
          }
    @isTest 
    static void testGetDetails () {
        Account acc=[select id from account where name='Test'];
        
         Account_Plans__c app=[select id,Account__c,name,BU_Identifier__c,Type__c,Customer_Group__c from Account_Plans__c where name='testGrp'];
        string result= KAM_AccountTeamsCntl.getDetails( JSON.serialize(new Map<String, Object> {'accountId' => acc.Id}));
         System.assert(result != null , 'Unable to get details');
         KAM_AccountTeamsCntl.getDetails( JSON.serialize(new Map<String, Object> {'accountId' => null}));
         string result1= KAM_AccountTeamsCntl.getDetails( JSON.serialize(app));
        
    }
     @isTest 
    static void TestgetGroupDetails () {
        Account acc=[select id from account where name='Test'];
         Account_Plans__c app1=[select id,Account__c,name,BU_Identifier__c,Type__c,Customer_Group__c from Account_Plans__c where name='test'];
        Account_Plans__c app=[select id,Account__c,name,BU_Identifier__c,Type__c,Customer_Group__c from Account_Plans__c where name='testGrp'];
        string result= KAM_AccountTeamsCntl.getGroupDetails( JSON.serialize(new Map<String, Object> {'accountPlan' =>app}));
         System.assert(result != null , 'Unable to get details');
         string result1= KAM_AccountTeamsCntl.getGroupDetails( JSON.serialize(acc));
        KAM_AccountTeamsCntl.getGroupDetails(  JSON.serialize(new Map<String, Object> {'accountPlan' =>app1}));
        
        
    }
    @isTest 
    static void TestgetAccountTeamsForGroup()
    {
      Account acc=[select id from account where name='Test'];
      List<object> result= KAM_AccountTeamsCntl.getAccountTeamsForGroup(acc.Id);
         System.assert(result != null && !result.isEmpty () , 'Unable to get details');
      KAM_AccountTeamsCntl.getAccountTeamsForGroup(null);  
    }
}