src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <label>Inco Terms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CFR</fullName>
                    <label>CFR - Costs and freight</label>
                </value>
                <value>
                    <fullName>CIF</fullName>
                    <label>CIF - Costs, insurance &amp; freight</label>
                </value>
                <value>
                    <fullName>CIP</fullName>
                    <label>CIP - Carriage and insurance paid</label>
                </value>
                <value>
                    <fullName>CPT</fullName>
                    <label>CPT - Carriage paid to</label>
                </value>
                <value>
                    <fullName>DAP</fullName>
                    <label>DAP - Delivered At Place</label>
                </value>
                <value>
                    <fullName>DDP</fullName>
                    <label>DDP - Delivered Duty Paid</label>
                </value>
                <value>
                    <fullName>DPU</fullName>
                    <label>DPU - Delivered At Place Unloaded</label>
                </value>
                <value>
                    <fullName>EXW</fullName>
                    <label>EXW - Ex Works</label>
                </value>
                <value>
                    <fullName>FAS</fullName>
                    <label>FAS - Free Along Sideship</label>
                </value>
                <value>
                    <fullName>FCA</fullName>
                    <label>FCA - Free Carrier</label>
                </value>
                <value>
                    <fullName>FOB</fullName>
                    <label>FOB - Free On Board</label>
                </value>
                <value>
                    <fullName>Instore</fullName>
                </value>
                <value>
                    <fullName>CNF</fullName>
                    <isActive>false</isActive>
                    <label>CNF</label>
                </value>
                <value>
                    <fullName>DAT</fullName>
                    <isActive>false</isActive>
                    <label>DAT</label>
                </value>
                <value>
                    <fullName>DDU</fullName>
                    <isActive>false</isActive>
                    <label>DDU</label>
                </value>
                <value>
                    <fullName>DES</fullName>
                    <isActive>false</isActive>
                    <label>DES</label>
                </value>
                <value>
                    <fullName>FOR</fullName>
                    <isActive>false</isActive>
                    <label>FOR</label>
                </value>
                <value>
                    <fullName>FOT</fullName>
                    <isActive>false</isActive>
                    <label>FOT</label>
                </value>
                <value>
                    <fullName>UN</fullName>
                    <isActive>false</isActive>
                    <label>UN</label>
                </value>
                <value>
                    <fullName>Z05</fullName>
                    <isActive>false</isActive>
                    <label>Z05</label>
                </value>
                <value>
                    <fullName>Z06</fullName>
                    <isActive>false</isActive>
                    <label>Z06</label>
                </value>
                <value>
                    <fullName>Z09</fullName>
                    <isActive>false</isActive>
                    <label>Z09</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <label>Sales Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SG41 - 01 - 03</fullName>
                </value>
                <value>
                    <fullName>SG41 - 02 - 03</fullName>
                </value>
                <value>
                    <fullName>SG41 - 07 - 03</fullName>
                </value>
                <value>
                    <fullName>SG42 - 01 - 03</fullName>
                </value>
                <value>
                    <fullName>SG42 - 02 - 03</fullName>
                </value>
                <value>
                    <fullName>SG42 - 07 - 03</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Sales_Area__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Credit Limit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Distribution Channel</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Division</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Inco Terms</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Org</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Conditions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipping Conditions</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Terms of Payment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To Delete</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Area</label>
    <nameField>
        <displayFormat>SalesArea--{00000}</displayFormat>
        <label>Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SalesAreaTriggerHandler.cls
public class SalesAreaTriggerHandler extends TriggerHandlerBase {
    public override void handleBeforeInsert() {
        Map<Id, Map<String, Sales_Area__c>> newSalesAreaMap = new Map<Id, Map<String, Sales_Area__c>>();
        for(Sales_Area__c obj : (List<Sales_Area__c>)Trigger.new) {
            if(!newSalesAreaMap.containsKey(obj.Account_Name__c)) {
                newSalesAreaMap.put(obj.Account_Name__c, new Map<String, Sales_Area__c>());
            }
            newSalesAreaMap.get(obj.Account_Name__c).put(obj.Sales_Org__c + '_' + obj.Distribution_Channel__c + '_' + obj.Division__c, obj);
        }
        // OlamLogger.logPretty('newSalesAreaMap', newSalesAreaMap);
        
        // Select existing Sales areas for the accounts
        Set<Id> accIds = newSalesAreaMap.keySet();
        Map<Id, Map<String, Sales_Area__c>> existingSalesAreaMap = new Map<Id, Map<String, Sales_Area__c>>();
        for(Sales_Area__c obj : [Select Id, 
                                     Account_Name__r.Id, 
                                     Sales_Org__c, 
                                     Distribution_Channel__c, 
                                     Division__c, 
                                 	 Credit_Limit__c,
                                     Inco_Terms__c,  
                                     Shipping_Conditions__c, 
                                     Terms_of_Payment__c
                                 from Sales_Area__c 
                                 where Account_Name__r.Id in :accIds]) {
            if(!existingSalesAreaMap.containsKey(obj.Account_Name__r.Id)) {
                existingSalesAreaMap.put(obj.Account_Name__r.Id, new Map<String, Sales_Area__c>());
            }
            existingSalesAreaMap.get(obj.Account_Name__r.Id).put(obj.Sales_Org__c + '_' + obj.Distribution_Channel__c + '_' + obj.Division__c, obj);
        }
        // OlamLogger.logPretty('existingSalesAreaMap', existingSalesAreaMap);
        
        // Remove non match
        // Existing: 1 2 3
        // New:      2 3 4
        // Remove 1 here
        // List<Sales_Area__c> toDelete = new List<Sales_Area__c>();
        // for(Id accId : existingSalesAreaMap.keySet()) {
        //      for(String salesArea : existingSalesAreaMap.get(accId).keySet()) {
        //         if(!newSalesAreaMap.get(accId).containsKey(salesArea)) {
        //             toDelete.add(existingSalesAreaMap.get(accId).get(salesArea));
        //         } 
        //     }
        // }
        // if(!toDelete.isEmpty())
        //  delete toDelete;
        
        // Remove the duplicate one from the new list
        // If the value is changed then delete the existing one
        // Existing: 1 2 
        // New:      1 2(Changed) 3
        // Mark new 1 as delete and delete existing 2
        List<Sales_Area__c> toDelete = new List<Sales_Area__c>();
        for(Id accId : existingSalesAreaMap.keySet()) {
            for(String salesArea : existingSalesAreaMap.get(accId).keySet()) {
                if(newSalesAreaMap.get(accId).containsKey(salesArea)) {
                    // OlamLogger.log('!!!!!!!!! Set ' + salesArea + ' to delete');
                    Sales_Area__c existingSA = existingSalesAreaMap.get(accId).get(salesArea);
                    Sales_Area__c newSA = newSalesAreaMap.get(accId).get(salesArea);
                    if(newSA.To_Delete__c == true) {
                        toDelete.add(existingSA);
                    }
                    else if(newSA.Inco_Terms__c == existingSA.Inco_Terms__c && 
                       newSA.Shipping_Conditions__c == existingSA.Shipping_Conditions__c && 
                       newSA.Terms_of_Payment__c == existingSA.Terms_of_Payment__c &&
                       newSA.Credit_Limit__c == existingSA.Credit_Limit__c) {
                           
                        newSA.To_Delete__c = True;
                    }
                    else {
                        toDelete.add(existingSA);
                    }
                } 
            }
        } 
        if(!toDelete.isEmpty())
            delete toDelete;
    }
    
    public override void handleAfterInsert() {
        Set<Id> accIds = new Set<Id>();
        for(Sales_Area__c obj : (List<Sales_Area__c>)Trigger.new) {
            accIds.add(obj.Account_Name__c);
        }
        
        List<Sales_Area__c> toDelete = [Select Id from Sales_Area__c where Account_Name__c in :accIds and To_Delete__c = True];
        if(!toDelete.isEmpty())
            delete toDelete;
    }
    
}