src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Regions__c</fullName>
        <description>To Identify the account region</description>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                    <isActive>false</isActive>
                    <label>Africa</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                    <isActive>false</isActive>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>Europe</fullName>
                    <isActive>false</isActive>
                    <label>Europe</label>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                    <isActive>false</isActive>
                    <label>Latin America</label>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                    <isActive>false</isActive>
                    <label>Middle East</label>
                </value>
                <value>
                    <fullName>North America</fullName>
                    <isActive>false</isActive>
                    <label>North America</label>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                    <isActive>false</isActive>
                    <label>Oceania</label>
                </value>
                <value>
                    <fullName>South America</fullName>
                    <isActive>false</isActive>
                    <label>South America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ofi_Region__c</fullName>
        <label>ofi Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ofi_Sub_Region_2__c</fullName>
        <label>ofi Sub Region 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia and New Zealand</fullName>
                </value>
                <value>
                    <fullName>Caribbean</fullName>
                </value>
                <value>
                    <fullName>Central America</fullName>
                </value>
                <value>
                    <fullName>Central Asia</fullName>
                </value>
                <value>
                    <fullName>Channel Islands</fullName>
                </value>
                <value>
                    <fullName>East Africa</fullName>
                </value>
                <value>
                    <fullName>East Asia</fullName>
                </value>
                <value>
                    <fullName>East Europe</fullName>
                </value>
                <value>
                    <fullName>Melanesia</fullName>
                </value>
                <value>
                    <fullName>Micronesia</fullName>
                </value>
                <value>
                    <fullName>Middle Africa</fullName>
                </value>
                <value>
                    <fullName>North Africa</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>North Europe</fullName>
                </value>
                <value>
                    <fullName>Polynesia</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                </value>
                <value>
                    <fullName>South America</fullName>
                </value>
                <value>
                    <fullName>South Asia</fullName>
                </value>
                <value>
                    <fullName>South-East Asia</fullName>
                </value>
                <value>
                    <fullName>South Europe</fullName>
                </value>
                <value>
                    <fullName>West Africa</fullName>
                </value>
                <value>
                    <fullName>West Asia</fullName>
                </value>
                <value>
                    <fullName>West Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ofi_Sub_Region__c</fullName>
        <label>ofi Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Asia</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Region_Update__mdt.object
<CustomObject>
    <fields>
        <fullName>ofi_Region__c</fullName>
        <label>ofi Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                    <default>true</default>
                    <label>APAC</label>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ofi_Sub_Region_2__c</fullName>
        <label>ofi Sub Region 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>South Asia</fullName>
                    <default>true</default>
                    <label>South Asia</label>
                </value>
                <value>
                    <fullName>North Europe</fullName>
                </value>
                <value>
                    <fullName>South Europe</fullName>
                </value>
                <value>
                    <fullName>North Africa</fullName>
                </value>
                <value>
                    <fullName>Polynesia</fullName>
                </value>
                <value>
                    <fullName>Middle Africa</fullName>
                </value>
                <value>
                    <fullName>Caribbean</fullName>
                </value>
                <value>
                    <fullName>South America</fullName>
                </value>
                <value>
                    <fullName>West Asia</fullName>
                </value>
                <value>
                    <fullName>Australia and New Zealand</fullName>
                </value>
                <value>
                    <fullName>West Europe</fullName>
                </value>
                <value>
                    <fullName>East Europe</fullName>
                </value>
                <value>
                    <fullName>Central America</fullName>
                </value>
                <value>
                    <fullName>West Africa</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                </value>
                <value>
                    <fullName>East Africa</fullName>
                </value>
                <value>
                    <fullName>South-East Asia</fullName>
                </value>
                <value>
                    <fullName>East Asia</fullName>
                </value>
                <value>
                    <fullName>Melanesia</fullName>
                </value>
                <value>
                    <fullName>Micronesia</fullName>
                </value>
                <value>
                    <fullName>Channel Islands</fullName>
                </value>
                <value>
                    <fullName>Central Asia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ofi_Sub_Region__c</fullName>
        <label>ofi Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Asia</fullName>
                    <default>true</default>
                    <label>Asia</label>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Region Update</label>
    <pluralLabel>Region_Updates</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Regions__c</fullName>
        <label>Regions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AccountRegionUpdate.cls
public class AccountRegionUpdate 
{
    Public static void RegionUpdate(list<account> ListofNewAccounts)
    { 
        map<string, Region_Update__mdt> mapofiregion = Region_Update__mdt.getAll();
        system.debug('mapofiregion'+ mapofiregion);    
        for(account tempacc: ListofNewAccounts) 
        {
            
            if (tempacc.BillingCountryCode != Null && tempacc.BillingCountryCode != '' )
                
            { system.debug('mapofiregion'+ mapofiregion);
             system.debug('BillingCountry'+ tempacc.BillingCountryCode);
             system.debug('Key'+ mapofiregion.containskey(tempacc.BillingCountryCode));
             if(mapofiregion.containskey(tempacc.BillingCountryCode))
             {
                 tempacc.Regions__c = mapofiregion.get(tempacc.BillingCountryCode).ofi_Region__c;//Pramodh added for temp, untill production data updated
                 //tempacc.ofi_Region__c = mapofiregion.get(tempacc.BillingCountryCode).ofi_Region__c;
                 tempacc.ofi_Sub_Region__c = mapofiregion.get(tempacc.BillingCountryCode).ofi_Sub_Region__c;
                 tempacc.ofi_Sub_Region_2__c = mapofiregion.get(tempacc.BillingCountryCode).ofi_Sub_Region_2__c;
                 //system.debug('mapofiregion'+ mapofiregion);
                 //system.debug('BillingCountry'+ tempacc.BillingCountryCode);
             }
            }
        }
    }
    
    //Added by Bharatesh - Replacing Ashwini's fnctionality in AccountTriggerHanlder.beforeInsert
    public static void setOwnerToIntegrationUser(List<Account> listOfNewAccounts){
        //AccountTriggerHelper.validatePostalCode(listOfNewAccounts);
        //Reassigning Account Owner as "Intergration user"
        ID customLabelValue = System.Label.Integration_user_id;  //fetching custom label id of "Intergration user"
        for(Account tempAccount : listOfNewAccounts)
        {
            tempAccount.OwnerId = customLabelValue;  //Custom label having id of "Intergration user"  is assigned here
        }
        
    }
}