src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Pardot</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Account Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>DAIRY</fullName>
                </value>
                <value>
                    <fullName>DAIRY ALTERNATIVES</fullName>
                </value>
                <value>
                    <fullName>FROZEN DAIRY</fullName>
                </value>
                <value>
                    <fullName>FILLINGS (WB)</fullName>
                </value>
                <value>
                    <fullName>SYRUPS (WB)</fullName>
                </value>
                <value>
                    <fullName>BEVERAGES</fullName>
                </value>
                <value>
                    <fullName>CHOCOLATE (LIKE)</fullName>
                </value>
                <value>
                    <fullName>CONFECTIONERY MIXES</fullName>
                </value>
                <value>
                    <fullName>FILLINGS (FB)</fullName>
                </value>
                <value>
                    <fullName>SPREADS (FB)</fullName>
                </value>
                <value>
                    <fullName>SYRUPS (FB)</fullName>
                </value>
                <value>
                    <fullName>DECORATION</fullName>
                </value>
                <value>
                    <fullName>DAIRY MIXES</fullName>
                </value>
                <value>
                    <fullName>INSTANT MIXES</fullName>
                </value>
                <value>
                    <fullName>BAKERY MIXES</fullName>
                </value>
                <value>
                    <fullName>REPACKING</fullName>
                </value>
                <value>
                    <fullName>BAKERY</fullName>
                </value>
                <value>
                    <fullName>CEREALS</fullName>
                </value>
                <value>
                    <fullName>OTHER APPLICATIONS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Configuration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Bussiness_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                    <label>Spices</label>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver_Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Approver Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Configuration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Application_Pardot.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Confectionery</fullName>
    </customValue>
    <customValue>
        <fullName>Drinks</fullName>
    </customValue>
    <customValue>
        <fullName>Ice Creams</fullName>
    </customValue>
    <customValue>
        <fullName>Desserts</fullName>
    </customValue>
    <customValue>
        <fullName>Savoury</fullName>
    </customValue>
    <customValue>
        <fullName>Bevarage</fullName>
    </customValue>
    <customValue>
        <fullName>Frozen Desserts</fullName>
    </customValue>
    <masterLabel>application</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/QuoteLineItemTriggerTest.cls
@isTest
public class QuoteLineItemTriggerTest {

    @testSetup
    public static void setupData()
    {
        //Create an Account
        //Account acc = TestData_Factory.createAccount(true);
        Account acc = new Account();
        acc.name='TestForQuote1';
        acc.BillingCountry = 'India';
        acc.BillingStreet ='Test';
        //acc.Segment__c = 'Agent/ Distributor';
        insert acc;
         Contact con =new Contact();
        con.AccountId=acc.Id;
        con.LastName='Ben';
        con.Email='abc@gmail.com';
        insert con;
        
        
        //Get the pricebookId
        Id pricebookId = Test.getStandardPricebookId();
        
      /*  //Create an Opportunity
       // Opportunity opp = TestData_Factory.createOpportunity(acc, pricebookId, true);
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Name = 'Test Opp for QuoteLine';
        opp.StageName = 'Briefing';
        opp.RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId();
        opp.CloseDate = System.today();
       
        opp.Application__c = 'Agent/ Distributor';
        opp.Pricebook2Id = pricebookId;
        opp.CurrencyIsoCode = 'USD';
        insert opp;
        //Create a Quote
       // Quote quote = TestData_Factory.createQuote(acc, opp, true);
         Quote quote=new  Quote(OpportunityId=opp.id,Bussiness_Unit__c=opp.Business_Unit__c,name='Testing QuoteLine',Status='Draft');
         insert quote;
        //Create a Product
        Product2 prod = TestData_Factory.createProduct('12-Spices', 'Tropical', 'Pepper', 'Black Pepper', true);
        
        //Create a PricebookEntry
        //PricebookEntry pbe = TestData_Factory.createPricebookEntry(pricebookId, prod, true);
        
        PricebookEntry pbe = [Select Id from PricebookEntry where Product2Id =: prod.Id and CurrencyIsoCode =: opp.CurrencyIsoCode limit 1];
            */
        Product2 prod = new Product2(
            Name = 'Beans Cocoa',
            IsActive = true
        );
        insert prod;
        // Id pricebookId = Test.getStandardPricebookId();
        System.debug('PBI '+pricebookId);
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            CurrencyIsoCode = 'USD',
            UnitPrice = 0,
            IsActive = true
        );
        insert pbe;
        Opportunity opp = new Opportunity();
        opp.AccountId=acc.Id;
        opp.Name='Gain Test Opportunity For QuoteLine';
        //opp.ContactId=con.Id;
        opp.StageName='Offering';
        opp.CloseDate=System.today()+1;
        opp.Type='New Business';
        opp.Business_Unit__c='Spice';
        opp.Pricebook2Id=pricebookId;
        //opp.CurrencyIsoCode='USD - U.S. Dollar';
        insert opp;
        OpportunityLineItem oli=new OpportunityLineItem();
        oli.OpportunityId=opp.Id;
        oli.UnitPrice=44;
        oli.PricebookEntryId=pbe.Id;
        insert oli;
        Quote quote=new Quote();
        quote.OpportunityId=opp.Id;
        quote.Name=opp.Name;
        quote.Bussiness_Unit__c=opp.Business_Unit__c;
        quote.ExpirationDate=opp.CloseDate;
        quote.Status='Draft';
        insert quote;
        QuoteLineItem qli=new QuoteLineItem();
        qli.QuoteId=quote.Id;
        //qli.Product2Id=p.Id;
        qli.PricebookEntryId=pbe.Id;
        qli.UnitPrice = 0;
        qli.Volume__c=3;
        qli.Quantity=5;
        qli.Approver_Comment__c = 'Test';
        qli.Product_Configuration__c='[{"varient_character_mapping":"ZVAR_MULTI_THRU","uom":"%","quantitative":"Yes","qualitative":"","olam_range":"0,000 - 50,000","mic":"-U100","description":"% THRU US #100","customer_range":"0,000 - 50,000"},{"varient_character_mapping":"ZVAR2_MULTI_THRU","uom":"%","quantitative":"No","qualitative":"","olam_range":"0,000 - 80,000","mic":"-U200","description":"% THRU UK #200","customer_range":"0,000 - 80,000"}]';
        insert qli;
        
        //Create a QuoteLineItem
        
        QuoteLineItem qLI1 = TestData_Factory.createQuoteLineItemNew(pbe, prod, quote,'N/A', true);
        QuoteLineItem qLI2 = TestData_Factory.createQuoteLineItemNew(pbe, prod, quote,'Not Started', true);
       
        QuoteLineItem qLI3 = TestData_Factory.createQuoteLineItemNew(pbe, prod, quote, 'In Progress', true);
        qLI3.Approval_Status__c = 'In Progress';
        QuoteLineItem qLI4 = TestData_Factory.createQuoteLineItemNew(pbe, prod, quote,'Accepted', true);
        qLI4.Approval_Status__c = 'Accepted';
        QuoteLineItem qLI5 = TestData_Factory.createQuoteLineItemNew(pbe, prod, quote,'Rejected', true);
        qLI5.Approval_Status__c = 'Rejected';
        QuoteLineItem qLI6 = TestData_Factory.createQuoteLineItemNew(pbe, prod, quote,'Recalled', true);
        qLI6.Approval_Status__c = 'Recalled';
        
    }
    
    @isTest
    public static void checkValidation()
    {
        Test.startTest();
        List<QuoteLineItem> QuoLIList = [Select id,Product2.Name,quoteid,Approval_Status__c,Product_Configuration__c from QuoteLineItem];
         
        QuoLIList[0].Product_Configuration__c='[{"olam_material_code":"100000039072","customer_sap_id":"1234","customer_material_code":"","configurations":[{"varient_character_mapping":"","uom":"%","quantitative":"Yes","qualitative":"","olam_range":"0,000 - 500,000","mic":"-U100","indicator":"Product","description":"MOLD COUNT PER GRAM","customer_range":"0,000 - 500,000"},{"varient_character_mapping":"MOIST","uom":"","quantitative":"Yes","qualitative":"","olam_range":"0,00 - 500,00","mic":"","indicator":"Product","description":"Moist 6","customer_range":"0,00 - 500,00"}]}]';
        update QuoLIList[0];
        delete QuoLIList[1];
        
        Test.stopTest();
    }
    @isTest	
    public static void UpdateQuoteStatusTest()	
    {	
        Quote q = [Select id,name from Quote Limit 1];	
        /*QuoteLineItem qLI1 = new QuoteLineItem();	
qLI1.QuoteId = q.Id;	
qLI1.Approval_Status__c = 'N/A';	
insert qLI1;	
QuoteLineItem qLI2 = new QuoteLineItem();	
qLI2.QuoteId = q.Id;	
qLI2.Approval_Status__c = 'NotStarted';	
insert qLI2;	
QuoteLineItem qLI3 = new QuoteLineItem();	
qLI3.QuoteId = q.Id;	
qLI3.Approval_Status__c = 'InProgress';	
insert qLI3;	
QuoteLineItem qLI4 = new QuoteLineItem();	
qLI4.QuoteId = q.Id;	
qLI4.Approval_Status__c = 'Accepted';	
insert qLI4;	
QuoteLineItem qLI5 = new QuoteLineItem();	
qLI5.QuoteId = q.Id;	
qLI5.Approval_Status__c = 'Rejected';	
insert qLI5;	
QuoteLineItem qLI6 = new QuoteLineItem();	
qLI6.QuoteId = q.Id;	
qLI6.Approval_Status__c = 'Recalled';	
insert qLI6; */	
        QuoteLineItemTriggerHelper.updateQuoteStatus(q.Id);	
    }

}