src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Key Account</fullName>
                </value>
                <value>
                    <fullName>Global Account</fullName>
                </value>
                <value>
                    <fullName>Regional Key Account</fullName>
                </value>
                <value>
                    <fullName>Regional Account</fullName>
                </value>
                <value>
                    <fullName>Local Key Account</fullName>
                </value>
                <value>
                    <fullName>Local Account</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(Owner.UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;, 
IF( CONTAINS(Owner.UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;, &apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Plan_Overview_Component__mdt.object
<CustomObject>
    <fields>
        <fullName>ApexClass__c</fullName>
        <label>ApexClass</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Name__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                    <label>Individual</label>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Plan Overview Component</label>
    <pluralLabel>Account Plan Overview Components</pluralLabel>
</CustomObject>

src/objects/Account_Plans__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <label>BU Identifier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <formula>Account__r.Customer_Group__c</formula>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plans Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Engagement_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Engagement Plans</relationshipLabel>
        <relationshipName>Engagement_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Engagement Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Engagement Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Approval_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Request for edit</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

src/classes/KAM_EngagementPlanGrpCntlTest.cls
@isTest
public class KAM_EngagementPlanGrpCntlTest {
    @testSetup
    public static void createData()
    {
        Account acc=new Account();
        acc.Name='DemoAccount';
        acc.Account_Type__c='Distributor';
        acc.BillingCountry='India';
        acc.BillingStreet='Pune-Mumbai road';
        acc.Customer_Group__c='Demo';
        insert acc;
        
        Account_Plans__c ap=new Account_Plans__c();
        ap.Account__c=acc.Id;
        ap.StartDate__c=system.today();
        ap.EndDate__c=system.today().addDays (365);
        ap.BU_Identifier__c='Cocoa';
        ap.Type__c='Individual';
        ap.Year__c='2023';
        ap.Description__c='This is a test class';
        ap.Name='TestDemo';
        insert ap;
        
        Engagement_Plan__c ep=new Engagement_Plan__c();
        ep.Account__c=ap.Account__c;
        ep.Approval_Status__c='Approved';
        ep.Start_date__c= ap.StartDate__c;
        ep.End_Date__c=ap.EndDate__c;
        ep.Business_Unit__c= ap.BU_Identifier__c;
        insert ep;
    }
    
    public static testmethod void testGetDetails () {
       List<Account_Plans__c> accPlan = [SELECT Id,Name,StartDate__c,EndDate__c,BU_Identifier__c,Customer_Group__c FROM Account_Plans__c ];
        System.assert(accPlan != null && !accPlan.isEmpty (), 'Unable to find the accountPlan');
        
        List<Account_Plan_Overview_Component__mdt> accountPlanMetaData 
            = (List<Account_Plan_Overview_Component__mdt>) KAM_CustomMetaDataDAO.getCustomMetadataRecords (
                'SELECT Id, DeveloperName, Title__c, Order__c, ApexClass__c, Component_Name__c, Is_Active__c, Type__c FROM Account_Plan_Overview_Component__mdt WHERE DeveloperName = \'Group_Engagement_Plan\'');
        System.assert(accountPlanMetaData.size () > 0, 'Unable to find BudgetActualsGrp component details ' );
        
        String res 
            = KAM_AccountPlanOverviewCntl.getDetails(
                JSON.serialize(accountPlanMetaData[0]),
                JSON.serialize(new Map<String, Object> {'accountPlan' => accPlan[0]})
            );
        List<Account> accounts = (List<Account>) JSON.deserialize(res, List<Account>.class);
        System.assert(!accounts.isEmpty (), 'no accounts found');
        
    }
    
   
    
    public static testmethod void test_getDetailsNull()
    {
        Account_Plans__c ap=new Account_Plans__c();
        KAM_EngagementPlanGrpCntl epgc=new KAM_EngagementPlanGrpCntl();
        epgc.getDetails(JSON.serialize(new Map<String, Object> {''=> ap}));
    }
    
    public static testmethod void test_getGroupDetails()
    { List<Account_Plans__c> accPlan = [SELECT Id,Name,StartDate__c,EndDate__c,BU_Identifier__c,Customer_Group__c FROM Account_Plans__c ];
        System.assert(accPlan != null && !accPlan.isEmpty (), 'Unable to find the accountPlan');
        
        List<Account_Plan_Overview_Component__mdt> accountPlanMetaData 
            = (List<Account_Plan_Overview_Component__mdt>) KAM_CustomMetaDataDAO.getCustomMetadataRecords (
                'SELECT Id, DeveloperName, Title__c, Order__c, ApexClass__c, Component_Name__c, Is_Active__c, Type__c FROM Account_Plan_Overview_Component__mdt WHERE DeveloperName = \'Group_Engagement_Plan\'');
        System.assert(accountPlanMetaData.size () > 0, 'Unable to find BudgetActualsGrp component details ' );
        
        String res 
            = KAM_AccountPlanOverviewCntl.getDetails(
                JSON.serialize(accountPlanMetaData[0]),
                JSON.serialize(new Map<String, Object> {'accountPlan' => accPlan[0]})
            );
        List<Account> ar = (List<Account>) JSON.deserialize(res, List<Account>.class);
        System.assert(!ar.isEmpty (), 'no results found');
        
    }
    
    public static testmethod void test_getGroupDetailsNull()
    {
        try{
            Account_Plans__c ap=new Account_Plans__c();
            KAM_EngagementPlanGrpCntl.getGroupDetails(JSON.serialize(new Map<String, Object> {''=> ap}));
            KAM_EngagementPlanGrpCntl.getGroupDetails(JSON.serialize(new Map<String, Object> {'accountPlan'=> ap}));
        }catch(Exception e){}    
    }
    
    public static testmethod void test_getEngagementPlans()
    {
        Account_Plans__c ap=[Select id,StartDate__c,EndDate__c from Account_Plans__c where createdDate=Today Limit 1];
        System.assert(ap!=null, 'Its having null values');
        KAM_EngagementPlanGrpCntl.getEngagementPlans(JSON.serialize(ap));
    }
    
}

/*
 public static testmethod void test_getDetails()
    {
        Account_Plans__c ap=[Select id,StartDate__c,EndDate__c from Account_Plans__c where createdDate=Today Limit 1];
        System.assert(ap!=null, 'Its having null values');
        KAM_EngagementPlanGrpCntl epgc=new KAM_EngagementPlanGrpCntl();
        String res=epgc.getDetails(JSON.serialize(new Map<String, Object> {'accountPlan'=> ap}));
        List<Account> acc=[
                SELECT Id, Name
                   FROM Account
                WHERE CreatedDate=Today Limit 1
            ];
        //System.debug('res===========>'+JSON.deserializeUntyped(res));
        System.assertEquals(JSON.serialize(acc), res);
    }
*/