src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <label>Inco Terms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CFR</fullName>
                    <label>CFR - Costs and freight</label>
                </value>
                <value>
                    <fullName>CIF</fullName>
                    <label>CIF - Costs, insurance &amp; freight</label>
                </value>
                <value>
                    <fullName>CIP</fullName>
                    <label>CIP - Carriage and insurance paid</label>
                </value>
                <value>
                    <fullName>CPT</fullName>
                    <label>CPT - Carriage paid to</label>
                </value>
                <value>
                    <fullName>DAP</fullName>
                    <label>DAP - Delivered At Place</label>
                </value>
                <value>
                    <fullName>DDP</fullName>
                    <label>DDP - Delivered Duty Paid</label>
                </value>
                <value>
                    <fullName>DPU</fullName>
                    <label>DPU - Delivered At Place Unloaded</label>
                </value>
                <value>
                    <fullName>EXW</fullName>
                    <label>EXW - Ex Works</label>
                </value>
                <value>
                    <fullName>FAS</fullName>
                    <label>FAS - Free Along Sideship</label>
                </value>
                <value>
                    <fullName>FCA</fullName>
                    <label>FCA - Free Carrier</label>
                </value>
                <value>
                    <fullName>FOB</fullName>
                    <label>FOB - Free On Board</label>
                </value>
                <value>
                    <fullName>Instore</fullName>
                </value>
                <value>
                    <fullName>CNF</fullName>
                    <isActive>false</isActive>
                    <label>CNF</label>
                </value>
                <value>
                    <fullName>DAT</fullName>
                    <isActive>false</isActive>
                    <label>DAT</label>
                </value>
                <value>
                    <fullName>DDU</fullName>
                    <isActive>false</isActive>
                    <label>DDU</label>
                </value>
                <value>
                    <fullName>DES</fullName>
                    <isActive>false</isActive>
                    <label>DES</label>
                </value>
                <value>
                    <fullName>FOR</fullName>
                    <isActive>false</isActive>
                    <label>FOR</label>
                </value>
                <value>
                    <fullName>FOT</fullName>
                    <isActive>false</isActive>
                    <label>FOT</label>
                </value>
                <value>
                    <fullName>UN</fullName>
                    <isActive>false</isActive>
                    <label>UN</label>
                </value>
                <value>
                    <fullName>Z05</fullName>
                    <isActive>false</isActive>
                    <label>Z05</label>
                </value>
                <value>
                    <fullName>Z06</fullName>
                    <isActive>false</isActive>
                    <label>Z06</label>
                </value>
                <value>
                    <fullName>Z09</fullName>
                    <isActive>false</isActive>
                    <label>Z09</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ZU13 - Net 60 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>Z070 - 2% 15 days, 60 days net</fullName>
                </value>
                <value>
                    <fullName>ZU10 - Net 30 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>ZU14 - Net 90 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>ZU17 - Payment in Advance,Prepayment</fullName>
                </value>
                <value>
                    <fullName>ZU07 - Net 15 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>ZS87 - CAD at Sight In Trust@120 day-98%-2% Pay on req</fullName>
                </value>
                <value>
                    <fullName>ZU12 - Net 45 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>USBM - 2% 10 NET 45</fullName>
                </value>
                <value>
                    <fullName>US0D - 1% 10 NET 60</fullName>
                </value>
                <value>
                    <fullName>ZU04 - Net 7 days - Date of Invoice</fullName>
                    <default>true</default>
                    <label>ZU04 - Net 7 days - Date of Invoice</label>
                </value>
                <value>
                    <fullName>ZS96 - CAD at Sight In Trust @ 75 day - 100%</fullName>
                </value>
                <value>
                    <fullName>USAE - Net due in 65 days</fullName>
                </value>
                <value>
                    <fullName>ZU11 - Net 40 days - Date of Invoice</fullName>
                </value>
                <value>
                    <fullName>SG06 - Letter of credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>KG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>External_Product_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Product Code</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <description>Text Box Field Inco Terms</description>
        <inlineHelpText>Enter Inco Terms</inlineHelpText>
        <label>Inco Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFR - Costs and freight</fullName>
                </value>
                <value>
                    <fullName>CIF - Costs, insurance &amp; freight</fullName>
                </value>
                <value>
                    <fullName>CIP - Carriage and insurance paid</fullName>
                </value>
                <value>
                    <fullName>CPT - Carriage paid to</fullName>
                </value>
                <value>
                    <fullName>DAP - Delivered At Place</fullName>
                </value>
                <value>
                    <fullName>DDP - Delivered Duty Paid</fullName>
                </value>
                <value>
                    <fullName>EXW - Ex Works</fullName>
                </value>
                <value>
                    <fullName>FAS - Free Along Sideship</fullName>
                </value>
                <value>
                    <fullName>FCA - Free Carrier</fullName>
                </value>
                <value>
                    <fullName>FOB - Free On Board</fullName>
                </value>
                <value>
                    <fullName>DPU - Delivered At Place Unloaded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Olam_Quote_Number__c</fullName>
        <formula>Opportunity.OlamQuoteNumber__c &amp;&apos;_&apos;&amp; TEXT(Version__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Olam Quote Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <formula>TEXT( Opportunity.Account.Payment_Terms__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Terms</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_Conditions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Terms &amp; Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Material_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Material Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Olam_Total_Offer__c</fullName>
        <formula>Volume__c *  UnitPrice</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Olam Total Offer</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measure__c</fullName>
        <label>Unit Of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Unit_of_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MT</fullName>
        <default>true</default>
        <label>MT</label>
    </customValue>
    <customValue>
        <fullName>LB</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>QE</fullName>
        <isActive>false</isActive>
        <label>QE</label>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
        <isActive>false</isActive>
        <label>Carton</label>
    </customValue>
    <masterLabel>Unit of Measure</masterLabel>
</GlobalValueSet>

src/classes/QuotePDFCustomCntl.cls
public class QuotePDFCustomCntl {
    
    public String quoteId {get;set;}
    public Quote quote {get;set;}
    public Double total {get;set;}
    public Date Today { get { return Date.today(); }}
    
    public QuotePDFCustomCntl(ApexPages.StandardController s){
        quoteId = ApexPages.currentPage().getParameters().get('Id');
        
        quote = [SELECT Id, Name,Inco_Terms__c,ExpirationDate,Payment_Terms__c,Contract_Start_Date__c,Contract_End_Date__c,Olam_Quote_Number__c, Account.Name,Opportunity.RecordType.Name,Terms_Conditions__c,Account.BillingStreet,
                 Account.BillingCity,Account.BillingState,Account.BillingPostalCode, Account.BillingCountry,Opportunity.Owner.Name,
                 (SELECT Id, Product2.Name,Approval_Status__c,TotalPrice,Olam_Total_Offer__c, UnitPrice,Unit_Of_Measure__c, Volume__c,Quantity,Product2.ProductCode,Product2.External_Product_Code__c, Customer_Material_Code__c FROM QuoteLineItems WHERE ((Approval_Status__c='Accepted' OR Approval_Status__c='N/A'))) 
                 FROM Quote 
                 WHERE Id = :quoteId];
        System.debug('Quote'+quote);
        System.debug('qLI'+quote.QuoteLineItems);
        total = 0;
        for(QuoteLineItem q : quote.QuoteLineItems )
        {
            total += q.Olam_Total_Offer__c;
        }
        
    }
}