src/objects/Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Matrix1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Matrix2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                    <label>Spices</label>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sub Category 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMENA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Matrix</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Approval Matrix Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BLANK</fullName>
                </value>
                <value>
                    <fullName>DEZAAN</fullName>
                </value>
                <value>
                    <fullName>HERSHEY</fullName>
                </value>
                <value>
                    <fullName>HUYSMAN</fullName>
                </value>
                <value>
                    <fullName>JOANES</fullName>
                </value>
                <value>
                    <fullName>MACAO</fullName>
                </value>
                <value>
                    <fullName>NEUTRAL</fullName>
                </value>
                <value>
                    <fullName>STARBUCKS</fullName>
                </value>
                <value>
                    <fullName>UNICAO</fullName>
                </value>
                <value>
                    <fullName>BT</fullName>
                </value>
                <value>
                    <fullName>CPKELCO</fullName>
                </value>
                <value>
                    <fullName>DAMIN</fullName>
                </value>
                <value>
                    <fullName>GC</fullName>
                </value>
                <value>
                    <fullName>NICHE</fullName>
                </value>
                <value>
                    <fullName>PLOT</fullName>
                </value>
                <value>
                    <fullName>TRIAL</fullName>
                </value>
                <value>
                    <fullName>OTHERS</fullName>
                </value>
                <value>
                    <fullName>OCP</fullName>
                </value>
                <value>
                    <fullName>ASTRA</fullName>
                </value>
                <value>
                    <fullName>RAW MAT</fullName>
                </value>
                <value>
                    <fullName>SEMI FINISH ILHEUS BRAZIL</fullName>
                </value>
                <value>
                    <fullName>ASTRA A</fullName>
                </value>
                <value>
                    <fullName>THIRD PARTY CAKE /RAWMAT</fullName>
                </value>
                <value>
                    <fullName>JB COCOA</fullName>
                </value>
                <value>
                    <fullName>DEZAAN FE</fullName>
                </value>
                <value>
                    <fullName>PT. BUMITANGERANG</fullName>
                </value>
                <value>
                    <fullName>DEZAAN/SINGAPORE</fullName>
                </value>
                <value>
                    <fullName>BT/THIRD_PARTY_CAKE</fullName>
                    <label>BT/THIRD PARTY CAKE</label>
                </value>
                <value>
                    <fullName>SEMI_FINISH_MANNHEIM</fullName>
                    <label>SEMI FINISH MANNHEIM</label>
                </value>
                <value>
                    <fullName>SEMI_FINISH_SINGAPORE</fullName>
                    <label>SEMI FINISH SINGAPORE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acid</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI HH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI LH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI MH</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Blanched</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Oil Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Reject</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth Organic</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN STYLE CH</fullName>
    </customValue>
    <customValue>
        <fullName>AMF</fullName>
    </customValue>
    <customValue>
        <fullName>Analogue</fullName>
    </customValue>
    <customValue>
        <fullName>Black Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Bleached</fullName>
    </customValue>
    <customValue>
        <fullName>Blends</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Ingredient</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTERMLKCONCENTRATE</fullName>
    </customValue>
    <customValue>
        <fullName>Butter Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Cagliata</fullName>
    </customValue>
    <customValue>
        <fullName>Calcium Caseinate</fullName>
    </customValue>
    <masterLabel>Product Sub Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>#640 Colored</fullName>
    </customValue>
    <customValue>
        <fullName>#640 Whites</fullName>
    </customValue>
    <customValue>
        <fullName>100#</fullName>
    </customValue>
    <customValue>
        <fullName>200#</fullName>
    </customValue>
    <customValue>
        <fullName>40#</fullName>
    </customValue>
    <customValue>
        <fullName>40# Block</fullName>
    </customValue>
    <customValue>
        <fullName>40#Colby Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# colored</fullName>
    </customValue>
    <customValue>
        <fullName>40#Monterey Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# Pepper Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# White</fullName>
    </customValue>
    <customValue>
        <fullName>500# Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>500# White</fullName>
    </customValue>
    <customValue>
        <fullName>60-80#</fullName>
    </customValue>
    <customValue>
        <fullName>70%</fullName>
    </customValue>
    <customValue>
        <fullName>72.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>80%</fullName>
    </customValue>
    <customValue>
        <fullName>80% salted</fullName>
    </customValue>
    <customValue>
        <fullName>80% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>AA InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Extra No. 1</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Pieces</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Select Sheller Run</fullName>
    </customValue>
    <masterLabel>Product Sub Category 2</masterLabel>
</GlobalValueSet>

src/classes/QuoteLineApprovalService.cls
public class QuoteLineApprovalService implements QuoteLineApprovalServiceInterface {
    public List<QuoteLineApprovalWrapper> getQuoteLineApprovers(String businessUnit, String region, List<QuoteLineItem> quoteLineList){
        List<QuoteLineApprovalWrapper> quoteLineApprovalList = new List<QuoteLineApprovalWrapper>();
        
        Set<String> productCategorySet = new Set<String>();
        Set<String> productSubCategorySet = new Set<String>{null};
        Set<String> productSubCategory2Set = new Set<String>{null};
        
        for(QuoteLineItem quoteLine :quoteLineList){
            if(quoteLine.Product2.Product_Category__c != null){
                productCategorySet.add(quoteLine.Product2.Product_Category__c);
            }
            
            if(quoteLine.Product2.Product_Sub_Category__c != null){
                productSubCategorySet.add(quoteLine.Product2.Product_Sub_Category__c);
            }
            
            if(quoteLine.Product2.Product_Sub_Category_2__c != null){
                productSubCategory2Set.add(quoteLine.Product2.Product_Sub_Category_2__c);
            }
        }
        
        Map<String, Approval_Matrix__c> approvalMatrixMap = getApprovalMatrixMap(businessUnit, region, productCategorySet, productSubCategorySet, productSubCategory2Set);
        
        for(QuoteLineItem quoteLine :quoteLineList){
            if(approvalMatrixMap.containsKey(getKey(quoteLine, 'SubCategory2'))){
                quoteLineApprovalList.add(new QuoteLineApprovalWrapper(quoteLine, approvalMatrixMap.get(getKey(quoteLine, 'SubCategory2'))));
            }
            else
                if(approvalMatrixMap.containsKey(getKey(quoteLine, 'SubCategory'))){
                    quoteLineApprovalList.add(new QuoteLineApprovalWrapper(quoteLine, approvalMatrixMap.get(getKey(quoteLine, 'SubCategory'))));
                }
            else
                if(approvalMatrixMap.containsKey(getKey(quoteLine, 'Category'))){
                    quoteLineApprovalList.add(new QuoteLineApprovalWrapper(quoteLine, approvalMatrixMap.get(getKey(quoteLine, 'Category'))));
                }
            else{
                quoteLineApprovalList.add(new QuoteLineApprovalWrapper(quoteLine, new Approval_Matrix__c()));
            }
        }
        
        return quoteLineApprovalList;
    }
    
    
    public String getKey(QuoteLineItem quoteLine, String level){
        String key = '';
        
        if(level == 'SubCategory2'){
            key = quoteLine.Product2.Product_Category__c + '_' + quoteLine.Product2.Product_Sub_Category__c + '_' + quoteLine.Product2.Product_Sub_Category_2__c;
        }
        if(level == 'SubCategory'){
            key = quoteLine.Product2.Product_Category__c + '_' + quoteLine.Product2.Product_Sub_Category__c;
        }
        if(level == 'Category'){
            key = quoteLine.Product2.Product_Category__c;
        }
        
        return key;
    }
    
    
    public Map<String, Approval_Matrix__c> getApprovalMatrixMap(String businessUnit, String region, Set<String> productCategorySet, Set<String> productSubCategorySet, Set<String> productSubCategory2Set){
        Map<String, Approval_Matrix__c> approvalMatrixMap = new Map<String, Approval_Matrix__c>();
        
        String queryString = getQueryString(businessUnit, region, productCategorySet, productSubCategorySet, productSubCategory2Set);
        
        for(Approval_Matrix__c approvalMatrix :Database.query(queryString)){
            String key = '';
            if(approvalMatrix.Product_Category__c != null && approvalMatrix.Product_Category__c != ''){
                key += approvalMatrix.Product_Category__c;
            }
            
            if(approvalMatrix.Product_Sub_Category__c != null && approvalMatrix.Product_Sub_Category__c != ''){
                key += '_' + approvalMatrix.Product_Sub_Category__c;
            }
            
            if(approvalMatrix.Product_Sub_Category_2__c != null && approvalMatrix.Product_Sub_Category_2__c != ''){
                key += '_' + approvalMatrix.Product_Sub_Category_2__c;
            }
            
            approvalMatrixMap.put(key, approvalMatrix);
        }
        
        return approvalMatrixMap;
    }
    
    
    public String getQueryString(String businessUnit, String region, Set<String> productCategorySet, Set<String> productSubCategorySet, Set<String> productSubCategory2Set){
        String queryString = 'SELECT Approver_1__c, Approver_2__c, Approver_3__c, Approver_1__r.Name, Approver_2__r.Name, Approver_3__r.Name, Brand__c, Product_Category__c, Product_Sub_Category__c, Product_Sub_Category_2__c ';
        queryString += 'FROM Approval_Matrix__c ';
        queryString += 'WHERE Business_Unit__c = :businessUnit AND Region__c = :region ';
        
        if(!productCategorySet.isEmpty()){
            queryString += 'AND Product_Category__c IN :productCategorySet ';
        }
        
        if(!productSubCategorySet.isEmpty()){
            queryString += 'AND Product_Sub_Category__c IN :productSubCategorySet ';
        }
        
        if(!productSubCategory2Set.isEmpty()){
            queryString += 'AND Product_Sub_Category_2__c IN :productSubCategory2Set ';
        }
        
        System.debug('Query String ---'+ queryString);
        
        return queryString; 
    }
}