src/objects/Brand_n_Comp__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brand_type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Brand</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand_type__c</fullName>
        <label>Brand type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consumption__c</fullName>
        <label>Consumption</label>
        <referenceTo>Consumption__c</referenceTo>
        <relationshipLabel>Brands &amp; Competitors</relationshipLabel>
        <relationshipName>Brands_n_competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Brand &amp; Competitor</label>
    <nameField>
        <displayFormat>BnC-{0000}</displayFormat>
        <label>Brand n Competitor</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brands &amp; Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consumption</relationshipLabel>
        <relationshipName>Consumption</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Combination_Key__c</fullName>
        <formula>TEXT(Business_Unit__c) + &apos;_&apos; + TEXT(Year__c) + &apos;_&apos; + TEXT(Category__c) + &apos;_&apos; +  TEXT(Sub_Category__c) + &apos;_&apos; + TEXT(Sub_Category_2__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Combination Key</label>
        <type>Text</type>
    </fields>
    <label>Consumption</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>RecordId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumption</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Account Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Combination_Key__c</fullName>
        <formula>TEXT(Opportunity.Business_Unit__c) + &apos;_&apos; +TEXT(YEAR(Opportunity.CloseDate)) + &apos;_&apos; + TEXT( PricebookEntry.Product2.Product_Category__c) + &apos;_&apos; +TEXT(PricebookEntry.Product2.Product_Sub_Category__c) + &apos;_&apos; + TEXT(PricebookEntry.Product2.Product_Sub_Category_2__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Combination Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumption_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consumption Brand</label>
        <referenceTo>Brand_n_Comp__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consumption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consumption</label>
        <referenceTo>Consumption__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BLANK</fullName>
                </value>
                <value>
                    <fullName>DEZAAN</fullName>
                </value>
                <value>
                    <fullName>HERSHEY</fullName>
                </value>
                <value>
                    <fullName>HUYSMAN</fullName>
                </value>
                <value>
                    <fullName>JOANES</fullName>
                </value>
                <value>
                    <fullName>MACAO</fullName>
                </value>
                <value>
                    <fullName>NEUTRAL</fullName>
                </value>
                <value>
                    <fullName>STARBUCKS</fullName>
                </value>
                <value>
                    <fullName>UNICAO</fullName>
                </value>
                <value>
                    <fullName>BT</fullName>
                </value>
                <value>
                    <fullName>CPKELCO</fullName>
                </value>
                <value>
                    <fullName>DAMIN</fullName>
                </value>
                <value>
                    <fullName>GC</fullName>
                </value>
                <value>
                    <fullName>NICHE</fullName>
                </value>
                <value>
                    <fullName>PLOT</fullName>
                </value>
                <value>
                    <fullName>TRIAL</fullName>
                </value>
                <value>
                    <fullName>OTHERS</fullName>
                </value>
                <value>
                    <fullName>OCP</fullName>
                </value>
                <value>
                    <fullName>ASTRA</fullName>
                </value>
                <value>
                    <fullName>RAW MAT</fullName>
                </value>
                <value>
                    <fullName>SEMI FINISH ILHEUS BRAZIL</fullName>
                </value>
                <value>
                    <fullName>ASTRA A</fullName>
                </value>
                <value>
                    <fullName>THIRD PARTY CAKE /RAWMAT</fullName>
                </value>
                <value>
                    <fullName>JB COCOA</fullName>
                </value>
                <value>
                    <fullName>DEZAAN FE</fullName>
                </value>
                <value>
                    <fullName>PT. BUMITANGERANG</fullName>
                </value>
                <value>
                    <fullName>DEZAAN/SINGAPORE</fullName>
                </value>
                <value>
                    <fullName>BT/THIRD_PARTY_CAKE</fullName>
                    <label>BT/THIRD PARTY CAKE</label>
                </value>
                <value>
                    <fullName>SEMI_FINISH_MANNHEIM</fullName>
                    <label>SEMI FINISH MANNHEIM</label>
                </value>
                <value>
                    <fullName>SEMI_FINISH_SINGAPORE</fullName>
                    <label>SEMI FINISH SINGAPORE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Brand.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>5 STAR</fullName>
    </customValue>
    <customValue>
        <fullName>ADECOAGRO</fullName>
    </customValue>
    <customValue>
        <fullName>AGRI-MARK</fullName>
    </customValue>
    <customValue>
        <fullName>AGROPUR</fullName>
    </customValue>
    <customValue>
        <fullName>ALBAN</fullName>
    </customValue>
    <customValue>
        <fullName>ALIMA</fullName>
    </customValue>
    <customValue>
        <fullName>ALIMENTA</fullName>
    </customValue>
    <customValue>
        <fullName>ALISA</fullName>
    </customValue>
    <customValue>
        <fullName>Ammerland</fullName>
    </customValue>
    <customValue>
        <fullName>AMUL</fullName>
    </customValue>
    <customValue>
        <fullName>ANDRUSHOVCA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENLAC</fullName>
    </customValue>
    <customValue>
        <fullName>ARLA</fullName>
    </customValue>
    <customValue>
        <fullName>ARLA DANO</fullName>
    </customValue>
    <customValue>
        <fullName>ARRABAWN</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATED MILK PRODUCERS</fullName>
    </customValue>
    <customValue>
        <fullName>AURIVO</fullName>
    </customValue>
    <customValue>
        <fullName>BABUSHKINA KRINKA</fullName>
    </customValue>
    <customValue>
        <fullName>BALCHEM</fullName>
    </customValue>
    <customValue>
        <fullName>Barry Callebaut</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIOIOSO</fullName>
    </customValue>
    <customValue>
        <fullName>BELGOMILK</fullName>
    </customValue>
    <customValue>
        <fullName>BELLADEL</fullName>
    </customValue>
    <customValue>
        <fullName>BELLAKT</fullName>
    </customValue>
    <customValue>
        <fullName>BIERUN</fullName>
    </customValue>
    <customValue>
        <fullName>BIERY</fullName>
    </customValue>
    <customValue>
        <fullName>BILOSERKIVKA</fullName>
    </customValue>
    <customValue>
        <fullName>BINCO</fullName>
    </customValue>
    <customValue>
        <fullName>BLOMMER</fullName>
    </customValue>
    <customValue>
        <fullName>BMI</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

src/classes/ConsumptionOpportunityLinkService.cls
public class ConsumptionOpportunityLinkService {
    
    @future
    public static void findAndUpdateConsumptionAndBrandAsync(Set<Id> oppLineIdSet){
    	findAndUpdateConsumptionAndBrand(oppLineIdSet);
    }
    
    
    public static void findAndUpdateConsumptionAndBrand(Set<Id> oppLineIdSet){
        List<OpportunityLineItem> oppLines = new List<OpportunityLineItem>();
        oppLines = getOppLines(oppLineIdSet);
        
        Set<String> combinationKeySet = new Set<String>();
        Set<Id> accountIdSet = new Set<Id>();
        
        for(OpportunityLineItem oppLine :oppLines){
        	combinationKeySet.add(oppLine.Combination_Key__c);
			accountIdSet.add(oppLine.Opportunity.AccountId);            
        }
        
        Map<String, List<OpportunityLineItem>> oppLineMap = new Map<String, List<OpportunityLineItem>>();
        oppLineMap = getOppLineMap(oppLines);
        
        Map<String, List<Consumption__c>> consumptionMap = new Map<String, List<Consumption__c>>();
        consumptionMap = getConsumptionMap(accountIdSet, combinationKeySet);
        
        
        List<OpportunityLineItem> oppLinesToUpdate = new List<OpportunityLineItem>();
        for(OpportunityLineItem oppLine :oppLines){
            if(consumptionMap.containsKey(oppLine.Opportunity.AccountId)){
                for(Consumption__c consumption :consumptionMap.get(oppLine.Opportunity.AccountId)){
                    if(
                        oppLine.Combination_Key__c == consumption.Combination_Key__c && 
                        (
                            oppLine.Opportunity.Application__c == consumption.Application__c ||
                            (oppLine.Opportunity.Application__c != null && oppLine.Opportunity.Application__c != '' && oppLine.Opportunity.Application__c.contains(consumption.Application__c)) 
                        )
                        
                    ){
                        oppLine.Consumption__c = consumption.Id;
                        
                        if(oppLine.Product2.Brand__c != null && consumption.Brands_n_competitors__r != null){
                            for(Brand_n_Comp__c brand :consumption.Brands_n_competitors__r){
                                if(oppLine.Product2.Brand__c.equalsIgnoreCase(brand.Brand__c)){
                                    oppLine.Consumption_Brand__c = brand.Id;
                                }
                            }
                        }
                    }
                }
                oppLinesToUpdate.add(oppLine);
            }
        }
        
        if(oppLinesToUpdate.size() > 0){
            update oppLinesToUpdate;
        }
    }
    
    
    public static Map<String, List<Consumption__c>> getConsumptionMap(Set<Id> accountIdSet, Set<String> combinationKeySet){
        Map<String, List<Consumption__c>> consumptionMap = new Map<String, List<Consumption__c>>();
        
        for(Consumption__c consumption :getConsumptionList(accountIdSet, combinationKeySet)){
            if(consumptionMap.containsKey(consumption.Account__c)){
                consumptionMap.get(consumption.Account__c).add(consumption);
            }
            else{
                consumptionMap.put(consumption.Account__c, new List<Consumption__c>{consumption});
            }
        }
        
        return consumptionMap;
    }
    
    
    public static List<Consumption__c> getConsumptionList(Set<Id> accountIdSet, Set<String> combinationKeySet){
    	List<Consumption__c> consumptionList = new List<Consumption__c>();
        
        consumptionList = [SELECT Id, Account__c, Combination_Key__c, Application__c, 
                           (SELECT Brand__c FROM Brands_n_competitors__r WHERE Brand_type__c = 'Internal') 
                          FROM Consumption__c 
                          WHERE Account__c IN :accountIdSet
                          AND Combination_Key__c IN :combinationKeySet];
        
        return consumptionList;
    }
    
    
    public static Map<String, List<OpportunityLineItem>> getOppLineMap(List<OpportunityLineItem> oppLines){
        Map<String, List<OpportunityLineItem>> oppLineMap = new Map<String, List<OpportunityLineItem>>();
        
        for(OpportunityLineItem oppLine :oppLines){
            if(oppLineMap.containsKey(oppLine.Opportunity.AccountId)){
                oppLineMap.get(oppLine.Opportunity.AccountId).add(oppLine);
            }
            else{
                oppLineMap.put(oppLine.Opportunity.AccountId, new List<OpportunityLineItem>{oppLine});
            }
        }
        
        return oppLineMap;
    }
    
    public static List<OpportunityLineItem> getOppLines(Set<Id> oppLineIdSet){
        List<OpportunityLineItem> oppLines = new List<OpportunityLineItem>();
        
        oppLines = [SELECT Id, Opportunity.AccountId, Opportunity.Application__c, Combination_Key__c, Product2.Brand__c FROM OpportunityLineItem WHERE Id IN :oppLineIdSet];
        
        return oppLines;
    }
}