src/objects/Brand_n_Comp__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brand_type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Brand</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand_type__c</fullName>
        <label>Brand type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consumption__c</fullName>
        <label>Consumption</label>
        <referenceTo>Consumption__c</referenceTo>
        <relationshipLabel>Brands &amp; Competitors</relationshipLabel>
        <relationshipName>Brands_n_competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Brand &amp; Competitor</label>
    <nameField>
        <displayFormat>BnC-{0000}</displayFormat>
        <label>Brand n Competitor</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brands &amp; Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consumption</relationshipLabel>
        <relationshipName>Consumption</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>Coffee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume_MT__c</fullName>
        <label>Annual Consumption Volume</label>
        <precision>11</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Consumption</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>RecordId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumption</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Consumption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consumption</label>
        <referenceTo>Consumption__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BLANK</fullName>
                </value>
                <value>
                    <fullName>DEZAAN</fullName>
                </value>
                <value>
                    <fullName>HERSHEY</fullName>
                </value>
                <value>
                    <fullName>HUYSMAN</fullName>
                </value>
                <value>
                    <fullName>JOANES</fullName>
                </value>
                <value>
                    <fullName>MACAO</fullName>
                </value>
                <value>
                    <fullName>NEUTRAL</fullName>
                </value>
                <value>
                    <fullName>STARBUCKS</fullName>
                </value>
                <value>
                    <fullName>UNICAO</fullName>
                </value>
                <value>
                    <fullName>BT</fullName>
                </value>
                <value>
                    <fullName>CPKELCO</fullName>
                </value>
                <value>
                    <fullName>DAMIN</fullName>
                </value>
                <value>
                    <fullName>GC</fullName>
                </value>
                <value>
                    <fullName>NICHE</fullName>
                </value>
                <value>
                    <fullName>PLOT</fullName>
                </value>
                <value>
                    <fullName>TRIAL</fullName>
                </value>
                <value>
                    <fullName>OTHERS</fullName>
                </value>
                <value>
                    <fullName>OCP</fullName>
                </value>
                <value>
                    <fullName>ASTRA</fullName>
                </value>
                <value>
                    <fullName>RAW MAT</fullName>
                </value>
                <value>
                    <fullName>SEMI FINISH ILHEUS BRAZIL</fullName>
                </value>
                <value>
                    <fullName>ASTRA A</fullName>
                </value>
                <value>
                    <fullName>THIRD PARTY CAKE /RAWMAT</fullName>
                </value>
                <value>
                    <fullName>JB COCOA</fullName>
                </value>
                <value>
                    <fullName>DEZAAN FE</fullName>
                </value>
                <value>
                    <fullName>PT. BUMITANGERANG</fullName>
                </value>
                <value>
                    <fullName>DEZAAN/SINGAPORE</fullName>
                </value>
                <value>
                    <fullName>BT/THIRD_PARTY_CAKE</fullName>
                    <label>BT/THIRD PARTY CAKE</label>
                </value>
                <value>
                    <fullName>SEMI_FINISH_MANNHEIM</fullName>
                    <label>SEMI FINISH MANNHEIM</label>
                </value>
                <value>
                    <fullName>SEMI_FINISH_SINGAPORE</fullName>
                    <label>SEMI FINISH SINGAPORE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Brand.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>5 STAR</fullName>
    </customValue>
    <customValue>
        <fullName>ADECOAGRO</fullName>
    </customValue>
    <customValue>
        <fullName>AGRI-MARK</fullName>
    </customValue>
    <customValue>
        <fullName>AGROPUR</fullName>
    </customValue>
    <customValue>
        <fullName>ALBAN</fullName>
    </customValue>
    <customValue>
        <fullName>ALIMA</fullName>
    </customValue>
    <customValue>
        <fullName>ALIMENTA</fullName>
    </customValue>
    <customValue>
        <fullName>ALISA</fullName>
    </customValue>
    <customValue>
        <fullName>Ammerland</fullName>
    </customValue>
    <customValue>
        <fullName>AMUL</fullName>
    </customValue>
    <customValue>
        <fullName>ANDRUSHOVCA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENLAC</fullName>
    </customValue>
    <customValue>
        <fullName>ARLA</fullName>
    </customValue>
    <customValue>
        <fullName>ARLA DANO</fullName>
    </customValue>
    <customValue>
        <fullName>ARRABAWN</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATED MILK PRODUCERS</fullName>
    </customValue>
    <customValue>
        <fullName>AURIVO</fullName>
    </customValue>
    <customValue>
        <fullName>BABUSHKINA KRINKA</fullName>
    </customValue>
    <customValue>
        <fullName>BALCHEM</fullName>
    </customValue>
    <customValue>
        <fullName>Barry Callebaut</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIOIOSO</fullName>
    </customValue>
    <customValue>
        <fullName>BELGOMILK</fullName>
    </customValue>
    <customValue>
        <fullName>BELLADEL</fullName>
    </customValue>
    <customValue>
        <fullName>BELLAKT</fullName>
    </customValue>
    <customValue>
        <fullName>BIERUN</fullName>
    </customValue>
    <customValue>
        <fullName>BIERY</fullName>
    </customValue>
    <customValue>
        <fullName>BILOSERKIVKA</fullName>
    </customValue>
    <customValue>
        <fullName>BINCO</fullName>
    </customValue>
    <customValue>
        <fullName>BLOMMER</fullName>
    </customValue>
    <customValue>
        <fullName>BMI</fullName>
    </customValue>
    <customValue>
        <fullName>Huysman</fullName>
        <label>HUYSMAN</label>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

src/classes/OpportunityLineItemTriggerTest.cls
@isTest(SeeAllData=false)
public class OpportunityLineItemTriggerTest {
    @testSetup static void setupData() {
        Account acc = new Account();
        acc.name='Test01';
        acc.BillingCountry = 'India';
        acc.BillingStreet ='Test';
        insert acc;
        
        Consumption__c consump = new Consumption__c(
            Account__c = acc.Id,
            Business_Unit__c = 'Cocoa',
            Year__c = String.valueOf(System.today().year()),
            Volume_MT__c = 100 
        );
        insert consump;
        
        Brand_n_Comp__c compBrand = new Brand_n_Comp__c(
            Consumption__c = consump.Id,
            Brand__c = 'Huysman',
            Brand_type__c = 'Internal'
        );
        insert compBrand;
        
        Product2 prod = new Product2(
            Name = 'Cocoa Beans',
            IsActive = true
        );
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        System.debug('PBI '+pricebookId);
        
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            CurrencyIsoCode = 'USD',
            UnitPrice = 0,
            IsActive = true
        );
        insert pbe;
    }
    
    @isTest static void testOne() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        
        Test.startTest();
        Opportunity opp = new Opportunity(
            Name = 'Test1',
            AccountId = acc.Id,
            CloseDate = System.Today(),
            CurrencyIsoCode = 'USD',
            StageName = 'Briefing',
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId(),
            Business_Unit__c = 'Cocoa',
            Pricebook2Id = Test.getStandardPricebookId()
        );
        insert opp;
        
        OpportunityLineItem oppli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            PricebookEntryId = [SELECT Id FROM PricebookEntry].Id
        );
        insert oppli;
        Test.stopTest();
    }
}