src/objects/Budget_vs_Actual_Line__c.object
<CustomObject>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actual Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Budget_vs_Actuals__c</fullName>
        <label>Budget vs Actuals</label>
        <referenceTo>Budget_vs_Actuals__c</referenceTo>
        <relationshipLabel>Budget vs Actual Lines</relationshipLabel>
        <relationshipName>Budget_vs_Actual_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Consumption__c</fullName>
        <label>Consumption Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Annual Budget Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Budget vs Actual Line</label>
    <nameField>
        <displayFormat>BVSAL-{0000000}</displayFormat>
        <label>Budget vs Actual Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget vs Actual Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget_vs_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budget vs Actuals</relationshipLabel>
        <relationshipName>Budget_vs_Actuals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Budget vs Actuals</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Budget vs Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget vs Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consumption</relationshipLabel>
        <relationshipName>Consumption</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_vs_Actual_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget vs Actual Line</label>
        <referenceTo>Budget_vs_Actual_Line__c</referenceTo>
        <relationshipLabel>Consumption</relationshipLabel>
        <relationshipName>Consumption</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>Coffee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume_MT__c</fullName>
        <label>Annual Consumption Volume</label>
        <precision>11</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Consumption</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>RecordId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumption</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acid</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI HH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI LH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI MH</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Blanched</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Oil Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Reject</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth Organic</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN STYLE CH</fullName>
    </customValue>
    <customValue>
        <fullName>AMF</fullName>
    </customValue>
    <customValue>
        <fullName>Analogue</fullName>
    </customValue>
    <customValue>
        <fullName>Black Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Bleached</fullName>
    </customValue>
    <customValue>
        <fullName>Blends</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Ingredient</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTERMLKCONCENTRATE</fullName>
    </customValue>
    <customValue>
        <fullName>Butter Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Cagliata</fullName>
    </customValue>
    <customValue>
        <fullName>Calcium Caseinate</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <masterLabel>Product Sub Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>#640 Colored</fullName>
    </customValue>
    <customValue>
        <fullName>#640 Whites</fullName>
    </customValue>
    <customValue>
        <fullName>100#</fullName>
    </customValue>
    <customValue>
        <fullName>200#</fullName>
    </customValue>
    <customValue>
        <fullName>40#</fullName>
    </customValue>
    <customValue>
        <fullName>40# Block</fullName>
    </customValue>
    <customValue>
        <fullName>40#Colby Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# colored</fullName>
    </customValue>
    <customValue>
        <fullName>40#Monterey Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# Pepper Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# White</fullName>
    </customValue>
    <customValue>
        <fullName>500# Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>500# White</fullName>
    </customValue>
    <customValue>
        <fullName>60-80#</fullName>
    </customValue>
    <customValue>
        <fullName>70%</fullName>
    </customValue>
    <customValue>
        <fullName>72.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>80%</fullName>
    </customValue>
    <customValue>
        <fullName>80% salted</fullName>
    </customValue>
    <customValue>
        <fullName>80% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>AA InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Extra No. 1</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Pieces</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Select Sheller Run</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Non Dairy</fullName>
    </customValue>
    <masterLabel>Product Sub Category 2</masterLabel>
</GlobalValueSet>

src/globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

src/classes/ConsumptionTriggerHandlerTest.cls
@isTest
public class ConsumptionTriggerHandlerTest {
    @testSetup
    public static void createData()
    {
        Account acc = new Account();
        acc.name='Test';
        acc.BillingCountry = 'India';
        acc.BillingStreet ='Test';
        insert acc;
        
        Budget_vs_Actuals__c ba=new Budget_vs_Actuals__c();
        ba.Account__c=acc.Id;
        ba.Name='Dairy-Demo';
        ba.Year__c= String.valueOf(System.today().year ());
        ba.Business_Unit__c='Dairy';
        insert ba;
        
        Budget_vs_Actual_Line__c bal=new Budget_vs_Actual_Line__c();
        bal.Business_Unit__c = 'Dairy';
        bal.Budget_vs_Actuals__c=ba.Id;
        bal.Actuals__c=6000;
        bal.Volume__c=2000;
        bal.Category__c='BLEND';
        bal.Total_Consumption__c=1000;
        bal.Sub_Category__c='Brown';
        bal.Sub_Category_2__c='Dairy';
        
        Budget_vs_Actual_Line__c bal2=new Budget_vs_Actual_Line__c();
        bal2.Business_Unit__c = 'Dairy';
        bal2.Budget_vs_Actuals__c=ba.Id;
        bal2.Actuals__c=6000;
        bal2.Volume__c=2000;
        bal2.Category__c='BLEND';
        bal2.Total_Consumption__c=1000;
        bal2.Sub_Category__c='Brown';
        bal2.Sub_Category_2__c='Non Dairy';
        
        Budget_vs_Actual_Line__c bal1=new Budget_vs_Actual_Line__c();
        bal1.Business_Unit__c = 'Dairy';
        bal1.Budget_vs_Actuals__c=ba.Id;
        bal1.Actuals__c=6000;
        bal1.Volume__c=2000;
        bal1.Category__c='BLEND';
        bal1.Total_Consumption__c=1000;
        bal1.Sub_Category__c='Brown';
        
        insert new List<Budget_vs_Actual_Line__c> {bal, bal1, bal2};
    }
    @isTest
    static void testHandleBeforeInsert () {
        List<Account> accList = [SELECT Id, (SELECT Id, Name From Contacts) FROM Account where Name = 'Test'];
        System.assert(accList != null && !accList.isEmpty (), 'Unable to find the account');
        
        Test.startTest();
        Consumption__c c=new Consumption__c();
        c.Account__c=accList[0].Id;
        c.Volume_MT__c=350;
        c.Business_Unit__c='Dairy';
        //c.Budget_vs_Actual_Line__c=bal.Id;
        c.Year__c= String.valueOf(System.today().year ());
        c.Category__c='BLEND';
        c.Sub_Category__c='Brown';
        
        Consumption__c c1=new Consumption__c();
        c1.Account__c=accList[0].Id;
        c1.Volume_MT__c=350;
        c1.Business_Unit__c='Dairy';
        //c.Budget_vs_Actual_Line__c=bal.Id;
        c1.Year__c= String.valueOf(System.today().year ());
        c1.Category__c='BLEND';
        c1.Sub_Category__c='White';
        
        Consumption__c c2=new Consumption__c();
        c2.Account__c=accList[0].Id;
        c2.Volume_MT__c=350;
        c2.Business_Unit__c='Dairy';
        //c.Budget_vs_Actual_Line__c=bal.Id;
        c2.Year__c= String.valueOf(System.today().year ());
        c2.Category__c='BLEND';
        c2.Sub_Category__c='Brown';
        c2.Sub_Category_2__c='Dairy';
        
        insert new List<Consumption__c> {c1, c, c2};

        System.assertEquals(
            [SELECT Id, Category__c, Sub_Category__c, Sub_Category_2__c FROM Budget_vs_Actual_Line__c WHERE 
                 Budget_vs_Actuals__r.Year__c =: c.Year__c 
                 AND Budget_vs_Actuals__r.Account__c =: c.Account__c
                 AND Category__c =: c.Category__c
                 AND Sub_Category__c =: c.Sub_Category__c
                 AND Sub_Category_2__c =: c.Sub_Category_2__c
                ].Id, 
            [SELECT Id,Budget_vs_Actual_Line__c FROM Consumption__c WHERE Id=:c.Id].Budget_vs_Actual_Line__c,
            'Mismatch in the line items attached'
        );
        
        System.assertEquals(
            [SELECT Id, Category__c, Sub_Category__c, Sub_Category_2__c FROM Budget_vs_Actual_Line__c WHERE 
                 Budget_vs_Actuals__r.Year__c =: c2.Year__c 
                 AND Budget_vs_Actuals__r.Account__c =: c2.Account__c
                 AND Category__c =: c2.Category__c
                 AND Sub_Category__c =: c2.Sub_Category__c
                 AND Sub_Category_2__c =: c2.Sub_Category_2__c
                ].Id, 
            [SELECT Id,Budget_vs_Actual_Line__c FROM Consumption__c WHERE Id=:c2.Id].Budget_vs_Actual_Line__c,
            'Mismatch in the line items attached'
        );
       
        Test.stopTest();
        
        
    }
    
    @isTest
    static void testHandleBeforeUpdate () {
        List<Account> accList = [SELECT Id, (SELECT Id, Name From Contacts) FROM Account where Name = 'Test'];
        System.assert(accList != null && !accList.isEmpty (), 'Unable to find the account');
        
        Test.startTest();
        Consumption__c c=new Consumption__c();
        c.Account__c=accList[0].Id;
        c.Volume_MT__c=350;
        c.Business_Unit__c='Dairy';
        c.Year__c= String.valueOf(System.today().year ());
        c.Category__c='BLEND';
        c.Sub_Category__c='Brown';
        c.Sub_Category_2__c='Dairy';
        
        Consumption__c c1=new Consumption__c();
        c1.Account__c=accList[0].Id;
        c1.Volume_MT__c=350;
        c1.Business_Unit__c='Dairy';
        c1.Year__c= String.valueOf(System.today().year ());
        c1.Category__c='BLEND';
        c1.Sub_Category__c='White';
        
        Consumption__c c3=new Consumption__c();
        c3.Account__c=accList[0].Id;
        c3.Volume_MT__c=350;
        c3.Business_Unit__c='Dairy';
        c3.Year__c= String.valueOf(System.today().year ());
        c3.Category__c='BLEND';
        c3.Sub_Category__c='White';
        
        Consumption__c c2=new Consumption__c();
        c2.Account__c=accList[0].Id;
        c2.Volume_MT__c=350;
        c2.Business_Unit__c='Dairy';
        c2.Year__c= String.valueOf(System.today().year ());
        c2.Category__c='BLEND';
        c2.Sub_Category__c='Brown';
        
        insert new List<Consumption__c> {c1, c, c2, c3};

        Id blineId = [SELECT Id, Category__c, Sub_Category__c, Sub_Category_2__c FROM Budget_vs_Actual_Line__c WHERE 
                 Budget_vs_Actuals__r.Year__c =: c.Year__c 
                 AND Budget_vs_Actuals__r.Account__c =: c.Account__c
                 AND Category__c =: c.Category__c
                 AND Sub_Category__c =: c.Sub_Category__c
                 AND Sub_Category_2__c =: c.Sub_Category_2__c
                ].Id;
        System.assertEquals(
            blineId, 
            [SELECT Id,Budget_vs_Actual_Line__c FROM Consumption__c WHERE Id=:c.Id].Budget_vs_Actual_Line__c,
            'Mismatch in the line items attached'
        );            
        
        c.Category__c='BLEND';
        c.Sub_Category__c='Brown';
        c.Sub_Category_2__c='Non Dairy';
        update c;
        
        System.assertEquals(
            [SELECT Id, Category__c, Sub_Category__c, Sub_Category_2__c FROM Budget_vs_Actual_Line__c WHERE 
                 Budget_vs_Actuals__r.Year__c =: c.Year__c 
                 AND Budget_vs_Actuals__r.Account__c =: c.Account__c
                 AND Category__c =: c.Category__c
                 AND Sub_Category__c =: c.Sub_Category__c
                 AND Sub_Category_2__c =: c.Sub_Category_2__c
                ].Id, 
            [SELECT Id,Budget_vs_Actual_Line__c FROM Consumption__c WHERE Id=:c.Id].Budget_vs_Actual_Line__c,
            'Mismatch in the line items attached'
        );
        
        List<Consumption__c> consumptionList = [SELECT Id FROM Consumption__c where Budget_vs_Actual_Line__c =: blineId];
        System.assert(consumptionList.size() ==0, 'Mismatch in the child size');
        Test.stopTest();
        
        
    }
}