src/objects/Budget_vs_Actual_Line__c.object
<CustomObject>
    <fields>
        <fullName>Budget_vs_Actuals__c</fullName>
        <label>Budget vs Actuals</label>
        <referenceTo>Budget_vs_Actuals__c</referenceTo>
        <relationshipLabel>Budget vs Actual Lines</relationshipLabel>
        <relationshipName>Budget_vs_Actual_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Budget vs Actual Line</label>
    <nameField>
        <displayFormat>BVSAL-{0000000}</displayFormat>
        <label>Budget vs Actual Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget vs Actual Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget_vs_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Budget vs Actuals</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Budget vs Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget vs Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

src/classes/BudgetLineConsumptionLinkBatch.cls
public class BudgetLineConsumptionLinkBatch implements Database.Batchable<sObject>{
    
    public String year;
    
    
    public BudgetLineConsumptionLinkBatch(String year){
        this.year = year;
    }
    
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('SELECT Id FROM Budget_vs_Actual_Line__c WHERE Budget_vs_Actuals__r.Year__c = :year');
    }
    
    
    public void execute(Database.BatchableContext BC, List<Budget_vs_Actual_Line__c> records){
        BudgetActualLineTriggerHandler budgetTriggerHanlder = new BudgetActualLineTriggerHandler();
        budgetTriggerHanlder.updateConsumptions(records);
    }
    
    
    public void finish(Database.BatchableContext BC){
    }
}