src/objects/Budget_vs_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budget vs Actuals</relationshipLabel>
        <relationshipName>Budget_vs_Actuals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <label>Budget vs Actuals</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Budget vs Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget vs Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/BudgetVSActualTriggerHandler.cls
public class BudgetVSActualTriggerHandler extends TriggerHandlerBase{
    public override void handleAfterInsert() {
        
        //Added by Bharatesh as part of OFI
        SharingObjectRecordsHandler.shareBudgetsWithAccountTeams((Map<Id,Budget_vs_Actuals__c>)Trigger.newMap);
    }
    //Pramodh Added for user Access check
    public override void handleBeforeInsert(){
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Access_Set_Admins');
        if( hasCustomPermission){
            
        }else{
            BudgetVSActualTriggerHandler.userPrivilageCheck((List<Budget_vs_Actuals__c>)Trigger.New);
        }
    }
    public override void handleBeforeUpdate(){
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Access_Set_Admins');
        if( hasCustomPermission){
            
        }else{
            BudgetVSActualTriggerHandler.userPrivilageCheck((List<Budget_vs_Actuals__c>)Trigger.New);
        }
    }
    public static void userPrivilageCheck(List<Budget_vs_Actuals__c> listOfNewBudgetActuals ){
        set<Id> setOfAccountIds = new Set<Id>();
        Map<Id,Map<Id,String>> mapOfAccIdWithMapOfUserBus = new Map<Id,Map<Id,String>>();
        for(Budget_vs_Actuals__c tempBudgetActual : listOfNewBudgetActuals){
            setOfAccountIds.add(tempBudgetActual.Account__c);
        }
        mapOfAccIdWithMapOfUserBus = SharingUtility.getAccountTeamsUserBUs(setOfAccountIds);
        for(Budget_vs_Actuals__c tempBudgetActual : listOfNewBudgetActuals){
            boolean error = false;
            system.debug('tempBudgetActual.Business_Unit__c '+tempBudgetActual.Business_Unit__c);
            If(mapOfAccIdWithMapOfUserBus.containsKey(tempBudgetActual.Account__c)){
                If(mapOfAccIdWithMapOfUserBus.get(tempBudgetActual.Account__c).ContainsKey(userInfo.getUserId()) ){
                    If(mapOfAccIdWithMapOfUserBus.get(tempBudgetActual.Account__c).get(userInfo.getUserId()) == tempBudgetActual.Business_Unit__c ||
                       mapOfAccIdWithMapOfUserBus.get(tempBudgetActual.Account__c).get(userInfo.getUserId()) == 'All'){
                           
                       }else{
                           error = true;
                       }
                }else{
                    error = true;
                }
            }else{
                error = true;
            }
            if(error){
                tempBudgetActual.addError('You do not have enough permission to create/update this record');
            }
        }
    }
}