src/objects/Budget_vs_Actual_Line__c.object
<CustomObject>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actual Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Budget_vs_Actuals__c</fullName>
        <label>Budget vs Actuals</label>
        <referenceTo>Budget_vs_Actuals__c</referenceTo>
        <relationshipLabel>Budget vs Actual Lines</relationshipLabel>
        <relationshipName>Budget_vs_Actual_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Consumption__c</fullName>
        <label>Consumption Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Annual Budget Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Budget vs Actual Line</label>
    <nameField>
        <displayFormat>BVSAL-{0000000}</displayFormat>
        <label>Budget vs Actual Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget vs Actual Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget_vs_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budget vs Actuals</relationshipLabel>
        <relationshipName>Budget_vs_Actuals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Budget vs Actuals</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Budget vs Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget vs Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consumption</relationshipLabel>
        <relationshipName>Consumption</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_vs_Actual_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget vs Actual Line</label>
        <referenceTo>Budget_vs_Actual_Line__c</referenceTo>
        <relationshipLabel>Consumption</relationshipLabel>
        <relationshipName>Consumption</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>Coffee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Consumption</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>RecordId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumption</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acid</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI HH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI LH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI MH</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Blanched</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Oil Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Reject</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth Organic</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN STYLE CH</fullName>
    </customValue>
    <customValue>
        <fullName>AMF</fullName>
    </customValue>
    <customValue>
        <fullName>Analogue</fullName>
    </customValue>
    <customValue>
        <fullName>Black Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Bleached</fullName>
    </customValue>
    <customValue>
        <fullName>Blends</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Ingredient</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTERMLKCONCENTRATE</fullName>
    </customValue>
    <customValue>
        <fullName>Butter Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Cagliata</fullName>
    </customValue>
    <customValue>
        <fullName>Calcium Caseinate</fullName>
    </customValue>
    <masterLabel>Product Sub Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>#640 Colored</fullName>
    </customValue>
    <customValue>
        <fullName>#640 Whites</fullName>
    </customValue>
    <customValue>
        <fullName>100#</fullName>
    </customValue>
    <customValue>
        <fullName>200#</fullName>
    </customValue>
    <customValue>
        <fullName>40#</fullName>
    </customValue>
    <customValue>
        <fullName>40# Block</fullName>
    </customValue>
    <customValue>
        <fullName>40#Colby Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# colored</fullName>
    </customValue>
    <customValue>
        <fullName>40#Monterey Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# Pepper Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# White</fullName>
    </customValue>
    <customValue>
        <fullName>500# Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>500# White</fullName>
    </customValue>
    <customValue>
        <fullName>60-80#</fullName>
    </customValue>
    <customValue>
        <fullName>70%</fullName>
    </customValue>
    <customValue>
        <fullName>72.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>80%</fullName>
    </customValue>
    <customValue>
        <fullName>80% salted</fullName>
    </customValue>
    <customValue>
        <fullName>80% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>AA InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Extra No. 1</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Pieces</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Select Sheller Run</fullName>
    </customValue>
    <masterLabel>Product Sub Category 2</masterLabel>
</GlobalValueSet>

src/globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

src/classes/ConsumptionTriggerHandler.cls
public class ConsumptionTriggerHandler extends TriggerHandlerBase {
    
    public override void handleAfterInsert() {
        //Commented by Bharatesh as part of OFI
        //new OlamObjectSharing('Consumption__c', Trigger.new).addSharing();
        
        //Added by Bharatesh as part of OFI
        
        SharingObjectRecordsHandler.shareConsumptionsWithAccountTeams((Map<Id,Consumption__c>)Trigger.newMap);
        
        
    }
    
    public override void handleBeforeInsert() {
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Access_Set_Admins');
        if( hasCustomPermission){
            
        }else{
            ConsumptionTriggerHandler.userPrivilageCheck((List<Consumption__c>)Trigger.New);
            
        }
        updateBudgetLineRef ((List<Consumption__c>) Trigger.new);
        
    }
    public override void handleBeforeUpdate() {
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Access_Set_Admins');
        if( hasCustomPermission){
            
        }else{
            ConsumptionTriggerHandler.userPrivilageCheck((List<Consumption__c>)Trigger.New);
            
        }
        
        List <Consumption__c> consumptions = identifyCatSubCatChanges (
            (List<Consumption__c>)Trigger.new,  
            (Map<Id, Consumption__c>)Trigger.oldMap
        );
        if (!consumptions.isEmpty ()) {
            updateBudgetLineRef (consumptions);
        }
    }
    
    public void updateConsumptionRefs (List <Consumption__c> consumptions) {
        
        List<Consumption__c> consumptionUpdateList = new List<Consumption__c> ();
        for (Consumption__c eachConsumption : updateBudgetLineRef (consumptions)) {
            consumptionUpdateList.add (new Consumption__c (Id = eachConsumption.Id, Budget_vs_Actual_Line__c = eachConsumption.Budget_vs_Actual_Line__c));
        }
        if (!consumptionUpdateList.isEmpty ()) {
            Database.SaveResult [] results = Database.update(consumptionUpdateList, false);
            
            for (Database.SaveResult result : results) {
                if (!result.isSuccess()) {
                    //todo: handle error
                    System.debug('Errors :' + result.getErrors());
                }
            }
        }
    }
    
    private List <Consumption__c> identifyCatSubCatChanges (List<Consumption__c> newList, Map<Id, Consumption__c> oldMap) {
        
        List <Consumption__c> changedItems = new List<Consumption__c> ();
        
        for (Consumption__c eachLine : newList) {
            if (oldMap.containsKey (eachLine.Id)
                && 
                (
                    eachLine.Category__c != oldMap.get (eachLine.Id).Category__c
                    || eachLine.Sub_Category__c != oldMap.get (eachLine.Id).Sub_Category__c
                    || eachLine.Sub_Category_2__c != oldMap.get (eachLine.Id).Sub_Category_2__c
                )
               ) {
                   changedItems.add (eachLine);
               }
        }
        return changedItems;
    }
    
    private List<Consumption__c> updateBudgetLineRef (List<Consumption__c> records) {
        Map<String, List<Consumption__c>> consumptionsMap   = new Map<String, List<Consumption__c>> (); 
        Set<String> buTypes                                 = new Set<String> ();
        Set<String> categories                              = new Set<String> ();
        Set<String> subCategories                           = new Set<String> ();
        Set<String> subCategoriesTwo                        = new Set<String> ();
        Set<Id> accountIds                                  = new Set<Id> ();
        Set<String> years                         = new Set<String> ();
        
        for (Consumption__c eachConsumption : records) {
            String key = '';
            if (String.isNotBlank(eachConsumption.Account__c)) {
                key += eachConsumption.Account__c;
                accountIds.add (eachConsumption.Account__c);
            }
            if (String.isNotBlank(eachConsumption.Business_Unit__c)) {
                key += eachConsumption.Business_Unit__c;
                buTypes.add (eachConsumption.Business_Unit__c);
            }
            if (String.isNotBlank(eachConsumption.Year__c)) {
                key += eachConsumption.Year__c;
                years.add (eachConsumption.Year__c);
            }
            if (String.isNotBlank(eachConsumption.Category__c)) {
                key += eachConsumption.Category__c;
                categories.add(eachConsumption.Category__c);
            }
            if (String.isNotBlank(eachConsumption.Sub_Category__c)) {
                key += eachConsumption.Sub_Category__c;
                subCategories.add (eachConsumption.Sub_Category__c);
            }
            if (String.isNotBlank(eachConsumption.Sub_Category_2__c)) {
                key += eachConsumption.Sub_Category_2__c;
                subCategoriesTwo.add (eachConsumption.Sub_Category_2__c);
            }
            key = key.trim();
            
            if (consumptionsMap.containsKey (key)) {
                consumptionsMap.get (key).add (eachConsumption);
            } else {
                consumptionsMap.put (key, new List<Consumption__c> {eachConsumption});
            }
        }
        
        //        if (consumptionsMap.isEmpty ()) { return; }
        
        for (Budget_vs_Actual_Line__c eachLine : [
            SELECT Id, Actuals__c, Budget_vs_Actuals__c, Category__c, Sub_Category__c, 
            Sub_Category_2__c, Total_Consumption__c, Volume__c, 
            Budget_vs_Actuals__r.Account__c, Budget_vs_Actuals__r.Business_Unit__c,
            Budget_vs_Actuals__r.Year__c    
            FROM Budget_vs_Actual_Line__c
            WHERE Budget_vs_Actuals__r.Account__c IN : accountIds
            AND Budget_vs_Actuals__r.Business_Unit__c IN : buTypes
            AND Budget_vs_Actuals__r.Year__c IN : years
            //AND Category__c IN : categories
            //AND Sub_Category__c IN : subCategories
            //AND Sub_Category_2__c IN : subCategoriesTwo
            LIMIT :(Limits.getLimitQueryRows() - Limits.getQueryRows())
        ]) {
            
            String key = '';
            if (String.isNotBlank(eachLine.Budget_vs_Actuals__r.Account__c)) {
                key += eachLine.Budget_vs_Actuals__r.Account__c;
            }
            if (String.isNotBlank(eachLine.Budget_vs_Actuals__r.Business_Unit__c)) {
                key += eachLine.Budget_vs_Actuals__r.Business_Unit__c;
            }
            if (String.isNotBlank(eachLine.Budget_vs_Actuals__r.Year__c)) {
                key += eachLine.Budget_vs_Actuals__r.Year__c;
            }
            if (String.isNotBlank(eachLine.Category__c)) {
                key += eachLine.Category__c;
            }
            if (String.isNotBlank(eachLine.Sub_Category__c)) {
                key += eachLine.Sub_Category__c;
            }
            if (String.isNotBlank(eachLine.Sub_Category_2__c)) {
                key += eachLine.Sub_Category_2__c;
            }
            key = key.trim();
            
            if (consumptionsMap.containsKey (key)) {
                for (Consumption__c  eachConsumption : consumptionsMap.get (key)) {
                    eachConsumption.Budget_vs_Actual_Line__c = eachLine.Id;
                }
                //removed because we need to identify if any of the records doesn't have any matching budget line. 
                //during updation for the given key combination, 
                consumptionsMap.remove (key);
            }
        }
        // set the Budget_vs_Actual_Line__c references to null
        if (!consumptionsMap.isEmpty ()) {
            for (String key : consumptionsMap.keySet ()) {
                for (Consumption__c  eachConsumption : consumptionsMap.get (key)) {
                    eachConsumption.Budget_vs_Actual_Line__c = null;
                }
            }
        }
        
        return records;
    }
    //Pramodh Added for Validation Check
    
    public static void userPrivilageCheck(List<Consumption__c> listOfNewConsumptions ){
        set<Id> setOfAccountIds = new Set<Id>();
        Map<Id,Map<Id,String>> mapOfAccIdWithMapOfUserBus = new Map<Id,Map<Id,String>>();
        for(Consumption__c tempConsumption : listOfNewConsumptions){
            setOfAccountIds.add(tempConsumption.Account__c);
        }
        mapOfAccIdWithMapOfUserBus = SharingUtility.getAccountTeamsUserBUs(setOfAccountIds);
        for(Consumption__c tempConsumption : listOfNewConsumptions){
            boolean error = false;
            If(mapOfAccIdWithMapOfUserBus.containsKey(tempConsumption.Account__c)){
                If(mapOfAccIdWithMapOfUserBus.get(tempConsumption.Account__c).ContainsKey(userInfo.getUserId()) ){
                    If(mapOfAccIdWithMapOfUserBus.get(tempConsumption.Account__c).get(userInfo.getUserId()) == tempConsumption.Business_Unit__c ||
                       mapOfAccIdWithMapOfUserBus.get(tempConsumption.Account__c).get(userInfo.getUserId()) == 'All'){
                           
                       }else{
                           error = true;
                       }
                }else{
                    error = true;
                }
            }else{
                error = true;
            }
            if(error){
                tempConsumption.addError('You do not have enough permission to create/update this record');
            }
        }
    }
}