src/objects/Budget_vs_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budget vs Actuals</relationshipLabel>
        <relationshipName>Budget_vs_Actuals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <label>Budget vs Actuals</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Budget vs Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget vs Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <formula>User__r.BU_Identifier__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/BudgetOwnerService.cls
public class BudgetOwnerService{
    List<Teams__c> teamsList = new List<Teams__c>();
    Map<Id, Map<String, Id>> accountBUPrimaryUserMap = new Map<Id, Map<String, Id>>();
    Map<Id, Map<String, List<Budget_vs_Actuals__c>>> accountBUBudgetMap = new Map<Id, Map<String, List<Budget_vs_Actuals__c>>>();
    List<Budget_vs_Actuals__c> bugetRecordsToUpdate = new List<Budget_vs_Actuals__c>();
    
    
    public BudgetOwnerService(List<Teams__c> teamsList){
        this.teamsList = teamsList;
    }
    
    
    public void changeBudgetRecordOwner(){
        createAccountBUPrimaryUserMap();
        if(accountBUPrimaryUserMap.size() > 0){
            getAccountBUBudgetMap();
            getBudgetRecordsToUpdateOwner();
            updateBudgetRecords();
        }
    }
    
    
    public void createAccountBUPrimaryUserMap(){
        for(Teams__c team :teamsList){
            if(team.Is_Primary__c){
                if(accountBUPrimaryUserMap.containsKey(team.Account__c)){
                    accountBUPrimaryUserMap.get(team.Account__c).put(team.BU__c, team.User__c);
                }
                else{
                    accountBUPrimaryUserMap.put(team.Account__c, new Map<String, Id>{team.BU__c => team.User__c});
                }
            }
        }
    }
    
    
    public void getAccountBUBudgetMap(){
        for(Budget_vs_Actuals__c budget :[SELECT Id, Account__c, Business_Unit__c, OwnerId FROM Budget_vs_Actuals__c WHERE Account__c IN :accountBUPrimaryUserMap.keySet()]){
            if(accountBUBudgetMap.containsKey(budget.Account__c)){
                if(accountBUBudgetMap.get(budget.Account__c).containsKey(budget.Business_Unit__c)){
                    accountBUBudgetMap.get(budget.Account__c).get(budget.Business_Unit__c).add(budget);
                }
                else{
                    accountBUBudgetMap.get(budget.Account__c).put(budget.Business_Unit__c, new List<Budget_vs_Actuals__c>{budget});
                }
                
            }
            else{
                accountBUBudgetMap.put(budget.Account__c, new Map<String, List<Budget_vs_Actuals__c>>{budget.Business_Unit__c => new List<Budget_vs_Actuals__c>{budget}});
            }
        }
    }
    
    
    public void getBudgetRecordsToUpdateOwner(){
        for(Id accId :accountBUPrimaryUserMap.keySet()){
            for(String bu :accountBUPrimaryUserMap.get(accId).keySet()){
                if(accountBUBudgetMap.containsKey(accId) && accountBUBudgetMap.get(accId).containsKey(bu)){
                    for(Budget_vs_Actuals__c budgetRecord: accountBUBudgetMap.get(accId).get(bu)){
                        budgetRecord.OwnerId = accountBUPrimaryUserMap.get(accId).get(bu);
                        bugetRecordsToUpdate.add(budgetRecord);
                    }    
                }
            }
        }
    }
    
    
    public void updateBudgetRecords(){
        if(bugetRecordsToUpdate.size() > 0){
            update bugetRecordsToUpdate;
        }
    }     
}