src/objects/Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consumption</relationshipLabel>
        <relationshipName>Consumption</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>Coffee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Consumption</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>RecordId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumption</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Interactions__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/ObjectSharingFieldMap_Test.cls
@isTest
public class ObjectSharingFieldMap_Test {
	
    @isTest
    public static void testOpportunity() {
        ObjectSharingFieldMap fieldMap = new ObjectSharingFieldMap('opportunity');
        
        System.assertEquals('AccountId', fieldMap.objectAccountId);
        System.assertEquals('Business_Unit__c', fieldMap.objectBU);
        System.assertEquals('OpportunityShare', fieldMap.shareObjectName);
        System.assertEquals('OpportunityId', fieldMap.shareParentId);
        System.assertEquals('OpportunityAccessLevel', fieldMap.shareAccessLevel);
    }
    
    @isTest
    public static void testInteractions() {
        ObjectSharingFieldMap fieldMap = new ObjectSharingFieldMap('Interactions__c');
        
        System.assertEquals('Account__c', fieldMap.objectAccountId);
        System.assertEquals('Business_Unit__c', fieldMap.objectBU);
        System.assertEquals('Interactions__Share', fieldMap.shareObjectName);
        System.assertEquals('ParentId', fieldMap.shareParentId);
        System.assertEquals('AccessLevel', fieldMap.shareAccessLevel);
    }
    
    @isTest
    public static void testConsumption() {
        ObjectSharingFieldMap fieldMap = new ObjectSharingFieldMap('Consumption__c');
        
        System.assertEquals('Account__c', fieldMap.objectAccountId);
        System.assertEquals('Business_Unit__c', fieldMap.objectBU);
        System.assertEquals('Consumption__Share', fieldMap.shareObjectName);
        System.assertEquals('ParentId', fieldMap.shareParentId);
        System.assertEquals('AccessLevel', fieldMap.shareAccessLevel);
    }
}