src/objects/Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consumption</relationshipLabel>
        <relationshipName>Consumption</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <label>Brands</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Brand</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>Coffee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Coverage__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer&apos;s Coverage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Volume_MT__c</fullName>
        <label>Annual Consumption Volume</label>
        <precision>11</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Consumption</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>RecordId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumption</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Interactions__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Brands__c</fullName>
        <label>Brands</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Present</fullName>
        <active>true</active>
        <businessProcess>Service%2FPresent</businessProcess>
        <description>Opportunity to present new concepts or solutions to the customer that may lead to new business</description>
        <label>Presentation Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <defaultValue>IF(CONTAINS($UserRole.Name, &apos;Cocoa&apos;), &apos;Cocoa Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Dairy&apos;), &apos;Dairy Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Spice&apos;), &apos;Spice Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Edible_Nuts&apos;), &apos;Edible_Nuts Sales Manager&apos;, &apos; &apos;)))))))</defaultValue>
        <label>Role Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Dairy Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Spice Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts Sales Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Brand.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>5 STAR</fullName>
    </customValue>
    <customValue>
        <fullName>ADECOAGRO</fullName>
    </customValue>
    <customValue>
        <fullName>AGRI-MARK</fullName>
    </customValue>
    <customValue>
        <fullName>AGROPUR</fullName>
    </customValue>
    <customValue>
        <fullName>ALBAN</fullName>
    </customValue>
    <customValue>
        <fullName>ALIMA</fullName>
    </customValue>
    <customValue>
        <fullName>ALIMENTA</fullName>
    </customValue>
    <customValue>
        <fullName>ALISA</fullName>
    </customValue>
    <customValue>
        <fullName>Ammerland</fullName>
    </customValue>
    <customValue>
        <fullName>AMUL</fullName>
    </customValue>
    <customValue>
        <fullName>ANDRUSHOVCA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENLAC</fullName>
    </customValue>
    <customValue>
        <fullName>ARLA</fullName>
    </customValue>
    <customValue>
        <fullName>ARLA DANO</fullName>
    </customValue>
    <customValue>
        <fullName>ARRABAWN</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATED MILK PRODUCERS</fullName>
    </customValue>
    <customValue>
        <fullName>AURIVO</fullName>
    </customValue>
    <customValue>
        <fullName>BABUSHKINA KRINKA</fullName>
    </customValue>
    <customValue>
        <fullName>BALCHEM</fullName>
    </customValue>
    <customValue>
        <fullName>Barry Callebaut</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIOIOSO</fullName>
    </customValue>
    <customValue>
        <fullName>BELGOMILK</fullName>
    </customValue>
    <customValue>
        <fullName>BELLADEL</fullName>
    </customValue>
    <customValue>
        <fullName>BELLAKT</fullName>
    </customValue>
    <customValue>
        <fullName>BIERUN</fullName>
    </customValue>
    <customValue>
        <fullName>BIERY</fullName>
    </customValue>
    <customValue>
        <fullName>BILOSERKIVKA</fullName>
    </customValue>
    <customValue>
        <fullName>BINCO</fullName>
    </customValue>
    <customValue>
        <fullName>BLOMMER</fullName>
    </customValue>
    <customValue>
        <fullName>BMI</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/OlamObjectSharing_Test.cls
@isTest
public class OlamObjectSharing_Test {
    //Commented as part of OFI as it is no more valid
    
    /*@testSetup
    public static void prepare() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
            UserRole r = new UserRole(DeveloperName = 'MyCustomRole', Name = 'Dairy Something');
            insert r;
            
            Id profileId = [SELECT Id FROM Profile WHERE Name = 'Dairy Sales'].Id;
            User u1 = new User(
                 ProfileId = profileId,
                 LastName = 'UnitTestUser1',
                 Email = 'unittestuser000@unittestuser.com',
                 Username = 'unittestuser000@unittestuser.com' + System.currentTimeMillis(),
                 CompanyName = 'TEST',
                 Title = 'title',
                 Alias = 'alias',
                 TimeZoneSidKey = 'America/Los_Angeles',
                 EmailEncodingKey = 'UTF-8',
                 LanguageLocaleKey = 'en_US',
                 LocaleSidKey = 'en_US',
                 UserRoleId = r.Id
            );    
            insert u1;
            
            User u2 = new User(
                 ProfileId = profileId,
                 LastName = 'UnitTestUser2',
                 Email = 'unittestuser002@unittestuser.com',
                 Username = 'unittestuser002@unittestuser.com' + System.currentTimeMillis(),
                 CompanyName = 'TEST',
                 Title = 'title',
                 Alias = 'alias',
                 TimeZoneSidKey = 'America/Los_Angeles',
                 EmailEncodingKey = 'UTF-8',
                 LanguageLocaleKey = 'en_US',
                 LocaleSidKey = 'en_US',
                 UserRoleId = r.Id
            );    
            insert u2;
        }
        
        List<String> userListString = new List<String>{'UnitTestUser1', 'UnitTestUser2'};
        List<User> userList = [SELECT Id FROM User WHERE LastName in :userListString];
        Id userId1 = userList[0].Id;
        Id userId2 = userList[1].Id;
        
        Account acc;
        Opportunity opp1;
        System.runAs (userList[0]) {
            acc = new Account(Name = 'UNIT TEST account', 
                                      OwnerId = userId1,
                                      BillingStreet = 'Test 1 street', 
                                      BillingCountry = 'Singapore');
            insert acc;
       
        
        Id RecordTypeIdOpportunity = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Present').getRecordTypeId();
        
        opp1 = new Opportunity();
        opp1.AccountId = acc.Id;
        opp1.Name = 'unittest - opp1';
		opp1.StageName = 'Briefing';
		opp1.CloseDate = date.newInstance(2050, 11, 21);
        opp1.Business_Unit__c = 'Dairy';
        opp1.RecordTypeId = RecordTypeIdOpportunity;
        insert opp1;
        }
        Teams__c team1Check = [Select Account__c, User__c 
                                 from Teams__c 
                                 where Account__c=:acc.Id and 
                                     User__c=:userId1 and 
                                     Is_Primary__c=true and 
                                     Role_Name__c='Dairy Sales Manager'];
        
        //System.runAs (userList[0]) {
        //    Teams__c team1 = new Teams__c(Account__c = acc.Id, 
        //                                  User__c = userId1, 
        //                                  Is_Primary__c = true,
        //                                  Role_Name__c = 'Dairy Sales Manager');
        //    insert team1;
        //}
        
       System.runAs (userList[0]) {
            Teams__c team2 = new Teams__c(Account__c = acc.Id,
                                         User__c = userId2,
                                         Is_Primary__c = false,
                                         Role_Name__c = 'Dairy Sales Manager');
            insert team2;
       }
    }
    
	@isTest
    public static void testAddSharingOpportunity() {
        // Arrange
        Id RecordTypeIdOpportunity = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Present').getRecordTypeId();
        
        Test.startTest();
        List<String> userListString = new List<String>{'UnitTestUser1', 'UnitTestUser2'};
		List<User> userList = [SELECT Id FROM User WHERE LastName in :userListString];
        Opportunity newOpp;
        Account acc = [select Id from Account where Name = 'UNIT TEST account'];
        
        System.runAs(userList[0]){
            
		newOpp = new Opportunity(AccountId = acc.Id, 
                                             Name = 'unittest - opp3', 
                                             StageName = 'Briefing', 
                                             CloseDate = date.newInstance(2050, 11, 21), 
                                             Business_Unit__c = 'Dairy', 
                                             RecordTypeId = RecordTypeIdOpportunity);
        // Action
        insert newOpp;
        }
        // Assert
        List<OpportunityShare> result = [select Id, OpportunityId, UserOrGroupId, RowCause from OpportunityShare where OpportunityId = :newOpp.Id and RowCause In('Manual','Owner') Order by RowCause];
        
        userList = [SELECT Id FROM User WHERE LastName in :userListString];
        
        System.debug('ttt '+result);
        
        Test.stopTest();
        System.assertEquals(2, result.size());
        System.assertEquals(newOpp.Id, result[0].OpportunityId);
        System.assertEquals(newOpp.Id, result[1].OpportunityId);
        System.assertEquals(userList[1].Id, result[0].UserOrGroupId);
        System.assertEquals(userList[0].Id, result[1].UserOrGroupId);
        System.assertEquals('Manual', result[0].RowCause);
        System.assertEquals('Owner', result[1].RowCause);
    }
    
    @isTest
    public static void testAddSharingConsumption() {
        // Arrange
        Id RecordTypeIdOpportunity = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Present').getRecordTypeId();
        
        Test.startTest();
                
        Date d = date.newInstance(2050, 11, 21);
        Account acc = [select Id from Account where Name = 'UNIT TEST account'];
		Consumption__c newConsumption = new Consumption__c(Account__c = acc.id, 
                                                           Business_Unit__c = 'Dairy', 
                                                           Coverage__c = d, 
                                                           Review_Date__c = d, 
                                                           Volume_MT__c = 1, 
                                                           Brands__c = 'Fonterra');
        // Action
        insert newConsumption;

        // Assert
        List<Consumption__Share> result = [select Id, ParentId, UserOrGroupId, RowCause from Consumption__Share where ParentId = :newConsumption.Id and RowCause = 'Manual'];
        
        List<String> userListString = new List<String>{'UnitTestUser1', 'UnitTestUser2'};
        List<User> userList = [SELECT Id FROM User WHERE LastName in :userListString];
        
        Test.stopTest();
        
        System.assertEquals(2, result.size());
        System.assertEquals(newConsumption.Id, result[0].ParentId);
        System.assertEquals(newConsumption.Id, result[1].ParentId);
        System.assertEquals(userList[0].Id, result[0].UserOrGroupId);
        System.assertEquals(userList[1].Id, result[1].UserOrGroupId);
        System.assertEquals('Manual', result[0].RowCause);
        System.assertEquals('Manual', result[1].RowCause);
    }
    
    @isTest
    public static void testAddSharingInteraction() {
        // Arrange
        Id RecordTypeIdOpportunity = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Present').getRecordTypeId();
        
        Test.startTest();
        
        Account acc = [select Id from Account where Name = 'UNIT TEST account'];
		Interactions__c newInteraction = new Interactions__c(Account__c = acc.id, 
                                                           Business_Unit__c = 'Dairy');
        // Action
        insert newInteraction;

        // Assert
        List<Interactions__Share> result = [select Id, ParentId, UserOrGroupId, RowCause from Interactions__Share where ParentId = :newInteraction.Id and RowCause = 'Manual'];

        List<String> userListString = new List<String>{'UnitTestUser1', 'UnitTestUser2'};
        List<User> userList = [SELECT Id FROM User WHERE LastName in :userListString];
        
        Test.stopTest();
        
        System.assertEquals(2, result.size());
        System.assertEquals(newInteraction.Id, result[0].ParentId);
        System.assertEquals(newInteraction.Id, result[1].ParentId);
        System.assertEquals(userList[0].Id, result[0].UserOrGroupId);
        System.assertEquals(userList[1].Id, result[1].UserOrGroupId);
        System.assertEquals('Manual', result[0].RowCause);
        System.assertEquals('Manual', result[1].RowCause);
    }*/
}