src/objects/Engagement_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Engagement Plans</relationshipLabel>
        <relationshipName>Engagement_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Engagement_Plan_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Engagement Plan Locked?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Engagement Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Engagement Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Engagement_Plan_Line__c.object
<CustomObject>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actuals (Number)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Attendee__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Attendee</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Engagement_Plan__c</fullName>
        <label>Engagement Plan</label>
        <referenceTo>Engagement_Plan__c</referenceTo>
        <relationshipLabel>Engagement Plan Lines</relationshipLabel>
        <relationshipName>Engagement_Plan_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Frequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Engagement_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Engagement (Date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned__c</fullName>
        <label>Planned (Number)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Engagement__c</fullName>
        <label>Type of Engagement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_Engagement</valueSetName>
        </valueSet>
    </fields>
    <label>Engagement Plan Line</label>
    <nameField>
        <displayFormat>EPN-{0000000}</displayFormat>
        <label>Engagement Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Plan Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Interactions__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Approval_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Request for edit</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Frequency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bi Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Half Yearly</fullName>
    </customValue>
    <customValue>
        <fullName>Need Based</fullName>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

src/globalValueSets/Type_of_Engagement.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>C Level Engagement</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial (Sales &amp; Pricing)</fullName>
    </customValue>
    <customValue>
        <fullName>Finance (Structures &amp; Payments)</fullName>
    </customValue>
    <customValue>
        <fullName>Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>Risk (Solutions)</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;D (Market View Exchange)</fullName>
    </customValue>
    <customValue>
        <fullName>Sales &amp; Ops Planning/Review</fullName>
    </customValue>
    <customValue>
        <fullName>Sustainability</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Type of Engagement</masterLabel>
</GlobalValueSet>

src/globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

src/classes/EngagementPlanSelector.cls
public Inherited sharing class EngagementPlanSelector {
    
    public static List<Engagement_Plan__c> getEngangementPlansByAccountId (String accountId, 
                                                                            String buIdentifier, 
                                                                            Date startDate, 
                                                                            Date endDate) {
        
        return [SELECT Id, Account__c, End_Date__c, Start_date__c, Is_Engagement_Plan_Locked__c,
                    Approval_Status__c,
                    (SELECT Id, Actuals__c, Attendee__c, Engagement_Plan__c, Description__c, 
                    Frequency__c, Last_Engagement_Date__c, Planned__c, Type_of_Engagement__c 
                    FROM Engagement_Plan_Lines__r)
                FROM Engagement_Plan__c 
                WHERE Account__c =: accountId
                AND Business_Unit__c =: buIdentifier
                AND Start_date__c =: startDate AND End_Date__c =:endDate
                LIMIT 1];
    }

    public static List<Engagement_Plan__c> getEngagementPlanByInteractionDetail (Interactions__c eachInteraction, Set<String> interactionType) {
        return [SELECT Id, Account__c, Business_Unit__c, End_Date__c, Start_date__c,
                (
                    SELECT Id, Actuals__c, Last_Engagement_Date__c, Type_of_Engagement__c 
                    FROM Engagement_Plan_Lines__r
                    WHERE Type_of_Engagement__c in: interactionType
                )
                FROM Engagement_Plan__c 
                WHERE Account__c =: eachInteraction.Account__c
                AND (Start_date__c <= Today AND End_Date__c >= Today)
                AND Business_Unit__c =: eachInteraction.Business_Unit__c
                LIMIT 1
        ];
    }
      public static List<Engagement_Plan__c> getEngangementPlansBytId (String EngagementPlanId) {
        
        return [SELECT Id, Account__c, End_Date__c, Start_date__c, Is_Engagement_Plan_Locked__c,
                    Approval_Status__c,Year__c,
                    (SELECT Id, Actuals__c, Attendee__c, Engagement_Plan__c, Description__c, 
                    Frequency__c, Last_Engagement_Date__c, Planned__c, Type_of_Engagement__c 
                    FROM Engagement_Plan_Lines__r)
                FROM Engagement_Plan__c 
                WHERE Id =: EngagementPlanId
                LIMIT 1];
    }
}