src/objects/Engagement_Plan_Line__c.object
<CustomObject>
    <fields>
        <fullName>Type_of_Engagement__c</fullName>
        <label>Type of Engagement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_Engagement</valueSetName>
        </valueSet>
    </fields>
    <label>Engagement Plan Line</label>
    <nameField>
        <displayFormat>EPN-{0000000}</displayFormat>
        <label>Engagement Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Plan Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Type_of_Engagement.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>C Level Engagement</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial (Sales &amp; Pricing)</fullName>
    </customValue>
    <customValue>
        <fullName>Finance (Structures &amp; Payments)</fullName>
    </customValue>
    <customValue>
        <fullName>Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>Risk (Solutions)</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;D (Market View Exchange)</fullName>
    </customValue>
    <customValue>
        <fullName>Sales &amp; Ops Planning/Review</fullName>
    </customValue>
    <customValue>
        <fullName>Sustainability</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Type of Engagement</masterLabel>
</GlobalValueSet>

src/classes/KAM_UtilTest.cls
@isTest
public class KAM_UtilTest {
    
    @isTest
    static  void testGetPickListValues() {
        List<KAM_Util.PicklistEntry> pickListEntries = KAM_Util.getPickListValues('Account', 'BillingCountryCode', true, true);
        System.assert(!pickListEntries.isEmpty (), 'Values not found for the give pick list field');
        
        pickListEntries = KAM_Util.getPickListValues('Engagement_Plan_Line__c', 'Type_of_Engagement__c', true, false);
        System.assert(!pickListEntries.isEmpty (), 'Values not found for the give pick list field');
    }
}