src/objects/Grant_Account_Teams_Access__e.object
<CustomObject>
    <label>Grant Account Teams Access</label>
    <pluralLabel>Grant Account Teams Access</pluralLabel>
</CustomObject>

src/objects/Retry_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Team</label>
        <referenceTo>Teams__c</referenceTo>
        <relationshipLabel>Retry Logs</relationshipLabel>
        <relationshipName>Retry_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retry_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Retry Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Team Creation</fullName>
                </value>
                <value>
                    <fullName>Account Team Grant Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retry Log</label>
    <nameField>
        <displayFormat>RL-{0000000000}</displayFormat>
        <label>Retry Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retry Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <defaultValue>&quot;Read Access&quot;</defaultValue>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read Access</fullName>
                </value>
                <value>
                    <fullName>Edit Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant_Access_Status__c</fullName>
        <label>Grant Access Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <defaultValue>IF(CONTAINS($UserRole.Name, &apos;Cocoa&apos;), &apos;Cocoa Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Dairy&apos;), &apos;Dairy Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Spice&apos;), &apos;Spice Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Edible_Nuts&apos;), &apos;Edible_Nuts Sales Manager&apos;, &apos; &apos;)))))))</defaultValue>
        <label>Role Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Dairy Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Spice Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts Sales Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Role_Name__c</fullName>
        <label>User Role Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Cocoa PDI Manager</fullName>
                </value>
                <value>
                    <fullName>Dairy Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Dairy PDI Manager</fullName>
                </value>
                <value>
                    <fullName>Spice Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Spice PDI Manager</fullName>
                </value>
                <value>
                    <fullName>Edible Nuts Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Edible Nuts PDI Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GrantTeamsAccessPEventScheduler.cls
global class GrantTeamsAccessPEventScheduler implements schedulable{
    
    global void execute(SchedulableContext SC) {
        //Check Accout Team records if Access has to be granted for any record based on checkbox field
        List<Teams__c> listOfAccountTeamsToGrantAccess = new List<Teams__c>();
        listOfAccountTeamsToGrantAccess = [Select Id,Name,Access_Level__c,Account__c,Is_Primary__c,Grant_Access_Status__c,Role_Name__c,User__c,User_Role_Name__c 
                                           from Teams__c 
                                           where Grant_Access_Status__c =: SharingUtility.TEAMS_GRANTACCESSSTATUS_INITIATED and
                                           Id NOT IN (
                                               Select Account_Team__c 
                                               from Retry_Log__c 
                                               where Type__c =: SharingUtility.RETRYLOGTYPE_ACCOUNT_TEAM_GRANT_ACCESS 
                                               and Retry_Count__c >: SharingUtility.ACCOUNTTEAMGRANTACCESS_RETRY_COUNT_LIMIT
                                           )
                                           limit 1];
        if(!listOfAccountTeamsToGrantAccess.isEmpty()){
            //Fire the grant access platform event
            Grant_Account_Teams_Access__e grantAccountTeamsAccessEvent = new Grant_Account_Teams_Access__e ();
            Database.SaveResult result = Eventbus.publish(grantAccountTeamsAccessEvent);
            
            //abort the current Job (it will be rescheduled in the platform event only if there is no record left to be processed )
            System.abortJob(SC.getTriggerId());
        }
        else{
            //abort the current Job (it will be rescheduled in the platform event only if there is no record left to be processed )
            System.abortJob(SC.getTriggerId());
            
            //Schedule a Job to run after 2 mins from now
            /*String hour = String.valueOf(Datetime.now().hour());
            String min = String.valueOf(Datetime.now().minute() + 2); 
            String seconds = String.valueOf(Datetime.now().second());
            
            String nextJobScheduleTime = seconds + ' ' + min + ' ' + hour + ' * * ?';*/
            Datetime workTime = System.now().addMinutes(2);
            String nextJobScheduleTime = '' + workTime.second() + ' ' + workTime.minute() + ' ' + workTime.hour()+ ' ' + workTime.day() + ' ' + workTime.month() + ' ? ' + workTime.year();
            String jobId = System.schedule('Grant Access Job- ' + String.valueOf(Datetime.now()), nextJobScheduleTime, new GrantTeamsAccessPEventScheduler());
        }
    }
}