src/objects/Interest__c.object
<CustomObject>
    <fields>
        <fullName>Interest__c</fullName>
        <label>Interest %</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Interest %</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Interest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bid_Open__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Bid Open</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Mix__c</fullName>
        <inlineHelpText>If Case Mix is yes, Kindly fill in Additional Notes</inlineHelpText>
        <label>Case Mix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exchange_Rate_Local_USD__c</fullName>
        <label>Exchange Rate (Local /USD)*</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate_USD_VND__c</fullName>
        <label>Exchange Rate (USD/VND)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Local_Currency__c</fullName>
        <label>Local Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IsoCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Plbs_Country_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PLBS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>PLBS_Product__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for tagging the Develop opportunity to the Tender opportunity when the samplings are requested</description>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Related)</relationshipLabel>
        <relationshipName>ChildOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_In_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person In Charge</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plbs_Annual_Unit__c</fullName>
        <label>Annual Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plbs_Est_Award__c</fullName>
        <label>Est. Award %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plbs_Manufacturing_Facility__c</fullName>
        <label>Manufacturing Facility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Plbs_Country_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plbs_Shelf_Price__c</fullName>
        <inlineHelpText>Local Currency</inlineHelpText>
        <label>Shelf Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plbs_Weight_G__c</fullName>
        <label>Weight(G)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tender_Contract_End__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tender Contract End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tender_Contract_Start__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tender Contract Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tender_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tender Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TCB__c.object
<CustomObject>
    <fields>
        <fullName>Container_Type__c</fullName>
        <label>Container Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dry</fullName>
                </value>
                <value>
                    <fullName>Reefer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Depth_Gusset_Height_mm__c</fullName>
        <label>Depth/ Gusset/ Height (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duty__c</fullName>
        <label>Duty (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Fobbing_Container__c</fullName>
        <label>Fobbing / Container</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Freight_Container__c</fullName>
        <label>Freight / Container</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Height_mm__c</fullName>
        <label>Height (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Import_Clearance_USD_Cont__c</fullName>
        <label>Import Clearance (USD/Cont)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Initial_Design__c</fullName>
        <label>Initial Design</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Months__c</fullName>
        <label>Interest Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest__c</fullName>
        <label>Interest (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Length_mm_1st__c</fullName>
        <label>Length (mm) (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loss_1st_PM__c</fullName>
        <label>Loss (1st PM)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loss_2nd_PM_Carton__c</fullName>
        <label>Loss (2nd PM - Carton)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loss_Product__c</fullName>
        <label>Loss (Product)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MOQ_Packaging_1st__c</fullName>
        <label>MOQ Packaging (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MOQ_Packaging_2nd__c</fullName>
        <label>MOQ Packaging (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Max_Height_mm__c</fullName>
        <label>Max Height (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Weight_kg__c</fullName>
        <label>Max Weight (kg)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Olam_WHs_Cost_USD_Pallet_Excl_PLT__c</fullName>
        <label>Olam WH&apos;s Cost (USD/Pallet) - Excl. PLT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Olam_WHs_Cost_USD_Pallet_Incl_PLT__c</fullName>
        <label>Olam WH&apos;s Cost (USD/Pallet) - Incl. PLT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Processing__c</fullName>
        <label>Processing</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Product Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs</relationshipLabel>
        <relationshipName>TCBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Other_Fixed_Costs__c</fullName>
        <label>Other Fixed Costs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PM_Type_1st__c</fullName>
        <label>PM Type (1st)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1st_PM_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PM_Type_2nd__c</fullName>
        <label>PM Type (2nd)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X2nd_PM_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Packing_Cost_lbs__c</fullName>
        <label>Packing Cost ($/lbs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pallet_Cost_USD_EA__c</fullName>
        <label>Pallet Cost (USD/EA)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pallet_Type__c</fullName>
        <label>Pallet Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pallet_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs (Opportunity)</relationshipLabel>
        <relationshipName>TCBs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Olam_WH_USD_Cont__c</fullName>
        <label>Port - Olam WH (USD/Cont)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Port_of_Entry__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Port of Entry</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quotations_Given_as_Per__c</fullName>
        <label>Quotations Given as Per</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Quotations_Given_as_Per</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TCB_FOB__c</fullName>
        <description>Olam_Opportunity_TCB_FOB__c, This field must used in Classes</description>
        <label>FOB (TCB)_</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tare_Weight_g_1st__c</fullName>
        <label>Tare Weight (g) (1st)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Term</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>WH_to_Customers_DC_Cost_USD_Pallet__c</fullName>
        <label>WH to Customer&apos;s DC Cost (USD/Pallet)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Width_mm_1st__c</fullName>
        <label>Width (mm) (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1st_PM_Pouch_jar__c</fullName>
        <label>PM (Pouch/jar) VND/EA (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1st_Printing__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Printing (1st)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1st_Structure__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Structure (1st)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X2nd_PM_Carton__c</fullName>
        <label>PM (Carton) - VND/EA (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TCB</label>
    <nameField>
        <displayFormat>TCB - {00000}</displayFormat>
        <label>TCB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/IsoCode.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
        <default>true</default>
        <label>AED</label>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>VND</fullName>
    </customValue>
    <description>For local currency in Tender Opportunity</description>
    <masterLabel>IsoCode</masterLabel>
</GlobalValueSet>

src/globalValueSets/Pallet_Set.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Disposal - 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal - 1x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal - 1.1x1.1m</fullName>
    </customValue>
    <customValue>
        <fullName>CHEP – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>CHEP – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>PECO – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>PECO – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>LOSCAM – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>LOSCAM – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 1x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 1.1x1.1m</fullName>
    </customValue>
    <masterLabel>Pallet Set</masterLabel>
</GlobalValueSet>

src/globalValueSets/Plbs_Country_Set.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei Darussalam</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>Cabo Verde</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <masterLabel>Country Set</masterLabel>
</GlobalValueSet>

src/globalValueSets/Quotations_Given_as_Per.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>40FT Container</fullName>
        <default>true</default>
        <label>40FT Container</label>
    </customValue>
    <customValue>
        <fullName>20FT Container</fullName>
    </customValue>
    <masterLabel>Quotations Given as Per</masterLabel>
</GlobalValueSet>

src/globalValueSets/Term.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CFR</fullName>
        <label>CFR - Costs and freight</label>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
        <label>CIF - Costs, insurance &amp; freight</label>
    </customValue>
    <customValue>
        <fullName>CIP</fullName>
        <label>CIP - Carriage and insurance paid</label>
    </customValue>
    <customValue>
        <fullName>CPT</fullName>
        <label>CPT - Carriage paid to</label>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
        <label>DAP - Delivered At Place</label>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
        <label>DDP - Delivered Duty Paid</label>
    </customValue>
    <customValue>
        <fullName>DPU</fullName>
        <label>DPU - Delivered At Place Unloaded</label>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
        <label>EXW - Ex Works</label>
    </customValue>
    <customValue>
        <fullName>FAS</fullName>
        <label>FAS - Free Along Sideship</label>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
        <label>FCA - Free Carrier</label>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
        <label>FOB - Free On Board</label>
    </customValue>
    <customValue>
        <fullName>Instore</fullName>
    </customValue>
    <masterLabel>Term</masterLabel>
</GlobalValueSet>

src/globalValueSets/X1st_PM_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DOY</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW</fullName>
    </customValue>
    <customValue>
        <fullName>FOUR SIDE SEAL</fullName>
    </customValue>
    <customValue>
        <fullName>DOY FLAT BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW BLOCK BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>VACUUM</fullName>
    </customValue>
    <customValue>
        <fullName>PET JAR</fullName>
    </customValue>
    <customValue>
        <fullName>GLASS JAR</fullName>
    </customValue>
    <customValue>
        <fullName>PET CYLINDER JAR</fullName>
    </customValue>
    <customValue>
        <fullName>METAL CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>COMPOSITE CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PET CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PAPER MILK BOTTLE</fullName>
    </customValue>
    <masterLabel>1st PM Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/X2nd_PM_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSC</fullName>
    </customValue>
    <customValue>
        <fullName>TRAY &amp; LID</fullName>
    </customValue>
    <customValue>
        <fullName>TRAY ONLY</fullName>
    </customValue>
    <customValue>
        <fullName>PRE CUT RSC</fullName>
    </customValue>
    <masterLabel>2nd PM Type</masterLabel>
</GlobalValueSet>

src/classes/CloneTenderOppWithProdController.cls
public class CloneTenderOppWithProdController {
    
    private ApexPages.StandardController controller {get;set;}
    private opportunity opp{get;set;}
    public Opportunity OpportunityCloned {get;set;}
    
    public CloneTenderOppWithProdController(ApexPages.StandardController controller){
                System.debug('Inside CloneTenderOppWithProdController');
        this.controller = controller;
        opp = (Opportunity)controller.getRecord();
        opp = [select id, owner.name,Accountid,Amount,CloseDate,Contractid,Description,NextStep,Name,stageName,Ownerid,Campaignid,IsPrivate,Probability,Pricebook2Id,Type,
               Tender_Number__c, Market__c, Person_In_Charge__c, Bid_Open__c,Tender_Contract_Start__c,Tender_Contract_End__c,LeadSource,
               Local_Currency__c, Exchange_Rate_Local_USD__c, Exchange_Rate_USD_VND__c from Opportunity where id =: opp.Id];
        System.debug('Opp '+Opp);
        OpportunityCloned = opp.clone(false,true);
        
    }
    
     public PageReference save() {
        System.debug('Inside Extension save');
        
        try {
            insert(OpportunityCloned);
            
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
         
         Map<String,Opportunity> oppProToClone = new Map<String,Opportunity>();
         Map<String,TCB__c> TCBToClone =new Map<String,TCB__c>();
         Map<string,string> mapOfChildOppToRefOppId= new Map<string,string>();
         set<String> setOfRefOppId = new set<String>();
        List<Opportunity> soppProduct = [select Id,owner.name,Accountid,Amount,CloseDate,Contractid,Description,LeadSource,NextStep,Name,stageName,Ownerid,Campaignid,IsPrivate,Probability,Pricebook2Id,Type,
                                         Parent_Opportunity__c, Plbs_Shelf_Price__c,Plbs_Weight_G__c, PLBS_Product__c, Case_Mix__c,Plbs_Annual_Unit__c,Plbs_Est_Award__c,Plbs_Manufacturing_Facility__c,
                                         (select Id,Quotations_Given_as_Per__c,Opportunity_Processing__c,Loss_Product__c,Loss_1st_PM__c,Loss_2nd_PM_Carton__c, Packing_Cost_lbs__c, Pallet_Cost_USD_EA__c,
                                         Initial_Design__c, Other_Fixed_Costs__c, Fobbing_Container__c, TCB_FOB__c,Interest__c , Interest_Months__c,Margin__c , Freight_Container__c, Duty__c,Import_Clearance_USD_Cont__c, 
                                         Olam_WHs_Cost_USD_Pallet_Excl_PLT__c ,Olam_WHs_Cost_USD_Pallet_Incl_PLT__c, WH_to_Customers_DC_Cost_USD_Pallet__c, Pallet_Type__c, Max_Height_mm__c, Port_Olam_WH_USD_Cont__c,
                                         Max_Weight_kg__c ,Term__c, Port_of_Entry__c, Container_Type__c, PM_Type_1st__c, X1st_PM_Pouch_jar__c, MOQ_Packaging_1st__c, X1st_Structure__c,  X1st_Printing__c , Tare_Weight_g_1st__c, Length_mm_1st__c,
                                         Width_mm_1st__c , Depth_Gusset_Height_mm__c , PM_Type_2nd__c ,X2nd_PM_Carton__c , MOQ_Packaging_2nd__c, Structure_2nd__c ,Printing_2nd__c, Tare_Weight_g_2nd__c, Length_Depth_mm__c, Width_mm_2nd__c ,
                                         Height_mm__c ,Unit_CTN__c ,Case_Mix_PL__c ,CTN_Layer__c ,Layer_PL__c ,Layer_PL_40HC__c , PL_20FT__c ,PL_40FT__c ,CTN_20FT__c, CTN_40FT__c , CTN_40FT_HC__c from TCBs__r)
                                         from Opportunity where Parent_Opportunity__c  =: opp.Id];

         for(Opportunity Opp:soppProduct){
             Opportunity inCopy = Opp.clone(false,true);
            inCopy.Parent_Opportunity__c = OpportunityCloned.Id;
            inCopy.StageName = 'Opening';
             for(TCB__c tcb: Opp.TCBs__r){
                 TCB__c inCopyTCB = tcb.clone(false,true);  
                 inCopyTCB.PM_Type_1st__c  = tcb.PM_Type_1st__c;
                 inCopyTCB.Quotations_Given_as_Per__c  = tcb.Quotations_Given_as_Per__c;
                 inCopyTCB.PM_Type_2nd__c  = tcb.PM_Type_2nd__c;
                 inCopyTCB.Pallet_Type__c  = tcb.Pallet_Type__c;
                 TCBToClone.put(Opp.Id,inCopyTCB);//only one TCb
             }                
            oppProToClone.put(Opp.id,inCopy);
         }

         insert oppProToClone.values();
         system.debug('oppProToClone after '+oppProToClone);
         
         for(String ReferenceOppId:oppProToClone.keySet()){
             mapOfChildOppToRefOppId.put(oppProToClone.get(ReferenceOppId).Id,ReferenceOppId);
         }
         
         system.debug('mapOfChildOppToRefOppId '+mapOfChildOppToRefOppId);       
         list<TCB__c> listOfNewTCB =[select Id,Opportunity__c from TCB__c where Opportunity__c in :mapOfChildOppToRefOppId.keySet()];
         system.debug('listOfNewTCB '+listOfNewTCB);
         for(TCB__c tcb : listOfNewTCB){
               System.debug('Inside TCB');
             if( mapOfChildOppToRefOppId.containsKey(tcb.Opportunity__c )){
                 TCBToClone.get( mapOfChildOppToRefOppId.get(tcb.Opportunity__c) ).Id = tcb.Id;
             }
         }
         upsert TCBToClone.values();
         system.debug('TCBToClone.values() After  '+TCBToClone.values());
         
         for(Opportunity OppProCloned : soppProduct){
            setOfRefOppId.add(OppProCloned.id);
        }

        List<OpportunityLineItem> inToClone = new List<OpportunityLineItem>();
        List<OpportunityLineItem> soppIngredient = [Select Id, Grade__c, Product2Id, ProductCode,PricebookEntryId, ListPrice, OpportunityId, Name, Quantity, Ratio__c, UnitPrice, TotalPrice
                                                    from OpportunityLineItem
                                                    Where OpportunityId =: oppProToClone.keySet()];
        
        
         
       // for(Opportunity newOppProductClone: oppProToClone.values()){
         //   String NewOppProId = newOppProductClone.id;
            for(OpportunityLineItem oLI : soppIngredient){
                OpportunityLineItem inCopyIn = oLI.clone(false,true);
                inCopyIn.OpportunityId = oppProToClone.get(oLI.OpportunityId).Id;
                inCopyIn.UnitPrice = null;
                inToClone.add(inCopyIn);
            } 
        //}
        
        if (intoClone.size() > 0) {
        	insert inToClone;    
        }  
         system.debug('Last '+[select Id,Opportunity__c from TCB__c where Opportunity__c in :mapOfChildOppToRefOppId.keySet()]);
		 return new PageReference('/'+OpportunityCloned.id);
     }
}