src/objects/Interactions__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/InteractionSelector.cls
public with sharing class InteractionSelector {
    
    public static List<Interactions__c> getInteractionsByAccountIds (Set<Id> accountIds, Set<String> bUs) {
        if (accountIds.contains(null)) {
            accountIds.remove(null);
        }
        return [SELECT Id, Business_Unit__c, Account__c 
                FROM Interactions__c 
                WHERE Account__c in: accountIds
                AND Business_Unit__c in: bUs];
    }
    
    public static List<Interactions__c> getInteractionsByIds (Set<Id> interactionIds) {
        if (interactionIds.contains(null)) {
            interactionIds.remove(null);
        }
        return [SELECT Id, Account__c, Business_Unit__c 
                FROM Interactions__c WHERE Id in : interactionIds];
    }
}