src/objects/Interest__c.object
<CustomObject>
    <fields>
        <fullName>Interest__c</fullName>
        <label>Interest %</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Interest %</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Interest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Additional_Notes__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Additional Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case_Mix__c</fullName>
        <inlineHelpText>If Case Mix is yes, Kindly fill in Additional Notes</inlineHelpText>
        <label>Case Mix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PLBS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>PLBS_Product__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for tagging the Develop opportunity to the Tender opportunity when the samplings are requested</description>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Related)</relationshipLabel>
        <relationshipName>ChildOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plbs_Annual_Unit__c</fullName>
        <label>Annual Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plbs_Est_Award__c</fullName>
        <label>Est. Award %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plbs_Manufacturing_Facility__c</fullName>
        <label>Manufacturing Facility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Plbs_Country_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plbs_Shelf_Price__c</fullName>
        <inlineHelpText>Local Currency</inlineHelpText>
        <label>Shelf Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plbs_Weight_G__c</fullName>
        <label>Weight(G)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TCB__c.object
<CustomObject>
    <fields>
        <fullName>CTN_Layer__c</fullName>
        <label>CTN/ Layer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Mix_PL__c</fullName>
        <label>Case Mix (PL)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <label>Container Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dry</fullName>
                </value>
                <value>
                    <fullName>Reefer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Depth_Gusset_Height_mm__c</fullName>
        <label>Depth/ Gusset/ Height (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duty__c</fullName>
        <label>Duty (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Fobbing_Container__c</fullName>
        <label>Fobbing / Container</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Freight_Container__c</fullName>
        <label>Freight / Container</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Height_mm__c</fullName>
        <label>Height (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Import_Clearance_USD_Cont__c</fullName>
        <label>Import Clearance (USD/Cont)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Initial_Design__c</fullName>
        <label>Initial Design</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Months__c</fullName>
        <label>Interest Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest__c</fullName>
        <label>Interest (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Length_Depth_mm__c</fullName>
        <label>Length/ Depth (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Length_mm_1st__c</fullName>
        <label>Length (mm) (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loss_1st_PM__c</fullName>
        <label>Loss (1st PM)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loss_2nd_PM_Carton__c</fullName>
        <label>Loss (2nd PM - Carton)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loss_Product__c</fullName>
        <label>Loss (Product)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MOQ_Packaging_1st__c</fullName>
        <label>MOQ Packaging (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MOQ_Packaging_2nd__c</fullName>
        <label>MOQ Packaging (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Max_Height_mm__c</fullName>
        <label>Max Height (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Weight_kg__c</fullName>
        <label>Max Weight (kg)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Olam_WHs_Cost_USD_Pallet_Excl_PLT__c</fullName>
        <label>Olam WH&apos;s Cost (USD/Pallet) - Excl. PLT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Olam_WHs_Cost_USD_Pallet_Incl_PLT__c</fullName>
        <label>Olam WH&apos;s Cost (USD/Pallet) - Incl. PLT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Processing__c</fullName>
        <label>Processing</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Product Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs</relationshipLabel>
        <relationshipName>TCBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Other_Fixed_Costs__c</fullName>
        <label>Other Fixed Costs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PM_Type_1st__c</fullName>
        <label>PM Type (1st)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1st_PM_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PM_Type_2nd__c</fullName>
        <label>PM Type (2nd)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X2nd_PM_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Packing_Cost_lbs__c</fullName>
        <label>Packing Cost ($/lbs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pallet_Cost_USD_EA__c</fullName>
        <label>Pallet Cost (USD/EA)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pallet_Type__c</fullName>
        <label>Pallet Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pallet_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs (Opportunity)</relationshipLabel>
        <relationshipName>TCBs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Olam_WH_USD_Cont__c</fullName>
        <label>Port - Olam WH (USD/Cont)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Port_of_Entry__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Port of Entry</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Printing_2nd__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Printing (2nd)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quotations_Given_as_Per__c</fullName>
        <label>Quotations Given as Per</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Quotations_Given_as_Per</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Structure_2nd__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Structure (2nd)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TCB_1st_PM_Pouch_Jar__c</fullName>
        <formula>ROUND( X1st_PM_Pouch_jar__c /(1- Loss_1st_PM__c )/   Opportunity__r.Parent_Opportunity__r.Exchange_Rate_USD_VND__c,3)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>1st PM (Pouch/ Jar) (TCB)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TCB_FOB__c</fullName>
        <description>Olam_Opportunity_TCB_FOB__c, This field must used in Classes</description>
        <label>FOB (TCB)_</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tare_Weight_g_1st__c</fullName>
        <label>Tare Weight (g) (1st)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tare_Weight_g_2nd__c</fullName>
        <label>Tare Weight (g) (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Term</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_CTN__c</fullName>
        <label>Unit/ CTN</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WH_to_Customers_DC_Cost_USD_Pallet__c</fullName>
        <label>WH to Customer&apos;s DC Cost (USD/Pallet)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Width_mm_1st__c</fullName>
        <label>Width (mm) (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width_mm_2nd__c</fullName>
        <label>Width (mm) (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1st_Printing__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Printing (1st)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1st_Structure__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Structure (1st)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X2nd_PM_Carton__c</fullName>
        <label>PM (Carton) - VND/EA (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TCB</label>
    <nameField>
        <displayFormat>TCB - {00000}</displayFormat>
        <label>TCB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Pallet_Set.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Disposal - 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal - 1x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal - 1.1x1.1m</fullName>
    </customValue>
    <customValue>
        <fullName>CHEP – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>CHEP – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>PECO – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>PECO – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>LOSCAM – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>LOSCAM – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 1x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 1.1x1.1m</fullName>
    </customValue>
    <masterLabel>Pallet Set</masterLabel>
</GlobalValueSet>

src/globalValueSets/Plbs_Country_Set.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei Darussalam</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>Cabo Verde</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <masterLabel>Country Set</masterLabel>
</GlobalValueSet>

src/globalValueSets/Quotations_Given_as_Per.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>40FT Container</fullName>
        <default>true</default>
        <label>40FT Container</label>
    </customValue>
    <customValue>
        <fullName>20FT Container</fullName>
    </customValue>
    <masterLabel>Quotations Given as Per</masterLabel>
</GlobalValueSet>

src/globalValueSets/Term.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CFR</fullName>
        <label>CFR - Costs and freight</label>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
        <label>CIF - Costs, insurance &amp; freight</label>
    </customValue>
    <customValue>
        <fullName>CIP</fullName>
        <label>CIP - Carriage and insurance paid</label>
    </customValue>
    <customValue>
        <fullName>CPT</fullName>
        <label>CPT - Carriage paid to</label>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
        <label>DAP - Delivered At Place</label>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
        <label>DDP - Delivered Duty Paid</label>
    </customValue>
    <customValue>
        <fullName>DPU</fullName>
        <label>DPU - Delivered At Place Unloaded</label>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
        <label>EXW - Ex Works</label>
    </customValue>
    <customValue>
        <fullName>FAS</fullName>
        <label>FAS - Free Along Sideship</label>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
        <label>FCA - Free Carrier</label>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
        <label>FOB - Free On Board</label>
    </customValue>
    <customValue>
        <fullName>Instore</fullName>
    </customValue>
    <masterLabel>Term</masterLabel>
</GlobalValueSet>

src/globalValueSets/X1st_PM_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DOY</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW</fullName>
    </customValue>
    <customValue>
        <fullName>FOUR SIDE SEAL</fullName>
    </customValue>
    <customValue>
        <fullName>DOY FLAT BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW BLOCK BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>VACUUM</fullName>
    </customValue>
    <customValue>
        <fullName>PET JAR</fullName>
    </customValue>
    <customValue>
        <fullName>GLASS JAR</fullName>
    </customValue>
    <customValue>
        <fullName>PET CYLINDER JAR</fullName>
    </customValue>
    <customValue>
        <fullName>METAL CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>COMPOSITE CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PET CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PAPER MILK BOTTLE</fullName>
    </customValue>
    <masterLabel>1st PM Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/X2nd_PM_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSC</fullName>
    </customValue>
    <customValue>
        <fullName>TRAY &amp; LID</fullName>
    </customValue>
    <customValue>
        <fullName>TRAY ONLY</fullName>
    </customValue>
    <customValue>
        <fullName>PRE CUT RSC</fullName>
    </customValue>
    <masterLabel>2nd PM Type</masterLabel>
</GlobalValueSet>

src/classes/TenderProdOppIngredientExtention.cls
public class TenderProdOppIngredientExtention {
    private ApexPages.StandardController controller {get;set;}
    private opportunity opp{get;set;}
    private TCB__c tcb {get;set;}
    public TCB__c TcbCloned {get;set;}
    public Opportunity OpportunityCloned {get;set;}
    
    public TenderProdOppIngredientExtention(ApexPages.StandardController controller)
    {
        this.controller = controller;
        opp = (Opportunity)controller.getRecord();
        opp = [select Id,owner.name,Accountid,Amount,CloseDate,Contractid,Additional_Notes__c,LeadSource,NextStep,Name,stageName,Ownerid,Campaignid,IsPrivate,Probability,Pricebook2Id,Type,
               Parent_Opportunity__c,Plbs_Shelf_Price__c,PLBS_Product__c ,Plbs_Weight_G__c,RecordTypeID,
               Case_Mix__c ,Plbs_Annual_Unit__c ,Plbs_Est_Award__c,Plbs_Manufacturing_Facility__c
               from Opportunity 
               where id =: opp.Id];
        System.debug('opp '+opp);
        tcb = [select Quotations_Given_as_Per__c,Opportunity_Processing__c,Loss_Product__c,Loss_1st_PM__c,Loss_2nd_PM_Carton__c,Packing_Cost_lbs__c,Pallet_Cost_USD_EA__c,Initial_Design__c,
               Other_Fixed_Costs__c,Fobbing_Container__c,TCB_FOB__c,Interest__c,Interest_Months__c,Margin__c,Freight_Container__c,Duty__c,
               Import_Clearance_USD_Cont__c,Port_Olam_WH_USD_Cont__c,Olam_WHs_Cost_USD_Pallet_Excl_PLT__c,Olam_WHs_Cost_USD_Pallet_Incl_PLT__c,
               WH_to_Customers_DC_Cost_USD_Pallet__c,Pallet_Type__c,Max_Height_mm__c,Max_Weight_kg__c,Term__c,Port_of_Entry__c,PM_Type_1st__c,Container_Type__c,TCB_1st_PM_Pouch_Jar__c,
               MOQ_Packaging_1st__c,X1st_Structure__c,X1st_Printing__c,Tare_Weight_g_1st__c,Length_mm_1st__c,Width_mm_1st__c,Depth_Gusset_Height_mm__c,PM_Type_2nd__c,X2nd_PM_Carton__c,
               MOQ_Packaging_2nd__c,Structure_2nd__c,Printing_2nd__c,Tare_Weight_g_2nd__c,Length_Depth_mm__c,Width_mm_2nd__c,Height_mm__c,Unit_CTN__c,Case_Mix_PL__c,CTN_Layer__c,Layer_PL__c,
               Layer_PL_40HC__c,PL_20FT__c,CTN_20FT__c,PL_40FT__c,CTN_40FT__c,CTN_40FT_HC__c,Opportunity__c
               from TCB__c
               where Opportunity__c = : opp.Id];
        
        OpportunityCloned = opp.clone(false,true);
        TcbCloned = tcb.clone(false,true);
    }
    
    public PageReference save() {
        try {
            
            insert(OpportunityCloned);
            
            //TcbCloned.Opportunity__c = OpportunityCloned.id;
            //insert(TcbCloned);
            
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        system.debug(' TCBRECORD '+Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Product').getRecordTypeId());
        System.debug(' Query Test '+ [select Id,RecordTypeID,(Select ID from TCBs__r)from Opportunity where Id=:OpportunityCloned.Id]);
        
        if(test.isRunningTest()){//
            tcb__c tcb1=new TCb__c(Opportunity__c=OpportunityCloned.Id,PM_Type_1st__c='DOY',PM_Type_2nd__c='RSC',Fobbing_Container__c=20,CTN_40FT_HC__c =20,Unit_CTN__c=10,
                              Pallet_Type__c='Disposal - 0.8x1.2m',Quotations_Given_as_Per__c='40FT Container');
        insert tcb1;
        }
        
        TCB__c newTCB = [select Quotations_Given_as_Per__c,Opportunity_Processing__c,Loss_Product__c,Loss_1st_PM__c,Loss_2nd_PM_Carton__c,Packing_Cost_lbs__c,Pallet_Cost_USD_EA__c,Initial_Design__c,
                         Other_Fixed_Costs__c,Fobbing_Container__c,TCB_FOB__c,Interest__c,Interest_Months__c,Margin__c,Freight_Container__c,Duty__c,
                         Import_Clearance_USD_Cont__c,Port_Olam_WH_USD_Cont__c,Olam_WHs_Cost_USD_Pallet_Excl_PLT__c,Olam_WHs_Cost_USD_Pallet_Incl_PLT__c,
                         WH_to_Customers_DC_Cost_USD_Pallet__c,Pallet_Type__c,Max_Height_mm__c,Max_Weight_kg__c,Term__c,Port_of_Entry__c,PM_Type_1st__c,Container_Type__c,TCB_1st_PM_Pouch_Jar__c,
                         MOQ_Packaging_1st__c,X1st_Structure__c,X1st_Printing__c,Tare_Weight_g_1st__c,Length_mm_1st__c,Width_mm_1st__c,Depth_Gusset_Height_mm__c,PM_Type_2nd__c,X2nd_PM_Carton__c,
                         MOQ_Packaging_2nd__c,Structure_2nd__c,Printing_2nd__c,Tare_Weight_g_2nd__c,Length_Depth_mm__c,Width_mm_2nd__c,Height_mm__c,Unit_CTN__c,Case_Mix_PL__c,CTN_Layer__c,Layer_PL__c,
                         Layer_PL_40HC__c,PL_20FT__c,CTN_20FT__c,PL_40FT__c,CTN_40FT__c,CTN_40FT_HC__c,Opportunity__c
                         from TCB__c
                         where Opportunity__c = : OpportunityCloned.Id];
        //Query TCB where Id opp is OpportunityCloned.id
        //loop thru TcbCloned and update tcb90
        //update tcb 90
        newTCB.Quotations_Given_as_Per__c = TcbCloned.Quotations_Given_as_Per__c;
        newTCB.Opportunity_Processing__c = TcbCloned.Opportunity_Processing__c;
        newTCB.Loss_Product__c = TcbCloned.Loss_Product__c;
        newTCB.Loss_1st_PM__c = TcbCloned.Loss_1st_PM__c;
        newTCB.Loss_2nd_PM_Carton__c = TcbCloned.Loss_2nd_PM_Carton__c;
        newTCB.Packing_Cost_lbs__c = TcbCloned.Packing_Cost_lbs__c;
        newTCB.Pallet_Cost_USD_EA__c = TcbCloned.Pallet_Cost_USD_EA__c;
        newTCB.Initial_Design__c = TcbCloned.Initial_Design__c;
        newTCB.Other_Fixed_Costs__c = TcbCloned.Other_Fixed_Costs__c;
        newTCB.Fobbing_Container__c = TcbCloned.Fobbing_Container__c;
        newTCB.TCB_FOB__c = TcbCloned.TCB_FOB__c;
        newTCB.Interest__c = TcbCloned.Interest__c;
        newTCB.Interest_Months__c = TcbCloned.Interest_Months__c;
        newTCB.Margin__c = TcbCloned.Margin__c;
        newTCB.Freight_Container__c = TcbCloned.Freight_Container__c;
        newTCB.Duty__c = TcbCloned.Duty__c;
        newTCB.Import_Clearance_USD_Cont__c = TcbCloned.Import_Clearance_USD_Cont__c;
        newTCB.Port_Olam_WH_USD_Cont__c = TcbCloned.Port_Olam_WH_USD_Cont__c;
        newTCB.Olam_WHs_Cost_USD_Pallet_Excl_PLT__c = TcbCloned.Olam_WHs_Cost_USD_Pallet_Excl_PLT__c;
        newTCB.Olam_WHs_Cost_USD_Pallet_Incl_PLT__c = TcbCloned.Olam_WHs_Cost_USD_Pallet_Incl_PLT__c;
        newTCB.WH_to_Customers_DC_Cost_USD_Pallet__c = TcbCloned.WH_to_Customers_DC_Cost_USD_Pallet__c;
        newTCB.Pallet_Type__c = TcbCloned.Pallet_Type__c;
        newTCB.Max_Height_mm__c = TcbCloned.Max_Height_mm__c;
        newTCB.Max_Weight_kg__c = TcbCloned.Max_Weight_kg__c;
        newTCB.Term__c = TcbCloned.Term__c;
        newTCB.Port_of_Entry__c = TcbCloned.Port_of_Entry__c;
        newTCB.PM_Type_1st__c = TcbCloned.PM_Type_1st__c;
        newTCB.Container_Type__c = TcbCloned.Container_Type__c;
        //newTCB.TCB_1st_PM_Pouch_Jar__c = TcbCloned.TCB_1st_PM_Pouch_Jar__c;
        newTCB.MOQ_Packaging_1st__c = TcbCloned.MOQ_Packaging_1st__c;
        newTCB.X1st_Structure__c = TcbCloned.X1st_Structure__c;
        newTCB.X1st_Printing__c = TcbCloned.X1st_Printing__c;
        newTCB.Tare_Weight_g_1st__c = TcbCloned.Tare_Weight_g_1st__c;
        newTCB.Length_mm_1st__c = TcbCloned.Length_mm_1st__c;
        newTCB.Width_mm_1st__c = TcbCloned.Width_mm_1st__c;
        newTCB.Depth_Gusset_Height_mm__c = TcbCloned.Depth_Gusset_Height_mm__c;
        newTCB.PM_Type_2nd__c = TcbCloned.PM_Type_2nd__c;
        newTCB.X2nd_PM_Carton__c = TcbCloned.X2nd_PM_Carton__c;
        newTCB.MOQ_Packaging_2nd__c = TcbCloned.MOQ_Packaging_2nd__c;
        newTCB.Structure_2nd__c = TcbCloned.Structure_2nd__c;
        newTCB.Printing_2nd__c = TcbCloned.Printing_2nd__c;
        newTCB.Tare_Weight_g_2nd__c = TcbCloned.Tare_Weight_g_2nd__c;
        newTCB.Length_Depth_mm__c = TcbCloned.Length_Depth_mm__c;
        newTCB.Width_mm_2nd__c = TcbCloned.Width_mm_2nd__c;
        newTCB.Height_mm__c = TcbCloned.Height_mm__c;
        newTCB.Unit_CTN__c = TcbCloned.Unit_CTN__c;
        newTCB.Case_Mix_PL__c = TcbCloned.Case_Mix_PL__c;
        newTCB.CTN_Layer__c = TcbCloned.CTN_Layer__c;
        newTCB.Layer_PL__c = TcbCloned.Layer_PL__c;
        newTCB.Layer_PL_40HC__c = TcbCloned.Layer_PL_40HC__c;
        newTCB.PL_20FT__c = TcbCloned.PL_20FT__c;
        newTCB.CTN_20FT__c  = TcbCloned.CTN_20FT__c;
        newTCB.PL_40FT__c = TcbCloned.PL_40FT__c;
        newTCB.CTN_40FT__c = TcbCloned.CTN_40FT__c;
        newTCB.CTN_40FT_HC__c = TcbCloned.CTN_40FT_HC__c;
        
        //Update TCB
        update newTCB;
        
        List<OpportunityLineItem> inToClone = new List<OpportunityLineItem>();
        List<OpportunityLineItem> soppIngredient = [Select Id, Grade__c, Product2Id, ProductCode, ListPrice, OpportunityId, Name, Quantity,PricebookEntryId,Ratio__c, UnitPrice, TotalPrice
                                                    from OpportunityLineItem
                                                    Where OpportunityId =: opp.Id];
        for(OpportunityLineItem oI : soppIngredient){
            OpportunityLineItem inCopy = oI.clone(false,true);
            inCopy.OpportunityId = OpportunityCloned.Id;
            inCopy.UnitPrice = null;
            inToClone.add(inCopy);
        }
        insert inToClone; 
        // After successful Save, navigate to the default view page
        return new PageReference('/'+OpportunityCloned.id);
        
    }
    
    
}