src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PLBS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>PLBS_Product__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plbs_Weight_G__c</fullName>
        <label>Weight(G)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>TEXT(PLBS_Product__r.Product_Family__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Ingredient_Price_No_Processing__c</fullName>
        <label>Total Ingredient Price(No Processing)</label>
        <summarizedField>OpportunityLineItem.Total_Price_Olam__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Packing_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Packing Cost</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Packing Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Cost</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pallet__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Pallet</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Pallet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pallet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PLBS_Product__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Family__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>PLBS_Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Family</valueSetName>
        </valueSet>
    </fields>
    <label>Private Label Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Private Label Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Price_Kit__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processing_cost_USD_lb__c</fullName>
        <label>Processing cost (USD/lb)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Processing_loss__c</fullName>
        <label>Processing loss %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PLBS_Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Family</valueSetName>
        </valueSet>
    </fields>
    <label>Product Price Kit</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product Price Kit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Price Kit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quotations_as_per__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Quotations as per</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Quotations as per Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations as per</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TCB__c.object
<CustomObject>
    <fields>
        <fullName>Clearance_Pack_FL__c</fullName>
        <formula>IF(ISPICKVAL(  Quotations_Given_as_Per__c , &quot;40FT Container&quot;),  Import_Clearance_USD_Cont__c /  Pack_40FT_HC_FL__c ,  Import_Clearance_USD_Cont__c /  Pack_20FT_FL__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Clearance/ Pack (FL)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Dest_Haulage_Port_WH_Pack_FL__c</fullName>
        <formula>IF(ISPICKVAL(  Quotations_Given_as_Per__c , &quot;40FT Container&quot;),  Port_Olam_WH_USD_Cont__c /  Pack_40FT_HC_FL__c , Port_Olam_WH_USD_Cont__c /  Pack_20FT_FL__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dest. Haulage (Port - WH)/ Pack (FL)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Duty_Pack_FL__c</fullName>
        <formula>(TCB_FOB__c +  Freight_Pack_FL__c )*  Duty__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duty/ Pack (FL)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fixed_Costs_TCB__c</fullName>
        <formula>Other_Fixed_Costs__c / Opportunity__r.Plbs_Annual_Unit__c / Opportunity__r.Plbs_Est_Award__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fixed Costs (TCB)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Freight_Pack_FL__c</fullName>
        <formula>ROUND(IF(ISPICKVAL(  Quotations_Given_as_Per__c  , &quot;40FT Container&quot;),  Freight_Container__c /  Pack_40FT_HC_FL__c ,  Freight_Container__c /   Pack_20FT_FL__c ),2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Freight/ Pack (FL)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Initial_Design_TCB__c</fullName>
        <formula>Initial_Design__c / Opportunity__r.Plbs_Annual_Unit__c / Opportunity__r.Plbs_Est_Award__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initial Design (TCB)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_TCB__c</fullName>
        <formula>(  Product_TCB__c +  TCB_1st_PM_Pouch_Jar__c +  TCB_2nd_PM_Outer__c +  Pallet_TCB__c +  Packing_TCB__c +  Initial_Design_TCB__c +  Fixed_Costs_TCB__c +  Fobbing_Fee_TCB__c )*  Interest_Months__c / 12 *  Interest__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Interest (TCB)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loss_Product__c</fullName>
        <label>Loss (Product)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Margin_TCB__c</fullName>
        <formula>(  Product_TCB__c +  TCB_1st_PM_Pouch_Jar__c +  TCB_2nd_PM_Outer__c +  Pallet_TCB__c +  Packing_TCB__c +  Initial_Design_TCB__c +  Fixed_Costs_TCB__c +  Fobbing_Fee_TCB__c +  Interest_TCB__c )*  Margin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Margin (TCB)</label>
        <precision>18</precision>
        <scale>16</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Processing__c</fullName>
        <label>Processing</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Product Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs</relationshipLabel>
        <relationshipName>TCBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Packing_TCB__c</fullName>
        <formula>Packing_Cost_lbs__c * Opportunity__r.Plbs_Weight_G__c / 1000 * 2.2046</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Packing (TCB)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Packing_loss__c</fullName>
        <label>Packing loss %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pallet_TCB__c</fullName>
        <formula>IF( ISPICKVAL( Quotations_Given_as_Per__c , &quot;40FT Container&quot;),  Pallet_Cost_USD_EA__c /  Pack_40HC_PL__c , Pallet_Cost_USD_EA__c /  Pack_PL__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pallet (TCB)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_TCB__c</fullName>
        <formula>Total_Ingredient_Price__c *  Opportunity__r.Plbs_Weight_G__c / 1000 /( 1 -  Loss_Product__c )*2.2046</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product (TCB)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quotations_Given_as_Per__c</fullName>
        <label>Quotations Given as Per</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Quotations_Given_as_Per</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TCB_1st_PM_Pouch_Jar__c</fullName>
        <formula>ROUND( X1st_PM_Pouch_jar__c /(1- Loss_1st_PM__c )/   Opportunity__r.Parent_Opportunity__r.Exchange_Rate_USD_VND__c,3)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>1st PM (Pouch/ Jar) (TCB)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TCB_2nd_PM_Outer__c</fullName>
        <formula>X2nd_PM_Carton__c /(1 -  Loss_2nd_PM_Carton__c )/  Opportunity__r.Parent_Opportunity__r.Exchange_Rate_USD_VND__c  / Unit_CTN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>2nd PM (Outer) (TCB)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trucking_Pack_FL__c</fullName>
        <formula>IF(ISPICKVAL( Quotations_Given_as_Per__c , &quot;40FT Container&quot;),  WH_to_Customers_DC_Cost_USD_Pallet__c /  Pack_40HC_PL__c, WH_to_Customers_DC_Cost_USD_Pallet__c /  Pack_PL__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trucking/ Pack (FL)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WH_Cost_Dest_Pack_FL__c</fullName>
        <formula>IF(ISPICKVAL(  Quotations_Given_as_Per__c , &quot;40FT Container&quot;),  Olam_WHs_Cost_USD_Pallet_Incl_PLT__c /  Pack_40HC_PL__c , Olam_WHs_Cost_USD_Pallet_Incl_PLT__c /  Pack_PL__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>WH Cost (Dest.)/ Pack (FL)</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Currency</type>
    </fields>
    <label>TCB</label>
    <nameField>
        <displayFormat>TCB - {00000}</displayFormat>
        <label>TCB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/X1st_PM__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loss__c</fullName>
        <label>Loss %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>1st PM</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>1st PM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1st PM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/X2nd_PM__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loss__c</fullName>
        <label>Loss %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>2nd PM</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>2nd PM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>2nd PM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/PLBS_Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Nut mixes</fullName>
    </customValue>
    <customValue>
        <fullName>Pasteurized nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Dry roasted nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Oil roasted nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Salts nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Seasoned nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Trail mixes</fullName>
    </customValue>
    <customValue>
        <fullName>Natural nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Blanched nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Diced nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Slivered nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Sliced nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Nut meal</fullName>
    </customValue>
    <customValue>
        <fullName>Natural paste</fullName>
    </customValue>
    <customValue>
        <fullName>Blanched paste</fullName>
    </customValue>
    <customValue>
        <fullName>Roasted paste</fullName>
    </customValue>
    <customValue>
        <fullName>Pure paste</fullName>
    </customValue>
    <customValue>
        <fullName>Flavored paste</fullName>
    </customValue>
    <customValue>
        <fullName>Granola</fullName>
    </customValue>
    <customValue>
        <fullName>Protein</fullName>
    </customValue>
    <customValue>
        <fullName>Coated bars</fullName>
    </customValue>
    <customValue>
        <fullName>Nut-based cookies</fullName>
    </customValue>
    <customValue>
        <fullName>Natural oil</fullName>
    </customValue>
    <customValue>
        <fullName>Infused oil</fullName>
    </customValue>
    <customValue>
        <fullName>Natural milk</fullName>
    </customValue>
    <customValue>
        <fullName>Flavored milk</fullName>
    </customValue>
    <customValue>
        <fullName>Single Nuts/Fruits</fullName>
        <isActive>false</isActive>
        <label>Single Nuts/Fruits</label>
    </customValue>
    <customValue>
        <fullName>Mixed Nuts</fullName>
        <isActive>false</isActive>
        <label>Mixed Nuts</label>
    </customValue>
    <customValue>
        <fullName>Nut Meal/Flour</fullName>
        <isActive>false</isActive>
        <label>Nut Meal/Flour</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Family.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Snacks</fullName>
    </customValue>
    <customValue>
        <fullName>Ingredients</fullName>
    </customValue>
    <customValue>
        <fullName>Paste</fullName>
    </customValue>
    <customValue>
        <fullName>Bars &amp; Cookies</fullName>
    </customValue>
    <customValue>
        <fullName>Nut &amp; Seed Oils</fullName>
    </customValue>
    <customValue>
        <fullName>Milk</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

src/globalValueSets/Quotations_Given_as_Per.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>40FT Container</fullName>
        <default>true</default>
        <label>40FT Container</label>
    </customValue>
    <customValue>
        <fullName>20FT Container</fullName>
    </customValue>
    <masterLabel>Quotations Given as Per</masterLabel>
</GlobalValueSet>

src/classes/TCBTriggerHelper.cls
public class TCBTriggerHelper {
            

    public static void updateFromPriceKit(list<TCB__c> listOfTCB, Set<id> setOfOppID,boolean isUpdate){
        system.debug('Inside updateFromPriceKit');
        Map<id,Opportunity> mapOfOppID = new  Map<id,Opportunity>();
        Set<String> productFamily = new Set<String>();
        Set<String> productCategory= new Set<String>();
        Map<id,id> mapOfOppIdToProdId=new Map<id,id>();      
        List<TCB__c> listOfTCBToUpdate = new List<TCB__c>();
        
        for(Opportunity Opp:[select id,PLBS_Product__c,Plbs_Weight_G__c from Opportunity where id in :setOfOppID]){
            mapOfOppID.put(opp.id,opp);
            mapOfOppIdToProdId.put(opp.Id,opp.PLBS_Product__c); 
        }
        system.debug('mapOfOppID ' +mapOfOppID);
        system.debug('mapOfOppIdToProdId ' +mapOfOppIdToProdId);
        Map<Id,PLBS_Product__c>  oppProductMap = new Map<Id,PLBS_Product__c>([Select id, Product_Family__c , Product_Category__c from PLBS_Product__c
                                                                              where id in: mapOfOppIdToProdId.values()]);
        system.debug('oppProductMap' +oppProductMap);
        if(oppProductMap.values().size() > 0){
            for(PLBS_Product__c proPrice: oppProductMap.values()){
                productFamily.add(proPrice.Product_Family__c);
                productCategory.add(proPrice.Product_Category__c);
            }
        }
        
        List<Product_Price_Kit__c> priceKitList = [Select id, Product_Family__c , Product_Category__c, Processing_loss__c , Processing_cost_USD_lb__c	
                                                   from Product_Price_Kit__c
                                                   where Product_Family__c in: productFamily
                                                   And Product_Category__c in: productCategory
                                                   And Active__c = TRUE];
        system.debug('priceKitList ' +priceKitList);
        for(TCB__c Tcb: listOfTCB){
            for (Product_Price_Kit__c matchedPrice : priceKitList) {
                if (matchedPrice.Product_Family__c == oppProductMap.get(mapOfOppIdToProdId.get(Tcb.Opportunity__c)).Product_Family__c &&
                    matchedPrice.Product_Category__c == oppProductMap.get(mapOfOppIdToProdId.get(Tcb.Opportunity__c)).Product_Category__c) {
                        if(isUpdate){
                            TCB__c tempTcb = new TCB__c(Id=Tcb.Id);
                            tempTcb.Opportunity_Processing__c = matchedPrice.Processing_cost_USD_lb__c;
                            tempTcb.Packing_loss__c  = (0.5 + (1/mapOfOppID.get(Tcb.Opportunity__c).Plbs_Weight_G__c)*100);
                            tempTcb.Loss_Product__c = matchedPrice.Processing_loss__c + (0.5 + (1/mapOfOppID.get(Tcb.Opportunity__c).Plbs_Weight_G__c )*100);
                            listOfTCBToUpdate.add(tempTcb);	
                            system.debug('TCB Update '+Tcb.Opportunity_Processing__c +' ' + Tcb.Packing_loss__c  +' '+Tcb.Loss_Product__c);
                        }else{
                            Tcb.Opportunity_Processing__c = matchedPrice.Processing_cost_USD_lb__c;
                            Tcb.Packing_loss__c  = (0.5 + (1/mapOfOppID.get(Tcb.Opportunity__c).Plbs_Weight_G__c)*100);
                            Tcb.Loss_Product__c = matchedPrice.Processing_loss__c + (0.5 + (1/mapOfOppID.get(Tcb.Opportunity__c).Plbs_Weight_G__c )*100);
                            system.debug('TCB VALUES '+Tcb.Opportunity_Processing__c +' ' + Tcb.Packing_loss__c  +' '+Tcb.Loss_Product__c);
                        }
                    }
            }
        }
        if(!listOfTCBToUpdate.isEmpty()){
            system.debug('TCB listOfTCBToUpdate '+listOfTCBToUpdate);
            update listOfTCBToUpdate;
        }
    }
    
    public static void calculate_EBITDA_FOB_DDP_USA_Pack_Floor_Load(list<TCB__c> listOfTCB,set<Id> OppId){
            Map<Id,Opportunity> mapOfIdToOpp=new map<Id,opportunity>([select id,Total_Ingredient_Price_No_Processing__c,Plbs_Weight_G__c from Opportunity where Id in :OppId]);
        String[] FieldSet1 = new String[]{'Product_TCB__c','TCB_1st_PM_Pouch_Jar__c','TCB_2nd_PM_Outer__c','Packing_TCB__c',
            								'Initial_Design_TCB__c','Fixed_Costs_TCB__c','Interest_TCB__c','Margin_TCB__c'};
     
        String[] fieldSet2 = new String[]{'Freight_Pack_FL__c','Duty_Pack_FL__c','Clearance_Pack_FL__c','Dest_Haulage_Port_WH_Pack_FL__c',
            								'WH_Cost_Dest_Pack_FL__c','Trucking_Pack_FL__c','Pallet_TCB__c'};        
       
                        
                        for(TCB__c tcb: listOfTCB) {
                            Decimal sum1a = 0;
                            for(String field1a: FieldSet1){
                                if (tcb.get(field1a) != null){
                                    sum1a  += (Decimal)tcb.get(field1a);
                                }
                            }
                            // calculate sum1b
                            Decimal sum1b = 0;
                            Decimal sum1 = 0;
                         if (	  tcb.Quotations_Given_as_Per__c 	== '40FT Container' 
                                && tcb.Pack_40FT_HC_FL__c 			!= null 
                                && tcb.Pack_40FT_HC_FL__c 			!= 0 
                                && tcb.Fobbing_Container__c 		!= null
                               ){
                                   
                                   sum1b = tcb.Fobbing_Container__c/tcb.Pack_40FT_HC_FL__c;
                               }
                            else if(   tcb.Quotations_Given_as_Per__c 	!= '40FT Container' //check 20 or 40ft, confirm it?
                                    && tcb.Pack_20FT_FL__c 				!= null 
                                    && tcb.Pack_20FT_FL__c 				!= 0 
                                    && tcb.Fobbing_Container__c			!= null
                                   ){
                                       sum1b = tcb.Fobbing_Container__c/tcb.Pack_20FT_FL__c;
                                   }
                            sum1 = sum1a + sum1b;
                            tcb.FOB_USD_Pack_Floor_Load__c = sum1;
                               // calculate sum2                    
                            Decimal sum2 =0;
                            tcb.DDP_USD_Pack_Floor_Load__c = 0;
                            for(String field2: fieldSet2){
                                if(tcb.get(field2) != null){
                                    system.debug(field2);
                                    system.debug((Decimal)tcb.get(field2));
                                    sum2 += (Decimal)tcb.get(field2);
                                    system.debug('tcb.FOB_USD_Pack_Floor_Load__c');
                                    system.debug(tcb.FOB_USD_Pack_Floor_Load__c);
                                    tcb.DDP_USD_Pack_Floor_Load__c = sum2 + tcb.FOB_USD_Pack_Floor_Load__c;
                                }
                            }
                            system.debug('sum1a: ' + sum1a + '  ' + 'sum1b: ' + sum1b + '  '+ 'sum1: ' + sum1 + '  '+ 'sum2: ' + sum2 + '  '+ 'Final:'+ tcb.DDP_USD_Pack_Floor_Load__c);
                             system.debug('Total Int ' + mapOfIdToOpp.get(tcb.Opportunity__c).Total_Ingredient_Price_No_Processing__c +' '+ mapOfIdToOpp.get(tcb.Opportunity__c).Plbs_Weight_G__c);
                             system.debug('tcb.Interest_TCB__c ' +tcb.Interest_TCB__c +' '+tcb.Margin_TCB__c); 
                            tcb.EBITDA_USD_Pack__c = 0;
                            if(  mapOfIdToOpp.get(tcb.Opportunity__c).Total_Ingredient_Price_No_Processing__c != null 
                               && mapOfIdToOpp.get(tcb.Opportunity__c).Total_Ingredient_Price_No_Processing__c != 0
                               && tcb.Interest_TCB__c            != null
                               && tcb.Margin_TCB__c 			 != null
                               && mapOfIdToOpp.get(tcb.Opportunity__c).Plbs_Weight_G__c 		 != null
                               && mapOfIdToOpp.get(tcb.Opportunity__c).Plbs_Weight_G__c			 != 0){
                                   tcb.EBITDA_USD_Pack__c = tcb.Interest_TCB__c + tcb.Margin_TCB__c 
                                       - ((1450836.38/5880000)/1000 * mapOfIdToOpp.get(tcb.Opportunity__c).Plbs_Weight_G__c);
                               }
                            else if(mapOfIdToOpp.get(tcb.Opportunity__c).Total_Ingredient_Price_No_Processing__c != null
                                    && mapOfIdToOpp.get(tcb.Opportunity__c).Total_Ingredient_Price_No_Processing__c == 0){
                                        tcb.EBITDA_USD_Pack__c = 0;
                                    }
                            system.debug('EBITDA_USD_Pack__c: ' + tcb.EBITDA_USD_Pack__c);
                         
                        }
    }
    
    public static void updateFrom1stPM(list<TCB__c> listOfTCB, Set<String> PmType1st){
        system.debug('Inside updateFrom1stPM');
        map<String,X1st_PM__c> mapofPm1st = new Map<String, X1st_PM__c>();
        List<X1st_PM__c> Pm1stList = [Select id, X1st_PM_Type__c, Loss__c from X1st_PM__c
                                      where X1st_PM_Type__c  in: pmType1st And Active__c = TRUE];
        system.debug('Pm1stList '+Pm1stList);
        for(X1st_PM__c match1stPM : Pm1stList){
            mapofPm1st.put(match1stPM.X1st_PM_Type__c, match1stPM);
        }
        
        for(TCB__c tcb:listOfTCB){
            if(mapofPm1st.containsKey(tcb.PM_Type_1st__c)){
                tcb.Loss_1st_PM__c=mapofPm1st.get(tcb.PM_Type_1st__c).Loss__c;
                system.debug('tcb.Loss_1st_PM__c '+tcb.Loss_1st_PM__c);
            }
        }
        
    }
    
    public static void updateFrom2ndPM(list<TCB__c> listOfTCB, Set<String> PmType2nd){
        system.debug('Inside updateFrom2ndPM');
        map<String,X2nd_PM__c> mapOfPm2nd = new Map<String, X2nd_PM__c>();
        List<X2nd_PM__c> Pm2ndList = [Select id, X2nd_PM_Type__c, Loss__c from X2nd_PM__c
                                      where X2nd_PM_Type__c in: pmType2nd And Active__c = TRUE ];
        system.debug('Pm2ndList '+Pm2ndList); 
        
        for(X2nd_PM__c match2ndPM : Pm2ndList){
            mapOfPm2nd.put(match2ndPM.X2nd_PM_Type__c, match2ndPM);
        }
        
        for(TCB__c tcb:listOfTCB){
            if(mapOfPm2nd.containsKey(tcb.PM_Type_2nd__c)){
                tcb.Loss_2nd_PM_Carton__c=mapOfPm2nd.get(tcb.PM_Type_2nd__c).Loss__c;
                system.debug('tcb.Loss_2nd_PM_Carton__c '+tcb.Loss_2nd_PM_Carton__c);
            }
        }
    }
    
    public static void updateFromPallet(list<TCB__c> listOfTCB, Set<String> palletType){
        system.debug('Inside updateFromPallet'); 
        map<String,Pallet__c> mapofPalletType = new Map<String, Pallet__c>(); 
        List<Pallet__c > PalletList = [Select id, Pallet_Type__c , USD_each__c from Pallet__c 
                                       where Pallet_Type__c  in: palletType And Active__c = TRUE];
        system.debug('PalletList '+PalletList);
        
        for(Pallet__c matchList : PalletList){
            mapofPalletType.put(matchList.Pallet_Type__c, matchList);
        }
        
        for(TCB__c tcb:listOfTCB){
            if(mapofPalletType.containsKey(tcb.Pallet_Type__c)){
                tcb.Pallet_Cost_USD_EA__c=mapofPalletType.get(tcb.Pallet_Type__c).USD_each__c;
                system.debug('tcb.Pallet_Cost_USD_EA__c '+tcb.Pallet_Cost_USD_EA__c);
            }
        }        
    }
    
    public static void updateFromPackingCost(set<Id> setOfOppIdToUpdateTCB){
        
        list<TCB__c> listOfTCBToUpdate= new list<TCB__c>();
        list<TCB__c> listOfTCB=[select Id,opportunity__r.Plbs_Weight_G__c,Packing_Cost_lbs__c from TCB__c where opportunity__c in :setOfOppIdToUpdateTCB];
        List<Packing_Cost__c > PackingCostList = [Select id, Packing_Cost_lbs__c, From__c, To__c from Packing_Cost__c 
                                                  where Active__c = TRUE];
        for(TCB__c tcb:listOfTCB){
            for(Packing_Cost__c MatchedList: PackingCostList){
                system.debug('tcb.Opportunity__r.Plbs_Weight_G__c '+tcb.Opportunity__r.Plbs_Weight_G__c+' MatchedList.From__c '+MatchedList.From__c+' MatchedList.To__c '+MatchedList.To__c );
                if(MatchedList.From__c < tcb.Opportunity__r.Plbs_Weight_G__c && MatchedList.To__c >=  tcb.Opportunity__r.Plbs_Weight_G__c){
                    TCB__c tcbs=new TCB__c(Id=tcb.Id);
                    tcbs.Packing_Cost_lbs__c = MatchedList.Packing_Cost_lbs__c;
                    system.debug('tcbs.Packing_Cost_lbs__c '+tcbs.Packing_Cost_lbs__c);
                    listOfTCBToUpdate.add(tcbs);
                }
            }
        }
        if(!listOfTCBToUpdate.isEmpty()){
            system.debug('listOfTCBToUpdate '+listOfTCBToUpdate);
            update listOfTCBToUpdate;
        }
    }
    
    public static void updateFromQuotationsAsPer(list<TCB__c> listOfTCB, Set<String> QuotationsAsPer){ 
        system.debug('Inside updateFromQuotationsAsPer'); 
        map<String,Quotations_as_per__c> mapOfQuotationsAsPer = new Map<String, Quotations_as_per__c>();
        List<Quotations_as_per__c  > QuotationsList = [Select id , USD__c, Fobbing_container__c  
                                                       from Quotations_as_per__c where Fobbing_container__c in:QuotationsAsPer And Active__c = TRUE];
        system.debug('QuotationsList '+QuotationsList);
        
        for(Quotations_as_per__c matchList : QuotationsList){
            mapOfQuotationsAsPer.put(matchList.Fobbing_container__c, matchList);
        }
        
        for(TCB__c tcb:listOfTCB){
            if(mapOfQuotationsAsPer.containsKey(tcb.Quotations_Given_as_Per__c)){
                tcb.Fobbing_Container__c=mapOfQuotationsAsPer.get(tcb.Quotations_Given_as_Per__c).USD__c;
                system.debug('tcb.Fobbing_Container__c '+tcb.Fobbing_Container__c);
            }
        }      
    }
    
}