src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Dispatched__c</fullName>
        <label>Quantity Dispatched</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_of_measure__c</fullName>
        <label>Unit of measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Development_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <label>Development Code</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sample_Request__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sample_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Development_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Development Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Product</label>
        <referenceTo>OpportunityLineItem</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Dispatched__c</fullName>
        <label>Quantity Dispatched</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SAP_Line_Item_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OSSM Line Item Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sample_Request__c</fullName>
        <label>Sample Request</label>
        <referenceTo>Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_of_measure__c</fullName>
        <label>Unit of measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                    <label>Metric Ton</label>
                </value>
                <value>
                    <fullName>LB</fullName>
                    <label>US pound</label>
                </value>
                <value>
                    <fullName>KG</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Gram</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sample Request Line Item</label>
    <nameField>
        <displayFormat>SRLI-{00000}</displayFormat>
        <label>Sample Request Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SampleRequest__e.object
<CustomObject>
    <fields>
        <fullName>SampleRequestId__c</fullName>
        <label>SampleRequestId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SampleRequest</label>
    <pluralLabel>SampleRequests</pluralLabel>
</CustomObject>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Unit_of_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MT</fullName>
        <default>true</default>
        <label>MT</label>
    </customValue>
    <customValue>
        <fullName>LB</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>QE</fullName>
        <isActive>false</isActive>
        <label>QE</label>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
        <isActive>false</isActive>
        <label>Carton</label>
    </customValue>
    <masterLabel>Unit of Measure</masterLabel>
</GlobalValueSet>

src/classes/SampleRequestLineItemHandler.cls
public class SampleRequestLineItemHandler 
{
    public static boolean isInitiatedFromSampleRequest = false;
    
    
    public static void afterInsert(List<Sample_Request_Line_Item__c> SampleRequestLineItemList){
        SampleRequestLineItemHelper.publishPlatformEvent(SampleRequestLineItemList);
    }
    
    
    public static void beforeUpdate(List<Sample_Request_Line_Item__c> SampleRequestList,Map<id,Sample_Request_Line_Item__c> oldSampleReqsMap){
        setIntegrationStatusOnStatusChange(SampleRequestList, oldSampleReqsMap);
        setIntegrationStatusQuantityChange(SampleRequestList, oldSampleReqsMap);
    }
    
	
	 public static void afterUpdate(List<Sample_Request_Line_Item__c> SampleRequestList,Map<id,Sample_Request_Line_Item__c> oldSampleReqsMap){
        if(OpportunityProductTriggerHelper.isIniatedFromOpportunityProduct == false){
            SampleRequestLineItemHandler.updateOppoLineOnOssmChanges(SampleRequestList,oldSampleReqsMap);
        }
         
        
        SampleRequestLineItemHelper.publishPlatformEventOnFeedback(SampleRequestList,oldSampleReqsMap);
        
        sendRequestOnAmmendment(SampleRequestList,oldSampleReqsMap);
        
    }

    
    public static void setIntegrationStatusOnStatusChange(List<Sample_Request_Line_Item__c> SampleRequestList,Map<id,Sample_Request_Line_Item__c> oldSampleReqsMap){
        Set<String> feedbackStatus = new Set<String>{'7', '8', '9', '10', '12', '13', '14', '16'};
        
        for(Sample_Request_Line_Item__c srLine :SampleRequestList){
            if(srLine.Sampling_Status__c != oldSampleReqsMap.get(srLine.Id).Sampling_Status__c && feedbackStatus.contains(srLine.Sampling_Status__c)){
                srLine.Integration_Status__c = 'feedback_update';
            }
        }
    }
    
    
    public static void setIntegrationStatusQuantityChange(List<Sample_Request_Line_Item__c> SampleRequestList,Map<id,Sample_Request_Line_Item__c> oldSampleReqsMap){
        for(Sample_Request_Line_Item__c srLine :SampleRequestList){
            if(srLine.SAP_Line_Item_Id__c != null && (srLine.Quantity__c != oldSampleReqsMap.get(srLine.Id).Quantity__c || srLine.Unit_of_measure__c != oldSampleReqsMap.get(srLine.Id).Unit_of_measure__c)){
                srLine.Integration_Status__c = 'amendment';
            }
        }
    }
  
     
   
    
    
    public static void sendRequestOnAmmendment(List<Sample_Request_Line_Item__c> SampleRequestList,Map<id,Sample_Request_Line_Item__c> oldSampleReqsMap){
        Set<String> sampleRequestIdSet = new Set<String>();
        
        for(Sample_Request_Line_Item__c srLine :SampleRequestList){
            if(srLine.Integration_Status__c != oldSampleReqsMap.get(srLine.Id).Integration_Status__c && srLine.Integration_Status__c == 'amendment'){
                sampleRequestIdSet.add(srLine.Sample_Request__c);
            }
        }
        
        List<SampleRequest__e> sreqEvtList = new List<SampleRequest__e>();
        for(id srid : sampleRequestIdSet){
            sreqEvtList.add(new SampleRequest__e(SampleRequestId__c=srid));     
        }
        
        SampleRequestLineItemHelper.publishPlatformEventsForSampleRequest(sreqEvtList);
    }
    
    //This method updates the sampling_status_c, Tracking_Number__c and Development_Code__c in OpportunityLineItem and Product__c respectively
    //based on the values updated in SampleRequestLineItem by Cloud Integration Tool
    //Joel Tom   
    public static void updateOppoLineOnOssmChanges(List<Sample_Request_Line_Item__c> SampleRequestList,Map<id,Sample_Request_Line_Item__c> oldSampleReqsMap){
        Map<Id,Sample_Request_Line_Item__c> SRLineMapToUpdateOppProdct = new Map<Id,Sample_Request_Line_Item__c>();
        Map<Id,Sample_Request_Line_Item__c> SRLineMapToUpdateProdct = new Map<Id,Sample_Request_Line_Item__c>();
        
        for(Sample_Request_Line_Item__c srlin:SampleRequestList)
        {
            if(srlin.Sampling_Status__c != oldSampleReqsMap.get(srlin.id).Sampling_Status__c 
               || srlin.Tracking_Number__c != oldSampleReqsMap.get(srlin.id).Tracking_Number__c
               || srlin.Integration_Status__c != oldSampleReqsMap.get(srlin.id).Integration_Status__c //newly added
               || srlin.Quantity_Dispatched__c != oldSampleReqsMap.get(srlin.id).Quantity_Dispatched__c //new added
            ){                   
                   SRLineMapToUpdateOppProdct.put(srlin.Opportunity_Product__c,srlin);               
            }
            if(srlin.Development_Code__c != oldSampleReqsMap.get(srlin.id).Development_Code__c ){
                SRLineMapToUpdateProdct.put(srlin.Product__c,srlin);
            }
            
        }      
        
        Map<Id,OpportunityLineItem> OppLineItemMap = new Map<Id,OpportunityLineItem> ([SELECT id,Quantity_Dispatched__c,Tracking_Number__c,Integration_Status__c,Sampling_Status__c  FROM OpportunityLineItem WHERE Id IN :SRLineMapToUpdateOppProdct.keySet()]); 
        Map<Id, Product2> Product2Map = new Map<Id,Product2> ([SELECT id,Development_Code__c FROM Product2 WHERE Id IN :SRLineMapToUpdateProdct.keyset()]); 
        List<OpportunityLineItem > OpportunityItemsToUpdate = new List<OpportunityLineItem >();
        List<Product2> Product2ToUpdate = new List<Product2>();
   
        for(Sample_Request_Line_Item__c srlin : SampleRequestList){
            if(srlin.Sampling_Status__c != oldSampleReqsMap.get(srlin.id).Sampling_Status__c 
               || srlin.Tracking_Number__c != oldSampleReqsMap.get(srlin.id).Tracking_Number__c
               || srlin.Integration_Status__c != oldSampleReqsMap.get(srlin.id).Integration_Status__c //newly added
               ||  srlin.Quantity_Dispatched__c != oldSampleReqsMap.get(srlin.id).Quantity_Dispatched__c //newly added
            ){
                if(OppLineItemMap.containsKey(srlin.Opportunity_Product__c)){
                    OpportunityItemsToUpdate.add(new OpportunityLineItem(id = srlin.Opportunity_Product__c,Quantity_Dispatched__c=srlin.Quantity_Dispatched__c,Integration_Status__c=srlin.Integration_Status__c,Sampling_Status__c = srlin.Sampling_Status__c, Tracking_Number__c = srlin.Tracking_Number__c));
                }
            }
            
            if(srlin.Development_Code__c != oldSampleReqsMap.get(srlin.id).Development_Code__c){
                if(Product2Map.containsKey(srlin.Product__c)){
                    Product2ToUpdate.add(new Product2(id = srlin.Product__c,Development_Code__c = srlin.Development_Code__c));
                }
            }    
        }
        
        isInitiatedFromSampleRequest = true;
        
        if(Product2ToUpdate != null && Product2ToUpdate.size() > 0)
        {
            update Product2ToUpdate;
        }
        if(OpportunityItemsToUpdate != null && OpportunityItemsToUpdate.size() > 0)
        {
            update OpportunityItemsToUpdate;
        }   
        
    }
    
}