src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Quantity_of_Sample_Grams__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity of Sample</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM(Sample)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KG</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>MT</fullName>
                    <label>Metric Ton</label>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>LB</fullName>
                    <label>US pound</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/classes/RequestForSamplingControllerTest.cls
@isTest
public class RequestForSamplingControllerTest {
    @testSetup
    public static void testData() {
        //Opportunities
        List<Opportunity> lstOpportunity = new List<Opportunity>();
        lstOpportunity.add(new Opportunity(Name='opp1', StageName='Preparation', CloseDate=system.today()));
        
        Database.SaveResult[] oppResult = Database.insert(lstOpportunity, false);
        List<Id> oppSuccessId = new List<Id>();
        for(Database.SaveResult result : oppResult) {
            if(result.isSuccess()) {
                oppSuccessId.add(result.getId());
            }
        }
        
        //Products
        List<Product2> lstProduct = new List<Product2>();
        lstProduct.add(new Product2(Name='p1'));
        
        Database.SaveResult[] productResult = Database.insert(lstProduct, false);
        List<Id> prodSuccessId = new List<Id>();
        for(Database.SaveResult result : productResult) {
            if(result.isSuccess()) {
                prodSuccessId.add(result.getId());
            }
        }
        
        //Pricebook
        List<Pricebook2> lstPriceBook = new List<Pricebook2>();
        lstPriceBook.add(new Pricebook2(name='Price Book'));
        
        Database.SaveResult[] priceBookResult = Database.insert(lstPriceBook, false);
        List<Id> priceBookId = new List<Id>();
        for(Database.saveResult result : priceBookResult) {
            if(result.isSuccess()) {
                priceBookId.add(result.getId());
            }
        }
        
        //PriceBookEntry
        List<PriceBookEntry> lstPriceBookEntry = new List<PriceBookEntry>();
        lstPriceBookEntry.add(new PriceBookEntry(UnitPrice=100, Pricebook2Id=Test.getStandardPricebookId(), Product2Id=prodSuccessId[0], isActive = true));
        
        Database.SaveResult[] priceBookEntryResult = Database.insert(lstPriceBookEntry, false);
        List<Id> priceBookEntryId = new List<Id>();
        for(Database.saveResult result : priceBookEntryResult) {
            if(result.isSuccess()) {
                priceBookEntryId.add(result.getId());
            }
        }
        
        List<OpportunityLineItem> lstOpportunityLineItem = new List<OpportunityLineItem>();
        //lstOpportunityLineItem.add(new OpportunityLineItem(Name='n1', UnitPrice='100'));
        
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = oppSuccessId[0];
        oli.Product2Id = prodSuccessId[0];
        oli.PricebookEntryId = priceBookEntryId[0];
        oli.Sampling_Status__c='7';
        oli.UoM__c = 'G';
        oli.Quantity_of_Sample_Grams__c = 100;
        lstOpportunityLineItem.add(oli);     
        insert lstOpportunityLineItem;
    }

    @isTest    
    public static void fetchOpportunityLineItemWrapperTest() {
        List<Opportunity> oppRecordId = [SELECT id, Name From Opportunity Limit 1];
        List<RequestForSamplingController.OpportunityLineItemWrapper> OpportunityLineItemWrapperList = new List<RequestForSamplingController.OpportunityLineItemWrapper>();
        OpportunityLineItemWrapperList = RequestForSamplingController.fetchOpportunityLineItemWrapper(oppRecordId[0].Id);
        System.debug('OpportunityLineItemWrapperList=> '+OpportunityLineItemWrapperList);
        System.assertEquals(1, OpportunityLineItemWrapperList.size());
        
        OpportunityLineItemWrapperList[0].firstSampleDueDate =System.Today();
        OpportunityLineItemWrapperList[0].PDandIUserId = UserInfo.getUserId();
        
        String response = RequestForSamplingController.processSampleRequests(OpportunityLineItemWrapperList);
        System.debug('response=>'+response);
        //System.assertEquals('SUCCESS', response);
    }
}