src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PLBS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>PLBS_Product__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plbs_Weight_G__c</fullName>
        <label>Weight(G)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PLBS_Product__c.object
<CustomObject>
    <label>Private Label Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Private Label Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TCB__c.object
<CustomObject>
    <fields>
        <fullName>CTN_20FT__c</fullName>
        <label>CTN/ 20FT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CTN_40FT_HC__c</fullName>
        <label>CTN/ 40FT HC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CTN_40FT__c</fullName>
        <label>CTN/ 40FT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CTN_Layer__c</fullName>
        <label>CTN/ Layer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Mix_PL__c</fullName>
        <label>Case Mix (PL)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Depth_Gusset_Height_mm__c</fullName>
        <label>Depth/ Gusset/ Height (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Height_mm__c</fullName>
        <label>Height (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Layer_PL_40HC__c</fullName>
        <label>Layer/ PL 40HC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Layer_PL__c</fullName>
        <label>Layer/ PL</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Length_Depth_mm__c</fullName>
        <label>Length/ Depth (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Length_mm_1st__c</fullName>
        <label>Length (mm) (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MOQ_Packaging_1st__c</fullName>
        <label>MOQ Packaging (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MOQ_Packaging_2nd__c</fullName>
        <label>MOQ Packaging (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Product Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs</relationshipLabel>
        <relationshipName>TCBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PL_20FT__c</fullName>
        <label>PL/ 20FT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PL_40FT__c</fullName>
        <label>PL/ 40FT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PM_Type_1st__c</fullName>
        <label>PM Type (1st)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1st_PM_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PM_Type_2nd__c</fullName>
        <label>PM Type (2nd)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X2nd_PM_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pallet_Type__c</fullName>
        <label>Pallet Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pallet_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Printing_2nd__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Printing (2nd)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Structure_2nd__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Structure (2nd)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tare_Weight_g_1st__c</fullName>
        <label>Tare Weight (g) (1st)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tare_Weight_g_2nd__c</fullName>
        <label>Tare Weight (g) (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_CTN__c</fullName>
        <label>Unit/ CTN</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width_mm_1st__c</fullName>
        <label>Width (mm) (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width_mm_2nd__c</fullName>
        <label>Width (mm) (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1st_PM_Pouch_jar__c</fullName>
        <label>PM (Pouch/jar) VND/EA (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1st_Printing__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Printing (1st)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1st_Structure__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Structure (1st)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X2nd_PM_Carton__c</fullName>
        <label>PM (Carton) - VND/EA (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TCB</label>
    <nameField>
        <displayFormat>TCB - {00000}</displayFormat>
        <label>TCB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Pallet_Set.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Disposal - 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal - 1x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal - 1.1x1.1m</fullName>
    </customValue>
    <customValue>
        <fullName>CHEP – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>CHEP – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>PECO – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>PECO – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>LOSCAM – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>LOSCAM – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 1x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 1.1x1.1m</fullName>
    </customValue>
    <masterLabel>Pallet Set</masterLabel>
</GlobalValueSet>

src/globalValueSets/X1st_PM_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DOY</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW</fullName>
    </customValue>
    <customValue>
        <fullName>FOUR SIDE SEAL</fullName>
    </customValue>
    <customValue>
        <fullName>DOY FLAT BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW BLOCK BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>VACUUM</fullName>
    </customValue>
    <customValue>
        <fullName>PET JAR</fullName>
    </customValue>
    <customValue>
        <fullName>GLASS JAR</fullName>
    </customValue>
    <customValue>
        <fullName>PET CYLINDER JAR</fullName>
    </customValue>
    <customValue>
        <fullName>METAL CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>COMPOSITE CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PET CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PAPER MILK BOTTLE</fullName>
    </customValue>
    <masterLabel>1st PM Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/X2nd_PM_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSC</fullName>
    </customValue>
    <customValue>
        <fullName>TRAY &amp; LID</fullName>
    </customValue>
    <customValue>
        <fullName>TRAY ONLY</fullName>
    </customValue>
    <customValue>
        <fullName>PRE CUT RSC</fullName>
    </customValue>
    <masterLabel>2nd PM Type</masterLabel>
</GlobalValueSet>

src/classes/OppSuggestionController.cls
public class OppSuggestionController {
    @AuraEnabled
    public static List<Opportunity> getSuggestionOpps(String recId) {
        
        Opportunity opp = [SELECT Id, Name, PLBS_Product__c, Plbs_Weight_G__c,
                           (select Id,PM_Type_1st__c,Unit_CTN__c from TCBs__r)
                           FROM Opportunity WHERE Id = :recId];
        System.debug('opp');
        System.debug(opp);
        
        List<Opportunity> suggestedOpps = new List<Opportunity>(); 
        for(Opportunity opps:[SELECT Id, Name, PLBS_Product__c, Account.Name, Plbs_Weight_G__c,(select Id,PM_Type_1st__c,PM_Type_2nd__c,Pallet_Type__c,Unit_CTN__c from TCBs__r)
                                           FROM Opportunity WHERE PLBS_Product__c = :opp.PLBS_Product__c AND Plbs_Weight_G__c = :opp.Plbs_Weight_G__c AND Id <> :recId]){
             for(TCB__c tcbs:opps.TCBs__r){
                 if(tcbs.PM_Type_1st__c==opp.TCBs__r[0].PM_Type_1st__c){
                    suggestedOpps.add(opps);
                     system.debug('Opps '+opps);
                 }
             }
        }
        System.debug('suggestedOpps');
        System.debug(suggestedOpps);
        return suggestedOpps;
    }
    
     @AuraEnabled
    public static boolean copy(String recId, String oppToCopyId) {
        System.debug('Inside Copy');
        Tcb__c oppToCopy = [SELECT Id, Name,
                                 MOQ_Packaging_2nd__c,
                                 X1st_Printing__c,
                           MOQ_Packaging_1st__c,
                           X1st_PM_Pouch_jar__c,
                           Tare_Weight_g_1st__c,
                           Length_mm_1st__c,
                           Width_mm_1st__c,
                           X1st_Structure__c,   
                           Case_Mix_PL__c,
                           Depth_Gusset_Height_mm__c,
                           PM_Type_2nd__c,
                           X2nd_PM_Carton__c,
                           Tare_Weight_g_2nd__c,
                           Length_Depth_mm__c,
                           Width_mm_2nd__c,
                           Structure_2nd__c,
                           Printing_2nd__c,
                           Height_mm__c,
                           Unit_CTN__c,
                           Layer_PL__c,
                           Layer_PL_40HC__c,
                           PL_20FT__c,
                           PL_40FT__c,
                           CTN_20FT__c,
                           CTN_40FT__c,
                           CTN_40FT_HC__c, 
                           CTN_Layer__c 
                           FROM Tcb__c WHERE Opportunity__c = :oppToCopyId];
        
        Tcb__c destinationOpp = [SELECT Id, Name,
                                      MOQ_Packaging_2nd__c,
                                 X1st_Printing__c,
                           MOQ_Packaging_1st__c,
                           X1st_PM_Pouch_jar__c,
                           Tare_Weight_g_1st__c,
                           Length_mm_1st__c,
                           Width_mm_1st__c,
                           X1st_Structure__c,   
                           Case_Mix_PL__c,
                           Depth_Gusset_Height_mm__c,
                           PM_Type_2nd__c,
                           X2nd_PM_Carton__c,
                           Tare_Weight_g_2nd__c,
                           Length_Depth_mm__c,
                           Width_mm_2nd__c,
                           Structure_2nd__c,
                           Printing_2nd__c,
                           Height_mm__c,
                           Unit_CTN__c,
                           Layer_PL__c,
                           Layer_PL_40HC__c,
                           PL_20FT__c,
                           PL_40FT__c,
                           CTN_20FT__c,
                           CTN_40FT__c,
                           CTN_40FT_HC__c, 
                           CTN_Layer__c
                           FROM Tcb__c WHERE Opportunity__c = :recId];
        
        destinationOpp.MOQ_Packaging_2nd__c = oppToCopy.MOQ_Packaging_2nd__c;
        destinationOpp.X1st_Structure__c = oppToCopy.X1st_Structure__c;
        destinationOpp.X1st_Printing__c = oppToCopy.X1st_Printing__c;
        destinationOpp.MOQ_Packaging_1st__c = oppToCopy.MOQ_Packaging_1st__c;
        destinationOpp.X1st_PM_Pouch_jar__c = oppToCopy.X1st_PM_Pouch_jar__c;
        destinationOpp.Tare_Weight_g_1st__c = oppToCopy.Tare_Weight_g_1st__c;
        destinationOpp.Length_mm_1st__c = oppToCopy.Length_mm_1st__c;
        destinationOpp.Width_mm_1st__c = oppToCopy.Width_mm_1st__c;
        destinationOpp.Case_Mix_PL__c = oppToCopy.Case_Mix_PL__c;
        destinationOpp.Depth_Gusset_Height_mm__c = oppToCopy.Depth_Gusset_Height_mm__c;
        destinationOpp.PM_Type_2nd__c = oppToCopy.PM_Type_2nd__c;
        destinationOpp.X2nd_PM_Carton__c = oppToCopy.X2nd_PM_Carton__c;
        destinationOpp.Tare_Weight_g_2nd__c = oppToCopy.Tare_Weight_g_2nd__c;
        destinationOpp.Length_Depth_mm__c = oppToCopy.Length_Depth_mm__c;
        destinationOpp.Width_mm_2nd__c = oppToCopy.Width_mm_2nd__c;
        destinationOpp.Structure_2nd__c = oppToCopy.Structure_2nd__c;
        destinationOpp.Printing_2nd__c = oppToCopy.Printing_2nd__c;
        destinationOpp.Height_mm__c = oppToCopy.Height_mm__c;
        destinationOpp.Unit_CTN__c = oppToCopy.Unit_CTN__c;
        destinationOpp.Layer_PL__c = oppToCopy.Layer_PL__c;
        destinationOpp.Layer_PL_40HC__c = oppToCopy.Layer_PL_40HC__c;
        destinationOpp.PL_20FT__c = oppToCopy.PL_20FT__c; 
        destinationOpp.PL_40FT__c = oppToCopy.PL_40FT__c;
        destinationOpp.CTN_20FT__c = oppToCopy.CTN_20FT__c;
        destinationOpp.CTN_40FT__c = oppToCopy.CTN_40FT__c;
        destinationOpp.CTN_Layer__c = oppToCopy.CTN_Layer__c;
        destinationOpp.CTN_40FT_HC__c = oppToCopy.CTN_40FT_HC__c;
        
        Database.SaveResult result = Database.update(destinationOpp);
        return result.isSuccess();
    }

}