src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>TCB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TCB</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TCB__c.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.OpportunityId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TCB__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TCB__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Product Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs</relationshipLabel>
        <relationshipName>TCBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TCB</label>
    <nameField>
        <displayFormat>TCB - {00000}</displayFormat>
        <label>TCB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/PLBSComponentController_Test.cls
@isTest
public class PLBSComponentController_Test {

    @testSetup
    public static void createData()
{
     Profile profOfi = [select id from profile where name='OFI'];
        
        
        User ofiuser = new User(alias = 'jack qu', email='jackqu@noemail.com',
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US',
                                localesidkey='en_US', profileid = profOfi.Id,
                                timezonesidkey='America/Los_Angeles',  username='jackqu@noemail.com');
        insert ofiuser;  
        
        User ofiuser1 = new User(alias = 'jack8', email='jackqu@noemail.com',
                                 emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US',
                                 localesidkey='en_US', profileid = profOfi.Id,
                                 timezonesidkey='America/Los_Angeles',  username='jack8@noemail.com');
        insert ofiuser1;
        
        List<user> currentuser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Account acc= OFI_TestDataFactory.createMultipleAccount('Test for Quote', 'India','In', null, null, null, true);
        Account acc1= OFI_TestDataFactory.createMultipleAccount('TestQuote1', 'India','In', null, null, null, true);
        Account acc2= OFI_TestDataFactory.createMultipleAccount('TestQuoteFailure', 'India','In', null, null, null, true);
        
        
      Id priceBookID = Test.getStandardPricebookId();
        
        Product2 p_test = new Product2(IsActive=true,Name='test Product',Description='Description for test Product');
        insert p_test;
        
        PricebookEntry pbe = new PricebookEntry(IsActive=true,Pricebook2Id=priceBookID,Product2Id=p_test.Id,UnitPrice=10.00);  
        insert pbe;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId =acc1.id;
        opp.CloseDate =system.today()+30;
        opp.StageName= 'Offering';
        opp.Business_Unit__c='All';   
        opp.Pricebook2Id=pricebookId;
        opp.RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId();
        insert opp;
    	TCB__c tcb = new TCB__c();
    	tcb.Opportunity__c = opp.Id;
    insert tcb;
}
     @isTest
    public static void testScenario()
    {
        Opportunity opp = [Select Id, Name From Opportunity];
        PLBSComponentController.getTCBId(opp.Id);
    }
}