src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Volume_MT__c</fullName>
        <inlineHelpText>Possible / Potential Volume Olam (MT) expects to get</inlineHelpText>
        <label>Estimated Volume</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Samples_Sent__c</fullName>
        <label>Number of Samples Sent</label>
        <summaryFilterItems>
            <field>OpportunityLineItem.Sampling_Status__c</field>
            <operation>equals</operation>
            <value>Samples Sent, Pending Feedback, Resampling, Sample Accepted, Sample Rejected, Resample Sent to the Customer, &quot;Sample Approved, asking for bulk sample&quot;, Kept on Hold, No Response, Project Dropped</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sample_Accepted_Flag__c</fullName>
        <label>Sample Accepted Flag</label>
        <summaryFilterItems>
            <field>OpportunityLineItem.Sampling_Status__c</field>
            <operation>equals</operation>
            <value>Sample Accepted</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sample_Sent_Flag__c</fullName>
        <description>Get the count of Sample sent from Opportunity Line Item</description>
        <label>Sample Sent Flag</label>
        <summaryFilterItems>
            <field>OpportunityLineItem.Sampling_Status__c</field>
            <operation>equals</operation>
            <value>Samples Sent</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <businessProcess>Service%2FPresent</businessProcess>
        <description>Request from customer for documents, logistics issues, other ad hoc requests. Does not have any commercial impact</description>
        <label>Service</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category_2__c</fullName>
        <label>Product Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Sub_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acid</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI HH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI LH</fullName>
    </customValue>
    <customValue>
        <fullName>ADPI MH</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Blanched</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Ingredient Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Almond InShell Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Kernel Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Oil Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Reject</fullName>
    </customValue>
    <customValue>
        <fullName>Almond Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth</fullName>
    </customValue>
    <customValue>
        <fullName>Amaranth Organic</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN STYLE CH</fullName>
    </customValue>
    <customValue>
        <fullName>AMF</fullName>
    </customValue>
    <customValue>
        <fullName>Analogue</fullName>
    </customValue>
    <customValue>
        <fullName>Black Alkalized</fullName>
    </customValue>
    <customValue>
        <fullName>Bleached</fullName>
    </customValue>
    <customValue>
        <fullName>Blends</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Ingredient</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Nut Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTERMLKCONCENTRATE</fullName>
    </customValue>
    <customValue>
        <fullName>Butter Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Cagliata</fullName>
    </customValue>
    <customValue>
        <fullName>Calcium Caseinate</fullName>
    </customValue>
    <masterLabel>Product Sub Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>#640 Colored</fullName>
    </customValue>
    <customValue>
        <fullName>#640 Whites</fullName>
    </customValue>
    <customValue>
        <fullName>100#</fullName>
    </customValue>
    <customValue>
        <fullName>200#</fullName>
    </customValue>
    <customValue>
        <fullName>40#</fullName>
    </customValue>
    <customValue>
        <fullName>40# Block</fullName>
    </customValue>
    <customValue>
        <fullName>40#Colby Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# colored</fullName>
    </customValue>
    <customValue>
        <fullName>40#Monterey Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# Pepper Jack</fullName>
    </customValue>
    <customValue>
        <fullName>40# White</fullName>
    </customValue>
    <customValue>
        <fullName>500# Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>500# White</fullName>
    </customValue>
    <customValue>
        <fullName>60-80#</fullName>
    </customValue>
    <customValue>
        <fullName>70%</fullName>
    </customValue>
    <customValue>
        <fullName>72.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>80%</fullName>
    </customValue>
    <customValue>
        <fullName>80% salted</fullName>
    </customValue>
    <customValue>
        <fullName>80% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82.5% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>82% unsalted</fullName>
    </customValue>
    <customValue>
        <fullName>AA InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Akcakoca Natural</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Extra No. 1</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich InShell</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Pieces</fullName>
    </customValue>
    <customValue>
        <fullName>Aldrich Select Sheller Run</fullName>
    </customValue>
    <masterLabel>Product Sub Category 2</masterLabel>
</GlobalValueSet>

src/classes/OpportunitySelector.cls
public inherited sharing class OpportunitySelector {
    public static List<Opportunity> getPresentationOpportunities  (Id accountId, String bu, Date startDate, Date endDate) {
        Set<Id> recordTypes = new Set<Id> {
            OpportunityConstants.PRESENT_OPPORTUNITY_RECORD_TYPE_ID
            
        };

        return [
            SELECT Id, Name, CreatedDate, Estimated_Volume_MT__c, Number_of_Samples_Sent__c, Sample_Sent_Flag__c, Sample_Accepted_Flag__c,
            StageName, LastModifiedDate, OwnerId, Owner.Name, 
            CloseDate, Business_Unit__c, Account.Name, AccountId,
            
            (SELECT Id, Product2.Name, Sample_Sent_Date__c, toLabel(Sampling_Status__c), Product2.Product_Category__c, 
            Product2.Product_Sub_Category__c, Product2.Product_Sub_Category_2__c,
            Volume__c, Product2Id
            FROM OpportunityLineItems)

            FROM Opportunity
            WHERE AccountId =: accountId
            AND RecordTypeId in: recordTypes
            AND Business_Unit__c =: bu
            AND (CloseDate >=: startDate AND CloseDate <=: endDate)
        ];
    }
    public static List<Opportunity> getServiceOpportunities  (Id accountId, String bu, Date startDate, Date endDate) {
        Set<Id> recordTypes = new Set<Id> {
           
            OpportunityConstants.SERVICE_OPPORTUNITY_RECORD_TYPE_ID
        };

        return [
            SELECT Id, Name, CreatedDate, Estimated_Volume_MT__c, Number_of_Samples_Sent__c, Sample_Sent_Flag__c, Sample_Accepted_Flag__c,
            StageName, LastModifiedDate, OwnerId, Owner.Name, 
            CloseDate, Business_Unit__c, Account.Name, AccountId,
            
            (SELECT Id, Product2.Name, Sample_Sent_Date__c, toLabel(Sampling_Status__c), Product2.Product_Category__c, 
            Product2.Product_Sub_Category__c, Product2.Product_Sub_Category_2__c,
            Volume__c, Product2Id
            FROM OpportunityLineItems)

            FROM Opportunity
            WHERE AccountId =: accountId
            AND RecordTypeId in: recordTypes
            AND Business_Unit__c =: bu
            AND (CloseDate >=: startDate AND CloseDate <=: endDate)
        ];
    }
    
    public static List<Opportunity> getGroupPresentationOpportunities  (Set<Id> accountIds, String bu, Date startDate, Date endDate) {
        Set<Id> recordTypes = new Set<Id> {
            OpportunityConstants.PRESENT_OPPORTUNITY_RECORD_TYPE_ID
        };

        return [
            SELECT Id, Name, CreatedDate, Estimated_Volume_MT__c, Number_of_Samples_Sent__c, Sample_Sent_Flag__c, Sample_Accepted_Flag__c,
            StageName, LastModifiedDate, OwnerId, Owner.Name, 
            CloseDate, Business_Unit__c, Account.Name, AccountId,
            
            (SELECT Id, Product2.Name, Sample_Sent_Date__c, toLabel(Sampling_Status__c), Product2.Product_Category__c, 
            Product2.Product_Sub_Category__c, Product2.Product_Sub_Category_2__c,
            Volume__c, Product2Id
            FROM OpportunityLineItems)

            FROM Opportunity
            WHERE AccountId in: accountIds
            AND RecordTypeId in: recordTypes
            AND Business_Unit__c =: bu
            AND (CloseDate >=: startDate AND CloseDate <=: endDate)
        ];
    }
    public static List<Opportunity> getGroupServiceOpportunities  (Set<Id> accountIds, String bu, Date startDate, Date endDate) {
        Set<Id> recordTypes = new Set<Id> {
            OpportunityConstants.SERVICE_OPPORTUNITY_RECORD_TYPE_ID
        };
        System.debug('in service');
        return [
            SELECT Id, Name, CreatedDate, Estimated_Volume_MT__c, Number_of_Samples_Sent__c, Sample_Sent_Flag__c, Sample_Accepted_Flag__c,
            StageName, LastModifiedDate, OwnerId, Owner.Name, 
            CloseDate, Business_Unit__c, Account.Name, AccountId,
            
            (SELECT Id, Product2.Name, Sample_Sent_Date__c, toLabel(Sampling_Status__c), Product2.Product_Category__c, 
            Product2.Product_Sub_Category__c, Product2.Product_Sub_Category_2__c,
            Volume__c, Product2Id
            FROM OpportunityLineItems)

            FROM Opportunity
            WHERE AccountId in: accountIds
            AND RecordTypeId in: recordTypes
            AND Business_Unit__c =: bu
            AND (CloseDate >=: startDate AND CloseDate <=: endDate)
        ];
    }
    public static List<Opportunity> getDefendDevelopGainOpportunities (Id accountId, String bu, Date startDate, Date endDate) {
        Set<Id> recordTypes = new Set<Id> {
            OpportunityConstants.DEFEND_OPPORTUNITY_RECORD_TYPE_ID,
            OpportunityConstants.DEVELOP_OPPORTUNITY_RECORD_TYPE_ID,
            OpportunityConstants.GAIN_OPPORTUNITY_RECORD_TYPE_ID
        };

        return [
            SELECT Id, Name, StageName, OwnerId, Owner.Name, 
            CloseDate, Business_Unit__c, IsClosed, Account.Name, AccountId,
            (SELECT Id, Product2.Product_Category__c, 
            Product2.Product_Sub_Category__c, Product2.Product_Sub_Category_2__c,
            Volume__c, Converted_Volume_in_MT__c,  Product2Id
            FROM OpportunityLineItems)
            FROM Opportunity
            WHERE AccountId =: accountId
            AND RecordTypeId in: recordTypes
            AND Business_Unit__c =: bu
            AND (CloseDate >=: startDate AND CloseDate <=: endDate)
            //AND StageName =: OpportunityConstants.OPPORTUNITY_STAGE_CLOSING_WON
        ];
    }
    public static List<Opportunity> getGroupDefendDevelopGainOpportunities (Set<Id> accountIds, String bu, Date startDate, Date endDate) {
        Set<Id> recordTypes = new Set<Id> {
            OpportunityConstants.DEFEND_OPPORTUNITY_RECORD_TYPE_ID,
            OpportunityConstants.DEVELOP_OPPORTUNITY_RECORD_TYPE_ID,
            OpportunityConstants.GAIN_OPPORTUNITY_RECORD_TYPE_ID
        };

        return [
            SELECT Id, Name, StageName, OwnerId, Owner.Name, 
            CloseDate, Business_Unit__c, IsClosed, Account.Name, AccountId,
            (SELECT Id, Product2.Product_Category__c, 
            Product2.Product_Sub_Category__c, Product2.Product_Sub_Category_2__c,
            Volume__c, Converted_Volume_in_MT__c, Product2Id
            FROM OpportunityLineItems)
            FROM Opportunity
            WHERE AccountId in: accountIds
            AND RecordTypeId in: recordTypes
            AND Business_Unit__c =: bu
            AND (CloseDate >=: startDate AND CloseDate <=: endDate)
        ];
    }
    

    //Todo : Update the status check which are the status need to be considered
    public static List<Opportunity> getOpenDefendDevelopOpportunities (Id accountId, String bu, Date startDate, Date endDate) {
        Set<Id> recordTypes = new Set<Id> {
            OpportunityConstants.DEFEND_OPPORTUNITY_RECORD_TYPE_ID,
            OpportunityConstants.DEVELOP_OPPORTUNITY_RECORD_TYPE_ID
        };

        return [
            SELECT Id, Name, CreatedDate, Estimated_Volume_MT__c, Number_of_Samples_Sent__c, Sample_Sent_Flag__c, Sample_Accepted_Flag__c, 
            StageName, LastModifiedDate, OwnerId, Owner.Name, 
            CloseDate, Business_Unit__c, Account.Name, AccountId,
            (SELECT Id, Product2.Name, Sample_Sent_Date__c, toLabel(Sampling_Status__c), Product2.Product_Category__c, 
            Product2.Product_Sub_Category__c, Product2.Product_Sub_Category_2__c,
            Volume__c, Product2Id, CreatedDate, Sample_Acceptance_Rejection_Date__c
            FROM OpportunityLineItems)
            FROM Opportunity
            WHERE AccountId =: accountId
            AND RecordTypeId in: recordTypes
            AND Business_Unit__c =: bu
            AND (CloseDate >=: startDate AND CloseDate <=: endDate)
            AND StageName !=: OpportunityConstants.OPPORTUNITY_STAGE_CLOSING_WON
            ORDER BY CreatedDate DESC
        ];
    }
    
    public static List<Opportunity> getGroupOpenDefendDevelopOpportunities (Set<Id> accountIds, String bu, Date startDate, Date endDate) {
        Set<Id> recordTypes = new Set<Id> {
            OpportunityConstants.DEFEND_OPPORTUNITY_RECORD_TYPE_ID,
            OpportunityConstants.DEVELOP_OPPORTUNITY_RECORD_TYPE_ID
        };

        return [
            SELECT Id, Name, CreatedDate, Estimated_Volume_MT__c, Number_of_Samples_Sent__c, Sample_Sent_Flag__c, Sample_Accepted_Flag__c, 
            StageName, LastModifiedDate, OwnerId, Owner.Name, 
            CloseDate, Business_Unit__c, Account.Name, AccountId,
            (SELECT Id, Product2.Name, Sample_Sent_Date__c, toLabel(Sampling_Status__c), Product2.Product_Category__c, 
            Product2.Product_Sub_Category__c, Product2.Product_Sub_Category_2__c,
            Volume__c, Product2Id, CreatedDate, Sample_Acceptance_Rejection_Date__c
            FROM OpportunityLineItems)
            FROM Opportunity
            WHERE AccountId in: accountIds
            AND RecordTypeId in: recordTypes
            AND Business_Unit__c =: bu
            AND (CloseDate >=: startDate AND CloseDate <=: endDate)
            AND StageName !=: OpportunityConstants.OPPORTUNITY_STAGE_CLOSING_WON
            ORDER BY CreatedDate DESC
        ];
    }
    
    //added by rajat start- 26/7/21
    public static String getOpportunityRecordTypeNameFromId(Id recordtypeId){
        System.debug('Record Type Id - Selector :'+recordtypeId);
        String strRecordDevName ;
        if(recordtypeId != null){
            strRecordDevName = Schema.SObjectType.Opportunity.getRecordTypeInfosById().get(recordtypeId).getDeveloperName(); 
        }
        System.debug('Record Type Name :'+strRecordDevName);
        if(strRecordDevName != null){
            return strRecordDevName;
        }else {
            return null;
        } 
    }
    //added by rajat end- 26/7/21
}