src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PDI_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PDI Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PDI_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PDI Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PDNI_Approval_Status__c</fullName>
        <label>PDI Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PLM_Approval_Status__c</fullName>
        <label>PLM Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Bulk_Sample_Quantity__c</fullName>
        <label>Bulk Sample Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_of_Sample_Grams__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity of Sample</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Resampling_Quantity__c</fullName>
        <label>Resampling Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sample_Feedback__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Helps to capture the feedback received from the customer</inlineHelpText>
        <label>Sample Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sample_with_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sample with Billing?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM(Sample)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KG</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>MT</fullName>
                    <label>Metric Ton</label>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>LB</fullName>
                    <label>US pound</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Development_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <label>Development Code</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/classes/OpportunityProductTriggerTest.cls
@isTest(SeeAllData=false)
public class OpportunityProductTriggerTest {

    @testSetup public static void setup() {
        TestDataFactory.setup();
    }
    
    
    @isTest
    static void createSampleRequestAndLineItemAndUpdate() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        opp.PDI_Lead__c = UserInfo.getUserId();
        opp.PDI_Member__c = UserInfo.getUserId();
        opp.PLM_Approval_Status__c = 'Approved';
        opp.PDNI_Approval_Status__c = 'Approved';
        update opp;
        
        SamplingRequestToOSSMController.createSampleRequest(opp.Id);
        
        Test.startTest();
        OpportunityLineItem oplitmObj = [SELECT Id FROM OpportunityLineItem LIMIT 1];
        oplitmObj.Quantity_of_Sample_Grams__c = 33.00;
        oplitmObj.Sampling_Status__c = '1';
        oplitmObj.Sample_with_Billing__c = true;
        oplitmObj.Sample_Feedback__c = 'sdajggggdasd';
        oplitmObj.UoM__c = 'G';
        oplitmObj.Resampling_Quantity__c = 10;
        oplitmObj.Bulk_Sample_Quantity__c = 100;
        update oplitmObj;
        Test.stopTest();
    }
    
    
    static testMethod void createOpp() {
        test.startTest();
        Id oppRecordTNMId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId();
        
        Account acc = new Account();
        acc.name='Test';
        acc.BillingCountry = 'India';
        //acc.Operating_Geographics__c ='Test';
        acc.BillingStreet ='Test';
        insert acc;
        
        
        Id pricebookId = Test.getStandardPricebookId();
        Product2 prod = new Product2(
            Family = '03-Cocoa and Speciality',
            Name ='Testing',
            QuantityUnitOfMeasure ='KG',
            Development_Code__c = 'Test1234123'
        );
        insert prod;   
        
        PricebookEntry pbEntry = [Select id from PricebookEntry where Pricebook2Id =: pricebookId and
            Product2Id =: prod.Id and isActive = true AND CurrencyISOCode = 'USD'];
            
           
       
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId =acc.id;
        opp.CloseDate =system.today()+30;
        opp.StageName= 'Offering';
        opp.Pricebook2Id = pricebookId;
        opp.RecordTypeId = oppRecordTNMId;
        
        insert opp;
        
        
        OpportunityLineItem opl=new OpportunityLineItem();
        opl.OpportunityId = opp.Id;
        opl.Product2Id = prod.Id;
        opl.Quantity = 12.00;
        opl.PricebookEntryId=pbEntry.Id;
        insert opl;
        test.stopTest();
    } 
   
}