src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_Team_Member_Role__mdt.object
<CustomObject>
    <description>Opportunity team member roles</description>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Role__c</fullName>
        <label>Opportunity Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Team Member Role</label>
    <pluralLabel>Opportunity Team Member Roles</pluralLabel>
</CustomObject>

src/objects/PriceBook_Record__mdt.object
<CustomObject>
    <description>used to store price book name and its id</description>
    <fields>
        <fullName>PriceBookID__c</fullName>
        <label>PriceBookID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>PriceBook Record</label>
    <pluralLabel>PriceBook Records</pluralLabel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <defaultValue>&quot;Read Access&quot;</defaultValue>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read Access</fullName>
                </value>
                <value>
                    <fullName>Edit Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BU_Identifier__c</fullName>
        <formula>IF( CONTAINS(UserRole.Name, &apos;Cocoa&apos;) , &apos;Cocoa&apos;,
IF( CONTAINS(UserRole.Name, &apos;Dairy&apos;) , &apos;Dairy&apos;,
IF( CONTAINS(UserRole.Name, &apos;Spice&apos;) , &apos;Spice&apos;,
IF( CONTAINS(UserRole.Name, &apos;Edible_Nuts&apos;) , &apos;Edible_Nuts&apos;, &apos;&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Identifier</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/opportunityTriggerOfiUser.cls
// 
// Class created by Punam
// Last modified by Joel Tom on 24/01/2022
// 

public class opportunityTriggerOfiUser {
    
    public static void checkUserAccess(list<opportunity> oppList)
    {     
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Access_Set_Admins');
        if(!hasCustomPermission && userInfo.getName() != System.Label.Automated_Process){
            User u=[Select Id,Name,Email,BU_Identifier__c,UserRole.Name from User where Id=:userinfo.getuserId()];
            Map<string,Teams__c> mapOfUserIdToTeams =new Map<string,Teams__c>();
            Map<String,PriceBook_Record__mdt> mapofLabeltoPricebook=new Map<String,PriceBook_Record__mdt>();
            
            Set<id> AccountIds = new Set<id>();
            for(opportunity opp:oppList)
            { 
                AccountIds.add(opp.AccountId);
            }
            
            mapOfUserIdToTeams=opportunityTriggerOfiUser.getAccountTeams(AccountIds);
            mapofLabeltoPricebook=opportunityTriggerOfiUser.getPriceBook();
            for(opportunity opp:oppList)
            {
                if(opp.RecordTypeId==OpportunityConstants.GAIN_OPPORTUNITY_RECORD_TYPE_ID 
                   || opp.RecordTypeId==OpportunityConstants.DEFEND_OPPORTUNITY_RECORD_TYPE_ID 
                   || opp.RecordTypeId==OpportunityConstants.DEVELOP_OPPORTUNITY_RECORD_TYPE_ID 
                   || opp.RecordTypeId==OpportunityConstants.PRESENT_OPPORTUNITY_RECORD_TYPE_ID 
                   || opp.RecordTypeId==OpportunityConstants.SERVICE_OPPORTUNITY_RECORD_TYPE_ID
                   || opp.RecordTypeId==OpportunityConstants.TENDERING_OPPORTUNITY_RECORD_TYPE_ID)
                {
                    String BU;
                    boolean isAccountTeam=false;
                    if(!mapOfUserIdToTeams.isempty()){
                        if((mapOfUserIdToTeams.containskey(String.ValueOF(opp.AccountId)+String.valueOf(u.Id)))){
                            BU=mapOfUserIdToTeams.get(String.ValueOF(opp.AccountId)+String.valueOf(u.Id)).Business_Unit__c;
                            isAccountTeam=true;
                            
                            if(!mapofLabeltoPricebook.isEmpty()){ 
                                PriceBook_Record__mdt pr1=mapofLabeltoPricebook.get(BU);
                                if(BU != OpportunityConstants.OFI_BU_ALL){
                                    opp.Pricebook2Id=pr1.PriceBookID__c;
                                }
                                else{
                                    if(opp.Business_Unit__c!=null){
                                        PriceBook_Record__mdt pr2=mapofLabeltoPricebook.get(opp.Business_Unit__c);
                                        opp.Pricebook2Id=pr2.PriceBookID__c;
                                    }
                                    else{
                                        opp.Business_Unit__c.addError('Please Select the Business Unit'); 
                                    }
                                }   
                            }
                        }else{
                            opp.addError(system.label.OFI_Opportunity_Create_Error_Msg);
                        }
                    }
                    else{ opp.addError(system.label.OFI_Opportunity_Create_Error_Msg);}
                    
                    if(isAccountTeam==true){
                        if(BU!=OpportunityConstants.OFI_BU_ALL && opp.RecordTypeId==OpportunityConstants.GAIN_OPPORTUNITY_RECORD_TYPE_ID){    
                            if(opp.Business_Unit__c==null){
                                opp.Business_Unit__c = BU;   
                            }
                            if(opp.Business_Unit__c!=BU && opp.RecordTypeId==OpportunityConstants.GAIN_OPPORTUNITY_RECORD_TYPE_ID){
                                opp.Business_Unit__c.addError(system.label.OFI_OpportunityField_Create_Error_Msg+' : '+BU);
                            }	
                        }   
                        if(BU==OpportunityConstants.OFI_BU_ALL && (opp.RecordTypeId==OpportunityConstants.DEFEND_OPPORTUNITY_RECORD_TYPE_ID 
                                                                   || opp.RecordTypeId==OpportunityConstants.PRESENT_OPPORTUNITY_RECORD_TYPE_ID 
                                                                   || opp.RecordTypeId==OpportunityConstants.SERVICE_OPPORTUNITY_RECORD_TYPE_ID
                                                                   || opp.RecordTypeId==OpportunityConstants.TENDERING_OPPORTUNITY_RECORD_TYPE_ID
                                                                   || opp.RecordTypeId==OpportunityConstants.DEVELOP_OPPORTUNITY_RECORD_TYPE_ID))
                        {
                            
                            if(opp.Business_Unit__c == null || opp.Business_Unit__c == OpportunityConstants.OFI_BU_ALL){
                                opp.Business_Unit__c.addError('Please Select the Business Unit');
                            }
                        }
                        else{
                            if(BU!=OpportunityConstants.OFI_BU_ALL && (opp.RecordTypeId==OpportunityConstants.DEFEND_OPPORTUNITY_RECORD_TYPE_ID 
                                                                       || opp.RecordTypeId==OpportunityConstants.PRESENT_OPPORTUNITY_RECORD_TYPE_ID 
                                                                       || opp.RecordTypeId==OpportunityConstants.SERVICE_OPPORTUNITY_RECORD_TYPE_ID
                                                                       || opp.RecordTypeId==OpportunityConstants.TENDERING_OPPORTUNITY_RECORD_TYPE_ID
                                                                       || opp.RecordTypeId==OpportunityConstants.DEVELOP_OPPORTUNITY_RECORD_TYPE_ID))
                            {
                                if(opp.Business_Unit__c==null){
                                    opp.Business_Unit__c = BU;   
                                }      
                            }
                            if(opp.Business_Unit__c!=BU && (opp.RecordTypeId==OpportunityConstants.DEFEND_OPPORTUNITY_RECORD_TYPE_ID 
                                                            || opp.RecordTypeId==OpportunityConstants.PRESENT_OPPORTUNITY_RECORD_TYPE_ID 
                                                            || opp.RecordTypeId==OpportunityConstants.SERVICE_OPPORTUNITY_RECORD_TYPE_ID
                                                            || opp.RecordTypeId==OpportunityConstants.TENDERING_OPPORTUNITY_RECORD_TYPE_ID
                                                            || opp.RecordTypeId==OpportunityConstants.DEVELOP_OPPORTUNITY_RECORD_TYPE_ID))
                            {
                                opp.Business_Unit__c.addError(system.label.OFI_OpportunityField_Create_Error_Msg+' : '+BU);
                            }  
                        }
                    }
                }
                else{ opp.addError(system.label.OFI_Opportunity_Create_Error_Msg); }  
            }     
        }
    }
    
    public static void checkUserAccessForUpdateOpp(list<opportunity> newoppList,Map<Id,Opportunity> oldMapOfOpp)
    {
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Access_Set_Admins');
        if(!hasCustomPermission && userInfo.getName() != System.Label.Automated_Process){
            User u=[Select Id,Name,Email,BU_Identifier__c,UserRole.Name from User where Id=:userinfo.getuserId()];
            Map<string,Teams__c> mapOfUserIdToTeams =new Map<string,Teams__c>();
            Map<String,PriceBook_Record__mdt> mapofLabeltoPricebook=new Map<String,PriceBook_Record__mdt>();
            Map<String,Opportunity_Team_Member_Role__mdt> mapofLabeltoOppTeamMemberRoleMDT=new Map<String,Opportunity_Team_Member_Role__mdt>();
            Set<id> AccountIds = new Set<id>();
            Set<id> OppId=new set<Id>();
            for(opportunity opp:newoppList)
            {
                AccountIds.add(opp.AccountId);
                OppId.add(opp.Id);
            }
            
            //Code Added by Joel Tom to validate Opp team members
            Map<Id,Map<Id,String>> oppUserRoleMap = fetchOppTeamMemberAndRole(OppId);
            
            mapOfUserIdToTeams=opportunityTriggerOfiUser.getAccountTeams(AccountIds);
            mapofLabeltoPricebook=opportunityTriggerOfiUser.getPriceBook();
            mapofLabeltoOppTeamMemberRoleMDT = getOppTeamMemberRoleMDT('Opportunity');
            
            for(opportunity opp:newoppList)
            { 
                if(!oppUserRoleMap.isEmpty() && (opp.RecordTypeId==OpportunityConstants.DEFEND_OPPORTUNITY_RECORD_TYPE_ID || opp.RecordTypeId==OpportunityConstants.DEVELOP_OPPORTUNITY_RECORD_TYPE_ID || opp.RecordTypeId==OpportunityConstants.GAIN_OPPORTUNITY_RECORD_TYPE_ID )){
                    if(oppUserRoleMap.containskey(opp.Id)){    
                        if(!(mapofLabeltoOppTeamMemberRoleMDT.containsKey(oppUserRoleMap.get(opp.Id).get(userinfo.getuserId())))){
                            validateAccountTeamUserAccessOnUpdate(opp,mapOfUserIdToTeams, mapofLabeltoPricebook,oldMapOfOpp);
                        }
                    }
                    else{validateAccountTeamUserAccessOnUpdate(opp,mapOfUserIdToTeams, mapofLabeltoPricebook,oldMapOfOpp);} 
                }
                else{validateAccountTeamUserAccessOnUpdate(opp,mapOfUserIdToTeams, mapofLabeltoPricebook,oldMapOfOpp);} 
            }
        }   
    }
    
    //Method Added by Joel Tom to validate the Opp team members user access
    public static void validateAccountTeamUserAccessOnUpdate(opportunity opp, Map<string,Teams__c> mapOfUserIdToTeams, Map<String,PriceBook_Record__mdt> mapofLabeltoPricebook, Map<Id,Opportunity> oldMapOfOpp){
        if(opp.RecordTypeId==OpportunityConstants.GAIN_OPPORTUNITY_RECORD_TYPE_ID 
           || opp.RecordTypeId==OpportunityConstants.DEFEND_OPPORTUNITY_RECORD_TYPE_ID 
           || opp.RecordTypeId==OpportunityConstants.PRESENT_OPPORTUNITY_RECORD_TYPE_ID 
           || opp.RecordTypeId==OpportunityConstants.SERVICE_OPPORTUNITY_RECORD_TYPE_ID
           || opp.RecordTypeId==OpportunityConstants.TENDERING_OPPORTUNITY_RECORD_TYPE_ID
           || opp.RecordTypeId==OpportunityConstants.DEVELOP_OPPORTUNITY_RECORD_TYPE_ID )
        {
            String BU;
            boolean isAccountTeam=false;
            if(!mapOfUserIdToTeams.isempty()){
                if((mapOfUserIdToTeams.containskey(String.ValueOF(opp.AccountId)+String.valueOf(userinfo.getuserId())))){
                    BU=mapOfUserIdToTeams.get(String.ValueOF(opp.AccountId)+String.valueOf(userinfo.getuserId())).Business_Unit__c;
                    isAccountTeam=true;
                    PriceBook_Record__mdt pr1=mapofLabeltoPricebook.get(BU);
                    if(BU != OpportunityConstants.OFI_BU_ALL){
                        opp.Pricebook2Id=pr1.PriceBookID__c;
                    }
                    else{
                        PriceBook_Record__mdt pr2=mapofLabeltoPricebook.get(opp.Business_Unit__c);
                        opp.Pricebook2Id=pr2.PriceBookID__c;
                    }   
                } 
            }
            else{ opp.addError(system.label.OFI_Opportunity_Create_Error_Msg);}
            
            if(isAccountTeam==true){
                if((BU==OpportunityConstants.OFI_BU_ALL) || ((oldMapOfOpp.get(opp.id).Business_Unit__c==BU) && (oldMapOfOpp.get(opp.id).Business_Unit__c==opp.Business_Unit__c) )){ 
                }
                else{opp.addError(system.label.OFI_Opportunity_Create_Error_Msg);}  
            }
            else{opp.addError(system.label.OFI_Opportunity_Create_Error_Msg);}
        }
    }
    
    //Method Added by Joel Tom to get the Opp team members
    public static Map<Id,Map<Id,String>> fetchOppTeamMemberAndRole(Set<Id> OppId){
        Map<Id,Map<Id,String>> oppUserRoleMap = new Map<Id,Map<Id,String>>();
        List <OpportunityTeamMember> oppTeamMembersList = [Select UserId, TeamMemberRole, OpportunityId from OpportunityTeamMember where OpportunityId IN:OppId];
        for(OpportunityTeamMember oppTeamItem:oppTeamMembersList){
            if(oppUserRoleMap.containsKey(oppTeamItem.OpportunityId)){
                oppUserRoleMap.get(oppTeamItem.OpportunityId).put(oppTeamItem.UserId ,oppTeamItem.TeamMemberRole);
            }
            else{
                oppUserRoleMap.put(oppTeamItem.OpportunityId, new Map<Id,String>{oppTeamItem.UserId => oppTeamItem.TeamMemberRole});
            }  
        }
        return oppUserRoleMap;
    }
    
    public static  Map<String,PriceBook_Record__mdt> getPriceBook()
    {
        list<PriceBook_Record__mdt> priceBookdetails=[select label,PriceBookID__c from PriceBook_Record__mdt];
        Map<String,PriceBook_Record__mdt> mapofLabeltoPricebook=new Map<String,PriceBook_Record__mdt>();
        for(PriceBook_Record__mdt pricebook:priceBookdetails){
            mapofLabeltoPricebook.put(pricebook.label,pricebook);
        }
        return mapofLabeltoPricebook;
    }
    
    public static Map<string,Teams__c> getAccountTeams(Set<id> accntId)
    {
        list<Teams__c> listOfTeams=[Select id,Name,Business_Unit__c,Account__c,Is_Primary__c,User__c,Access_Level__c /*,Access_Set_Role__c*/ from Teams__c where Access_Level__c=:OpportunityConstants.EDIT_ACCESS AND Account__c IN:accntId];
        Map<string,Teams__c> mapOfUserIdToTeams =new Map<string,Teams__c>();
        For(Teams__c tempTeam: listOfTeams){
            mapOfUserIdToTeams.put(String.valueOf(tempTeam.Account__c) + String.valueOF(tempTeam.User__c),tempTeam);
        }
        return mapOfUserIdToTeams;
    }
    
    public static  Map<String,Opportunity_Team_Member_Role__mdt> getOppTeamMemberRoleMDT(String ObjectName)
    {
        list<Opportunity_Team_Member_Role__mdt> OppTeamMemberRole=[select label,Opportunity_Role__c from Opportunity_Team_Member_Role__mdt where Object_Name__c =:ObjectName];
        Map<String,Opportunity_Team_Member_Role__mdt> mapofLabeltoOppTeamMemberRole=new Map<String,Opportunity_Team_Member_Role__mdt>();
        for(Opportunity_Team_Member_Role__mdt role:OppTeamMemberRole){
            mapofLabeltoOppTeamMemberRole.put(role.Opportunity_Role__c,role);
        }
        return mapofLabeltoOppTeamMemberRole;
    }
    
}