src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Local_Currency__c</fullName>
        <label>Local Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IsoCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PLBS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>PLBS_Product__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for tagging the Develop opportunity to the Tender opportunity when the samplings are requested</description>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Related)</relationshipLabel>
        <relationshipName>ChildOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plbs_Annual_Unit__c</fullName>
        <label>Annual Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plbs_Est_Award__c</fullName>
        <label>Est. Award %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plbs_Weight_G__c</fullName>
        <label>Weight(G)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>TEXT(PLBS_Product__r.Product_Family__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sample</fullName>
                </value>
                <value>
                    <fullName>Match</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Application Development</fullName>
                    <isActive>false</isActive>
                    <label>Application Development</label>
                </value>
                <value>
                    <fullName>Co-development</fullName>
                    <isActive>false</isActive>
                    <label>Co-development</label>
                </value>
                <value>
                    <fullName>Ingredient Development</fullName>
                    <isActive>false</isActive>
                    <label>Ingredient Development</label>
                </value>
                <value>
                    <fullName>New Development</fullName>
                    <isActive>false</isActive>
                    <label>New Development</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ratio__c</fullName>
        <label>Ratio</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/objects/PLBS_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Family__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>PLBS_Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Family</valueSetName>
        </valueSet>
    </fields>
    <label>Private Label Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Private Label Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TCB__c.object
<CustomObject>
    <fields>
        <fullName>CTN_40FT_HC__c</fullName>
        <label>CTN/ 40FT HC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fobbing_Container__c</fullName>
        <label>Fobbing / Container</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Product Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs</relationshipLabel>
        <relationshipName>TCBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PM_Type_1st__c</fullName>
        <label>PM Type (1st)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1st_PM_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PM_Type_2nd__c</fullName>
        <label>PM Type (2nd)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X2nd_PM_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pallet_Type__c</fullName>
        <label>Pallet Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pallet_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs (Opportunity)</relationshipLabel>
        <relationshipName>TCBs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotations_Given_as_Per__c</fullName>
        <label>Quotations Given as Per</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Quotations_Given_as_Per</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_CTN__c</fullName>
        <label>Unit/ CTN</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TCB</label>
    <nameField>
        <displayFormat>TCB - {00000}</displayFormat>
        <label>TCB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/IsoCode.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
        <default>true</default>
        <label>AED</label>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>VND</fullName>
    </customValue>
    <description>For local currency in Tender Opportunity</description>
    <masterLabel>IsoCode</masterLabel>
</GlobalValueSet>

src/globalValueSets/Pallet_Set.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Disposal - 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal - 1x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal - 1.1x1.1m</fullName>
    </customValue>
    <customValue>
        <fullName>CHEP – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>CHEP – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>PECO – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>PECO – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>LOSCAM – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>LOSCAM – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 1x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 1.1x1.1m</fullName>
    </customValue>
    <masterLabel>Pallet Set</masterLabel>
</GlobalValueSet>

src/globalValueSets/PLBS_Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Nut mixes</fullName>
    </customValue>
    <customValue>
        <fullName>Pasteurized nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Dry roasted nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Oil roasted nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Salts nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Seasoned nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Trail mixes</fullName>
    </customValue>
    <customValue>
        <fullName>Natural nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Blanched nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Diced nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Slivered nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Sliced nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Nut meal</fullName>
    </customValue>
    <customValue>
        <fullName>Natural paste</fullName>
    </customValue>
    <customValue>
        <fullName>Blanched paste</fullName>
    </customValue>
    <customValue>
        <fullName>Roasted paste</fullName>
    </customValue>
    <customValue>
        <fullName>Pure paste</fullName>
    </customValue>
    <customValue>
        <fullName>Flavored paste</fullName>
    </customValue>
    <customValue>
        <fullName>Granola</fullName>
    </customValue>
    <customValue>
        <fullName>Protein</fullName>
    </customValue>
    <customValue>
        <fullName>Coated bars</fullName>
    </customValue>
    <customValue>
        <fullName>Nut-based cookies</fullName>
    </customValue>
    <customValue>
        <fullName>Natural oil</fullName>
    </customValue>
    <customValue>
        <fullName>Infused oil</fullName>
    </customValue>
    <customValue>
        <fullName>Natural milk</fullName>
    </customValue>
    <customValue>
        <fullName>Flavored milk</fullName>
    </customValue>
    <customValue>
        <fullName>Single Nuts/Fruits</fullName>
        <isActive>false</isActive>
        <label>Single Nuts/Fruits</label>
    </customValue>
    <customValue>
        <fullName>Mixed Nuts</fullName>
        <isActive>false</isActive>
        <label>Mixed Nuts</label>
    </customValue>
    <customValue>
        <fullName>Nut Meal/Flour</fullName>
        <isActive>false</isActive>
        <label>Nut Meal/Flour</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Family.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Snacks</fullName>
    </customValue>
    <customValue>
        <fullName>Ingredients</fullName>
    </customValue>
    <customValue>
        <fullName>Paste</fullName>
    </customValue>
    <customValue>
        <fullName>Bars &amp; Cookies</fullName>
    </customValue>
    <customValue>
        <fullName>Nut &amp; Seed Oils</fullName>
    </customValue>
    <customValue>
        <fullName>Milk</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

src/globalValueSets/Quotations_Given_as_Per.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>40FT Container</fullName>
        <default>true</default>
        <label>40FT Container</label>
    </customValue>
    <customValue>
        <fullName>20FT Container</fullName>
    </customValue>
    <masterLabel>Quotations Given as Per</masterLabel>
</GlobalValueSet>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/X1st_PM_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DOY</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW</fullName>
    </customValue>
    <customValue>
        <fullName>FOUR SIDE SEAL</fullName>
    </customValue>
    <customValue>
        <fullName>DOY FLAT BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW BLOCK BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>VACUUM</fullName>
    </customValue>
    <customValue>
        <fullName>PET JAR</fullName>
    </customValue>
    <customValue>
        <fullName>GLASS JAR</fullName>
    </customValue>
    <customValue>
        <fullName>PET CYLINDER JAR</fullName>
    </customValue>
    <customValue>
        <fullName>METAL CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>COMPOSITE CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PET CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PAPER MILK BOTTLE</fullName>
    </customValue>
    <masterLabel>1st PM Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/X2nd_PM_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSC</fullName>
    </customValue>
    <customValue>
        <fullName>TRAY &amp; LID</fullName>
    </customValue>
    <customValue>
        <fullName>TRAY ONLY</fullName>
    </customValue>
    <customValue>
        <fullName>PRE CUT RSC</fullName>
    </customValue>
    <masterLabel>2nd PM Type</masterLabel>
</GlobalValueSet>

src/classes/TenderProdOppIngredientExtention_Test.cls
@isTest
public class TenderProdOppIngredientExtention_Test {
	@istest static void testMethod1(){
        Id ParentRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Opportunity').getRecordTypeId();
        Id TCBRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PLBS Tendering Product').getRecordTypeId();
        Account acc = new Account(Name = 'UNIT TEST account1', BillingCity='TestIndia', BillingStreet = 'Test 1 street', BillingCountry = 'India', BillingCountryCode ='IN', BillingPostalCode = '123456' , ShippingStreet = 'Test 2 street', ShippingCountry = 'India', ShippingCountryCode ='IN', ShippingPostalCode = '123456');        
        insert acc;
        Product2 product1 = new Product2(Name = 'UNIT TEST Product 1');
        insert product1;
            Product2 product2 = new Product2(Name = 'UNIT TEST Product 2');
        insert product2;
            Product2 product3 = new Product2(Name = 'UNIT TEST Product 3');
        insert product3;
        Pricebook2 standardPricebook = new Pricebook2(Id = Test.getStandardPricebookId(),IsActive = true);     
        Update standardPricebook;
            Pricebook2 PLBSIngredient = new Pricebook2(Name = 'PLBS Ingredient',IsActive = true);     
        Insert PLBSIngredient;
            PricebookEntry pbEntry1 = new PricebookEntry(Pricebook2Id = standardPricebook.Id, Product2Id = product1.Id, UnitPrice = 100, IsActive = true);
        insert pbEntry1;
        PricebookEntry pbEntry2 = new PricebookEntry(Pricebook2Id = PLBSIngredient.Id, Product2Id = product1.Id, UnitPrice = 100, IsActive = true);
        insert pbEntry2;
            PricebookEntry pbEntry5 = new PricebookEntry(Pricebook2Id = standardPricebook.Id, Product2Id = product3.Id, UnitPrice = 100, IsActive = true);
        insert pbEntry5;
            PricebookEntry pbEntry6 = new PricebookEntry(Pricebook2Id = standardPricebook.Id, Product2Id = product2.Id, UnitPrice = 100, IsActive = true);
        insert pbEntry6;
            PricebookEntry pbEntry3 = new PricebookEntry(Pricebook2Id = PLBSIngredient.Id, Product2Id = product2.Id, UnitPrice = 100, IsActive = true);
        insert pbEntry3;
            
            PricebookEntry pbEntry4 = new PricebookEntry(Pricebook2Id = PLBSIngredient.Id, Product2Id = product3.Id, UnitPrice = 100, IsActive = true);
        insert pbEntry4;
        PLBS_Product__c plbsPro=new PLBS_Product__c(Name='TestingPro',Product_Family__c='Snacks',Product_Category__c='Nut mixes');
        insert plbsPro;
        Opportunity opp = new Opportunity(AccountId = acc.Id, 
                                          Name = 'unittest - opp',
                                          StageName = 'Briefing',
                                          CloseDate = date.newInstance(2050, 11, 21),
                                          Business_Unit__c = 'Dairy',
                                          RecordTypeId = ParentRecordTypeId,
                                          Local_Currency__c='USD',
                                          Pricebook2Id = standardPricebook.Id,
                                          Project_Type__c = 'Sample');
        insert opp;
        Opportunity opp1 = new Opportunity(AccountId = acc.Id, 
                                           Name = 'unittest - opp1',
                                           parent_Opportunity__c=Opp.Id,
                                           StageName = 'Briefing',
                                           PLBS_Product__c = plbsPro.Id,
                                           Plbs_Weight_G__c=100,
                                           CloseDate = date.newInstance(2050, 11, 21),
                                           Business_Unit__c = 'Dairy',
                                           RecordTypeId = TCBRecordTypeId,
                                           Pricebook2Id = standardPricebook.Id,
                                           Plbs_Annual_Unit__c =1,
                                           Plbs_Est_Award__c=1000,
                                           Project_Type__c = 'Sample');
        insert opp1;
        update new Opportunity(Id = opp1.Id, Pricebook2Id = PLBSIngredient.Id);
          //While Deploying to Product Rewrite bcz opportunity Trigger will active At That time
        tcb__c tcb1=new TCb__c(Opportunity__c=Opp1.Id,PM_Type_1st__c='DOY',PM_Type_2nd__c='RSC',Fobbing_Container__c=20,CTN_40FT_HC__c =20,Unit_CTN__c=10,
                              Pallet_Type__c='Disposal - 0.8x1.2m',Quotations_Given_as_Per__c='40FT Container');
        insert tcb1;
        /*tcb__c t=[select id from tcb__c where Opportunity__c=:opp1.Id];
        tcb__c tcb=new TCb__c(Id = t.Id,Opportunity__c=Opp1.Id,PM_Type_1st__c='DOY',PM_Type_2nd__c='RSC',Fobbing_Container__c=20,CTN_40FT_HC__c =20,Unit_CTN__c=10,
                              Pallet_Type__c='Disposal - 0.8x1.2m',Quotations_Given_as_Per__c='40FT Container');
        update tcb;*/
        
        OpportunityLineItem oppLineItem1 = new OpportunityLineItem(OpportunityId = opp1.Id, 
                                                                   Product2Id = product3.Id, 
                                                                   PricebookEntryId = pbEntry4.Id,Ratio__c=100,
                                                                   Sampling_Status__c = '7');
        insert oppLineItem1;
        
        PageReference pageRef = Page.CloneTenderProdOppWithIngredient;
        Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('id',opp1.id);
        
        
        // Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opp1);
        TenderProdOppIngredientExtention generateOF = new TenderProdOppIngredientExtention(sc);
        try{
        generateOF.save();
        }catch(Exception e){
            
        }
    }
}