src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Volume_MT__c</fullName>
        <inlineHelpText>Possible / Potential Volume Olam (MT) expects to get</inlineHelpText>
        <label>Estimated Volume</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Sample_Due_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Sample Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key_Driver_to_Win_Project__c</fullName>
        <label>Key Driver to Win Project</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cost</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Time to Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for tagging the Develop opportunity to the Tender opportunity when the samplings are requested</description>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Related)</relationshipLabel>
        <relationshipName>ChildOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sample</fullName>
                </value>
                <value>
                    <fullName>Match</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Application Development</fullName>
                    <isActive>false</isActive>
                    <label>Application Development</label>
                </value>
                <value>
                    <fullName>Co-development</fullName>
                    <isActive>false</isActive>
                    <label>Co-development</label>
                </value>
                <value>
                    <fullName>Ingredient Development</fullName>
                    <isActive>false</isActive>
                    <label>Ingredient Development</label>
                </value>
                <value>
                    <fullName>New Development</fullName>
                    <isActive>false</isActive>
                    <label>New Development</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Text (Account.Regions__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Margin__c</fullName>
        <label>Target Margin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Selling_Price__c</fullName>
        <label>Target Selling Price (Per Unit)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_of_Sample_Grams__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity of Sample</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM(Sample)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KG</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>MT</fullName>
                    <label>Metric Ton</label>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>LB</fullName>
                    <label>US pound</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/globalValueSets/Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>West Europe</fullName>
    </customValue>
    <customValue>
        <fullName>East Europe and Russia</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Central America</fullName>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and North Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Sub Sahara Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Central Asia</fullName>
    </customValue>
    <customValue>
        <fullName>East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia and New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>North East</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>West Coast</fullName>
    </customValue>
    <customValue>
        <fullName>South West</fullName>
    </customValue>
    <customValue>
        <fullName>South East</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
        <isActive>false</isActive>
        <label>APAC</label>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/classes/RequestForSamplingController.cls
/**
* @description       : Controller for the RequestForSampling component that deletes selected product from an opportunity
* @author            : Bharatesh Shetty
* @group             : 
* @last modified on  : 09-06-2021
* @last modified by  : Bharatesh Shetty
**/
public class RequestForSamplingController{
    public RequestForSamplingController() {
        
    }
    /**
* @description : To fetch all the Opportunity Line Items for the currect opportunity
* @author Bharatesh Shetty | 09-01-2021 
* @param recordId 
* @return List<OpportunityLineItemWrapper> 
**/
    @AuraEnabled 
    public static List<OpportunityLineItemWrapper> fetchOpportunityLineItemWrapper(Id recordId ){     
        List<OpportunityLineItemWrapper> lstOpportunityLineItemWrapper = new List<OpportunityLineItemWrapper>();
        // query OpportunityLineItem records related to opportunity and create 'OpportunityLineItemWrapper' class instance for each record. 
        for(OpportunityLineItem opLineItem : [Select id,Name,OpportunityId,Product2Id,Region__c,Country__c,UoM__c,Quantity_of_Sample_Grams__c,Volume__c,UnitPrice,
                                              Opportunity.Name,Opportunity.PriceBook2Id,Opportunity.Estimated_Volume_MT__c,Opportunity.Target_Selling_Price__c,
                                              Opportunity.First_Sample_Due_Date__c,Opportunity.Key_Driver_to_Win_Project__c,Opportunity.Target_Margin__c,Opportunity.CloseDate,
                                              Product2.Name,Product2.Product_Category__c,Opportunity.CurrencyIsoCode
                                              from OpportunityLineItem 
                                              where OpportunityId =:recordId 
                                              order by Name]){
                                                  // by default checkbox should be false  
                                                  lstOpportunityLineItemWrapper.add(new OpportunityLineItemWrapper(false,opLineItem,opLineItem.Opportunity.Name+' '+opLineItem.Product2.Name));
                                              } 
        // return the 'lstOpportunityLineItemWrapper' list 
        return lstOpportunityLineItemWrapper; 
    }
    
    @AuraEnabled
    public static String processSampleRequests(List<OpportunityLineItemWrapper> listOfSelectedOppLineItemWrapper) { 
        System.debug('listOfSelectedOppLineItemWrapper: '+listOfSelectedOppLineItemWrapper);
        String returnResponse = 'SOME ERROR OCCURRED. PLEASE CONTACT SYSTEM ADMIN.' ;
        Savepoint sp = Database.setSavepoint();
        try{
            if(!listOfSelectedOppLineItemWrapper.isEmpty()){
                
                List<Opportunity> listOfOppsToCreate = new  List<Opportunity>();
                List<OpportunityLineItem> listOfOppLineItemsToCreate = new  List<OpportunityLineItem>();
                List<OpportunityTeamMember> listOfOppTeamMemberToCreate = new  List<OpportunityTeamMember>();
                Map<String,PriceBookEntry> mapOfProductIdVsPBE = new Map<String,PriceBookEntry>();
                RelationshipUtiltiy relUtil = new RelationshipUtiltiy();
                Set<Id> setOfProductIds = new Set<Id>();
                String parentOppPriceBookId;
                String parentOppCurrencyISOCode;
               //Query for map
                for(OpportunityLineItemWrapper  eachProductSamplingReq : listOfSelectedOppLineItemWrapper){
                    if(String.isBlank(parentOppPriceBookId)){
                        parentOppPriceBookId = eachProductSamplingReq.objOpportunityLineItem.Opportunity.PriceBook2Id;
                    }
                    if(String.isBlank(parentOppCurrencyISOCode)){
                        parentOppCurrencyISOCode = eachProductSamplingReq.objOpportunityLineItem.Opportunity.CurrencyIsoCode;
                   }
                    if(eachProductSamplingReq.objOpportunityLineItem.Product2Id != NULL){
                        setOfProductIds.add(eachProductSamplingReq.objOpportunityLineItem.Product2Id);
                    }
                }   
                
                if(!setOfProductIds.isEmpty()){
                    System.debug('setOfProductIds: '+setOfProductIds);
                    System.debug('parentOppPriceBookId: '+parentOppPriceBookId);
                    System.debug('parentOppCurrencyISOCode: '+parentOppCurrencyISOCode);
                    for(PriceBookEntry pbe : [Select id,Name,Product2Id, PriceBook2Id
                                              from PriceBookEntry
                                              where Product2Id =: setOfProductIds and PriceBook2Id =: parentOppPriceBookId AND CurrencyISOCode =: parentOppCurrencyISOCode]){
                                                  mapOfProductIdVsPBE.put(pbe.Product2Id,pbe); 
                                              }
                    if(!mapOfProductIdVsPBE.isEmpty()){
                        for(OpportunityLineItemWrapper  eachProductSamplingReq : listOfSelectedOppLineItemWrapper){
                            //For each Product Sampling requested, create a new Develop opportunity.
                            Opportunity opp = createOpportunity(eachProductSamplingReq);
                            listOfOppsToCreate.add(opp);
                            //Attach File captured as Sample spec for each opportunity
                            
                            //For each Product Sampling requested, create a new OpportunityTeamMember.
                            
                            Id pricebookEntryId;
                            if(mapOfProductIdVsPBE.containsKey(eachProductSamplingReq.objOpportunityLineItem.Product2Id)){
                                pricebookEntryId = mapOfProductIdVsPBE.get(eachProductSamplingReq.objOpportunityLineItem.Product2Id).Id;
                            }
                            OpportunityLineItem oppLineitem = createOpportunityLineItem(eachProductSamplingReq, opp, pricebookEntryId);
                            
                            //Register relationship between oppLineitem and opp instances
                            relUtil.registerRelationship(oppLineitem, opp, OpportunityLineItem.OpportunityId);
                            listOfOppLineItemsToCreate.add(oppLineitem);
                            
                            //For each Product Sampling requested, create a new OpportunityLineItem.
                            OpportunityTeamMember oppTeamMember = createOpportunityTeamMember(eachProductSamplingReq, opp);
                            
                            //Register relationship between oppTeamMember and opp instances
                            relUtil.registerRelationship(oppTeamMember, opp, OpportunityTeamMember.OpportunityId);
                            listOfOppTeamMemberToCreate.add(oppTeamMember);
                        }
                        if(!listOfOppsToCreate.isEmpty() && !listOfOppTeamMemberToCreate.isEmpty() && !listOfOppLineItemsToCreate.isEmpty()){
                            //insert Opportunity
                            insert listOfOppsToCreate;
                            System.debug('listOfOppsToCreate : '+listOfOppsToCreate);
                            
                            //resolve relationship and insert OpportunityTeamMember
                            relUtil.resolve('OpportunityTeamMember');
                            insert listOfOppTeamMemberToCreate;
                            System.debug('listOfOppTeamMemberToCreate : '+listOfOppTeamMemberToCreate);
                            
                            // resolve relationship andinsert OpportunnityLineItem
                            relUtil.resolve('OpportunityLineItem');
                            insert listOfOppLineItemsToCreate;
                            System.debug('listOfOppLineItemsToCreate : '+listOfOppLineItemsToCreate);
                            
                            returnResponse = 'SUCCESS';
                        }
                        else{
                            System.debug('listOfOppsToCreate or listOfOppTeamMemberToCreate or  listOfOppLineItemsToCreate is empty');
                        }
                    }
                    else{
                        System.debug('queried mapOfProductIdVsPBE is empty');
                    }
                }
                else{
                    System.debug('setOfProductIds is empty');
                }
            }
            else{
                System.System.debug('Selected list empty');
            }
        }
        catch(Exception e){
            System.debug('Exception Message: '+e.getMessage());
            System.debug('Exception StacktraceSTring: '+e.getStackTraceString());
            returnresponse = e.getMessage();
            //returnresponse ='Divided by zero. Error';
            Database.rollback(sp);
        }
        return returnresponse;
    }
    
    @AuraEnabled
    public static Map<String,List <String>> getSelectOptionsForFields(Map<String,sObject> mapOfPicklistFieldNameWithSobject) {
        Map<String,List <String>> mapOfFieldNameWithOptions = new Map<String,List <String>>();
        for(String fieldName : mapOfPicklistFieldNameWithSobject.keySet()){
            mapOfFieldNameWithOptions.put(fieldName,getselectOptions(mapOfPicklistFieldNameWithSobject.get(fieldName),fieldName));
        }
        return mapOfFieldNameWithOptions;
    }
    // method for fetch picklist values dynamic  
    @AuraEnabled
    public static List < String > getselectOptions(sObject objObject, string fld) {
        system.debug('objObject --->' + objObject);
        system.debug('fld --->' + fld);
        List < String > allOpts = new list < String > ();
        // Get the object type of the SObject.
        Schema.sObjectType objType = objObject.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();
        
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        }
        system.debug('allOpts ---->' + allOpts);
        allOpts.sort();
        return allOpts;
    }
    
    public static Opportunity createOpportunity(OpportunityLineItemWrapper eachOpportunityLineItemWrapper){
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = OpportunityConstants.DEVELOP_OPPORTUNITY_RECORD_TYPE_ID;
        opp.Name = eachOpportunityLineItemWrapper.OppName;
        opp.Parent_Opportunity__c = eachOpportunityLineItemWrapper.objOpportunityLineItem.OpportunityId;
        opp.AccountId = eachOpportunityLineItemWrapper.accountId;
        opp.Estimated_Volume_MT__c = eachOpportunityLineItemWrapper.estimatedVolume;
        opp.Target_Selling_Price__c = eachOpportunityLineItemWrapper.taregtSellingPrice;
        opp.StageName = OpportunityConstants.OPPORTUNITY_STAGE_BRIEFING;
        opp.First_Sample_Due_Date__c = eachOpportunityLineItemWrapper.firstSampleDueDate;
        opp.Key_Driver_to_Win_Project__c = eachOpportunityLineItemWrapper.keyDriverToWinProject;
        opp.Target_Margin__c = eachOpportunityLineItemWrapper.targetMargin;
        opp.CloseDate = eachOpportunityLineItemWrapper.firstSampleDueDate;
        opp.Project_Type__c = 'Sample';
        opp.CurrencyIsoCode = eachOpportunityLineItemWrapper.objOpportunityLineItem.Opportunity.CurrencyIsoCode;
        return opp;
    }
    
    public static OpportunityTeamMember createOpportunityTeamMember(OpportunityLineItemWrapper eachOpportunityLineItemWrapper, Opportunity oppRecord){
        OpportunityTeamMember OppTeamMember = new OpportunityTeamMember();
        OppTeamMember.OpportunityId = oppRecord.Id;
        OppTeamMember.OpportunityAccessLevel = OpportunityConstants.OPPORTUNITY_TEAM_MEMBER_EDIT_ACCESS;
        OppTeamMember.UserId = eachOpportunityLineItemWrapper.PDandIUserId;
        OppTeamMember.TeamMemberRole = OpportunityConstants.OPPORTUNITY_TEAM_PDandI_MEMBER_ROLE;
        return OppTeamMember;
    }
    
    public static OpportunityLineItem createOpportunityLineItem(OpportunityLineItemWrapper eachOpportunityLineItemWrapper, Opportunity oppRecord, Id PBEId){
        OpportunityLineItem OppLineItem = new OpportunityLineItem();
        OppLineItem.OpportunityId = oppRecord.Id;
        OppLineItem.PricebookEntryId = PBEId;
        OppLineItem.Product2Id = eachOpportunityLineItemWrapper.objOpportunityLineItem.Product2Id;
        OppLineItem.Region__c = eachOpportunityLineItemWrapper.objOpportunityLineItem.Region__c;
        OppLineItem.Country__c = eachOpportunityLineItemWrapper.objOpportunityLineItem.Country__c;
        OppLineItem.Sampling_Status__c = OpportunityConstants.sampleStatus_New;
        //Sample Quantity
        OppLineItem.UoM__c = eachOpportunityLineItemWrapper.unitOfMeasure;
        OppLineItem.Quantity_of_Sample_Grams__c = eachOpportunityLineItemWrapper.quantityOfSample;
        
        return OppLineItem;
    }
    public class OpportunityLineItemWrapper {
        
        @AuraEnabled public String reasonForRemoval {get;set;}
        @AuraEnabled public boolean isChecked {get;set;}
        @AuraEnabled public Id accountId {get;set;}
        @AuraEnabled public Id PDandIUserId {get;set;}
        @AuraEnabled public String OppName {get;set;}
        @AuraEnabled public Decimal estimatedVolume {get;set;}
        @AuraEnabled public Decimal taregtSellingPrice {get;set;}
        @AuraEnabled public Date firstSampleDueDate{get;set;}
        @AuraEnabled public String keyDriverToWinProject {get;set;}
        @AuraEnabled public String targetMargin {get;set;}
        //Sample Quantity
        @AuraEnabled public String unitOfMeasure {get;set;}
        @AuraEnabled public Decimal quantityOfSample {get;set;}
        
        @AuraEnabled public OpportunityLineItem objOpportunityLineItem{get;set;}
        public OpportunityLineItemWrapper(boolean isChecked, OpportunityLineItem objOpportunityLineItem, String OppName){
            this.isChecked = isChecked;
            this.objOpportunityLineItem = objOpportunityLineItem;
            this.OppName = OppName;
        }
        public OpportunityLineItemWrapper(){
        }
    }
}