src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PDI_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PDI Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PDI_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PDI Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PDNI_Approval_Status__c</fullName>
        <label>PDI Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PLM_Approval_Status__c</fullName>
        <label>PLM Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sample_Request__c.object
<CustomObject>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sample_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Sample_Request__c</fullName>
        <label>Sample Request</label>
        <referenceTo>Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sample Request Line Item</label>
    <nameField>
        <displayFormat>SRLI-{00000}</displayFormat>
        <label>Sample Request Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SampleRequestResponseRESTTest.cls
@isTest(SeeAllData=false)
public class SampleRequestResponseRESTTest { 
    @testSetup public static void setup() {
    	TestDataFactory.setup();
    }
    
    
    static testMethod void testMethod1(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        opp.PDI_Lead__c = UserInfo.getUserId();
        opp.PDI_Member__c = UserInfo.getUserId();
        opp.PLM_Approval_Status__c = 'Approved';
        opp.PDNI_Approval_Status__c = 'Approved';
        update opp;
		SamplingRequestToOSSMController.createSampleRequest(opp.Id);
        
        test.startTest();
        Sample_Request__c sr = [SELECT Id FROM Sample_Request__c LIMIT 1];
        List<Sample_Request_Line_Item__c> srlin = [SELECT Id FROM Sample_Request_Line_Item__c LIMIT 1];
        RestRequest request = new RestRequest();
        request.requestUri =
            'https://olam--olamcrmstg.my.salesforce.com/services/apexrest/SampleRequestResponse/';
        request.httpMethod = 'POST';
        RestContext.request = request;
        SampleRequestResponseREST.SampleRequest s = new  SampleRequestResponseREST.SampleRequest();
        s.flag = 'sdfs';
        list<SampleRequestResponseREST.SampleRequestLine> srlinlist = new list<SampleRequestResponseREST.SampleRequestLine>();
        SampleRequestResponseREST.SampleRequestLine srln = new SampleRequestResponseREST.SampleRequestLine();
        srln.sap_lineitem_id = 'vhjvjv';
        srln.sf_lineitem_id = srlin[0].id;
        srlinlist.add(srln);
        s.sap_sample_request_id = 'sdfs';
        s.sf_sample_request_id = sr.id;
        s.items = srlinlist;
        s.status = 'sdfs';
        boolean b = SampleRequestResponseREST.updateSampleRequest(s);   
        test.stopTest();        
    }
}