src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_Team_Member_Role__mdt.object
<CustomObject>
    <description>Opportunity team member roles</description>
    <label>Opportunity Team Member Role</label>
    <pluralLabel>Opportunity Team Member Roles</pluralLabel>
</CustomObject>

src/objects/PriceBook_Record__mdt.object
<CustomObject>
    <description>used to store price book name and its id</description>
    <fields>
        <fullName>PriceBookID__c</fullName>
        <label>PriceBookID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>PriceBook Record</label>
    <pluralLabel>PriceBook Records</pluralLabel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Bussiness_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                    <label>Spices</label>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <defaultValue>&quot;Read Access&quot;</defaultValue>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read Access</fullName>
                </value>
                <value>
                    <fullName>Edit Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/QuoteOFITriggerHandler.cls
// 
// Class created by Ashwini
// Last modified by Joel Tom on 24/01/2022
// 

public class QuoteOFITriggerHandler {
    public static void checkUserAccess(list<Quote> quoteList)
    {
        Map<string,Opportunity> mapOfUserIdToQu =new Map<string,Opportunity>();
        Map<String,PriceBook_Record__mdt> mapofLabeltoPricebook=new Map<String,PriceBook_Record__mdt>();
        Map<string,Teams__c> mapOfUserIdToTeams =new Map<string,Teams__c>();
        Set<id> AccountIds = new Set<id>();
        Set<id> oppIds=new Set<id>();
        map<id,id> OppIdQuoteId=new map<Id,id>();
        
        for(Quote qu:quoteList)
        {
            oppIds.add(qu.OpportunityId); 
        	OppIdQuoteId.put(qu.Id,qu.OpportunityId);
        }
        
        Map<id,List<Opportunity>> mapofopp=new  Map<id,List<Opportunity>>();
        mapofopp= getAccountId(oppIds );
        
        for(Id accid:mapofopp.keySet())
        {
            for(Opportunity opp: mapofopp.get(accid)) 
            {
                AccountIds.add(opp.AccountId);
            } 
        }
        
        mapOfUserIdToTeams=QuoteOFITriggerHandler.getAccountTeams(AccountIds);
        mapOfUserIdToQu=QuoteOFITriggerHandler.getAccountQu(oppIds);
        mapofLabeltoPricebook=QuoteOFITriggerHandler.getPriceBook(); 
        
        //Code Added by Joel Tom to validate Opp team members
        Map<Id,Map<Id,String>> oppUserRoleMap = opportunityTriggerOfiUser.fetchOppTeamMemberAndRole(oppIds);
        Map<String,Opportunity_Team_Member_Role__mdt> mapofLabeltoOppTeamMemberRoleMDT = opportunityTriggerOfiUser.getOppTeamMemberRoleMDT('Opportunity');
        
        for(Quote qu:quoteList)
        { 
            if(!oppUserRoleMap.isEmpty()){
                Id oppid = OppIdQuoteId.get(qu.id);
                if(oppUserRoleMap.containskey(oppid)){    
                    if(mapofLabeltoOppTeamMemberRoleMDT.containsKey(oppUserRoleMap.get(oppid).get(userinfo.getuserId()))){
                        String BU;
                        BU=mapOfUserIdToQu.get(String.ValueOF(qu.OpportunityId)).Business_Unit__c;
                        if(!mapofLabeltoPricebook.isEmpty()){ 
                            PriceBook_Record__mdt pr1=mapofLabeltoPricebook.get(BU);
                            qu.Pricebook2Id = pr1.PriceBookID__c;
                        }
                        qu.Bussiness_Unit__c = BU;
                    }else{
                        validateAccountTeamUserAccessOnInsert(qu,mapOfUserIdToTeams, mapofLabeltoPricebook,mapOfUserIdToQu);
                    }
                }
                else{validateAccountTeamUserAccessOnInsert(qu,mapOfUserIdToTeams, mapofLabeltoPricebook,mapOfUserIdToQu);} 
            }
            else{validateAccountTeamUserAccessOnInsert(qu,mapOfUserIdToTeams, mapofLabeltoPricebook,mapOfUserIdToQu);} 
        }
    }
            
   //Method Added by Joel Tom to validate the Opp team members user access
    public static void validateAccountTeamUserAccessOnInsert(Quote qu, Map<string,Teams__c> mapOfUserIdToTeams, Map<String,PriceBook_Record__mdt> mapofLabeltoPricebook, Map<string,Opportunity> mapOfUserIdToQu)
    {
        String BU;
        if(!mapOfUserIdToTeams.isempty()){
            BU=mapOfUserIdToQu.get(String.ValueOF(qu.OpportunityId)).Business_Unit__c;
            Teams__c teamObj=mapOfUserIdToTeams.get(String.valueOf(userinfo.getuserId()));       
            
            if(mapOfUserIdToTeams.containskey(String.valueOf(userinfo.getuserId())) && (BU==teamObj.Business_Unit__c || teamObj.Business_Unit__c =='All')){     
                if(!mapofLabeltoPricebook.isEmpty()){ 
                    PriceBook_Record__mdt pr1=mapofLabeltoPricebook.get(BU);
                    qu.Pricebook2Id=pr1.PriceBookID__c;
                }
                qu.Bussiness_Unit__c = BU;
            }else{
                qu.addError(system.label.OFI_Quote_Create_Error_Msg);
            }
        }
        else{ qu.addError(system.label.OFI_Quote_Create_Error_Msg);} 
    }
    
    
    public static void checkUserAccessForUpdate(list<Quote> newquoteList,Map<Id,Quote> oldMapOfQuote)
    {   
        Map<string,Opportunity> mapOfUserIdToQu =new Map<string,Opportunity>();
        Map<String,PriceBook_Record__mdt> mapofLabeltoPricebook=new Map<String,PriceBook_Record__mdt>();
        Map<string,Teams__c> mapOfUserIdToTeams =new Map<string,Teams__c>();
        Set<id> AccountIds = new Set<id>();
        Set<id> oppIds=new Set<id>();
        map<id,id> OppIdQuoteId=new map<Id,id>();
        
        for(Quote qu:newquoteList)
        {
            oppIds.add(qu.OpportunityId);
            OppIdQuoteId.put(qu.Id,qu.OpportunityId);
        }
        
        Map<id,List<Opportunity>> mapofopp=new  Map<id,List<Opportunity>>();
        mapofopp= getAccountId(oppIds );
        
        for(Id accid:mapofopp.keySet())
        {
            for(Opportunity opp: mapofopp.get(accid)) 
            {
                AccountIds.add(opp.AccountId);
            }  
        }
        
        //Code Added by Joel Tom to validate Opp team members
        Map<Id,Map<Id,String>> oppUserRoleMap = opportunityTriggerOfiUser.fetchOppTeamMemberAndRole(oppIds);
        Map<String,Opportunity_Team_Member_Role__mdt> mapofLabeltoOppTeamMemberRoleMDT = opportunityTriggerOfiUser.getOppTeamMemberRoleMDT('Opportunity');
        
        mapOfUserIdToTeams=QuoteOFITriggerHandler.getAccountTeams(AccountIds);
        mapOfUserIdToQu=QuoteOFITriggerHandler.getAccountQu(oppIds);
        mapofLabeltoPricebook=QuoteOFITriggerHandler.getPriceBook(); 
        
        for(Quote qu:newquoteList)
           { 
                if(!oppUserRoleMap.isEmpty()){
                    Id oppid = OppIdQuoteId.get(qu.id);
                    if(oppUserRoleMap.containskey(oppid)){    
                        if(!(mapofLabeltoOppTeamMemberRoleMDT.containsKey(oppUserRoleMap.get(oppid).get(userinfo.getuserId())))){
                            validateAccountTeamUserAccessOnUpdate(qu,mapOfUserIdToTeams, mapofLabeltoPricebook,oldMapOfQuote,mapOfUserIdToQu);
                        }
                    }
                    else{validateAccountTeamUserAccessOnUpdate(qu,mapOfUserIdToTeams, mapofLabeltoPricebook,oldMapOfQuote,mapOfUserIdToQu);} 
                }
                else{validateAccountTeamUserAccessOnUpdate(qu,mapOfUserIdToTeams, mapofLabeltoPricebook,oldMapOfQuote,mapOfUserIdToQu);} 
               
        }
    }
    
    //Method Added by Joel Tom to validate the Opp team members user access
    public static void validateAccountTeamUserAccessOnUpdate(Quote qu, Map<string,Teams__c> mapOfUserIdToTeams, Map<String,PriceBook_Record__mdt> mapofLabeltoPricebook, Map<Id,Quote> oldMapOfQuote, Map<string,Opportunity> mapOfUserIdToQu)
    {
        String BU;
        Teams__c obj=mapOfUserIdToTeams.get(String.valueOf(userinfo.getuserId()));
        boolean isAccountTeam=false;
        if(!mapOfUserIdToTeams.isempty()){
            BU=mapOfUserIdToQu.get(String.ValueOF(qu.OpportunityId)).Business_Unit__c;
            if(mapOfUserIdToTeams.containskey(String.valueOf(userinfo.getuserId())) && (BU==obj.Business_Unit__c || obj.Business_Unit__c=='All')){
                isAccountTeam=true;
                PriceBook_Record__mdt pr1=mapofLabeltoPricebook.get(BU);
                qu.Pricebook2Id=pr1.PriceBookID__c;
            }
            else{ 
                qu.addError(system.label.OFI_Quote_Create_Error_Msg);}
        }
        else{ 
            qu.addError(system.label.OFI_Quote_Create_Error_Msg);
        }
        
        if(isAccountTeam==true){
            if((BU==OpportunityConstants.OFI_BU_ALL) || ((oldMapOfQuote.get(qu.id).Bussiness_Unit__c==BU)&& (oldMapOfQuote.get(qu.id).Bussiness_Unit__c==qu.Bussiness_Unit__c) )){ 
            }
            else{
                qu.addError(system.label.OFI_Quote_Create_Error_Msg);
            }
        }
        else{
            qu.addError(system.label.OFI_Quote_Create_Error_Msg);
        } 
    
    }
    
    public static Map<string,Opportunity> getAccountQu(set<id> oppId)
    {
        list<Opportunity> listOfTeams=[Select id,Name,Business_Unit__c,AccountId from Opportunity where Id In :oppId   ];
        Map<string,Opportunity> mapOfUserIdToTeams =new Map<string,Opportunity>();
        For(Opportunity tempOpp: listOfTeams){
            mapOfUserIdToTeams.put(String.valueOf(tempOpp.id),tempOpp);
        }
        return mapOfUserIdToTeams;
    }
    
    public static  Map<String,PriceBook_Record__mdt> getPriceBook()
    {
        list<PriceBook_Record__mdt> priceBookdetails=[select label,PriceBookID__c from PriceBook_Record__mdt];
        Map<String,PriceBook_Record__mdt> mapofLabeltoPricebook=new Map<String,PriceBook_Record__mdt>();
        for(PriceBook_Record__mdt pricebook:priceBookdetails){
            mapofLabeltoPricebook.put(pricebook.label,pricebook);
        }
        return mapofLabeltoPricebook;
    }
    
    public static Map<string,Teams__c> getAccountTeams(Set<id> accntId)
    {
        list<Teams__c> listOfTeams=[Select id,Name,Business_Unit__c,Account__c,Is_Primary__c,User__c,Access_Level__c from Teams__c where Access_Level__c=:OpportunityConstants.EDIT_ACCESS AND Account__c IN:accntId];
        Map<string,Teams__c> mapOfUserIdToTeams =new Map<string,Teams__c>();
        For(Teams__c tempTeam: listOfTeams){
            mapOfUserIdToTeams.put(String.valueOF(tempTeam.User__c),tempTeam);
        }
        return mapOfUserIdToTeams;
    }
    
    public static Map<id,List<Opportunity>> getAccountId(Set<id> oppId)
    {
        list<Opportunity> listOfTeams=[Select id,Business_Unit__c,AccountId from Opportunity where Id IN:oppId];
        Map<id,List<Opportunity>> mapOfUserIdToTeams =new Map<id,List<Opportunity>>();
        For(Opportunity tempopp: listOfTeams){
            if(mapOfUserIdToTeams.containsKey(tempopp.AccountId)){
                mapOfUserIdToTeams.get(tempopp.AccountId).add(tempopp);
            }else{
                mapOfUserIdToTeams.put(tempopp.AccountId,new List<Opportunity>{tempopp});
            }
        }
        return mapOfUserIdToTeams;
    }
}