src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PDI_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PDI Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PDI_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PDI Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PDNI_Approval_Status__c</fullName>
        <label>PDI Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PLM_Approval_Status__c</fullName>
        <label>PLM Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sample_Request__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sample_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sample_Request__c</fullName>
        <label>Sample Request</label>
        <referenceTo>Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sample Request Line Item</label>
    <nameField>
        <displayFormat>SRLI-{00000}</displayFormat>
        <label>Sample Request Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SampleRequestFeedbackRESTTest.cls
@isTest(SeeAllData=false)
public class SampleRequestFeedbackRESTTest {   
    @testSetup public static void setup() {
    	TestDataFactory.setup();
    }
    
    @istest
    static void testmethod1(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        opp.PDI_Lead__c = UserInfo.getUserId();
        opp.PDI_Member__c = UserInfo.getUserId();
        opp.PLM_Approval_Status__c = 'Approved';
        opp.PDNI_Approval_Status__c = 'Approved';
        update opp;
		SamplingRequestToOSSMController.createSampleRequest(opp.Id); 
        
        test.startTest();
        Sample_Request_Line_Item__c sampleRequestLine = [SELECT Id FROM Sample_Request_Line_Item__c LIMIT 1];
        sampleRequestLine.Integration_Status__c = 'feedback_update';
        update sampleRequestLine;
        
        RestRequest request = new RestRequest();
        request.requestUri = 'https://olam--olamcrmstg.my.salesforce.com/services/apexrest/SampleRequestFeedbackREST/'+[SELECT Id FROM Sample_Request__c LIMIT 1].Id;
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        SampleRequestFeedbackREST.SampleRequest s = SampleRequestFeedbackREST.getSampleRequestFeedback();
        test.stopTest(); 
    }
}