src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>KG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Bulk_Sample_Quantity__c</fullName>
        <label>Bulk Sample Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Bid__c</fullName>
        <label>Customer Bid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity_of_Sample_Grams__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity of Sample</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reason_for_Resampling__c</fullName>
        <label>Reason for Resampling</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sampling_Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change in Quantity</fullName>
                </value>
                <value>
                    <fullName>Change in Sample Spec</fullName>
                </value>
                <value>
                    <fullName>Change in Quantity &amp; Sample Spec</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resampling_Quantity__c</fullName>
        <label>Resampling Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sample_Feedback__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Helps to capture the feedback received from the customer</inlineHelpText>
        <label>Sample Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment_Month__c</fullName>
        <description>renamed to ETD on 16 June based on UAT feedback</description>
        <encryptionScheme>None</encryptionScheme>
        <label>ETD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Splits__c</fullName>
        <label>Splits</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Unit_of_measure__c</fullName>
        <label>Unit of measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Unit_of_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MT</fullName>
        <default>true</default>
        <label>MT</label>
    </customValue>
    <customValue>
        <fullName>LB</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>QE</fullName>
        <isActive>false</isActive>
        <label>QE</label>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
        <isActive>false</isActive>
        <label>Carton</label>
    </customValue>
    <masterLabel>Unit of Measure</masterLabel>
</GlobalValueSet>

src/classes/opportunityLineItemEdit.cls
public class opportunityLineItemEdit {  
    // method for fetch OpportunityLineItem records list  
    @AuraEnabled
    public static List < OpportunityLineItem  > fetchOpportunityLineItem(string opportunityId) {
        List < OpportunityLineItem > returnList = new List < OpportunityLineItem > ();
        
        for (OpportunityLineItem opli: [select id,Product2.Name,UnitPrice,Customer_Bid__c,Unit_of_measure__c,Description,PricebookEntry.Pricebook2Id,PricebookEntry.currencyisocode,
                                                              Volume__c,Shipment_Month__c,Splits__c,Sampling_Status__c,Quantity_of_Sample_Grams__c,
                                                              Tracking_Number__c,Tracking_URL__c,Reason_for_Resampling__c,Resampling_Quantity__c,Bulk_Sample_Quantity__c,Sample_Feedback__c from OpportunityLineItem  where opportunityId =: opportunityId]) {
            returnList.add(opli);
        }
        system.debug('returnList:'+returnList);
        return returnList;
    }
    
  // method for update records after inline editing  
    @AuraEnabled
    public static List < OpportunityLineItem > saveOpportunityLineItem(string opportunityId, List<OpportunityLineItem> lstOpportunityLineItem) {
		List < OpportunityLineItem > deleteOppLineItem  = new List < OpportunityLineItem >();
        List < OpportunityLineItem > UpsertOppLineItem  = new List < OpportunityLineItem >();
        set<Id> setOfProductIds = new Set<Id>();
        Map<Id,Id> mapOfPBE = new Map<Id,Id>();
        Map<Id,OpportunityLineItem> mapOfOpportunityLineItem = new Map<Id,OpportunityLineItem>([select id,Product2.Name,UnitPrice,Customer_Bid__c,Unit_of_measure__c,Description,
                                                              Volume__c,Shipment_Month__c,Splits__c,Sampling_Status__c,Quantity_of_Sample_Grams__c,
                                                              Tracking_Number__c,Tracking_URL__c,Reason_for_Resampling__c,Resampling_Quantity__c,Bulk_Sample_Quantity__c,Sample_Feedback__c,Opportunity.PriceBook2Id from OpportunityLineItem  where opportunityId =: opportunityId]);
        
        Opportunity opp = [SELECT Id, CurrencyIsoCode, Pricebook2Id FROM Opportunity WHERE Id =:opportunityId];
        
        for(OpportunityLineItem tempOppLineItem : lstOpportunityLineItem){
            setOfProductIds.add(tempOppLineItem.Product2Id );
        }
        for(PricebookEntry tempPBE : [SELECT Id, Product2Id FROM PricebookEntry where Product2Id IN: setOfProductIds AND CurrencyIsoCode = :opp.CurrencyIsoCode AND Pricebook2Id =: opp.Pricebook2Id]){
            mapOfPBE.put(tempPBE.Product2Id,tempPBE.Id);
        }
        
        for(OpportunityLineItem tempOppLineItem : lstOpportunityLineItem){
           system.debug('New Product '+tempOppLineItem.Product2Id);
            system.debug('Opp Id '+tempOppLineItem);
            OpportunityLineItem temp = new OpportunityLineItem();
            system.debug('Old Product '+mapOfOpportunityLineItem.get(tempOppLineItem.Id).Product2Id);
            If(tempOppLineItem.Product2Id != mapOfOpportunityLineItem.get(tempOppLineItem.Id).Product2Id){
                
                temp.PricebookEntryId = mapOfPBE.get(tempOppLineItem.Product2Id);
                deleteOppLineItem.add(new OpportunityLineItem(Id = tempOppLineItem.Id));
                temp.Id = null;
                temp.OpportunityId = opportunityId;
                temp.UnitPrice = tempOppLineItem.UnitPrice;
                temp.Customer_Bid__c = tempOppLineItem.Customer_Bid__c;
                temp.Unit_of_measure__c = tempOppLineItem.Unit_of_measure__c;
                temp.Description = tempOppLineItem.Description;
                temp.Volume__c = tempOppLineItem.Volume__c;
                temp.Shipment_Month__c = tempOppLineItem.Shipment_Month__c;
                temp.Splits__c = tempOppLineItem.Splits__c;
                temp.Sampling_Status__c = tempOppLineItem.Sampling_Status__c;
                temp.Quantity_of_Sample_Grams__c = tempOppLineItem.Quantity_of_Sample_Grams__c;
                temp.Tracking_Number__c = tempOppLineItem.Tracking_Number__c;
                temp.Tracking_URL__c = tempOppLineItem.Tracking_URL__c;
                temp.Reason_for_Resampling__c = tempOppLineItem.Reason_for_Resampling__c;
                temp.Resampling_Quantity__c = tempOppLineItem.Resampling_Quantity__c;
                temp.Bulk_Sample_Quantity__c = tempOppLineItem.Bulk_Sample_Quantity__c;
                temp.Sample_Feedback__c = tempOppLineItem.Sample_Feedback__c;
            }
            else{
                temp = tempOppLineItem;
            }
            UpsertOppLineItem.add(temp);
        }
        system.debug('deleteOppLineItem:'+deleteOppLineItem);
        system.debug('deleteOppLineItem size:'+deleteOppLineItem.size());
        system.debug('InsertOppLineItem:'+UpsertOppLineItem);
        system.debug('InsertOppLineItem size:'+UpsertOppLineItem.size());
        
        if(deleteOppLineItem.size()>0)
        	Delete deleteOppLineItem;
        if(UpsertOppLineItem.size()>0)
        	upsert UpsertOppLineItem;
        //system.debug('Id ze:'+InsertOppLineItem[0].Id);
        return lstOpportunityLineItem;
    }
    
  /* method for fetch picklist values dynamic  
    @AuraEnabled
    public static List < PricebookEntry > getProductList(string opportunityId) {
        Opportunity opp = [select id,pricebook2id from Opportunity where id =:opportunityId];
         List<PricebookEntry> PricebookEntryList = new List<PricebookEntry>();
        PricebookEntryList = ([Select id,Pricebook2Id,IsActive,Product2Id,
                                   Product2.name,
                                   Product2.id from PricebookEntry
                                   where Pricebook2Id =:OPP.Pricebook2Id 
                                   limit 20]);
        return PricebookEntryList;
    }*/
    // method for fetch picklist values dynamic  
    @AuraEnabled
    public static Map < String, String > getselectOptions(sObject objObject, string fld) {
        system.debug('objObject --->' + objObject);
        system.debug('fld --->' + fld);
        Map < String, String > allOpts = new Map < String, String > ();
        // Get the object type of the SObject.
        Schema.sObjectType objType = objObject.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();
        
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
            allOpts.put(a.getLabel(), a.getValue());
        }
        system.debug('*****allOpts***** ---->' + allOpts);
        //allOpts.sort();
        return allOpts;
    }
}