src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>First_Sample_Due_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Sample Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Total Products</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Dispatched__c</fullName>
        <label>Quantity Dispatched</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_of_Sample_Grams__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity of Sample</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sample_Feedback__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Helps to capture the feedback received from the customer</inlineHelpText>
        <label>Sample Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sample_with_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sample with Billing?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM(Sample)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KG</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>MT</fullName>
                    <label>Metric Ton</label>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>LB</fullName>
                    <label>US pound</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Development_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <label>Development Code</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sample_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sample Requests</relationshipLabel>
        <relationshipName>Sample_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sample Requests</relationshipLabel>
        <relationshipName>Sample_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PD_I__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PD&amp;I</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sample_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sample_Due_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sample Due Date</label>
        <type>Date</type>
    </fields>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sample_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Development_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Development Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Product</label>
        <referenceTo>OpportunityLineItem</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Dispatched__c</fullName>
        <label>Quantity Dispatched</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sample_Due_Date__c</fullName>
        <formula>Sample_Request__r.Sample_Due_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sample Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sample_Feedback__c</fullName>
        <description>Helps to capture the feedback received from the customer.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Sample Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sample_Request__c</fullName>
        <label>Sample Request</label>
        <referenceTo>Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sample_with_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sample with Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sample Request Line Item</label>
    <nameField>
        <displayFormat>SRLI-{00000}</displayFormat>
        <label>Sample Request Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    @testSetup public static void setup() {
        Id oppRecordTNMId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Gain Opportunity').getRecordTypeId();
        Id devRecTypId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Develop Opportunity').getRecordTypeId();
        
        Account acc = new Account();
        acc.name='Test Acct';
        acc.BillingCountry = 'India';
        acc.billingpostalcode = '123456';
        acc.BillingStreet ='Test';
        insert acc;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Product2 prod = new Product2(
            Family = '03-Cocoa and Speciality',
            Name ='Test',
            QuantityUnitOfMeasure ='KG',
            Development_Code__c = 'Test1234'
        );
        insert prod;   
        
        PricebookEntry pbEntry = [Select id from PricebookEntry where Pricebook2Id =: pricebookId and
                                  Product2Id =: prod.Id and isActive = true AND CurrencyISOCode = 'USD'];
        
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;  
        
        List<ContentDocument> documents = [
            SELECT Id, Title, LatestPublishedVersionId 
            FROM ContentDocument
        ];
        
        
        
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp3';
        opp.AccountId =acc.id;
        opp.CloseDate =system.today()+30;
        opp.StageName= 'Offering';
        opp.Pricebook2Id = pricebookId;
        opp.RecordTypeId = devRecTypId;    
        insert opp;
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=opp.id;
        contentlink.ShareType= 'V'; 
        contentlink.Visibility = 'AllUsers'; 
        contentlink.ContentDocumentId = documents[0].Id;
        insert contentlink;
        
        OpportunityTeamMember optm1 = new OpportunityTeamMember();
        optm1.UserId = userinfo.getUserId();
        optm1.OpportunityId = opp.id;
        optm1.TeamMemberRole = 'PD&I Member';
        insert optm1;
        
        OpportunityLineItem opl=new OpportunityLineItem();
        opl.OpportunityId = opp.Id;
        opl.Product2Id = prod.Id;
        opl.Quantity_of_Sample_Grams__c = 12.00;
        opl.Sample_with_Billing__c = false;
        opl.Sample_Feedback__c = 'sdasdadasd';
        opl.Sampling_Status__c = '1';
        opl.UoM__c = 'G';
        opl.PricebookEntryId=pbEntry.Id;
        opl.Integration_Status__c = 'amendment';
        opl.Quantity_Dispatched__c = 12;
        insert opl;
    }
    
    
    /*@isTest
    public static List<OpportunityLineItem> sendListOfOpptyLineItems(){
        
        List<OpportunityLineItem> oppLinListToUpdate = new List<OpportunityLineItem>();
        
        
        Account acc = [select id ,name from Account where name='Test Acct'];
        
        Product2 prod = [select id ,name from Product2 where name='Test'];
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry pbEntry = [Select id from PricebookEntry where Pricebook2Id =: pricebookId and
                                  Product2Id =: prod.Id and isActive = true AND CurrencyIsoCode = 'USD'];
        
        Opportunity opp = [select id ,name,First_Sample_Due_Date__c,CloseDate from Opportunity where name='Test Opp2'];
        Sample_Request__c sr = [select id,Account__c,PD_I__c,name,Sample_Due_Date__c 
                                from Sample_Request__c 
                                where Account__c=: acc.id and Opportunity__c=:opp.id and PD_I__c =: userinfo.getUserId() and Sample_Due_Date__c =:opp.First_Sample_Due_Date__c ];
        
        
        List<OpportunityLineItem> oppLinList = [select id,OpportunityId,Product2Id 
                                                from OpportunityLineItem 
                                                where OpportunityId=:opp.Id and Product2Id=:prod.id and
                                                PricebookEntryId =: pbEntry.Id
                                               ];
        
        return oppLinList;
        
    }
    
    
    @isTest
    public static List<Sample_Request_Line_Item__c> sendListOfSampleRequestLineItems(){
        
        Account acc = [select id ,name from Account where name='Test Acct'];
        
        Product2 prod = [select id ,name from Product2 where name='Test'];
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry pbEntry = [Select id from PricebookEntry where Pricebook2Id =: pricebookId and
                                  Product2Id =: prod.Id and isActive = true];
        
        Opportunity opp = [select id ,name,First_Sample_Due_Date__c,CloseDate from Opportunity where name='Test Opp2'];
        
        OpportunityLineItem oppLinObj = [select id,OpportunityId,Product2Id 
                                         from OpportunityLineItem 
                                         where OpportunityId=:opp.Id and Product2Id=:prod.id and
                                         PricebookEntryId =: pbEntry.Id limit 1
                                        ];
        
        Sample_Request__c sr = [select id,Account__c,PD_I__c,name,Sample_Due_Date__c 
                                from Sample_Request__c 
                                where Account__c=: acc.id and Opportunity__c=:opp.id and PD_I__c =: userinfo.getUserId() and Sample_Due_Date__c =:opp.First_Sample_Due_Date__c ];
        
        
        return [SELECT ID,Opportunity_Product__c,Product__c,Sampling_Status__c,Tracking_Number__c,Development_Code__c,Sample_Request__c,Integration_Status__c,Quantity_Dispatched__c 
                FROM Sample_Request_Line_Item__c 
                WHERE Opportunity_Product__c =:oppLinObj.Id AND Product__c =:prod.Id AND Sample_Request__c =:sr.id limit 1
               ];
        
    }
    
    @isTest
    public static Sample_Request__c sendSampleReuestRecord(){
        
        Account acc = [select id ,name from Account where name='Test Acct'];
        
        Product2 prod = [select id ,name from Product2 where name='Test'];
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry pbEntry = [Select id from PricebookEntry where Pricebook2Id =: pricebookId and
                                  Product2Id =: prod.Id and isActive = true];
        
        Opportunity opp = [select id ,name,First_Sample_Due_Date__c,CloseDate from Opportunity where name='Test Opp2'];
        
        OpportunityLineItem oppLinObj = [select id,OpportunityId,Product2Id 
                                         from OpportunityLineItem 
                                         where OpportunityId=:opp.Id and Product2Id=:prod.id and
                                         PricebookEntryId =: pbEntry.Id limit 1
                                        ];
        
        
        return [select id,Account__c,PD_I__c,name,Sample_Due_Date__c 
                from Sample_Request__c 
                where Account__c=: acc.id and Opportunity__c=:opp.id and PD_I__c =: userinfo.getUserId() and Sample_Due_Date__c =:opp.First_Sample_Due_Date__c limit 1];
    }
    
    public static void autoApprovedOpportunityRecord(id opportunityId){
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Approved.');
        req1.setNextApproverIds(new Id[]{UserInfo.getUserId()});
        req1.setObjectId(opportunityId);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setProcessDefinitionNameOrId('Manually_Select_Approver');
        req1.setSkipEntryCriteria(true);
        Approval.ProcessResult result = Approval.process(req1);
        Approval.ProcessWorkitemRequest req2 =  new Approval.ProcessWorkitemRequest();
        req2.setComments('Approving request.');
        req2.setAction('Approve');
        req2.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req2.setWorkitemId(result.getNewWorkitemIds().get(0));
        Approval.ProcessResult result2 =  Approval.process(req2);
        string s = SamplingRequestToOSSMController.createSampleRequest(opportunityId);
    }    */
    
}