src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PDI_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PDI Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PDI_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PDI Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PDNI_Approval_Status__c</fullName>
        <label>PDI Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PLM_Approval_Status__c</fullName>
        <label>PLM Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sample_Request__c.object
<CustomObject>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SampleRequestRESTTest.cls
@isTest(SeeAllData=false)
private class SampleRequestRESTTest{
    @testSetup public static void setup() {
    	TestDataFactory.setup();
    }
    
    
    static testMethod void testMethod1(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        opp.PDI_Lead__c = UserInfo.getUserId();
        opp.PDI_Member__c = UserInfo.getUserId();
        opp.PLM_Approval_Status__c = 'Approved';
        opp.PDNI_Approval_Status__c = 'Approved';
        update opp;
		SamplingRequestToOSSMController.createSampleRequest(opp.Id); 
        
        Test.startTest();
        
        Id recordId = [SELECT Id FROM Sample_Request__c LIMIT 1].Id;
        RestRequest request = new RestRequest();
        request.requestUri =
            'https://olam--olamcrmstg.my.salesforce.com/services/apexrest/SampleRequest/'
            + recordId ;
        request.httpMethod = 'GET';
        RestContext.request = request;
        // Call the method to test
        SampleRequestREST.SampleRequestWrapper sreq = SampleRequestREST.getSampleRequest(); 
        
        test.stopTest();     
    }
}