src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>KG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>External_Product_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Product Code</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <label>Approval Required ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <isActive>false</isActive>
                    <label>N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver_Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Approver Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Material_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Material Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_File_Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is File Uploaded ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Configuration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measure__c</fullName>
        <label>Unit Of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Unit_of_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MT</fullName>
        <default>true</default>
        <label>MT</label>
    </customValue>
    <customValue>
        <fullName>LB</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>QE</fullName>
        <isActive>false</isActive>
        <label>QE</label>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
        <isActive>false</isActive>
        <label>Carton</label>
    </customValue>
    <masterLabel>Unit of Measure</masterLabel>
</GlobalValueSet>

src/classes/QuoteLineItemsDisplayController.cls
public class QuoteLineItemsDisplayController {
    @AuraEnabled
    public static List<QuoteLineItem> fetchQuoteLineItems (String quoteId){
        System.debug('quoteId: '+quoteId);
        List<QuoteLineItem> QuoLIList = [SELECT Id,Product2.Name,Product2.External_Product_Code__c,UnitPrice,Quantity,Subtotal,Volume__c,Unit_Of_Measure__c,
                                         Approval_Required__c,Approval_Status__c,Quote.Status,Product_Configuration__c,Approver_Comment__c,Customer_Material_Code__c,Is_File_Uploaded__c
                                         FROM QuoteLineItem 
                                         WHERE QuoteID =: quoteId
                                        ];
        
        return QuoLIList;
    }
    @AuraEnabled
    public static Quote fetchQuoteDetails (String quoteId){
        System.debug('quoteId: '+quoteId);
        return [SELECT Id,Status,Opportunity.ContactId FROM Quote WHERE Id =: quoteId];
    }
    @AuraEnabled
    public static String deleteQuoteLineItems (List<QuoteLineItem> listOfQuoteLineItemsToDelete){
        User systeAdmin = [select id,email from User where  Profile.name = 'System Administrator' and IsActive=True limit 1];
        String returnResponse = 'OOOPS! Some error occurred. Please Contact System Admin. SYSTEM ADMIN EMAIL : '+systeAdmin.Email ;
        Savepoint sp = Database.setSavepoint();
        try{
            if(!listOfQuoteLineItemsToDelete.isEmpty()){
                delete listOfQuoteLineItemsToDelete;
                returnResponse = 'SUCCESS';
            }
        }
        catch(Exception e){
            returnresponse = 'OOOPS! Some error occurred. Please Contact System Admin. SYSTEM ADMIN EMAIL : '+systeAdmin.Email +' . ' +e.getMessage();
            //returnresponse ='Divided by zero. Error';
            Database.rollback(sp);
        }
        return returnResponse;
    }
    @AuraEnabled
    public static void deleteFiles(List<Id> listOfContentDocIds){
        //check if the ContentDocument Ids set is not empty    	
        if(!listOfContentDocIds.isEmpty()){
            List<ContentDocument> contentDocumentToDelete = new List<ContentDocument>();
            //query to get all ContentDocument that needs to be deleted
            contentDocumentToDelete = [Select id From ContentDocument Where Id IN :listOfContentDocIds];
            if(!contentDocumentToDelete.isEmpty()){
                try{
                    delete contentDocumentToDelete;
                } 
                catch(Exception ex){
                    System.debug('Exception--'+ex.getMessage());
                }	
            }
        }        
    }   
}