src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Total Products</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>KG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Configuration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_of_measure__c</fullName>
        <label>Unit of measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Product_Config_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Product Config Required?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductConfigMaster__c.object
<CustomObject>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product_Configuration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ProductConfigMaster</relationshipLabel>
        <relationshipName>ProductConfigMaster</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ProductConfigMaster</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ProductConfigMaster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductConfigMaster</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Bussiness_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Spice</fullName>
                    <label>Spices</label>
                </value>
                <value>
                    <fullName>Edible_Nuts</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <label>Approval Required ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <isActive>false</isActive>
                    <label>N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Config_Source__c</fullName>
        <label>Product Configuration Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved SKU</fullName>
                </value>
                <value>
                    <fullName>Product Config Master</fullName>
                </value>
                <value>
                    <fullName>SAP Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Configuration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measure__c</fullName>
        <label>Unit Of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit_of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Unit_of_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MT</fullName>
        <default>true</default>
        <label>MT</label>
    </customValue>
    <customValue>
        <fullName>LB</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>QE</fullName>
        <isActive>false</isActive>
        <label>QE</label>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
        <isActive>false</isActive>
        <label>Carton</label>
    </customValue>
    <masterLabel>Unit of Measure</masterLabel>
</GlobalValueSet>

src/classes/QuoteCreateNewFromOpptyCntl.cls
public class QuoteCreateNewFromOpptyCntl {
    
	@AuraEnabled 
    public static ResponseWrapper createQuote(String oppId){
        
        Savepoint sp = Database.setSavepoint();
        
        try{
            String message = 'SUCCESS';
            
            ResponseWrapper res = new ResponseWrapper();
            
            Opportunity opp = getOpportunity(oppId);
            
            if(opp.OpportunityLineItems != null && opp.OpportunityLineItems.size() > 0){
                
                //Newly added as part of product Config API and JSON changes
                Set<Id> setOfProdIdsforProdConfig = new Set<Id>();
                Map<Id, ProductConfigMaster__c> mapOfProductIdWithProdConfigMaster = new Map<Id, ProductConfigMaster__c>();
                
                for(OpportunityLineItem oppLine :opp.OpportunityLineItems){
                    if(oppLine.PricebookEntryId !=NULL && oppLine.PricebookEntry.Product2Id !=NULL && oppLine.PricebookEntry.Product2.Is_Product_Config_Required__c){
                        setOfProdIdsforProdConfig.add(oppLine.PricebookEntry.Product2Id);
                    }
                }
                
                if(!setOfProdIdsforProdConfig.isEmpty()){
                    for(ProductConfigMaster__c prodConfigMaster : [Select Id,Product__c,Product_Configuration__c 
                                                                     from ProductConfigMaster__c 
                                                                     where Product__c =: setOfProdIdsforProdConfig]){
                        mapOfProductIdWithProdConfigMaster.put(prodConfigMaster.Product__c,prodConfigMaster);
                    }
                }
                Quote newQuote = new Quote(
                    Name = opp.Name,
            		OpportunityId = opp.Id,
                    Ship_to_Party__c = opp.AccountId,
                    Bussiness_Unit__c = opp.Business_Unit__c,
                    CurrencyISOCode = opp.CurrencyISOCode,
                    Pricebook2Id = opp.Pricebook2Id,
                    ExpirationDate = opp.CloseDate,
                    Status = 'Not Started'
            	);
                insert newQuote;
                
                List<QuoteLineItem> quoteLineItemList = new List<QuoteLineItem>();
                for(OpportunityLineItem oppLine :opp.OpportunityLineItems){
                    QuoteLineItem quoteLine = new QuoteLineItem(
                    	QuoteId = newQuote.Id,
                        OpportunityLineItemId  = oppLine.Id,
                        UnitPrice = oppLine.UnitPrice,
                        Volume__c = oppLine.Volume__c,
                        Quantity = oppLine.Quantity,
                        PricebookEntryId = oppLine.PricebookEntryId,
                        Unit_of_Measure__c = oppLine.Unit_of_Measure__c,
                        Approval_Required__c = 'Yes'
                    );
                    if(mapOfProductIdWithProdConfigMaster.containsKey(oppLine.PricebookEntry.Product2Id)){
                        quoteLine.Product_Configuration__c = mapOfProductIdWithProdConfigMaster.get(oppLine.PricebookEntry.Product2Id).Product_Configuration__c;
                        quoteLine.Product_Config_Source__c = AddQuoteLineItemsController.PRODCONFIGSOURCE_PRODUCT_CONFIG_MASTER;
                    }
                    quoteLineItemList.add(quoteLine);
                }
                insert quoteLineItemList;
                
                res.quoteId = newQuote.Id;
            }
            else{
                message = 'There are no accepted products to create a quote';
            }
            
            res.message = message;
            return res;
    	}
        catch(Exception e){
            Database.rollback(sp);
            
            ResponseWrapper res = new ResponseWrapper();
            res.message = e.getMessage();
            res.quoteId = null;
            return res;
        }
    }
    
    
    public static Opportunity getOpportunity(String oppId){
       	return [SELECT Id, Name, AccountId, CloseDate, Pricebook2Id, CurrencyISOCode, Business_Unit__c, 
                (SELECT Id, PricebookEntryId,PricebookEntry.Product2.Is_Product_Config_Required__c, UnitPrice, Volume__c, Unit_of_Measure__c, Quantity FROM OpportunityLineItems WHERE Sampling_Status__c = '7')
                FROM Opportunity WHERE Id =:oppId];
    }
    
 
    public class ResponseWrapper{
        @AuraEnabled public String quoteId;
        @AuraEnabled public String message;
    }    
}