src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Volume__c</fullName>
        <description>Roll up summary of the Volume of the Opportunity Products</description>
        <inlineHelpText>Total of product volume after product acceptance</inlineHelpText>
        <label>Opportunity Volume (MT)</label>
        <summarizedField>OpportunityLineItem.Converted_Volume_in_MT__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_Log__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manually Removed</fullName>
                </value>
                <value>
                    <fullName>Not offered by Olam</fullName>
                </value>
                <value>
                    <fullName>Line Item Value Changed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OpportunityID__c</fullName>
        <label>OpportunityID</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Logs</relationshipLabel>
        <relationshipName>Opportunity_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product2Id</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Logs</relationshipLabel>
        <relationshipName>Opportunity_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Removal__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reason for Removal</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Olam Offer (per MT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume (MT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT( PricebookEntry.Product2.Product_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/classes/RemoveOpportunityProductController.cls
/**
 * @description       : Controller for the RemoveOpportuntityProducts component that deletes selected product from an opportunity
 * @author            : Bharatesh Shetty
 * @group             : 
 * @last modified on  : 09-01-2021
 * @last modified by  : Bharatesh Shetty
**/
public class RemoveOpportunityProductController{
    public RemoveOpportunityProductController() {

    }
    /**
    * @description : To fetch all the Opportunity Line Items for the currect opportunity
    * @author Bharatesh Shetty | 09-01-2021 
    * @param recordId 
    * @return List<OpportunityLineItemWrapper> 
    **/
    @AuraEnabled 
    public static List<OpportunityLineItemWrapper> fetchOpportunityLineItemWrapper(Id recordId ){     
        List<OpportunityLineItemWrapper> lstOpportunityLineItemWrapper = new List<OpportunityLineItemWrapper>();
        // query OpportunityLineItem records related to opportunity and create 'OpportunityLineItemWrapper' class instance for each record.
        for(OpportunityLineItem opLineItem : [Select id,Name,OpportunityId,Opportunity.Name,Product2Id,Product2.Name,Product2.Product_Category__c,Volume__c,UnitPrice 
                                              from OpportunityLineItem 
                                              where OpportunityId =:recordId 
                                              order by Name]){
            // by default checkbox should be false 
            lstOpportunityLineItemWrapper.add(new OpportunityLineItemWrapper(false,opLineItem));
        } 
        // return the 'lstOpportunityLineItemWrapper' list 
        return lstOpportunityLineItemWrapper; 
    }
    @AuraEnabled
    public static String deleteOpportunityLineItems(List<OpportunityLineItemWrapper> listOfSelectedOppLineItemWrapper) { 
        System.debug('listOfSelectedOppLineItemWrapper: '+listOfSelectedOppLineItemWrapper);
        String returnResponse = 'SOME ERROR OCCURRED. PLEASE CONTACT SYSTEM ADMIN.' ;
        Savepoint sp = Database.setSavepoint();
        try{
            if(!listOfSelectedOppLineItemWrapper.isEmpty()){
                List<OpportunityLineItem> listOfOppLineItemsToDelete = new  List<OpportunityLineItem>();
                List<Opportunity_Log__C> listOfOppLogsToInsert = new  List<Opportunity_Log__C>();
                
                /*for(OpportunityLineItem  eachSelectedLineitem : listOfSelectedOpLineItems){
                    listOfOppLineItemsToDelete.add (new OpportunityLineItem(Id = eachSelectedLineitem.Id));
                    //For each of the selected lineitems create an Opportunity Log record while removing OpportunityLineItem.
                    Opportunity_Log__C OppLogsToInsert = new Opportunity_Log__C();
                    OppLogsToInsert.Name = eachSelectedLineitem.Product2.Name;
                    OppLogsToInsert.OpportunityID__c = eachSelectedLineitem.OpportunityId;
                    OppLogsToInsert.Product2Id__c = eachSelectedLineitem.Product2Id;
                    OppLogsToInsert.Action__c = OpportunityLogConstants.ACTION_MANNUALLY_REMOVED;
                    listOfOppLogsToInsert.add (OppLogsToInsert);
                }
                if(!listOfOppLineItemsToDelete.isEmpty() && !listOfOppLogsToInsert.isEmpty()){
                    //Delete OpportunityLineItems
                    delete listOfOppLineItemsToDelete;
                    //Create Opportunity Logs
                    insert listOfOppLogsToInsert;
                }*/
                for(OpportunityLineItemWrapper  eachSelectedLineitemWrapper : listOfSelectedOppLineItemWrapper){
                    listOfOppLineItemsToDelete.add (new OpportunityLineItem(Id = eachSelectedLineitemWrapper.objOpportunityLineItem.Id));
                    //For each of the selected lineitems create an Opportunity Log record while removing OpportunityLineItem.
                    Opportunity_Log__C OppLogsToInsert = new Opportunity_Log__C();
                    OppLogsToInsert.Name = eachSelectedLineitemWrapper.objOpportunityLineItem.Product2.Name;
                    OppLogsToInsert.OpportunityID__c = eachSelectedLineitemWrapper.objOpportunityLineItem.OpportunityId;
                    OppLogsToInsert.Product2Id__c = eachSelectedLineitemWrapper.objOpportunityLineItem.Product2Id;
                    OppLogsToInsert.Action__c = OpportunityLogConstants.ACTION_MANNUALLY_REMOVED;
                    OppLogsToInsert.Reason_for_Removal__c = eachSelectedLineitemWrapper.reasonForRemoval;
                    OppLogsToInsert.Volume__c = eachSelectedLineitemWrapper.objOpportunityLineItem.Volume__c;
                    OppLogsToInsert.UnitPrice__c = eachSelectedLineitemWrapper.objOpportunityLineItem.UnitPrice;
                    listOfOppLogsToInsert.add (OppLogsToInsert);
                }
                if(!listOfOppLineItemsToDelete.isEmpty() && !listOfOppLogsToInsert.isEmpty()){
                    //Delete OpportunityLineItems
                    delete listOfOppLineItemsToDelete;
                    //Create Opportunity Logs
                    insert listOfOppLogsToInsert;
                    returnResponse = 'SUCCESS';
               
                }
            }
            else{
                System.System.debug('Selected list empty');
            }
        }
        catch(Exception e){
            System.debug('Exception Message: '+e.getMessage());
            System.debug('Exception StacktraceSTring: '+e.getStackTraceString());
            returnresponse = e.getMessage();
            //returnresponse ='Divided by zero. Error';
            Database.rollback(sp);
        }
        return returnresponse;
    }
    public class OpportunityLineItemWrapper {
        @AuraEnabled public String reasonForRemoval {get;set;}
        @AuraEnabled public boolean isChecked {get;set;}
        @AuraEnabled public OpportunityLineItem objOpportunityLineItem{get;set;}
        public OpportunityLineItemWrapper(boolean isChecked, OpportunityLineItem objOpportunityLineItem){
            this.isChecked = isChecked;
            this.objOpportunityLineItem = objOpportunityLineItem;
        }
        public OpportunityLineItemWrapper(){
        }
    }
}