src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote_Line_Approval__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Quote Line Approvals</relationshipLabel>
        <relationshipName>Quote_Line_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote Line Approvals</relationshipLabel>
        <relationshipName>Quote_Line_Approvals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line Approval</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Approval Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <label>Approval Required ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <isActive>false</isActive>
                    <label>N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BLEND</fullName>
    </customValue>
    <customValue>
        <fullName>Blended Product</fullName>
    </customValue>
    <customValue>
        <fullName>BMP</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTER</fullName>
    </customValue>
    <customValue>
        <fullName>By product</fullName>
    </customValue>
    <customValue>
        <fullName>CASEIN</fullName>
    </customValue>
    <customValue>
        <fullName>CHEESE</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Drink Mix</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Butter</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Cake</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Liquor</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Low Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Mid Fat Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa Powder &amp; Sugar</fullName>
    </customValue>
    <customValue>
        <fullName>CONDENSED</fullName>
    </customValue>
    <customValue>
        <fullName>CREAM</fullName>
    </customValue>
    <customValue>
        <fullName>Dehy</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Almond</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Brazil Nut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Cashew</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Hazelnut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Macadamia</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Mixed Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Peanut</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pecan</fullName>
    </customValue>
    <customValue>
        <fullName>EN - Pinenut</fullName>
    </customValue>
    <customValue>
        <fullName>Tropical</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

src/classes/SubmitForApprovalControllerTest.cls
@isTest
public class SubmitForApprovalControllerTest {
	
    @testSetup
    public static void setupData()
    {
        //Create an Account
        Account acc = TestData_Factory.createAccount(true);
        
        //Get the pricebookId
        Id pricebookId = Test.getStandardPricebookId();
        
        //Create an Opportunity
        Opportunity opp = TestData_Factory.createOpportunity(acc, pricebookId, true);
        
        //Create a Quote
        Quote quote = TestData_Factory.createQuote(acc, opp, true);
        
        //Create a Product
        Product2 prod = TestData_Factory.createProduct('12-Spices', 'Tropical', 'Pepper', 'Black Pepper', true);
        
        //Create a PricebookEntry
        //PricebookEntry pbe = TestData_Factory.createPricebookEntry(pricebookId, prod, true);
        
        PricebookEntry pbe = [Select Id from PricebookEntry where Product2Id =: prod.Id and CurrencyIsoCode =: opp.CurrencyIsoCode limit 1];
            
        //Create a QuoteLineItem
        QuoteLineItem qLI = TestData_Factory.createQuoteLineItem(pbe, prod, quote, true);
        qLI.Approval_Required__c = 'Yes';
        qLI.Approval_Status__c = 'Not Started;';
        QuoteLineItem qLI2 = TestData_Factory.createQuoteLineItem(pbe, prod, quote, true);
        qLI2.Approval_Required__c = 'Yes';
        qLI2.Approval_Status__c = 'Not Started';
        
        
        System.debug('qLI: '+qLI);
    }
    
    @isTest
    public static void getQuoteLineApprovalsTest()
    {
        Quote quo = [Select id,name from Quote Limit 1];
        Test.startTest();
        SubmitForApprovalController.getQuoteLineApprovals(quo.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void createQuoteLineApprovalTest()
    {
        Quote q = [Select Id, name from Quote Limit 1];
        QuoteLineItem qLI = [Select Id,Product2.Name from QuoteLineItem where QuoteId =: q.Id Limit 1];
        
        Quote_Line_Approval__c QLA = new Quote_Line_Approval__c();
       	QLA.Quote__c = q.Id;
        QLA.Quote_Line_Item__c = qLI.id;
        
        List<Quote_Line_Approval__c> QLAList = new List<Quote_Line_Approval__c>();
        QLAList.add(QLA);
        SubmitForApprovalController.createQuoteLineApprovals(QLAList);
	}
    
    @isTest
    public static void createQuoteLineApprovalTest_Catch()
    {
        Quote q = [Select Id, name from Quote Limit 1];
        QuoteLineItem qLI = [Select Id,Product2.Name from QuoteLineItem where QuoteId =: q.Id Limit 1];
        
        Quote_Line_Approval__c QLA = new Quote_Line_Approval__c();
       	QLA.Quote__c = q.Id;
        QLA.Quote_Line_Item__c = qLI.id;
        QLA.Product_Category__c = 'qwertyuiopokjhgfdsadfghjkljhgfdsdfghjklkjhythgrtyuiouytrtyuioiuytrtyuiopiuytrtyuiopiuytyui'
            +'sadfghfjggfjkjhdfghjkl;kjhgfdsdsfghjkl;kjhgfdfghjkl;lkjhgfdfghjkl;lkjhgfjkl;lkjhgfasdfghjkl;kjhgfdsafghjkl;kjhgfd'
            +'dsfghjkjhgfdsdfghjkl;sdfghjhgfdsdafsghjghgfvbnmnbvsadfghjhgfdcvfgbnhmnbvvdfbgnhmj,kbvccvdfbghnjmkjdcfvbghnjmkkmdcfvgbhnjm';
        
        List<Quote_Line_Approval__c> QLAList = new List<Quote_Line_Approval__c>();
        QLAList.add(QLA);
        SubmitForApprovalController.createQuoteLineApprovals(QLAList);
	}
}