src/objects/Quote_Line_Approval__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Line Approval</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Approval Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuoteLineApprovalTriggerHandler.cls
public class QuoteLineApprovalTriggerHandler {
    public static void onAfterInsert(List<Quote_Line_Approval__c> quoteLineApprovals){
        QuoteLineApprovalTriggerHelper.addPLMsToOpportunityTeams(quoteLineApprovals);
    }
    
    public static void onAfterUpdate(List<Quote_Line_Approval__c> quoteLineApprovals,Map<id,Quote_Line_Approval__c> quoteLineApprovalOldMap)
    {
        //QuoteLineItemId
        //Check if status change from InProgress to Accepted/Rejected
        // Map of Changed Status on QLA with Quote Line Item Id
        
        Map<ID,Quote_Line_Approval__c> mapOfIdWithQuoteLineApproval = new Map<ID,Quote_Line_Approval__c>();
        for(Quote_Line_Approval__c qLA : quoteLineApprovals){
            if(quoteLineApprovalOldMap.containsKey(qLA.Id))
            {   
                if(quoteLineApprovalOldMap.get(qLA.Id).Approval_Status__c == 'In Progress' && (qLA.Approval_Status__c == 'Approved'
                  || qLA.Approval_Status__c == 'Rejected'))
                {
                    
					mapOfIdWithQuoteLineApproval.put(qLA.Id,qLA);                    
                }
            }
        }
        
        QuoteLineApprovalTriggerHelper.addApproversComments(mapOfIdWithQuoteLineApproval);
        //Map of QuoteLineItemId with QuoteLineApproval
        
    }
}