src/objects/Sample_Request__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sample_Request_SAP_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sample Request OSSM Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sample_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Line_Item_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OSSM Line Item Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sample_Request__c</fullName>
        <label>Sample Request</label>
        <referenceTo>Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sample Request Line Item</label>
    <nameField>
        <displayFormat>SRLI-{00000}</displayFormat>
        <label>Sample Request Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SampleRequestResponseREST.cls
@RestResource(urlMapping='/SampleRequestResponse/*')
global with sharing class SampleRequestResponseREST{
    @HttpPost
    global static Boolean updateSampleRequest(SampleRequest record) {
        Boolean success = false;
        
        System.debug('OSSM RESPONSE --' + JSON.serialize(record));
        
        Sample_Request__c sampleRequest = new Sample_Request__c(
            Id = record.sf_sample_request_id,
            Sample_Request_SAP_Id__c = record.sap_sample_request_id,
            Integration_Status__c = record.flag == 'S' ? 'registered_in_ossm' : 'failed',
            Integration_Message__c = record.status
        );
        
        
        List<Sample_Request_Line_Item__c> lineItemsToUpdate = new List<Sample_Request_Line_Item__c>();
        
        for(SampleRequestLine item :record.items){
            lineItemsToUpdate.add(
                new Sample_Request_Line_Item__c(
                    Id = item.sf_lineitem_id, 
                    SAP_Line_Item_Id__c = record.flag == 'S' ? item.sap_lineitem_id : '',
                    Integration_Status__c = record.flag == 'S' ? 'registered_in_ossm' : 'failed'
                )    
            );
        }
        
        
        UPDATE sampleRequest;
        UPDATE lineItemsToUpdate;
        return true;
    }
    
    
    @testVisible
     global class SampleRequest{
        global String sf_sample_request_id;
        global String sap_sample_request_id;
        global String flag;
        global String status;
        global List<SampleRequestLine> items;
        
        global SampleRequest(){
            items = new List<SampleRequestLine>();
        }
    }  
    
    
    @testVisible
    global class SampleRequestLine{
        global String sf_lineitem_id;
        global String sap_lineitem_id;
    }
}