src/objects/Sample_Request__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Hours__c</fullName>
        <label>Actual Hours</label>
        <summarizedField>Sample_Request_Line_Item__c.Actual_Hours__c</summarizedField>
        <summaryForeignKey>Sample_Request_Line_Item__c.Sample_Request__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sample_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Hours__c</fullName>
        <label>Actual Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Created_By_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Created By Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Dispatch__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date of Dispatch</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Development_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Development Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modified_By_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Modified By Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Dispatched__c</fullName>
        <label>Quantity Dispatched</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SAP_Line_Item_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OSSM Line Item Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sample_Request__c</fullName>
        <label>Sample Request</label>
        <referenceTo>Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sample Request Line Item</label>
    <nameField>
        <displayFormat>SRLI-{00000}</displayFormat>
        <label>Sample Request Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/classes/SampleRequestDispatchREST.cls
@RestResource(urlMapping='/SampleRequestDispatch/*')
global with sharing class SampleRequestDispatchREST{
    public class CustomException extends Exception{}
    
    @HttpPost
    global static Boolean updateSampleRequest(List<SampleRequestLineItem> record) {
       
        System.debug('OSSM REQUEST -- '+JSON.serialize(record));
        try{
            Set<String> sapLineItemIdSet = new Set<String>();
            for(SampleRequestLineItem sampleLine :record){
                sapLineItemIdSet.add(sampleLine.sap_line_item_id);
            }
            
            Map<String, Sample_Request_Line_Item__c> sampleRequestLineMap = new Map<String, Sample_Request_Line_Item__c>();
            sampleRequestLineMap = getSampleRequestLineMap(record[0].sf_sample_request_id, sapLineItemIdSet);
            
            for(SampleRequestLineItem sampleLine :record){
                if(sampleRequestLineMap.containsKey(sampleLine.sap_line_item_id)){
                    Sample_Request_Line_Item__c srLine = sampleRequestLineMap.get(sampleLine.sap_line_item_id);
                    if(sampleLine.development_code != null) {srLine.Development_Code__c = sampleLine.development_code;}
                    if(sampleLine.quantity_of_sample != null) {srLine.Quantity_Dispatched__c = sampleLine.quantity_of_sample;}
                    if(sampleLine.sample_sent_status != null) {srLine.Sampling_Status__c = sampleLine.sample_sent_status;}
                    if(sampleLine.tracking_number != null) {srLine.Tracking_Number__c = sampleLine.tracking_number;}
                    if(sampleLine.modified_by != null) {srLine.Modified_By_Name__c = sampleLine.modified_by;}
                    if(sampleLine.created_by != null) {srLine.Created_By_Name__c = sampleLine.created_by;}
                    if(sampleLine.actual_hours != null) {srLine.Actual_Hours__c = srLine.Actual_Hours__c != null ? srLine.Actual_Hours__c + sampleLine.actual_hours : sampleLine.actual_hours;}
                    if(sampleLine.date_of_dispatch != null) {srLine.Date_of_Dispatch__c = sampleLine.date_of_dispatch;}
                }
                else{
                    throw new CustomException('Line item not found');
                }
            }
            
            update sampleRequestLineMap.values();
        }
        catch(Exception e){
            if(e.getMessage().contains('Development_Code__c duplicates')){
                throw new CustomException('Development code alreay exists.');
            }
            else{
                throw e;
            }
        }
        
        
        return true;
    }
    
    
    global static Map<String, Sample_Request_Line_Item__c> getSampleRequestLineMap(String sampleRequestId, Set<String> sapLineItemIdSet){
        Map<String, Sample_Request_Line_Item__c> sampleRequestLineMap = new Map<String, Sample_Request_Line_Item__c>();
        
        for(Sample_Request_Line_Item__c srLine :[SELECT Id, SAP_Line_Item_Id__c, Actual_Hours__c FROM Sample_Request_Line_Item__c WHERE Sample_Request__c =:sampleRequestId AND SAP_Line_Item_Id__c IN :sapLineItemIdSet]){
            sampleRequestLineMap.put(srLine.SAP_Line_Item_Id__c, srLine);
        }
        
        return sampleRequestLineMap;
    }
    
    
    global class SampleRequestLineItem{
        global String sf_sample_request_id;
        global String sap_line_item_id;
        global String development_code;
        global Decimal quantity_of_sample;
        global String sample_sent_status;
        global String tracking_number;
        global String created_by;
        global String modified_by;
        global Decimal actual_hours;
        global Date date_of_dispatch;
    }
}