src/objects/Sample_Request__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sample_Request_SAP_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sample Request OSSM Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sample_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Bulk_Sample_Quantity__c</fullName>
        <label>Bulk Sample Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reason_for_Resampling__c</fullName>
        <label>Reason for Resampling</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sampling_Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change in Quantity</fullName>
                </value>
                <value>
                    <fullName>Change in Sample Spec</fullName>
                </value>
                <value>
                    <fullName>Change in Quantity &amp; Sample Spec</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resampling_Quantity__c</fullName>
        <label>Resampling Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SAP_Line_Item_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OSSM Line Item Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sample_Feedback__c</fullName>
        <description>Helps to capture the feedback received from the customer.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Sample Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sample_Request__c</fullName>
        <label>Sample Request</label>
        <referenceTo>Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_of_measure__c</fullName>
        <label>Unit of measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MT</fullName>
                    <label>Metric Ton</label>
                </value>
                <value>
                    <fullName>LB</fullName>
                    <label>US pound</label>
                </value>
                <value>
                    <fullName>KG</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Gram</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sample Request Line Item</label>
    <nameField>
        <displayFormat>SRLI-{00000}</displayFormat>
        <label>Sample Request Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/classes/SampleRequestFeedbackREST.cls
@RestResource(urlMapping='/SampleRequestFeedback/*')
global with sharing class SampleRequestFeedbackREST{
     
    @HttpGet
    global static SampleRequest getSampleRequestFeedback() {
        RestRequest req = RestContext.request;
        String sampleRequestId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        
        System.debug('REQUEST -- '+sampleRequestId);
        
        List<SampleRequestLineItem> sampleRequestLineToReturn = new List<SampleRequestLineItem>();
        List<Sample_Request_Line_Item__c> sampleRequestLineListToUpdate = new List<Sample_Request_Line_Item__c>();
        
        for(Sample_Request_Line_Item__c srLine :[SELECT Id, Sample_Feedback__c, Sample_Request__r.Sample_Request_SAP_Id__c, SAP_Line_Item_Id__c , Sampling_Status__c, Reason_for_Resampling__c, Bulk_Sample_Quantity__c, Quantity__c, Unit_of_measure__c, Resampling_Quantity__c  FROM Sample_Request_Line_Item__c WHERE Sample_Request__c = :sampleRequestId AND Integration_Status__c = 'feedback_update']){
            SampleRequestLineItem srLineItem = new SampleRequestLineItem();
            srLineItem.sf_sample_request_id = sampleRequestId;
            srLineItem.sap_sample_request_id = srLine.Sample_Request__r.Sample_Request_SAP_Id__c;
            srLineItem.sap_lineitem_id = srLine.SAP_Line_Item_Id__c;
            srLineItem.status = srLine.Sampling_Status__c;
            
            if(srLine.Sampling_Status__c == '9'){
                srLineItem.quantity = srLine.Bulk_Sample_Quantity__c;
                srLineItem.unit_of_measure = srLine.Unit_of_measure__c;
            }
                
            srLineItem.sample_feedback = srLine.Sample_Feedback__c;
            if(srLine.Sampling_Status__c == '10'){
                srLineItem.sample_feedback = srLine.Reason_for_Resampling__c + ': ' + srLine.Sample_Feedback__c;
            }
            
            if(srLine.Reason_for_Resampling__c == 'Change in Quantity' || srLine.Reason_for_Resampling__c == 'Change in Quantity & Sample Spec'){
                srLineItem.quantity = srLine.Resampling_Quantity__c;
                srLineItem.unit_of_measure = srLine.Unit_of_measure__c;
            }
            
            
            
            sampleRequestLineListToUpdate.add(new Sample_Request_Line_Item__c(Id = srLine.Id, Integration_Status__c = 'update_sent_to_ossm'));
            
            sampleRequestLineToReturn.add(srLineItem);
        }
        
        UPDATE sampleRequestLineListToUpdate;
        
        SampleRequest result = new SampleRequest();
        result.root = sampleRequestLineToReturn;
        
        System.debug('Feedback Response Payload '+ JSON.serialize(result));
        
        return result;
    }
    
    
    global class SampleRequest{
        global List<SampleRequestLineItem> root;
        
        global SampleRequest(){
            root = new List<SampleRequestLineItem>();
        }
    }
    
    
    global class SampleRequestLineItem{
        global String sf_sample_request_id;
        global String sap_sample_request_id;
        global String sap_lineitem_id;
        global String status;
        global String sample_feedback;
        global Decimal quantity;
        global String unit_of_measure;
    }
}