src/objects/Sample_Request__c.object
<CustomObject>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Sample Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sample_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Sample_Request__c</fullName>
        <label>Sample Request</label>
        <referenceTo>Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Request Line Items</relationshipLabel>
        <relationshipName>Sample_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sampling_Status__c</fullName>
        <label>Sampling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sampling_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Sample Request Line Item</label>
    <nameField>
        <displayFormat>SRLI-{00000}</displayFormat>
        <label>Sample Request Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SampleFeedback__e.object
<CustomObject>
    <fields>
        <fullName>SampleRequestId__c</fullName>
        <label>SampleRequestId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>SampleFeedback</label>
    <pluralLabel>SampleFeedback</pluralLabel>
</CustomObject>

src/objects/SampleRequest__e.object
<CustomObject>
    <fields>
        <fullName>SampleRequestId__c</fullName>
        <label>SampleRequestId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SampleRequest</label>
    <pluralLabel>SampleRequests</pluralLabel>
</CustomObject>

src/globalValueSets/Sampling_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Samples Sent</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Pending Feedback</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Resampling</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sample Accepted</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Sample Rejected</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Resample Sent to the Customer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sample Approved, asking for bulk sample</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Kept on Hold</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>No Response</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Project Dropped</label>
    </customValue>
    <masterLabel>Sampling Status</masterLabel>
</GlobalValueSet>

src/classes/SampleRequestLineItemHelper.cls
public class SampleRequestLineItemHelper {
    
    public static void publishPlatformEvent(List<Sample_Request_Line_Item__c> SampleRequestLineItemList){
        List<SampleRequest__e> sreqEvtList = new  List<SampleRequest__e>();
        set<id> srIdset = new set<id>();
        for(Sample_Request_Line_Item__c srLinItmObj : SampleRequestLineItemList){
            srIdset.add(srLinItmObj.Sample_Request__c);              
        }
        for(id srid : srIdset){
            sreqEvtList.add(new SampleRequest__e(SampleRequestId__c=srid));     
        }
        
        publishPlatformEventsForSampleRequest(sreqEvtList);
    }
    
    
    public static void publishPlatformEventsForSampleRequest(List<SampleRequest__e> sampleRequestEventList){
        List<Database.SaveResult> results = EventBus.publish(sampleRequestEventList);
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event.');
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' +
                                 err.getStatusCode() +
                                 ' - ' +
                                 err.getMessage());
                }
            }       
        }
    }
    
    
    public static void publishPlatformEventOnFeedback(List<Sample_Request_Line_Item__c> SampleRequestLineItemList, Map<Id, Sample_Request_Line_Item__c> oldMap){
        Set<String> feedbackStatus = new Set<String>{'7', '8', '9', '10', '12', '13', '14', '16'};
        
        List<SampleFeedback__e> sreqEvtList = new  List<SampleFeedback__e>();
        set<id> srIdset = new set<id>();
        
        for(Sample_Request_Line_Item__c srLinItmObj : SampleRequestLineItemList){
            if(srLinItmObj.Sampling_Status__c != oldMap.get(srLinItmObj.Id).Sampling_Status__c && feedbackStatus.contains(srLinItmObj.Sampling_Status__c)){
                srIdset.add(srLinItmObj.Sample_Request__c);    
            }              
        }
        for(id srid : srIdset){
            sreqEvtList.add(new SampleFeedback__e(SampleRequestId__c=srid));     
        }
        List<Database.SaveResult> results = EventBus.publish(sreqEvtList);
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event.');
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' +
                                 err.getStatusCode() +
                                 ' - ' +
                                 err.getMessage());
                }
            }       
        }
        
    }
    
       
}