src/objects/TCB__c.object
<CustomObject>
    <fields>
        <fullName>CTN_20FT__c</fullName>
        <label>CTN/ 20FT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CTN_40FT_HC__c</fullName>
        <label>CTN/ 40FT HC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CTN_40FT__c</fullName>
        <label>CTN/ 40FT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CTN_Layer__c</fullName>
        <label>CTN/ Layer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Depth_Gusset_Height_mm__c</fullName>
        <label>Depth/ Gusset/ Height (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Height_mm__c</fullName>
        <label>Height (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Layer_PL_40HC__c</fullName>
        <label>Layer/ PL 40HC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Layer_PL__c</fullName>
        <label>Layer/ PL</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Length_Depth_mm__c</fullName>
        <label>Length/ Depth (mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Length_mm_1st__c</fullName>
        <label>Length (mm) (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MOQ_Packaging_1st__c</fullName>
        <label>MOQ Packaging (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MOQ_Packaging_2nd__c</fullName>
        <label>MOQ Packaging (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Product Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TCBs</relationshipLabel>
        <relationshipName>TCBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PL_20FT__c</fullName>
        <label>PL/ 20FT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PL_40FT__c</fullName>
        <label>PL/ 40FT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PM_Type_1st__c</fullName>
        <label>PM Type (1st)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1st_PM_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PM_Type_2nd__c</fullName>
        <label>PM Type (2nd)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X2nd_PM_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pallet_Type__c</fullName>
        <label>Pallet Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pallet_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tare_Weight_g_1st__c</fullName>
        <label>Tare Weight (g) (1st)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tare_Weight_g_2nd__c</fullName>
        <label>Tare Weight (g) (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_CTN__c</fullName>
        <label>Unit/ CTN</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width_mm_1st__c</fullName>
        <label>Width (mm) (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width_mm_2nd__c</fullName>
        <label>Width (mm) (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1st_PM_Pouch_jar__c</fullName>
        <label>PM (Pouch/jar) VND/EA (1st)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2nd_PM_Carton__c</fullName>
        <label>PM (Carton) - VND/EA (2nd)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TCB</label>
    <nameField>
        <displayFormat>TCB - {00000}</displayFormat>
        <label>TCB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Pallet_Set.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Disposal - 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal - 1x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal - 1.1x1.1m</fullName>
    </customValue>
    <customValue>
        <fullName>CHEP – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>CHEP – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>PECO – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>PECO – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>LOSCAM – 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>LOSCAM – 40x48 inches</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 0.8x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 1x1.2m</fullName>
    </customValue>
    <customValue>
        <fullName>Slip sheet - 1.1x1.1m</fullName>
    </customValue>
    <masterLabel>Pallet Set</masterLabel>
</GlobalValueSet>

src/globalValueSets/X1st_PM_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DOY</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW</fullName>
    </customValue>
    <customValue>
        <fullName>FOUR SIDE SEAL</fullName>
    </customValue>
    <customValue>
        <fullName>DOY FLAT BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>PILLOW BLOCK BOTTOM</fullName>
    </customValue>
    <customValue>
        <fullName>VACUUM</fullName>
    </customValue>
    <customValue>
        <fullName>PET JAR</fullName>
    </customValue>
    <customValue>
        <fullName>GLASS JAR</fullName>
    </customValue>
    <customValue>
        <fullName>PET CYLINDER JAR</fullName>
    </customValue>
    <customValue>
        <fullName>METAL CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>COMPOSITE CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PET CANISTER</fullName>
    </customValue>
    <customValue>
        <fullName>PAPER MILK BOTTLE</fullName>
    </customValue>
    <masterLabel>1st PM Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/X2nd_PM_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSC</fullName>
    </customValue>
    <customValue>
        <fullName>TRAY &amp; LID</fullName>
    </customValue>
    <customValue>
        <fullName>TRAY ONLY</fullName>
    </customValue>
    <customValue>
        <fullName>PRE CUT RSC</fullName>
    </customValue>
    <masterLabel>2nd PM Type</masterLabel>
</GlobalValueSet>

src/classes/PWR_Validate_Controller.cls
public class PWR_Validate_Controller {
    @AuraEnabled
    public static List<string> validate(String recId) {
        List<string> missingFields = new List<string>();
        TCB__c tcb = [SELECT Id, Name,
                           PM_Type_1st__c,
                           X1st_PM_Pouch_jar__c,
                           Tare_Weight_g_1st__c,
                           Length_mm_1st__c,
                           Width_mm_1st__c,
                           Depth_Gusset_Height_mm__c,
                           PM_Type_2nd__c,
                           X2nd_PM_Carton__c,
                           Tare_Weight_g_2nd__c,
                           Length_Depth_mm__c,
                           Width_mm_2nd__c,
                           Height_mm__c,
                           Unit_CTN__c,
                           Layer_PL__c,
                           Layer_PL_40HC__c,
                           PL_20FT__c,
                           PL_40FT__c,
                           CTN_20FT__c,
                           CTN_40FT__c,
                           CTN_40FT_HC__c, 
                           CTN_Layer__c,
                           MOQ_Packaging_1st__c,
                           MOQ_Packaging_2nd__c,
                           Pallet_Type__c 
                           
                           FROM TCB__c WHERE Opportunity__c = :recId];
        
        if (tcb.PM_Type_1st__c == null) {
            missingFields.add('PM Type (1st)');
        }
        if (tcb.X1st_PM_Pouch_jar__c == null) {
            missingFields.add('PM (Pouch/jar) VND/EA (1st)');
        }
        if (tcb.Tare_Weight_g_1st__c == null) {
            missingFields.add('Tare Weight (g) (1st)');
        }
        if (tcb.Length_mm_1st__c == null) {
            missingFields.add('Length (mm) (1st)');
        }
        if (tcb.Width_mm_1st__c == null) {
            missingFields.add('Width (mm) (1st)');
        }
        if (tcb.Depth_Gusset_Height_mm__c == null) {
            missingFields.add('Depth/ Gusset/ Height (mm)');
        }
        if (tcb.PM_Type_2nd__c == null) {
            missingFields.add('PM Type (2nd)');
        }
        if (tcb.X2nd_PM_Carton__c == null) {
            missingFields.add('PM (Carton) - VND/EA (2nd)');
        }
        if (tcb.Tare_Weight_g_2nd__c == null) {
            missingFields.add('Tare Weight (g) (2nd)');
        }
        if (tcb.Length_Depth_mm__c == null) {
            missingFields.add('Length/ Depth (mm)');
        }
        if (tcb.Width_mm_2nd__c == null) {
            missingFields.add('Width (mm) (2nd)');
        }
        if (tcb.Height_mm__c == null) {
            missingFields.add('Height (mm)');
        }
        if (tcb.Unit_CTN__c == null) {
            missingFields.add('Unit/ CTN');
        }
        
        if (tcb.CTN_Layer__c == null) {
            missingFields.add('CTN/ Layer');    
        }
        if (tcb.Layer_PL__c == null) {
            missingFields.add('Layer/ PL');   
        }
        if (tcb.Layer_PL_40HC__c == null) {
            missingFields.add('Layer/ PL 40HC');    
        }
        if (tcb.PL_20FT__c == null) {
            missingFields.add('PL/ 20FT');    
        }
        if (tcb.PL_40FT__c == null) {
            missingFields.add('PL/ 40FT');   
        }
        if (tcb.CTN_20FT__c == null) {
            missingFields.add('CTN/ 20FT');   
        }
        if (tcb.CTN_40FT__c == null) {
            missingFields.add('CTN/ 40FT');  
        }
        if (tcb.CTN_40FT_HC__c == null) {
            missingFields.add('CTN/ 40FT HC');
        }
         if (tcb.MOQ_Packaging_1st__c == null) {
            missingFields.add('MOQ Packaging (1st)');
        }
         if (tcb.MOQ_Packaging_2nd__c == null) {
            missingFields.add('MOQ Packaging (2nd)');
        }
         if (tcb.Pallet_Type__c == null) {
            missingFields.add('Pallet Type');
        }
        return missingFields;
    }
}