src/objects/Teams__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Identifier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <defaultValue>IF(CONTAINS($UserRole.Name, &apos;Cocoa&apos;), &apos;Cocoa Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Dairy&apos;), &apos;Dairy Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Spice&apos;), &apos;Spice Sales Manager&apos;,
(IF(CONTAINS($UserRole.Name, &apos;Edible_Nuts&apos;), &apos;Edible_Nuts Sales Manager&apos;, &apos; &apos;)))))))</defaultValue>
        <label>Role Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cocoa Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Dairy Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Spice Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Edible_Nuts Sales Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teams</label>
    <nameField>
        <label>Teams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/BU_Identifier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Spice</fullName>
        <label>Spices</label>
    </customValue>
    <customValue>
        <fullName>Edible_Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>BU Identifier</masterLabel>
</GlobalValueSet>

src/classes/OlamObjectSharing.cls
public class OlamObjectSharing {

    private Map<Id, List<SObject>> accountObjectMap;
    private List<SObject> objectList;
    private string accountIdFieldName;
    private string objectName;
    private ObjectSharingFieldMap objFieldMap;
    
    public OlamObjectSharing(String objName, List<SObject> inputs) {
        objectList = inputs;
        OlamLogger.logPretty('OlamObjectSharing for ' + objName, inputs);
        objFieldMap = new ObjectSharingFieldMap(objName);
        objectName = objName;
        accountIdFieldName = objFieldMap.objectAccountId;
        accountObjectMap = new Map<Id, List<SObject>>();
        for(SObject obj : inputs) {
            Id accountId = (Id)obj.get(accountIdFieldName);
            if(!accountObjectMap.containsKey(accountId)) {
                accountObjectMap.put(accountId, new List<SObject>());
            }
            accountObjectMap.get(accountId).add(obj);
        }
    }

    private List<SObject> getNewObjectShareList() {
        List<SObject> objShareList = new List<SObject>();
        Set<Id> accountIdList = accountObjectMap.keySet();
        
        for(Teams__c team: [Select Id, User__c , Account__c, Role_Name__c  
                                            from Teams__c 
                                            where Account__c in :accountIdList]) {
            for(SObject obj: accountObjectMap.get(team.Account__c)) {
                OlamLogger.log('getNewObjectShareList ' + team.User__c + ', ' + (Id)obj.get('OwnerId') + ', ' + team.Role_Name__c + ', ' + (String)obj.get('Business_Unit__c'));
                if(team.User__c <> (Id)obj.get('OwnerId') && 
                   OlamSharingHelper.isTeamMatchWithBU(team.Role_Name__c, (String)obj.get(objFieldMap.objectBU))) {
                    objShareList.add(OlamSharingHelper.createObjectShare(objectName, (Id)obj.get('Id'), team.User__c));
                }
            }
        }
        OlamLogger.logPretty('getNewObjectShareList return', objShareList);
        return objShareList;
    }
    
    public void addSharing() {
        List<SObject> objShareList = getNewObjectShareList();
        objShareList = OlamSharingHelper.filterDuplicateObjectShare(objectName, objShareList);
        insert objShareList;
    }

}